### ISSUE TITLE
Think about removing JA2BETAVERSION code

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#10]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

Think about removing JA2BETAVERSION code.
This code probably may not work anymore, since nobody tests it or even build.
I can't see value of keeping this code.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/10

**Comment by derSteFfi** [comment]
```
~/ja2-strat (git)-[master] % grep -r JA2BETA * | wc -l
319
```
For non-compiling code with 319 occurences and for the sake of maintainability i would vote for removal, simply because no one needs it anymore. The only Occurences i came across didn't have anything to do with current issues i am aware of.

**Comment by lynxlynxlynx** [comment]
Originally, there was another JA2DEMO define, but all that code got cut out.

**Comment by Manuel-K** [comment]
@lynxlynxlynx Wasn't this solved by #470?

**Comment by lynxlynxlynx** [comment]
Indeed, closing.
