### ISSUE TITLE
Game crashes because of helicopter.

### ISSUE THREAD

**Issue by Ksenofanex** [ja2-stracciatella/ja2-stracciatella#1010]
Bug:

Whenever i try to grab the second squad of my mercenaries with helicopter, it first says "saving..." and then immediately crashes to desktop. Crash popup says: "abort() has been called."

Here is a SS of it: https://imgur.com/a/vufFbGW

In the console, the error is like this:

2020/02/30 18:46:46 WARNING [Tactical Save   ] SynchronizeItemTempFile() Reported 0, should be 2

| JA2S version  |  Game version             | Vanilla bug? | Used to work? |
| ------------    | -------------------         | ------------ | ------------- |
| 0.16.1 release| JA2 Gold 1.12 English  |        ?          |         ?          |

How to produce the bug: Just try to grab a squad with helicopter, deploy it to another sector and then do the same with the other squad. Whenever helicopter comes to the sector in which second squad is avaliable, game first just outputs "saving..." and then crashes to the desktop. 

Here is the save file: https://easyupload.io/0qm0ln

My OS: Windows 10 Home

I don't use any other mods. Just Stracciatella with JA2 1.12 Gold.

Thanks in advance.

**Comment by lynxlynxlynx** [comment]
Are you playing in Dead is dead or why is it saving all of a sudden? I don't remember that popup from the strategic view.

**Comment by ja2-derek** [comment]
Should be the same issue as #1107. 

It should work if you first move your squad away from the I6 or B13.

**Comment by lynxlynxlynx** [comment]
Like noted, this should be avoidable, but also fixed now. If you can still reproduce, please reopen and provide a fresh save.
