### ISSUE TITLE
Cannot build ja2-launcher

### ISSUE THREAD

**Issue by lucasmr** [ja2-stracciatella/ja2-stracciatella#1012]
Followed the compilation instructions, I'm on Gentoo Linux.
```
$ mkdir _bin && cd _bin
$ cmake ../
$ make
```

The executable ja2 is built, but ja2-launcher is missing. No error messages as well. What is missing?

Thanks

**Comment by lynxlynxlynx** [comment]
Which fltk did cmake choose (yours or internal)?

**Comment by lucasmr** [comment]
None. I installed fltk manually and then cmake found the system library.

Maybe add fltk to the dependencies, and also take a look at the internal fallback?

Anyway, thanks. Closing.
