### ISSUE TITLE
JA2 1.13

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#102]
Originally reported by: **Anonymous**

---

First of all I would like to thank you for keeping up this project.
I'd like to ask if you have any plans for porting ja2 version 1.13 since it won't work with stracciatella?
For some reasons I cannot have JA2 run under emulators on mac os x but I would really love to. 

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/102

**Comment by brechtm** [comment]
Understood. How do you feel about including selected features from 1.13 (but off by default)? The new aiming system, for example?

**Comment by lynxlynxlynx** [comment]
some minor stuff was already included in that way. It really depends on how intrusive the change would have to be, as it means a maintenance burden.
