### ISSUE TITLE
clean up src/sgp/Platform.h

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1035]
There's no need for __min/__max as far as I can tell and they're used a bunch. We require c++11, so using the std versions should be fine. But better tackled after #738, so it doesn't cause unnecessary merge conflicts.

**Comment by flaviojs** [comment]
That PR is very big so it will have merge conflicts as other PRs get added.
I wouldn't delay this task because of it.

**Comment by lynxlynxlynx** [comment]
It's a simple cleanup task without any urgency attached, so there's no need to make things more difficult. There's plenty of other cleaning up that can be done without touching the blitters.

**Comment by selaux** [comment]
Idk why this was closed...will reopen.

**Comment by lynxlynxlynx** [comment]
This got done already in the clamping work.
