### ISSUE TITLE
CMake for VS2019 fails on clean check out

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1036]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

CMake build seems no longer works on a clean check out of current master. I never had SDL installed on the system but the build should come with SDL library.

How do I bring the build up to date?

```
D:\Workspace\ja2-stracciatella-clean\_vs>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19608.
-- The C compiler identification is MSVC 19.25.28612.0
-- The CXX compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- ja2-stracciatella version: 0.17.0-dev
-- Setting extra data dir to
-- Setting directory for libraries tolib
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
</FindSDL2.cmake>
CMake Error at D:/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2.cmake:175 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:145 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/Workspace/ja2-stracciatella-clean/_vs/CMakeFiles/CMakeOutput.log".
See also "D:/Workspace/ja2-stracciatella-clean/_vs/CMakeFiles/CMakeError.log".

D:\Workspace\ja2-stracciatella-clean\_vs>                                 
```
[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git |  N/A|    N/A |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
I guess it's since the build system rewrite. It does work on appveyor with the same version of msvc, but we install sdl2 system-wide there. Something must be wrong with the fallback.

**Comment by ja2-derek** [comment]
Sorry for the noise. Seems it's me using the wrong cmake command. It's been a while since I last did a clean build. 

The command I used just now is:
```
mkdir _vs
cd _vs
SET MSBuildExtensionsPath="C:\Program Files\MSBuild"
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-msvc.cmake -G "Visual Studio 16 2019" ..
```

The command in COMPILATION.md did not correctly locate the toolchain file for me.

**Comment by flaviojs** [comment]
The MSVC ci build uses ```-DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-msvc.cmake```.
