### ISSUE TITLE
Graphical glitch in main menu after quitting a game

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#106]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

There is a graphical glitch on the main menu screen:

![http://img.xrmb2.net/images/142535.jpeg](http://img.xrmb2.net/images/142535.jpeg)

This is how to reproduce:
1. Start a new game or load a game
2. End the current game and go back to main menu
3. The glitch will be there

More info:
- This does not work with standard resolution (640x480)
- I can reproduce this in both 800x600 and 1024x768
- This issue is not present in vanilla JA2 (because you can't change res there)
- The screen looks fine when starting JA2. It gets messed up only after exiting a game
- This issueis present in v0.12.258-win, but was already there before

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/106

**Comment by derSteFfi** [comment]
still present. 640x480 works fine, i tested 800x600 and 1920x980 and the glitch is present.

**Comment by JAsmine-ja2** [comment]
Still present in v0.15 as described in initial post.
