### ISSUE TITLE
Game stuck at NPC dialogue

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1062]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1 and master (ed9e1c2) | JA2 (Steam version)|   not sure |   not sure     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
Preferences: Subtitles and Pause Text Dialogue on. 

1. Order Merc 1 to do open a locked door
2. While the Merc 1 is moving towards the  door, have another Merc 2 to talk to a NPC that have multiple long quotes (Martha Graham in my case)
3. While the NPC is still talking, the Open Door popup appeared. The talking prompt box disappears
4. Close the open door prompt.
5. Have Merc 2 talk to NPC again. Now the game is stuck with a stop watch cursor. Nothing can be done. Unable to switch to Map view or do anything.

[//]: # (- the operating system)
OS is Win 10.

[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by flaviojs** [comment]
Can you provide a savefile for me to try?

**Comment by ja2-derek** [comment]
Save: [QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/4602920/QuickSave.zip)

I am able to reproduce with 0.16.1. With this quick save:

1. Order Buns go to close one of the crates in far right (in the room where Igor is)
2. While Buns is on her way, have Wolf give the letter to Fatima
3. Click through one Fatima's dialogue, then wait
4. Now the screen focuses on Buns with the crate action popup. Fatima is still talking but the talking dialogue has disappeared.
5. Fatima will finish the dialogue and stop there. Have Wolf talk to Fatima again, the game would get stuck.

There is no problem if I do not click on click-through any dialogue, or click-through all dialogues at step 3.

**Comment by flaviojs** [comment]
Infinite stop watch cursor:
1. `InitiateConversationFull` is called
2. `DialogueQueueIsEmptyOrSomebodyTalkingNow` is called
3. `FALSE` is returned because `gpCurrentTalkingFace` is not `NULL`
4. the "Wait....." branch is taken

When this happens I don't see a talking face in the screen so `gpCurrentTalkingFace` should `NULL`?
Next step, figure out which part of the spaghetti code failed to clear `gpCurrentTalkingFace`.

**Comment by lynxlynxlynx** [comment]
We should just prevent displaying the door popup if dialog is running.

**Comment by flaviojs** [comment]
In vanilla the door/box popup cancels the current dialog and freezes everything else.
After the popup disappears (I canceled or made a choice) the next dialog continues.

I have a feeling there were other issues related to this popup...
When did ours stop freezing stuff?

**Comment by flaviojs** [comment]
This is probably the same as #427.

**Comment by lynxlynxlynx** [comment]
Indeed. We can improve on the vanilla behaviour though, since the dialog state can be cut short.

**Comment by flaviojs** [comment]
#650 is also related?

There is so much spaghetti code around this that I would prefer to keep all related stuff as close to vanilla as possible and only consider changing it when the spaghetti code is structured. >.<'

**Comment by lynxlynxlynx** [comment]
All three look like the same thing to me. Not allowing to open the door popup shouldn't affect anything else if done early enough.

**Comment by flaviojs** [comment]
Feel free to make a PR. 😉

**Comment by lynxlynxlynx** [comment]
http://sprunge.us/3uVTYC?diff works fine for the first case (same as #427, #650), so just need to find something for the waiting situation (case two with item giving) before a dialog starts.
