### ISSUE TITLE
Civilians dying causes crash

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1068]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  Nightly and master |  JA2 (Steam version)|    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
### Reproducing the crash
- Indirectly wound an unnamed civilian (so that he/she will bleed out, but does not turn hostile)
- Go to Strategic Map screen. Fast forward
- Game crashes with "invalid profile id 200"

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/4619374/QuickSave.zip)

### Analysis

200 is `NO_PROFILE`. Call stack:
```
 	ja2.exe!GetProfile(const unsigned char id) Line 20	C++
	ja2.exe!StrategicHandlePlayerTeamMercDeath(SOLDIERTYPE & s) Line 90	C++
 	ja2.exe!HandleTakeDamageDeath(SOLDIERTYPE * pSoldier, unsigned char bOldLife, unsigned char ubReason) Line 5433	C++
 	ja2.exe!SoldierTakeDamage(SOLDIERTYPE * pSoldier, short sLifeDeduct, short sBreathLoss, unsigned char ubReason, SOLDIERTYPE * attacker) Line 5881	C++
 	ja2.exe!SoldierBleed(SOLDIERTYPE * s, unsigned char fBandagedBleed) Line 8018	C++
 	ja2.exe!CheckBleeding(SOLDIERTYPE * pSoldier) Line 7977	C++
 	ja2.exe!EVENT_BeginMercTurn(SOLDIERTYPE & s) Line 4057	C++
 	ja2.exe!HandleTacticalEndTurn() Line 162	C++
 	ja2.exe!HandleStrategicTurn() Line 93	C++
```

This issue is exposed by 500eed8733c529885f8433c604a70c9e66ce8c61. Apparently Strategic_Merc_Handler had always accessed an invalid memory location `gMercProfiles[200]`

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/9a57a1b99e23a3dc936d0be63312e17546c776ae/src/game/Strategic/Strategic_Merc_Handler.cc#L90-L91

[//]: # (- the operating system)
OS is Win10

[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

We should probably add a `NO_PROFILE` check there..

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by flaviojs** [comment]
Nice, another illegal memory access will be squashed. 👍

A NO_PROFILE check around the life insurance code seems appropriate, I'll make a PR.
