### ISSUE TITLE
Format string issue: "Hire for ${} per day"

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1073]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

![image](https://user-images.githubusercontent.com/63151803/82152889-e3a55100-9896-11ea-81a9-d8b84b10957c.png)

Should be somewhere in Interface_Dialogue.cc, `NPC_ACTION_ASK_ABOUT_PAYING_RPC_WITH_DAILY_SALARY`.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master | JA2 (Steam version)|    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
These should be all the places to fix:

```
$ grep -R st_format_printf  .  | grep '{}'
./game/AniViewScreen.cc:                        zError = st_format_printf("Animation str {} is not known: ", currFilename);
./game/Tactical/Interface_Dialogue.cc:                  zTemp2 = st_format_printf("${}", gMercProfiles[ubProfileID].sSalary);
./game/Tactical/Interface_Dialogue.cc:                  zTemp2 = st_format_printf("${}", GCM->getItem(LEATHER_JACKET_W_KEVLAR)->getPrice());
$
```

`ST::format`  should  be used instead.

**Comment by lynxlynxlynx** [comment]
Yeah, it actually already fixed, but the PR was postoponed for your work.

**Comment by ja2-derek** [comment]
Ah! I see
