### ISSUE TITLE
Warden at Tixa does not trigger Panic Button

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1080]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master/nightly | JA2 (Steam) |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
### Reproducing the bug
1. Go to Tixa (Any time except 5pm)
2. Fire a shot so enemy team goes to RED ALERT
3. Warden is supposed to trigger the button  to release tear gas, but this does not happen

[//]: # (- the operating system)
OS is Win 10

[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

### Analysis

This should be due to #871. In Tixa the Panic Button is always triggered by Warden. 

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/3a2697ce5b9a5cfefde8a106931b89ed71d81704/src/game/TacticalAI/PanicButtons.cc#L386-L393

But Warden is on `bTeam == 4`  (CIV_TEAM, WARDEN_CIV_GROUP):
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/3a2697ce5b9a5cfefde8a106931b89ed71d81704/src/game/TacticalAI/PanicButtons.cc#L367-L370

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by flaviojs** [comment]
I see... I didn't realize panic triggers are for the warden in TIXA and for the army in other places.
I'll make a PR.
