### ISSUE TITLE
"Travel to Surface?" prompt do not work in Cambria/Alma mine

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1087]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master/nightly/0.16.1 |  JA2 Steam version |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

There should be a "Travel to surface?" prompt, when the squad exits the deep underground lair sectors after clearing out the lair. This prompt works if lair is in Drassen, but it does not prompt if it is Cambria (Alma should have same problem but I have not tested)

I found the issue when I was looking into externalizing creature lair data. This is an old bug, might be a vanilla bug as well.

The issue is a mismatch of lair ID:

Cambria lair ID is `2`
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/9f76684de4cbab33ad8e31d756d2e6f5de44ede5/src/game/Strategic/Creature_Spreading.cc#L174-L177

The wrap code function has the wrong ID:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/9f76684de4cbab33ad8e31d756d2e6f5de44ede5/src/game/Strategic/Creature_Spreading.cc#L1366

So the warp code never matches in Cambria or Alma. 

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Nice find and indeed it was present already in the initial import. This should clearly have been using named constants. Some other checks are fine though.
