### ISSUE TITLE
Failed to Add Merc

### ISSUE THREAD

**Issue by ray-yang-ja2** [ja2-stracciatella/ja2-stracciatella#1094]
Hello

I used proedit to edit Prof.dat for the merc Gus's data(salary and items). 
After I hired Gus, it showed "game/Tactical/Merc_Hiring.cc: TacticalCreateSoldier in HireMerc():  Failed to Add Merc".

Is it possible to directly edit merc data by editing a json of ja2-stracciatella without going through the proedit ? Thank you.

JA2S version:ja2 1.12 gold

**Comment by ja2-derek** [comment]
`proedit` should work just fine. What are you trying to do?

You cannot edit merc stats/profiles via JSON. You can, however, override the merc dialogue text (.EDT).

**Comment by ray-yang-ja2** [comment]
I found out it crashed becasue I changed the 5.56mm magazines size from 30 to 100 in the magazines json.

When I hired a merc with a 5.56mm weapon, the game crashed.

So, there is no problem with proedit.

**Comment by lynxlynxlynx** [comment]
So what is the fastest way to reproduce? If you are talking about two issues, please open another one.
