### ISSUE TITLE
Use caching on build bots / speed up builds

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1102]
All three of our CI platforms support caching between builds (to some extent). We should use it to both speed build times and be less of a burden on the infrastructure.

Low hanging fruit: make sure to install all available dependencies, so the bundled one don't get used (eg. gtest). 
Perhaps string_theory can also be cached.
Crates should be possible too.

**Comment by ja2-derek** [comment]
Not sure how much time is taken to set up dependencies. Perhaps we should add some timing logs, or split them up into smaller sections.

`~/.cargo` should be very easy : https://docs.travis-ci.com/user/caching/#rust-cargo-cache

In my local, gcc compilation is the slowest. How about keeping and re-using the intermediate object files for PR builds (i.e. except nightly and releases)?

**Comment by lynxlynxlynx** [comment]
On the github workflows, timing is included by default.

Interesting idea about *.o — I wonder if/how well it could work. :thinking:

**Comment by ja2-derek** [comment]
Travis has the timing for each command run. 

GitHub CI only shows the overall time for the entire `cibuild.sh` script. We may want to split it.

But do we still need Travis build on PR? I think we only need Travis for nightly.

**Comment by ja2-derek** [comment]
I suggest:

- [ ] Disable Travis on PR, and focus on GitHub CI only
- [ ] Split `.github/scripts/ci-build.sh`for timing in logs
- [ ] Experiment with:
    - [ ] `make -j $NUM_CORES` 
    - [ ] Caching on GitHub CI ([docs](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows))
        - [ ] `ccache` - https://ccache.dev/
        - [ ] `~/.cargo`

**Comment by lynxlynxlynx** [comment]
I don't think -j would make sense, since it's just heavier on the infra. Some of the bots explicitly discourage it, though I don't remember which.

ccache — great idea, forgot about that. We'll perhaps have to make the cache per-runner though, so eg. the different msvc versions don't bust it for each other.

**Comment by lynxlynxlynx** [comment]
It also looks like we do two mingw builds, which is not really necessary. I suggest we drop either; the crosscompiling one is probably more worthwhile as far as testing the system goes.

**Comment by ja2-derek** [comment]
> It also looks like we do two mingw builds, which is not really necessary. I suggest we drop either; the crosscompiling one is probably more worthwhile as far as testing the system goes.

GitHub CI is configured to run only 1 mingw build. I see there is an unused definition for msys2 build.

Travis is doing another, but I think we should just drop Travis CI for PRs.

AppVeyor is doing MSVC builds. Not sure if it's worth to build on 3 MSVC versions for every PR.

**Comment by lynxlynxlynx** [comment]
Travis doesn't mind more make jobs:
https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-optimization

But we can also fail faster. The new unit test failure shows that we continue until the end on Travis. That's because we're in a script block and it's just the way Travis works:

So we can either use a code block instead of individual lines and and-chain everything or use set -e/set +e to be more strict. The latter might require moving the code to a separate file, not sure.

**Comment by ja2-derek** [comment]
Timeline of the latest AppVeyor build (win64):

00:00 build start
01:15 Starting 'fltk'
04:00 Completed 'fltk'
05:12 Completed 'string_theory'
05:20 Completed 'get-gtest'
08:00 lib-stracciatella finished
13:53 Generated Debug/ja2.exe
13:55 finished cargo-fmt-check
15:55 finished cargo-clippy
17:18 finished cargo-test
17:20 finished ja2.exe -unittests
19:01 finished upload artifacts
19:04 Build success

We can save 2.5 minutes by caching `lib-stracciatella` output, save 3 minutes by skipping rust static analysis (fmt/clippy) which will be done on other builds as well.

**Comment by lynxlynxlynx** [comment]
Analysis stuff should be there for all pr builds, while we can limit it elsewhere to the nightlies.
Why is FLTK taking so long? Is it building our own copy — if so, there's surely a windows build out there we can just download and cache.

**Comment by lynxlynxlynx** [comment]
I've enabled rolling builds on appveyor now. Noticed while looking at the last PR, that even though new commits were added, the old ones were still scheduled for building. Not so any more, which should help with the queuing significantly.

**Comment by ja2-derek** [comment]
Looks like some builds has failed because downloading of `editor.slf` hit GitHub's rate. Re-running should work, but not sure how we should resolve this in the long term. 

Maybe publish the SLF to cloud storage as well? It may as well sit behind a CDN. Our usage level should be well below any free tier limits.

```
 -- Downloading https://api.github.com/repos/ja2-stracciatella/free-ja2-resources/releases/latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   247  100   247    0     0   2352      0 --:--:-- --:--:-- --:--:--  2352
-- HTTP/1.1 403 rate limit exceeded
CMake Error at cmake/CurlFunctions.cmake:59 (message):
  unexpected reply
  result: 0
  http: HTTP/1.1 403 rate limit exceeded
  Date: Fri, 17 Jul 2020 11:32:56 GMT
...
```

**Comment by lynxlynxlynx** [comment]
That's odd, we only do it for nightlies and release builds.

**Comment by ja2-derek** [comment]
I have disabled Travis-CI.org building pushed PRs (https://docs.travis-ci.com/user/web-ui/#build-pushed-pull-requests). So Travis will only build branch pushes (master and nightly); PRs will be handled by GitHub CI and AppVeyor.

Let me know if there are any concerns. This can be reverted in the Travis web UI.

**Comment by ja2-derek** [comment]
Any objections if I stop the "msys2/mingw" build on AppVeyor? 

I don't see any values in building MinGW on Windows, when we already have the Visual C++ builds and Linux MinGW cross-build (on GitHub CI).

**Comment by selaux** [comment]
This is done, right? I will close the issue as we do build artifact caching everywhere...
