### ISSUE TITLE
H8 - Cambria Mine training militia not available

### ISSUE THREAD

**Issue by needless** [ja2-stracciatella/ja2-stracciatella#1103]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Sector H8, after capture the whole Cambria city sector, and trained milita in the city sectors. It is not possible to train militia at the Cambria mine.

Way to reproduce. Savegame attached to this bug report. Unzip the savegame, Load the save game, go to the Map Screen,  select the sector H8, 2 Mercs are already in the sector H8. Try to assign mercs to train milita in the Map Screen. The milita option is grayed out. This has been working in the vanilla version.

In the Map Screen the originally called "H8:Cambria Mine" is now called "H8:Urban Mine" in this game version. It ought to be called named "H8:Cambria Mine". It might have something to do with this bug.

[savegame.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/4741045/savegame.zip)

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git ver d1c82a9d9 | JA2 linux version  |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by needless** [comment]
Screenshot attached
![2020-06-07-001017_800x600_scrot](https://user-images.githubusercontent.com/906376/83955485-d0612200-a853-11ea-8d65-6766b51c5758.png)

**Comment by lynxlynxlynx** [comment]
There's a true linux version? Interesting ...
The label is clearly just data though, nothing to change there.

We did externalize part of this recently. How long ago did you start all this? Because for a bit, we didn't count H8 as part of Cambria, so now your save may be corrupted in this sense. CC @ja2-derek

**Comment by needless** [comment]
Yes it is true,  there has been a JA2 linux version available: https://www.linuxjournal.com/article/4832

**Comment by ja2-derek** [comment]
This is also fixed by https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1066.

**Comment by ja2-derek** [comment]
Assuming you are building directly from source and if you really want to fix your game, you can patch your save by adding these two lines to the end of LoadSavedGame(UINT8) in SaveLoadGame.cc:
```c++
	StrategicMap[SECTOR_INFO_TO_STRATEGIC_INDEX(SEC_H3)].bNameId = GRUMM;
	StrategicMap[SECTOR_INFO_TO_STRATEGIC_INDEX(SEC_H7)].bNameId = CAMBRIA;
```
But of course,take a backup before doing this.

**Comment by lynxlynxlynx** [comment]
Closing as fixed.
