### ISSUE TITLE
H3 Grum Mine is called Urban Mine

### ISSUE THREAD

**Issue by needless** [ja2-stracciatella/ja2-stracciatella#1104]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

The H3 Sector called Grum Mine is called H3:Urban Mine

Way to reproduce: Savegame is attached to this bug report. Unzip the savegame, Load the save game, go to the Map Screen, select the sector H3.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git d1c82a9 | JA2 linux verson  |    no    |    yes     |

[savegame.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/4741078/savegame.zip)

![2020-06-07-001007_800x600_scrot](https://user-images.githubusercontent.com/906376/83955667-9e50bf80-a855-11ea-95a9-719b6bda509c.png)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
Sorry about that. I believe this is fixed in https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1066

Unfortunately you must start a new game with the fixed version. There is no easy fix to the existing game.

**Comment by ja2-derek** [comment]
Closing this as it is the same problem as #1103. We can follow up there.

Also be sure to get all latest JSON files in externalized/ when you update your binary version.
