### ISSUE TITLE
ChanceToHIt display in Stracciatella?

### ISSUE THREAD

**Issue by Kokkolar** [ja2-stracciatella/ja2-stracciatella#1111]
Hello. Is it possible to know current CtH for the current target like in JA2 1.13?

**Comment by lynxlynxlynx** [comment]
No. You can apply https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1002/commits/b4fd08f7466ea1761fee7a91533609f696b8f3c0 to get circle scaling, but it doesn't present any percentage.

**Comment by wvx** [comment]
e2415757c4cea7baa045f8f838c06f5fd1442c8f The version I use does display the CtH as text in the bottom left. I could make this an option.

**Comment by Kokkolar** [comment]
> [e241575](https://github.com/ja2-stracciatella/ja2-stracciatella/commit/e2415757c4cea7baa045f8f838c06f5fd1442c8f) The version I use does display the CtH as text in the bottom left. I could make this an option.

I don't even know how to apply this kind of modes.
Can you describe how can i do that or where should i read about that? Coz i did not find any FAQ about that.

**Comment by wvx** [comment]
There is a binary release as part of the tests. You could use this version and edit game.json to enable the "accurate_aim_circle" mod. This version does not have the text but the aim circle will change size to indicate shot accuracy.

https://github.com/ja2-stracciatella/ja2-stracciatella/suites/784194415/artifacts/8304643

**Comment by lynxlynxlynx** [comment]
Closing then. Once the bugs get ironed out, this feature will likely land in the main codebase, but until then, it requires a bit more effort from anyone that wants to try it.
