### ISSUE TITLE
Game gets choppy in tactical real-time mode

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1136]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master | Steam version |    no    |    not sure     |

I notice the game gets choppy, and scrolls and UI responses are noticably delayed in certain situations. The delay starts in the middle of a fight, and when multiple enemies are on high alert. But it does not always happen.

I am running master build on Win 10. I am not sure if this issue is specific to me, as I haven't seen any other reports about performance. I remember seeing this is also in 0.16.1 in late game sectors, but I am not able to reproduce this issue from scratch - e.g. starting fresh game, teleporting to P3 does not reproduce it.

I did a profiling during the stuttering, and the results points to excessive debug logging. Game was not in debug mode during profiling.

Function breakdown by CPU time used:
![Perf01](https://user-images.githubusercontent.com/63151803/86505746-29908700-bdfb-11ea-87e1-9e18512b7f66.png)

Call stack of LogMessage:
![PERF02](https://user-images.githubusercontent.com/63151803/86505801-b89d9f00-bdfb-11ea-81b0-a6cc3f17b9d2.png)

As seen above, the problem is the debug logging the `RadioSighting` method. It takes about a third of the total CPU time spent. The choppiness seems to be gone when I commented out all those debug logs.

While I am not 100% certain about the root cause (as it is not easily reproducible), there should be no harm reducing debug logs. I suggest that we:

- [ ] Reduce or remove debug logging in the inner loops of `RadioSighting`
- [ ] ~Update `SLOGD`, to not do anything unless debug log is enabled~
- [ ] Improve efficiency of Logger_log in lib-stracc (#1137)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
Seeing all these `core::str` things in the profiling, the culprit might be [here](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/stracciatella_c_api/src/c/logger.rs#L29), doing some runtime string replacement for each log message. This can probably be substituted by some doing some magic in C++ to return the filename instead of the full file path. Can you check wether the issue persists for this branch: https://github.com/ja2-stracciatella/ja2-stracciatella/tree/fix-time-consuming-logging. The path is replaced at compile time there.

**Comment by ja2-derek** [comment]
Yes, your branch fixes the stuttering. `-debug` is now actually playable with this fix :) It used to be terribly slow.
