### ISSUE TITLE
Hit percentage beyond 100%

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1140]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  since 0.16 | Steam version |    no    |    yes|

A minor issue with the merc personnel stats. After #622, the shots hit after the target is dead are not counted. So there is a reproducable edge case:
1. Hire a merc with auto weapon
2. Get very close to an enemy  (to ensure all shots hit) at CRITICAL health
3. Fire full auto so the first shot registers and kills the enemy. Then the remaining other shots are counted in `usShotsHit` but not `usShotsFired`. With a newly hired merc you can get 400% hit percentage for a 4 shots burst.

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by wvx** [comment]
d8ca3841163e79dac4433d59c9715c0b9048bf57 untested

**Comment by ja2-derek** [comment]
The commit fixes this issue and is working fine
