### ISSUE TITLE
Drassen mine doubles production before depletion

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1144]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|   master | Steam version  |    yes?  |    N/A  |

## Background

At the start of every campaign, one mine is chosen for depletion after 10 days of mining. If Drassen is chosen, it should have 20 days of production before depletion.

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/f288e5da14768357a5fcf8e4b83ced1140919e33/src/game/Strategic/Strategic_Mines.cc#L135-L142

The head miner warns about depletion at after about 7.5 days (or 15 days for Drassen):

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/f288e5da14768357a5fcf8e4b83ced1140919e33/src/game/Strategic/Strategic_Mines.cc#L147-L148

The mine extraction rate is updated when the mine is close to depletion:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/f288e5da14768357a5fcf8e4b83ced1140919e33/src/game/Strategic/Strategic_Mines.cc#L341-L342

For all other mines, the production rate will go up slightly by 250 per day, and will run out after ~2 days. If it is Drassen, it will double the production rate and run out after ~2 days.

Here is my question - is this a bug? It is awkward to me to double the production rate all in a sudden, and that the mine will actually run out at around day 17 instead of day 20. 

A more correct way, to me, is to set the `uiOreRunningOutPoint` of Drassen to 12.5%, so it start the depletion sequence near day 17.5 instead. Doing so the production rate depletion handling is consistent with other mines, and it will actually last 20 days as promised. But that is a deviation from Vanilla. 

What do you think?

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
Calculations - assuming the same removal rate of 9900 per day, and 100% town loyalty

## Current logic

Mine | Daily Removal Rate | Days Before Depletion | Total Ore Supply | Head Miner Warn Day | uiOreRunningOutPoint | New Removal Rate | Days before depletion
-- | -- | -- | -- | -- | -- | -- | --
Drassen | 9900 | 20 | 198000 | 15 | 49500 | 20000 | 2.475
Others | 9900 | 10 | 99000 | 7.5 | 24750 | 10000 | 2.475

## Drassen to warn at 12.5% ore remaining


Mine | Daily Removal Rate | Days Before Depletion | Total Ore Supply | Head Miner Warn Day | uiOreRunningOutPoint | New Removal Rate | Days before depletion
-- | -- | -- | -- | -- | -- | -- | --
Drassen | 9900 | 20 | 198000 | 17.5 | 24750 | 10000 | 2.475
Others | 9900 | 10 | 99000 | 7.5 | 24750 | 10000 | 2.475

**Comment by lynxlynxlynx** [comment]
Sounds like a plan, go for it.
