### ISSUE TITLE
Add Integer Scaling to Resolution Options

### ISSUE THREAD

**Issue by BardBun** [ja2-stracciatella/ja2-stracciatella#1146]
Hello,

I would very much like to have Integer Scaling available for the game.

So that the original 640x480 can be perfectly sharp scaled up to 1280x960 (for fullHD) and 1920x1440 (for WQHD) in both windowed and fullscreen (with black borders) mode.

Integer Scaling makes the game looks so much nicer than that unsharp upscale you get otherwise.

**Comment by ja2-derek** [comment]
I think the "Pixel perfect centered" mode already does what you want.

**Comment by ja2-derek** [comment]
This function will be available in the upcoming 0.17 release (#715). Stay tuned
