### ISSUE TITLE
Segmentation fault mingw64

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1152]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Starting with $ ./ja2.exe -gamedir="C:\Program Files (x86)\Steam\steamapps\common\Jagged Alliance 2 Gold" -res=1600x1000 -window
Segmentation fault

[//]: # (Please also include:)
Starting in msys2 console
Windows 10 - mingw64

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by askondro** [comment]
Built with cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug ../ja2-stracciatella

Now it works

**Comment by ja2-derek** [comment]
Hey @askondro , which line/function does it crash? I am seeing a release-mode only crash with RapidJSON. Debug build is fine and I still not sure what's wrong.
