### ISSUE TITLE
Demoville - Slightly different AI?

### ISSUE THREAD

**Issue by BardBun** [ja2-stracciatella/ja2-stracciatella#1164]
https://www.youtube.com/watch?v=qDruxFvWxvs&t=20m17s

Can be seen at 20:17, I can't recall this AI behaviour in the finished game.

Is it possible to have these interrupts happen in the finished game as well through Stracciatella? Or is it just completely cut behaviour?

Also just wondering, would it be (legally) possible to distribute the Demoville Demo along with Stracciatella and have it available as a game mode under New Game ?

Afterall it's a free demo that is meant to be shared with people to get them to buy the game. I do have both, the German and English versions of Demoville. (the German one uses Fox and Bubba instead of Gasket and Dr. Q)

**Comment by lynxlynxlynx** [comment]
1. I see nothing special in the video.
2. We ripped most of the demo code out (even before #10), but perhaps the data could be salvaged into a mod replacement for the entry sector. Useless work though, since we wouldn't be able to distribute it with the code

**Comment by ja2-derek** [comment]
I think BardBun meant Ivan saw the enemy, and then got interrupted right before he shot. I only know changing stance and moving can get interrupted.

**Comment by BardBun** [comment]
He got Interrupted when he clicked to shoot and that doesn't happen in the final games. Interruptions during any other action is normal but just when you click to shoot the enemy rarely gets an Interrupt but only in the demo.

**Comment by lynxlynxlynx** [comment]
How can you know for sure? It's still a stance change: not prone/crouching/standing, but to the ready-to-fire position.
