### ISSUE TITLE
Game does not run

### ISSUE THREAD

**Issue by iGom** [ja2-stracciatella/ja2-stracciatella#1165]
| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.16.1/git-9303b49 | GOG English |    no    |    I try it first time     |

The game does not start on 0.16.1 and nothing happens, so i tried the latest development bulid and end up with rust error

`[ERROR] launcher\Launcher.cc: Command_execute "C:\\Program Files\\JA2 Stracciatella\\ja2.exe" []: exited with status code -1073741819`

**Comment by ja2-derek** [comment]
Hello there,

When you tried 0.16.1, did you try tapping "Enter" key in the log console window? That might unfreeze it.

And when you upgrade to development build, did you also overwrite the contents of the `externalized` folder? The contents in that folder have changed and are incompatible with the old version.

**Comment by iGom** [comment]
I uninstalled 0.16.1 before installing the development version. 
The game started working after hitting enter on the console (the log is still empty) on 0.16.1, but there is no HUD at resolutions higher than 800x600 in fullscreen mode.

**Comment by lynxlynxlynx** [comment]
This should now be fixed, so you can try the nightly build tomorrow or wait for the 0.17 release, which is just around the corner.

**Comment by iGom** [comment]
I compiled the latest bulid myself and there is black screen in resolutions higher than 1024x768

**Comment by ja2-derek** [comment]
> I compiled the latest bulid myself and there is black screen in resolutions higher than 1024x768 with pixel perfect settings

Pixel Perfect mode results in black screen if the actual window/screen size is smaller than the requested. I assume your screen is large enough. Does it work if you start in 1280x720 windowed mode and then maximize the window?

**Comment by iGom** [comment]
I use CRT monitor and I tried to run the game in 1600x1200 (2048x1536 is highest suporrted by monitor) 1280x780 works just fine, but 1600x900 and 1920x1080 don't, black screen in the latest master bulid and no HUD in 0.16.1 (yep bottom part of the screen is missing)

**Comment by ja2-derek** [comment]
I see. What is your desktop resolution?  Is it lower than 1600x900? 

0.17.0 uses a "desktop fullscreen" mode,  that it fills up the screen at the current resolution. It does not request to change the screen resolution.

**Comment by iGom** [comment]
It's 1600x1200, but I found a cause, I am using the Display Scaling option in Win10 i.e. 125% which was causing problems, instead of the default 100%, now the game displays correctly in 1600x1200
![image](https://user-images.githubusercontent.com/4786772/89130759-83ba6000-d4ff-11ea-8e38-e777a50a0554.png)

**Comment by lynxlynxlynx** [comment]
I guess we can close this then, thanks for retesting.

**Comment by ja2-derek** [comment]
Should we bring back "true" full screen mode as an option (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/6d00eec2bc398c06f5a5bc5beded00b700acd2f0)? But this is probably only useful to CRT monitors.

**Comment by lynxlynxlynx** [comment]
The majority was for removal, so as the last CRT user I was easily swayed. They've been on the way out for years, so I'm not convinced it is worth the effort to change and maintain it.

**Comment by ja2-derek** [comment]
Agreed. We can think about:

- Disallow / warn against resolution larger than the desktop
- Pixel-perfect scaling to have a minimum scaling of 1, so we display a partial screen rather than a black screen
