### ISSUE TITLE
Confusing instructions about Game CD on Linux

### ISSUE THREAD

**Issue by joonazan** [ja2-stracciatella/ja2-stracciatella#1177]
The How to Run says that on Linux you should copy over the files from the second CD as well. This seems to be unnecessary, however. The files in that CD's data folder are already present in the game's installation directory if a full install is chosen.

Could you actually just copy the data files from the CD instead of using the installer? I had to boot into Windows because I didn't get the installer to work on Wine.

**Comment by lynxlynxlynx** [comment]
Thanks for the heads up. Good enough? https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/commit/3481733564eef688afcb84934312145f9147d85c

I don't know what the contents of the CDs are, so can't comment on the possibility of a manual install. `assets/externalized/resource_packs/` contains some known install layouts, but that's it.

**Comment by joonazan** [comment]
I'd write "make sure that chose to copy everything to disk in the installer". CD2 isn't needed at all. It stores copies of some assets for people who couldn't fit everything on their HDD.

**Comment by lynxlynxlynx** [comment]
Thanks, simplified the text.
