### ISSUE TITLE
Unnecessary abort if externalized directory missing

### ISSUE THREAD

**Issue by alanswanson** [ja2-stracciatella/ja2-stracciatella#1187]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Game exits if externalized directory does not exist in game directory. Should not be compulsory (if not modding).

> _[ERROR] externalized/DefaultContentManager.cc: Failed to add to VFS '/usr/local/games/JaggedAlliance2/externalized': Path does not exist
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to add to VFS
> Aborted_

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git | Stracciatella  |    no    |    n/a     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

Editing src/externalized/DefaultContentManagerUT.cc at function DefaultContentManagerUT::init at the AddVFSLayer call and adding a third parameter for throwOnError set to false allowed game to run on my Linux system.

**Comment by ja2-derek** [comment]
Thank you for the report. Let's see what we can do here to improve. But I have a couple of things to clarify with you:

1. Are you talking about running unit tests only? The class `DefaultContentManagerUT` should only be used in Unit Tests.
1. The data from `externalized` is required to run the game, because the corresponding data had been removed from the codebase. 

There are nothing to fall back to if the data files are missing, and the game will not work without them. The `externalized` data must be present somewhere. 

If you are compiling from source, then it should be looking in the executable directory. That is controlled by `EXTRA_DATA_DIR` . You can find the data files in `assets/externalized` but they should also be copied to the build output directory.

**Comment by alanswanson** [comment]
Just ran the game over a few starting sectors, not a full playthrough. The **_COMPILATION.md_** file and **_how-to-run_** page weren't explicit that this (now) needs to be done. Personally not a fan of the externalized files if just running original unmodded game. Would there be a way to have them built in (and override if found in an externalized directory)?

Originally running from Tron's Stracciatella CVS which is a simple drop of the ja2 binary.

**Comment by ja2-derek** [comment]
Point taken.

The **how-to-run** page was written for people using the installer or packages, which come with the data files. The decision to separate data from codebase was made a few years back, and  I don't see any reason we want to go back. 

That said, proposals to improve the docs and embed data are welcome. (Maybe something like Rust include or C code generation from JSON data?)

**Comment by lynxlynxlynx** [comment]
Are you trying to convey that `make install` results in a non-working ja2s?

**Comment by alanswanson** [comment]
I generally avoid **make install** as spewing non-package managed files and coming from the old Stracciatella (after a few years away) just copied the ja2 binary, so my fault.

Quick scan of code would suggest readJsonDataFile could be changed to (as a default fallback) read from hex encoded embedded json files.

**Comment by lynxlynxlynx** [comment]
But why even copy it? From what I remember, ja2s always worked from the build dir too.

**Comment by alanswanson** [comment]
The normal reason, to be available in a shared game directory _/usr/local/games/JaggedAlliance2_ (to which users have no write permissions) rather than one users own build directory.

**Comment by lynxlynxlynx** [comment]
Ah, the classic fhs theory. You'll just have to get used to either of the two options. Btw, we do have an `uninstall` target, so if you don't want to use a custom prefix where you'd have full control, that's the best way to clean up after you're done.

**Comment by ja2-derek** [comment]
This should no longer be an issue after https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1215

On Linux, the game can now be packaged as a single file, with all data files bundled.
