### ISSUE TITLE
Incorrect body positions on high resolution

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#119]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

On high resolution positions of mercs and soldiers might not be correct.
See two attached images.  Resolution 1600x900, before_scroll.png is taken right after loading the game, after_scroll.png after scrolling a little bit up.
Position of the merc and soldiers changed for one tile.  After scrolling down they return into the original position.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/119

**Comment by selaux** [comment]
I can still reproduce this in master. Actually it seems to me that not the merc is changing position, but the map. When scrolling the map suddenly a different viewport is rendering while the merc stays at the same screen position.

**Comment by selaux** [comment]
I've looked into this a bit. Can anyone decipher what [CalcRenderParameters](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/Build/TileEngine/RenderWorld.cc#L5598) is doing? There is a lot of magic going on in that function and it seems to me like it could influence the rendering viewport.

**Comment by lynxlynxlynx** [comment]
I've came to the same conclusion and have a feeling that the whole system could be much simpler. It shows that the initial design wasn't influenced much by OO design. Several conversions could be dropped by just keeping more state.

**Comment by selaux** [comment]
I bisected the issue and it looks to me that this is a problem that is there since high-res rendering was introduced, I bisected it to this commit 3e55aa4fce91ff6eac4623b8c84b4daaf9c4f43a.

**Comment by maxrd2** [comment]
This should be fixed with commit 599301d (#733). Mercs, soldiers and items are now drawn on correct positions.
