### ISSUE TITLE
Rock cannot be thrown as a weapon

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1192]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1+  | JA2 Steam version |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)

Bug found when testing #1191

The rock (one can usually be found in A10) can be wielded and thrown as a weapon. In vanilla, it can be thrown like a grenade using the throwing cursor (`TOSSCURS`).

In Stracc 0.16.1 and later, when rock is wielded, the punch cursor is shown. You can attempt to attack but nothing will happen. The rock can be dropped or thrown like a helmet, but cannot be used to  attack  like a grenade or throwing knife.

[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by iwanPlays** [comment]
[this is fixed now] In 0.17 using a rock to attack freezes the game.

In ci-build\ja2-stracciatella_0.17.1-20210302+8662268_win-msvc64-142.zip using the rock to attack leads to it being tossed like a helmet: https://imgur.com/a/YQatlZ3

**Comment by ja2-derek** [comment]
I saw this also when I made the fix. But I did not investigate further as I don't know if this is vanilla or bug. We need to first determine what the correct behaviour (and animation) is.

Can you also try a few times with a merc of high dexterity and strength?
