### ISSUE TITLE
Framecap?

### ISSUE THREAD

**Issue by pos610** [ja2-stracciatella/ja2-stracciatella#1193]
Hi,

First of all, thanks a lot for your work guys!

I'd like to know how to disable the framecap in Stracciatella - I've tried forcing it off on both vanilla ja2.exe as well as the Stracciatella one via Nvidia control panel with no luck - vanilla is very fast and has anywhere between 70 and 200 fps but Stracciatella seems to be locked at 40 fps in tactical, map and laptop, only loading screens seem to have more fps.

I'm using the GOG 1.12 version with the latest Stracciatella release, Windows 10 2004, nvidia 2060, i7

**Comment by ja2-derek** [comment]
This is available in the nightly version only.

In nightly builds, you can reduce the values of `ms_per_game_cycle` and `ms_per_time_slice` in game.json, which will speed up the animations.

**Comment by pos610** [comment]
Thank you kindly!
