### ISSUE TITLE
Patches from Unfinished Business

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1198]
Here is my proposal to cherry-pick some bug fixes and minor improvements from Unfinished Business source code (#254). My selection criteria are 1) the intention is clear, 2) can be tested and verified, and 3) makes sense in vanilla.

### PATCH152: Notify of "someone else in sector" after battle

Vanilla behaviour: If your squad enters a sector via Strategic Movement with an important NPC (e.g. Skyrider), there is a pop-up saying your squad noticed somebody. But there is no notification at all if there happens to be enemies in the sector.

In UB ([PATCH152](https://github.com/ja2-derek/ja2-ub-comparison/commit/7eb9ea13)), the pop-up appears in Tactical after your win the battle.

### PATCH200: Light up soldier body if fake light is off

When "fake light" is turned off, the soldiers are supposed to have a [personal lighting](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7bdf5d3f7a7e8787fe3f68a3b5e4e9ae4b04d22f/src/game/Tactical/Soldier_Control.cc#L9071-L9077). But it does not really work in Vanilla, the lighting will be gone once you move the soldier:
![merc_lighting_van](https://user-images.githubusercontent.com/63151803/91233726-670ef200-e764-11ea-9bb3-9af33103603b.png)

Unfinished business fixes the personal lighting ([PATCH200](https://github.com/ja2-derek/ja2-ub-comparison/commit/56c4eb43)):
![merc_lighting_ub](https://user-images.githubusercontent.com/63151803/91233725-65ddc500-e764-11ea-9250-0410d281c466.png)

### PATCH208: Disarming trap when inventory is full

Vanilla behaviour: Disarming a pre-placed bomb trap (e.g. in Cambria SAM site) results in a mine, detonator or something similar. But if the merc's inventory is full, the object creation is cancelled, and there is an "Action Item" placed in the cursor.

This is fixed in UB ([PATCH208](https://github.com/ja2-derek/ja2-ub-comparison/commit/a464eaca)), the created object (mine or detonator) will be placed in the cursor.

### PATCH029: Disallow breaklights on rooftop

Vanilla behaviour: If you throw a breaklight on the rooftop, it either lights up the ground (at the same gridNo) or have no effects at all - and the breaklight is gone.

UB has a work-around ([PATCH029](https://github.com/ja2-derek/ja2-ub-comparison/commit/15f81683)), that the breaklight will not go off above the ground, and you can pick it up again.

### PATCH157: Pop-up explaining why drop-off cannot be set

Vanilla: Nothing happens if you try to change the drop-off point to an inaccessible sector.

Unfinished business ([PATCH157](https://github.com/ja2-derek/ja2-ub-comparison/commit/f2ecb49d)): Shows a pop-up explaining the location cannot be set as drop-off point. Nice to have but not as important in Vanilla, because unlike in UB, most sectors are accessible.

### PATCH027: "Don't fall through roof" hack

I have not tested this, but [PATCH027](https://github.com/ja2-derek/ja2-ub-comparison/commit/c55df3e9) seems relevant to #132, and we already have a test case there.

## Tactical AI improvements

_These might better be implemented as one option in game.json_

### PATCH218: Enemies avoid death trap ambushes

Corpses was meant to be [a warning to the AI](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/4737bf753e763c70f5ef656c18a7d429af8a9b2c/src/game/Tactical/Rotting_Corpses.cc#L1427-L1440), so the AI will [avoid running into ambushes](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b22697bf9c53239ddf6d1c35e9ed4b195c0db6d7/src/game/TacticalAI/DecideAction.cc#L1989-L1993) if they see corpses. It was not implemented correctly in vanilla, that `ubAIWarningValue` is never set. Fixed in UB ([PATCH218](https://github.com/ja2-derek/ja2-ub-comparison/commit/9d571c0d)).

### PATCH162: Prevent rooftop enemies from getting down

Rooftop is generally an advantageous position. This is especially true in Wildfire/NightOps maps, where we have some "guard post" structures. In UB ([PATCH162](https://github.com/ja2-derek/ja2-ub-comparison/commit/d39d891e)), enemies on guard on roofs are not allowed to go down.

**Comment by lynxlynxlynx** [comment]
All sounds fine, though some patches have typos. Are we just trying to whittle down the diff or can we improve?

**Comment by ja2-derek** [comment]
Patches will be manually ported. We can review and fix typos in the PRs

**Comment by selaux** [comment]
PATCH029: Disallow breaklights on rooftop sounds a little unintuitive to me. Why would breaklights not go off on the rooftop? Are there any issues with adding lights to the rooftop level?

**Comment by ja2-derek** [comment]
![breaklight_on_roof](https://user-images.githubusercontent.com/63151803/91364004-68a5ec00-e830-11ea-8b17-d80548cceb31.gif)

Yep, the function does not take any `bLevel` param, and is always assuming the ground:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/fea6115a26906ca08b461489a5eef6099f46f2e6/src/game/TileEngine/LightEffects.cc#L84

**Comment by ja2-derek** [comment]
Just checked in more details: PATCH027("Don't fall through roof" hack) is not related to #132 at all.

Not going to add this patch unless I can find a reproducible case of what it tries to fix.

**Comment by ja2-derek** [comment]
I will hold back the Tactical AI patches for now. Both are rather small patches, but requires more testing. I will do that when I am ready for my next play-through.
