### ISSUE TITLE
Proposal: Build distro-agnostic packages for Linux releases instead of Debian Package

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1213]
### What is wrong

Currently we only build a debian package for linux releases. This has the disadvantage that users of non debian-based systems have to compile the source for themselves, making the barrier to actually try out the game higher than necessary (e.g. I run arch linux, so i cannot test the PR builds as easily as I want to). Additionally it is not entirely clear with which debian-based system the deb package is actually compatible, although I personally never experienced issues with that.

### Proposal

We should have a look at more modern packaging options such as

- Flatpak
- AppImage
- Snap

I think the easiest route for us to go down is building AppImages, as there is no additional software required to run an AppImage on any Linux distribution, which makes the installation process quite easy (or even give the user the option not to install anything). Also we can keep the existing way of distributing releases via the github releases page. A disadvantage might be that we'll actually need some small code changes to support the game running from the AppImage. Also the adoption of AppImage is less than Snaps or Flatpaks respecitvely. What do you think?

PS: Here is a good comparison of the three (although it might be a little biased): https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

**Comment by ja2-derek** [comment]
I have only used Snap and I don't like it. We need to run in non-sandbox mode (for home directory and game data). So according to the (little biased) comparison, AppImage looks great.

Requiring code changes isn't really a drawback to me :)

**Comment by lynxlynxlynx** [comment]
All for AppImages, since it doesn't require a daemon and is relatively easy to set up.
