### ISSUE TITLE
Game crashed after helicopter landed. It deleted my save.

### ISSUE THREAD

**Issue by Borkason** [ja2-stracciatella/ja2-stracciatella#1216]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Created a new game, landed with the helicopter, walked around. A 'ding' sound appeared (I think because we met enemies) and the game crashed.

It also deleted my only save, deleting my character that I took quite a bit of time to create.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release |  GOG setup_jagged_alliance_2_1.12_(17794).exe   | I don't know what you mean by that |    first time I play this  |

- Windows 10

```
2020-09-13T11:55:47 [ERROR] sgp\Font.cc: Invalid character given U+0060
2020-09-13T11:55:47 [ERROR] sgp\Font.cc: Invalid character given U+0060
2020-09-13T11:55:47 [ERROR] sgp\Font.cc: Invalid character given U+0060
2020-09-13T11:56:51 [ERROR] sgp\FileMan.cc: Failed to created directory 'C:\Users\Daniel\Documents\JA2\SavedGames\Backup': Fs_createDir "C:\\Users\\Daniel\\Documents\\JA2\\SavedGames\\Backup": The system cannot find the path specified. (os error 3)
2020-09-13T11:56:53 [ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: Failed to create directory (class std::runtime_error)
2020-09-13T11:56:55 [ERROR] launcher\Launcher.cc: Command_execute "C:\\games\\JA2-Stracciatella_0.17.0\\ja2.exe" []: exited with status code -1073740791
```

I checked and the `C:\\Users\\Daniel\\Documents\\JA2\\SavedGames\\Backup"` path does exist.

I could not reproduce the issue.

**Comment by ja2-derek** [comment]
It shouldn't delete old saves. Were you playing the "Dead is dead" game mode?

**Comment by Borkason** [comment]
I was. Also Iron Man. There is an error.sav in the folder but it's not shown ingame. The Backup folder is empty.

**Comment by ja2-derek** [comment]
Just to make sure, are you checking the "DiD" tab in the load save screen?

Is the `Documents\JA2\SavedGames` folder empty also?

**Comment by Borkason** [comment]
SavedGames as an `error.sav` file and a `Backup` directory.
The *Continue Saved Game* is greyed out,

**Comment by ja2-derek** [comment]
OK. I can reproduce it.

It happens if you do not have the `JA2\SavedGames` directory at the beginning. The save will be first created at the first enemy sighting. I guess the `Backup` directory could not be created as the parent directory does not exist yet.

And when the game as crashes, the `error.sav` kicks in and creates the `SavedGames\` folder after the crash.

**Comment by ja2-derek** [comment]
You can try renaming `error.sav` to something like `SaveGame20.sav` and see if you can continue from there.

**Comment by Borkason** [comment]
Yeah, that worked! Thanks.
