### ISSUE TITLE
Editor folder instead of slf-archive

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#122]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

Right now, it seems like Stracciatella can't identify the ressource files for the map editor, if they're present as an folder within the data folder. Stracciatella looks only for the archive "editor.slf" within the data folder.
Maybe Stracciatella could also use the editor folder?

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/122

**Comment by selaux** [comment]
Stumbled across this when looking for a specific issuse. I think we can close this. The VFS should support an editor folder at the moment.
