### ISSUE TITLE
On what conditions do items disappear in sectors?

### ISSUE THREAD

**Issue by Borkason** [ja2-stracciatella/ja2-stracciatella#1230]
I revisited some sectors and most of the items I left there are gone. What are the conditions for items to disappear? What options do I have for long-term item storage?

**Comment by ja2-derek** [comment]
AFAIK items in sector can only be "stolen" by enemies ([source code](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b192d6ef4966b2f8226ec4fdc675fd766cd2fb13/src/game/Strategic/Player_Command.cc#L301-L308)). 

So you should store your important items in a sector you know enemies will not visit (e.g. far end of Grumm, San Mona if Kingpin is still alive, or underground sectors).

**Comment by JAsmine-ja2** [comment]
AFAIK Items can also be picked up during a battle by the enemy or the militia in tactical view.

> What options do I have for long-term item storage?

Standard procedure for many players (especially if they want to repair and/or sell ALL items) is to leave the items in a safe (safe = liberated and not likely to be attacked) town sector with one or two repairmen.

If you don't want to store a lot of items, only some 'important' stuff, you can hire cheap mercs (M.E.R.C. or even useless RPCs like Hamous) and assign them to your "mule squad" ;)

**Comment by Borkason** [comment]
Thanks!
