### ISSUE TITLE
Unlocked door suddenly closed and locked with no way to open.

### ISSUE THREAD

**Issue by Borkason** [ja2-stracciatella/ja2-stracciatella#1231]
### What is wrong
Merc *Deadpool* has a key that could be used to unlock the door in front of him. You can see that it worked because you can see inside the room. Suddenly the door closed and locked, both of which I didn't do, and I can't unlock it again with the key.

![grafik](https://user-images.githubusercontent.com/2971735/93721463-c78d2580-fb90-11ea-88fe-fee92afe3b32.png)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release 0.17.0 | JA2 Gold |        |        |

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5252544/SaveGame11.zip)

**Comment by ja2-derek** [comment]
The door is closed because Perko is scheduled to close the  shop at 19:00 every day. He will reopen in the morning.

I guess the door was not locked when you entered eariler.

**Comment by Borkason** [comment]
Duh.. Thanks.
