### ISSUE TITLE
Android Asset VFS layer improvements

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1248]
- [x] Make VFS case insensitive
- [x] Support mods from assets dir
- [ ] Get rid of ndk fork
- [x] Store JNI pointer internally

**Comment by lynxlynxlynx** [comment]
Is this / the ndk thing still relevant?

**Comment by selaux** [comment]
Yes. I'm actually currently looking into this. Looks like its working now after the linking update for SDL 2.0.20. Will open a PR soon.
