### ISSUE TITLE
Game hangs when loading a new music track

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1249]
### What is wrong

Currently whenever a new piece of music is loaded. This is not very noticeable on a desktop device, but on Android this hang lasts about 1-2 seconds on some devices.

My Guess is that this is caused by the `SoundConvertBuffer` logic: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SoundMan.cc#L561.

We should think about how to implement sound streaming for music pieces.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.17.0/git | any  | no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
Agreed...  this sounds like what [SDL_AudioStream](https://wiki.libsdl.org/Tutorials/AudioStream) does.

This should make #664 obsolete.

**Comment by selaux** [comment]
True, but it requires at least SDL2 `2.0.7` in order to build. I'm not quite sure if that is broadly available yet. E.g. on current Ubuntu LTS (16.04) only `2.0.4` is available as far as I can see. What about using some library to load and decode sound (and only use SDL2 for playback), e.g. https://github.com/mackron/miniaudio? That way we could also add support for `ogg`/`mp3` files.

**Comment by ja2-derek** [comment]
I think SDL version may continue to be a problem. We can require libsdl `>=2.0.8` for our `.deb` and tell people on stable/LTS to use AppImage. For development, we can try something like vcpkg or Conan to get pre-built libraries. 

That said, I am not against using another library for audio. There is also a [SDL_mixer](https://www.libsdl.org/projects/SDL_mixer/) that does similar things

**Comment by lynxlynxlynx** [comment]
Now that we have appimages, we don't need to be so stringent about dependency versions on linux. So I'm with Derek here, let's just go for it with SDL_AudioStream.

**Comment by selaux** [comment]
Sounds good to me.

**Comment by selaux** [comment]
Had a short look on this. From what I can see it is not possible to partially read WAVs using SDL2. So we would have to push the whole WAV file into the `SDL_AudioStream` at once when using only SDL2 functionality. Which brings us back to the hang again. We could use a separate thread to push to the audio stream, but then we have to mark it as unusable for the time of pushing, as the SDL2 interface is not thread safe (from my understanding). Additionally we then have the problem that the data is converted on push, so it takes up quite some memory and is not really streaming from disk.

**Comment by lynxlynxlynx** [comment]
SDL2_mixer is the next best candidate, then openal.
