### ISSUE TITLE
Enemy trapped on border of the tactical map

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#125]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

Sector A9 was attacked by 8 soldiers from the south. I killed 4 soldiers and searched for the others. This happened:
![enemy bug 3.jpg](https://bitbucket.org/repo/6zkzG5/images/2160126411-enemy%20bug%203.jpg)
The enemy soldier is trapped in the inaccessible southernmost tile of the map. He can't be seen but he can see me. He can't be shot and can't hit anything either.
He can't be revealed with ALT+E cheat but can be killed (only) with ALT+O cheat.
![enemy bug 1.jpg](https://bitbucket.org/repo/6zkzG5/images/531335157-enemy%20bug%201.jpg)

I have seen this kind of bug years ago in v1.13. I can remember how it was reported back then and fixed somehow.

I have noticed before, that in Stracciatella, all tactical maps have inaccessible tiles in the south and don't show all accessible tiles in the north.
It feels, like the player can observe too much of a map in the south but not enough in the north.
I hope, you can understand what I'm trying to express...

Savegame attached.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/125

**Comment by selaux** [comment]
Should we realease without this being fixed. It was really hard to reproduce...

**Comment by lynxlynxlynx** [comment]
I'm all for it, nobody even put this one on the roadmap. Just trivialities remain.

**Comment by derSteFfi** [comment]
I agree too.

**Comment by maxrd2** [comment]
Tweaking GridNoOnVisibleWorldTile() and changing if condition in there to dollowing solves the problem for this save, but not sure if it will stop this problem from happening again.
```
	if (... && sWorldY < (gsBLY - gsTLY - 10))
```

Will check the code that places soldiers into sector during attack.
It doesn't seem to consider GridNoOnVisibleWorldTile() before placing them. Will probably commit fix tomorrow.

**Comment by maxrd2** [comment]
Commit eee7588 (#733) should have fixed this. The game code, after getting all candidate map positions to place soldiers in sector, would call NewOKDestination() function to check if each destination is valid. And that function would return true even if tile was on invisible part of the map.

I've managed to reproduce it once in 15 tries with attached savegame. Then after patch i have retried ffew more times and it didn't happen. So maybe it's fixed and maybe it just didn't happen.

If someone wants to try some more, please load the save and fast forward the time... sector A9 will get invaded from south.
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2505363/SaveGame10.zip)
