### ISSUE TITLE
VfsFile_open performance

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1268]
Expanding https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1265#issuecomment-710732174 with profiling data. `VfsFile_open` is slow for me - I am on Linux (ext4 on SSD), with a mod that has over 20K files (extracted data files from UB). It freezes up to 60ms for every BATTLESND played (e.g. soldier acks).

## Findings

Below is a profiling session at the Tactical screen. I selected all mercs (`=`) and ordered them to walk about a few times. The majority of the time is spent on rendering (expected), and loading the sound (unexpected). One bottleneck is `DirFs` looking up files, at `stracciatella::unicode::Nfc::caseless`:

![image](https://user-images.githubusercontent.com/63151803/96328457-e2f72d80-1075-11eb-93d4-9998f8869c88.png)

---

`caseless` is doing the proper unicode "case folding", and it is understandably complex as it is supposed to work on every language. But isn't it an overkill for directory listing? I think we can just assume it's always ASCII and go for [eq_ignore_ascii_case](https://doc.rust-lang.org/std/string/struct.String.html#method.eq_ignore_ascii_case).

**Comment by ja2-derek** [comment]
There is also this [unicase](https://docs.rs/unicase/2.6.0/unicase/) crate which claims to use the faster ASCII comparison when applicable

**Comment by ja2-derek** [comment]
I did a quick test with UniCase. The latency reduced from 30-60 ms to 1-5 ms. 

```patch
diff --git a/rust/stracciatella/src/vfs/dir.rs b/rust/stracciatella/src/vfs/dir.rs
index 8c7b3cb37..71a35edde 100644
--- a/rust/stracciatella/src/vfs/dir.rs
+++ b/rust/stracciatella/src/vfs/dir.rs
@@ -5,6 +5,7 @@ use std::fmt;
 use std::io;
 use std::io::SeekFrom;
 use std::path::{Path, PathBuf};
+use unicase::UniCase;
 
 use crate::fs;
 use crate::fs::File;
@@ -48,6 +49,7 @@ impl DirFs {
                     "special path components are not supported",
                 ));
             }
+            let want_u = UniCase::new(want);
             for candidate in candidates {
                 if !candidate.is_dir() {
                     continue;
@@ -57,7 +59,7 @@ impl DirFs {
                     let is_match = path
                         .file_name()
                         .and_then(|x| x.to_str())
-                        .map(|x| want == Nfc::caseless(x).as_str())
+                        .map(|x| UniCase::new(x) == want_u)
                         .unwrap_or(false);
                     if is_match {
                         next.push(path);
```
I wonder if it could help #1249 as well.

**Comment by selaux** [comment]
I agree that unicode case folding is kind of overkill for directory listing / file access. But at the same time, it should probably only be a fallback and not the default case, as it is right now. If the exact path match exists, there should not be a need to check other paths (all the listing files is quite expensive as well). `fs::resolve_existing_components` already does it that way.

Can you have a look at https://github.com/ja2-stracciatella/ja2-stracciatella/tree/unicode-normalization-speedup, if this improves the issue for you? There I tried to do unicode normalization only when absolutely necessary. For me this gets rid of most of the unicode normalization stuff in the profile (but `Nfc::caseless` still is there).
