### ISSUE TITLE
Log window is empty (just black)

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1269]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
The log window is empty. It's just black.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold English  |    no    |    yes     |
![Untitled](https://user-images.githubusercontent.com/670935/96330966-b46b5980-1059-11eb-82f7-3c6971de9b30.png)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
Can you try pressing the Enter key at the log window?

**Comment by askondro** [comment]
no. nothing happens.

**Comment by ja2-derek** [comment]
Are you using Windows?

Is the game still working for you? I see your screenshot and it looks normal to me.

**Comment by lynxlynxlynx** [comment]
There's a log window, but only in the strategic view. Am I missing something?

**Comment by askondro** [comment]
I'm using windows, yes. The game is working fine. I just remember there was a log window.
For example, when somebody repairs an item, there would be a log message.
In strategic mode, there are also no logs.

Maybe my memory is bad. I will close this issue.

**Comment by lynxlynxlynx** [comment]
In tactical, the messages are displayed above the UI and fade away relatively quickly.
