### ISSUE TITLE
Supporting extra save game data from Lua scripts

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1272]
There is a need for mod Lua scripts to persist game states. We need a way for the mod to keep track of the game state, for anything outside of  the basic facilities (e.g. Facts, Quests) provided by the base game.

## Example use-cases

- Mappings - e.g. quote being said per soldier. It is much better and readable to use a real map than a long list of `FACT_X_HAS_DONE_Y`.Also there are only 500 `NUM_FACTS` slots and not enough for multiple mappings.
- Persisting non-boolean values like sector IDs, counters or amounts, though we might not need this often. Facts are UINT8, but they usually take `enum` or `BOOLEAN` value.
- Mods can opt to use this instead of Facts for everything, so as not to worry about assigning Fact IDs and the limit of `NUM_FACTS`

## Summary

- Allow scripts to save arbitrary, key-value pairs into save files.
- Using the same files so we don't need to manage another file (e.g. if we created an extra `.json` alongside the `.SAV` files.
- Re-purpose a few bytes in the [Air_Raid data range](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/fd8e3f44719c59ff36228ddf29942fd6b862ad52/src/game/SaveLoadGame.cc#L398-L399) to indicate the size of the extra data. Avoid the first bytes which is should be always `0` but would be used by older versions and vanilla.
- Append the data from scripts to the end of the save files.
- Increment [SAVE_GAME_VERSION](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/fd8e3f44719c59ff36228ddf29942fd6b862ad52/src/game/GameVersion.cc#L23) to `101`. This can be done but not necessary for this to work.

## Compatability

- Only to be activated on request by mod scripts (via an Observable)
- If no mod has requested to save data, we do not append to the end of the save, and the file will look exactly the same as before

## Details

- C++ does not allow dynamic typing, so the types must be fixed. We can use a `std::map<ST::string, int32_t>` and this should give us enough flexibility.
- Lua side can do nested tables, but on save, the tables must be flattened to a map from string to integer. I don't see a real need for string and float values, but it can be worked around if really needed. For example:
```lua
save_data_nested = {
    FavouriteMerc = MercsEnum.BARRY,
    QuoteUsed = {
      MercsEnum.BARRY = {
        QUOTE_101 = true,
        QUOTE_102 = false,
      },
    },
    If_We_Really_Want_Strings = {
        "If_You_Must",
    },
    Float_Value = {
      12.34,
      0.5
    },
}

same_data_flattened = {
    FavouriteMerc = 0,
    ['QuoteUsed.0.QUOTE_101'] = 1,
    ['QuoteUsed.0.QUOTE_102'] = 0,
    ['If_We_Really_Want_Strings.If_You_Must'] = 0,
    ['Float_Value.1'] = 12340,
    ['Float_Value.2'] = 500,
}
```

**Comment by selaux** [comment]
Some notes from me:

> C++ does not allow dynamic typing, so the types must be fixed. We can use a std::map<ST::string, int32_t> and this should give us enough flexibility.

As we have RapidJson, cant we somehow convert that nested map into JSON and just store that within the save game file (ideally in a compressed way)?

> Re-purpose a few bytes in the Air_Raid data range to indicate the size of the extra data. Avoid the first bytes which is should be always 0 but would be used by older versions and vanilla.

I would just append the new data instead. I think we can spare those 4 bytes to store the data length :wink:.

Does it make sense to also store the mods (and mod versions) that are currently enabled in the save game? I dislike the current way we handle interaction between mods and save games. E.g. when I enable a music-only mod such as `o-fortuna`, I cannot continue using my old save games without manually copying them into the new save game folder. This would require some kind of mod manifest though, where it specifies the mod version (but that might make sense anyways).

Otherwise sounds good to me.

**Comment by ja2-derek** [comment]
Thanks for the great input :)

RE JSON - the problem is to pass the nested table data from Lua to C++. It is doable if we embed and bundle a Lua JSON library, and then pass the JSON string across. But if it is already flattened and statically-typed, it don't make too much difference between `memcpy` and JSON encode. 

RE appending data at the end - I thought to re-purpose a range just to ensure that new saves can be loaded in Vanilla. I agree that it's much cleaner to simply append. It is easy to test if the vanilla game can tolerate and ignore extra data at the end of the file.

RE storing enableds mods in save - that makes a lot sense. We have already had some GitHub issues about mods. It will help to know what mods the save had.

RE mod manifest - a big YES from me, and I always wanted to have something like that. Doing that properly will need some more thoughts. Mod versioning, conflicts and save compatibility (with each other and with base vanilla) are something that comes to mind.
