### ISSUE TITLE
TravisCI Mac builds no longer free

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1276]
Heads up to the new TravisCI pricing model. I understand they no longer run Mac builds for free.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Maybe we should look at building nightly with GitHub action again 

[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

**Comment by lynxlynxlynx** [comment]
Appears so, let's migrate.

**Comment by ja2-derek** [comment]
I believe the easiest way is to make the `nightly` push with a Personal Access Token (see also https://github.com/ja2-stracciatella/ja2-stracciatella/issues/873#issuecomment-723438614). To proceed, I need an org admin to add the tokens as [encrypted secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets):

1. [Personal Access Token](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token) from any user with write repo access (maybe @madlab-bot ?). This token is used to push `nightly` branch, or directly run the workflow via GitHub API if push doesn't work.

2. Coverity scan token. We can migrate the coverity build into another scheduled GitHub Action. Something like [this](https://github.com/ruby/actions-coverity-scan/blob/master/.github/workflows/coverity-scan.yml).

**Comment by ja2-derek** [comment]
A Coverity scan was successfully submitted earlier today ([build](https://github.com/ja2-stracciatella/ja2-stracciatella/actions/runs/390820585)). But the Coverity dashboard is still not updated, and the [badge](https://scan.coverity.com/projects/8431/badge.svg?flat=1) still says "Coverity Failed".

Are you able to get any further information from Coverity side?

**Comment by lynxlynxlynx** [comment]
You should have the same access, but anyway, it says the last ok build was in october and anything later failed due to compilation errors:
```
Last Build Status: Failed. Your build has failed due to the following reason. Please fix the error and upload the build again.

Error details: 
invalid literal for int() with base 10: "tail: cannot open '/opt/workspace/ja2-stracciatella_ja2-stracciatella/cov-int/build-log.txt' for reading: No such file or directory
```
Like the results weren't successfully submitted, even though the upload was fine.

**Comment by ja2-derek** [comment]
That explains it. Thank you. 

But where do you get that error details?

**Comment by lynxlynxlynx** [comment]
Top of the page:
https://scan.coverity.com/projects/ja2-stracciatella-ja2-stracciatella?tab=overview

**Comment by ja2-derek** [comment]
Nothing for me. Probably admin-only.

There are only the Coverity Scan badge and then the heading "Analysis Metrics".

**Comment by lynxlynxlynx** [comment]
Now that it's fixed for sure. I've upped your privilege level, so if it ever happens again, you'll hopefully see it.
