### ISSUE TITLE
Game crashes when trying to enter Drassen Airport sector

### ISSUE THREAD

**Issue by JRF-github** [ja2-stracciatella/ja2-stracciatella#1288]
Load the attached savegame file, unpause the game, then enter the battle. Game will terminate with
the message [ERROR] sgp/SGP.cc: Game has been terminated due to an unrecoverable error: openGameResForReading: VfsFile_open "tilesets/17/t/grass.sti": entity not found

This is with the current master branch and was caused by [this change](https://github.com/ja2-stracciatella/ja2-stracciatella/commit/d08afb162f3685420dde4a24db9e8fd7a4e4b0e9#diff-e0e4d0953818444557b3c1e5003d15e6c8ec33eb58546d1667cca1127c7b9eed): in the case of this crash, res.tilesetID is 17, but there is no file 17/t/grass.sti in Tilesets.slf, so the error message is correct.  Before the change this would have used 0/t/grass.sti, which is working fine. I am using the german v1.05 data files, but that should not make any difference.

[SG10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5672579/SG10.zip)

**Comment by lynxlynxlynx** [comment]
Thanks for the deatiled report! Looks like we need to use a fallback in such cases.

**Comment by ja2-derek** [comment]
It may also be https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1218  that broke the tileset fallback. I will step through the code and find out which  case  it is.

**Comment by selaux** [comment]
I think it is. I fixed something like this in the (still open) VFS PR: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1275/commits/5e023eb9f7fe3b40b5b31b711a7a84805d07d372

**Comment by ja2-derek** [comment]
That commit looks good to me. Can we cherry-pick it to fix this crash @selaux?

**Comment by selaux** [comment]
Yes, feel free. I'm going to remove it from the PR when I have some time then...

**Comment by lynxlynxlynx** [comment]
No need, if the same thing is merged sooner, it will just be a noop in that branch.
