### ISSUE TITLE
Does ja2-stracciatella support old mods?

### ISSUE THREAD

**Issue by brechtm** [ja2-stracciatella/ja2-stracciatella#1290]
Is is possible to play, for example, Urban Chaos using ja2-stracciatella? I couldn't find any information on whether that mod requires JA2 or JA2UB. If it's the latter, I understand #254 will first need to be completed?

As some data has been externalized in ja2stracciatella, I guess any mod needs to be ported to JA2S by doing the same?

In any case, great to see this project is still being maintained!

**Comment by lynxlynxlynx** [comment]
Considering our history entry, it looks like it should just work:
https://ja2-stracciatella.github.io/history/#10-urban-chaos-2003

**Comment by ja2-derek** [comment]
I think Urban Chaos is more than a data file mod, coming with its own executable. So it should be possible to port it  if we know what was changed in the UC executable.

**Comment by ja2-derek** [comment]
Actually I am able to get in game with Stracciatella.

Get a fresh copy of vanilla JA2 (not  Straciatella) and  install Urban Chaos, then copy the altered Data/ directory into a Stracciatella mod directory.

So far I noticed some data differences, like town names, email sender names, item names, etc. But it seems playable

**Comment by brechtm** [comment]
> I think Urban Chaos is more than a data file mod, coming with its own executable. So it should be possible to port it if we know what was changed in the UC executable.

I see there was a 1.13 update for UC, so we might be able to find out somehow...

> Get a fresh copy of vanilla JA2 (not Straciatella) and install Urban Chaos, then copy the altered Data/ directory into a Stracciatella mod directory. Also delete the `INTRO/` or it will crash.

Thanks, I was able to get the game to start like this.

> So far I noticed some (hard-coded) data differences, like town names, email sender names, item names, etc. But it seems playable

Are these are contained in the custom UC executable? Have these been externalized already? How much work do you think would be involved in making a UC mod for JA2S? Any other pointers are always welcome...

One problem with these mods these days is that one has to go hunting on forums for information on to get them to work. It would be great if they could easily be installed into JA2S.

**Comment by ja2-derek** [comment]
JA2S does not support maps and data files from 1.13 because of all the new fancy features added. We should probably start with the "UC Classic" maps and files. 

I expect the work is mostly about 1) understanding what was changed, 2) porting mod data to JA2S format, and 3) debugging crashes.

It would be straight-forward if we can somehow get the source/patches applied to the JA2_UC executable. I suspect the UC installer is mostly for patching internal data - items, stats, strings, etc. I think 1.13 XMLs is a good starting point, but I don't know how much it differs from the classic version.

I ran into a crash soon after clearing the first sector. It needs some investigations. I hope it is just something simple like missing data.

**Comment by brechtm** [comment]
> JA2S does not support maps and data files from 1.13 because of all the new fancy features added. We should probably start with the "UC Classic" maps and files.

I meant to say that because there is a 1.13 version of UC, there might be a higher chance of finding the UC source files.

> It would be straight-forward if we can somehow get the source/patches applied to the JA2_UC executable.

I'm not sure where we would be able to find the UC source files. Perhaps I can ask over at the Bear's Pit forums?

> I suspect the UC installer is mostly for patching internal data - items, stats, strings, etc. I think 1.13 XMLs is a good starting point, but I don't know how much it differs from the classic version.

The UC distribution comes with alternative installation method instructions. You need to simply extract the ZIP files over an existing JA2 installation, so there is no patching going on. The _JA2_UC.exe_ is included as-is.

Diffing a vanilla JA2 install and the UC install shows that it mostly adds new files and overwrites just a couple. These are the files that are overwritten:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/652887/101988060-d23eee80-3c97-11eb-9e93-3dfd44e690bc.png">

**Comment by ja2-derek** [comment]
No harm asking, but I would doubt if  the original UC developers are still around.  We can also dive in 1.13 source code history to see what changes have been made for UC.

Based on the diff you posted, it looks like we are good to use the Data/ files. That also explains the crash with INTRO/ as you see the SMACK DLL is altered or upgraded.

If no source is available, we can start with the UC-1.13 table data XML, compare the contents with the corresponding version of Data-1.13. We should be able to get a sense of what map and item changes there are.

Then, we might be able to get basic UC support if we can pin down the crashes.

**Comment by ja2-derek** [comment]
We deviated from the original question.  Let's open another issue for Urban Chaos support.

Back to the original question:

- Data file only mod for plain JA2 (if any) should work on Stracciatella  - as long as it does not require a patched the executable
- Mods with modified executable (e.g.  Urban Chaos) requires porting - we need to somehow convert the modified data and code into externalized data (JSON or Lua)
- Unfinished Business mods (e.g. SOG69) is not yet supported (#254). But UB tilesets and items are supported already supported.
- Mods for 1.13 do not work on Stracciatella, and require conversion, as the items and map formats are different
