### ISSUE TITLE
Cannot board Heli in Central SAM I8

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#1293]
I have conquered the Central SAM in I8 next to Cambria. There are no enemies in this sector. The Helicopter is also in this sector

### What is wrong
It is impossible to board the helicopter. The `VEHICLE` Icon is grayed out.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.17.0 | JA2 1.12 GOG English  |    probably not    |    yes   |

**How to reproduce the bug:**
Try to `ASSIGN` any of the characters of `SQUAD 1` in I8 to `VEHICLE`

**Workaround**
Fly Helicopter to another sector and come back.

**Operating system**
MacOS Mojave 10.14.6

**Screenshot**
![vehicle](https://user-images.githubusercontent.com/39365524/102379710-6fb35e80-3fc7-11eb-91f2-6f2782bc142f.png)

**Savegame**
[savegame_heli.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5704073/savegame_heli.zip)

**Comment by ja2-derek** [comment]
Hey, I think the heli is still 4 minutes away from arriving the sector. If you look closely you see the helicopter icon is a tiny bit off.

**Comment by nemuc** [comment]
Thanks. You are right. Everything works, if waiting a bit for the heli.

As far as I remember, that was not the case before reloading.Then passing the time didn't help. But after loading the savegame this resolves the issue.

I am closing the issue, because I can't reproduce it.

**Comment by ja2-derek** [comment]
Yeh, happened to me before as well, that something is definitely wrong, but looks OK after re-loading and cannot be reproduced.
