### ISSUE TITLE
Build on mingw64 - Error with copying file stracciatella_c_api.lib

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1296]
warning: 6 warnings emitted

   Compiling stracciatella_c_api v0.1.0 (C:\msys64\home\askon\ja2-stracciatella\rust\stracciatella_c_api)
       Fresh stracciatella_bin v0.1.0 (C:\msys64\home\askon\ja2-stracciatella\rust\stracciatella_bin)
     Running `C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\release\build\stracciatella_c_api-37c0276cab9976c0\build-script-build`
     Running `rustc --crate-name stracciatella_c_api --edition=2018 'stracciatella_c_api\src\lib.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --emit=dep-info,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=b86b36c7e04ae56e -C extra-filename=-b86b36c7e04ae56e -C rpath --out-dir 'C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps' --target x86_64-pc-windows-gnu -C 'linker=C:/msys64/mingw64/bin/gcc.exe' -L 'dependency=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps' -L 'dependency=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\release\deps' --extern 'byteorder=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps\libbyteorder-57ee542adfefaf61.rlib' --extern 'hex=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps\libhex-905267d2b7a98abb.rlib' --extern 'libc=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps\liblibc-12354b246c435883.rlib' --extern 'log=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps\liblog-f7a339c5893a380c.rlib' --extern 'stracciatella=C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target\x86_64-pc-windows-gnu\release\deps\libstracciatella-a078c75db77825ea.rlib' --print=native-static-libs -L 'native=C:\Users\askon\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'`
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -ladvapi32 -lwinapi_advapi32 -lwinapi_cfgmgr32 -lwinapi_gdi32 -lwinapi_kernel32 -lwinapi_msimg32 -lwinapi_ole32 -lwinapi_opengl32 -lwinapi_shell32 -lwinapi_user32 -lwinapi_winspool -ladvapi32 -lws2_32 -luserenv

    Finished release [optimized + debuginfo] target(s) in 2.00s
Built target cargo-build-release
**Error copying file (if different) from "C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target/x86_64-pc-windows-gnu/release/stracciatella_c_api.lib" to "C:/msys64/home/askon/ja2-stracciatella-build/lib-stracciatella/lib/libstracciatella.a".**
make[2]: *** [dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/build.make:83: lib-stracciatella/include/stracciatella.h] Error 1
make[2]: *** Deleting file 'lib-stracciatella/include/stracciatella.h'
make[1]: *** [CMakeFiles/Makefile2:1124: dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by selaux** [comment]
Hi, thanks for the report. Can you check what files are actually in `C:/msys64/home/askon/ja2-stracciatella-build/dependencies/lib-stracciatella/target/x86_64-pc-windows-gnu/release/` after compiling? And what version of the rust compiler are you using? I'm asking because different versions might produce differently named artifacts in that directory. To be safe that this is not the case you can try to use rust/cargo 1.40.0...

**Comment by askondro** [comment]
Hello,

The version of rust is:

```
$ rustc --version
rustc 1.48.0
``` 

here is the content of the folder:

```
drwxr-xr-x 1 askon askon        0 Dec 20 19:12 build
drwxr-xr-x 1 askon askon        0 Dec 20 19:16 deps
drwxr-xr-x 1 askon askon        0 Dec 20 19:12 examples
drwxr-xr-x 1 askon askon        0 Dec 20 19:12 incremental
-rw-r--r-- 1 askon askon     2031 Dec 20 19:13 ja2-resource-pack.d
-rwxr-xr-x 2 askon askon 35704450 Dec 20 19:13 ja2-resource-pack.exe
-rw-r--r-- 1 askon askon     1948 Dec 20 19:13 libstracciatella.d
-rw-r--r-- 2 askon askon 16074670 Dec 20 19:13 libstracciatella.rlib
-rw-r--r-- 2 askon askon 46186872 Dec 20 19:16 libstracciatella_c_api.a
-rw-r--r-- 1 askon askon     3150 Dec 20 19:13 libstracciatella_c_api.d
```

**Comment by selaux** [comment]
So if you want to build with rust `1.48.0` you probably need to comment out [this if for MinGW](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/dependencies/lib-stracciatella/CMakeLists.txt#L12). Otherwise you need to install rust `1.40.0`.

**Comment by askondro** [comment]
This configuration works for me:

```
if (MINGW)
    set(RUSTC_STATICLIB_PREFIX "lib")
    set(RUSTC_STATICLIB_SUFFIX ".a")
else()
    set(RUSTC_STATICLIB_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
    set(RUSTC_STATICLIB_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
```
