### ISSUE TITLE
Talon can be loaded with multiple Grenades

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#130]
Originally reported by: **misanthropos (Bitbucket: [misanthropos](http://bitbucket.org/misanthropos), GitHub: [misanthropos](http://github.com/misanthropos))**

----------------------------------------

In this SavedGame Shank has a C7 equipped with a loaded talon and another loaded talon in his pocket.
Now you can add the other talon to the C7 and it results in a C7 equipped with talon and 2 Grenades. Take the empty talon, fill it and you can fill it up that way up to 3 Grenades and one can shoot them out one after another.

I guess this issue should not be resolved :) It could be fun!!!

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/130

**Comment by derSteFfi** [comment]
Build/Tactical/Items.cc:1007 (ValidItemAttachment)
```C
	// can't have two of the same attachment on an item
	/*if (FindAttachment( pObj, usAttachment ) != ITEM_NOT_FOUND)
	{
		fSameItem = TRUE;
	}*/
```
I don't know why this commented out. removing the comment solves this with correct on screen messages. ('You already have one of those attached'). Of course, the Talon is also not attached when this is commented out, but later in the process, starting at Items.cc:2007 (AttachObject)
```C
		UINT16 const temp_item   = target.usAttachItem[attach_pos];
		UINT16 const temp_status = target.bAttachStatus[attach_pos];

		target.usAttachItem[attach_pos]  = attachment.usItem;
		target.bAttachStatus[attach_pos] = attachment.bStatus[0];

		// Transfer any attachment (max 1) from the grenade launcher to the gun
		if (attachment.usItem          == UNDER_GLAUNCHER &&
				attachment.usAttachItem[0] != NOTHING)
		{
			INT8 const second_attach_pos = FindAttachment(&target, NOTHING);
			if (second_attach_pos == ITEM_NOT_FOUND)
			{ // Not enough room for all attachments - cancel!
				target.usAttachItem[attach_pos]  = NOTHING;
				target.bAttachStatus[attach_pos] = 0;
				return false;
			}
			else
			{
				target.usAttachItem[second_attach_pos]  = attachment.usAttachItem[0];
				target.bAttachStatus[second_attach_pos] = attachment.bAttachStatus[0];
				attachment.usAttachItem[0]  = NOTHING;
				attachment.bAttachStatus[0] = 0;
			}
		}
```
This was responsible for 'loading' the grenade although the original talon was already loaded. I'd vote for reactivating the part that recognises items of the same type. Opinions? Does anyone know why it was commented out?

**Comment by lynxlynxlynx** [comment]
It was commented out from the start, so we should just make it less bad.
