### ISSUE TITLE
No notification that squad has noticed Hamous in sector

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#1303]
In Jagged Alliance 2 Vanilla there is a notification if your squad has noticed an important person such as Hamous or Skyrider. It is in this format: `Squad x has noticed someone in sector Y.`

Here is a [video](https://www.youtube.com/watch?t=444&v=w91TCz3-6aQ) example from a Jagged Alliance 2 1.13 play-through.

### What is wrong

In two games I didn't find Hamous even though I was systematically searching for him using this [map](http://ja2v113.pbworks.com/f/1282624892/arulco_map_legend.jpg)

Instead of relying on the notification, I had to manually search the sector in tactical mode to find Hamous in Sector F12.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.17.0 (2020-08-03) | JA2 Gold English  |    no    |    unknown    |

**save game**
[SaveGame05.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5750717/SaveGame05.sav.zip)

How to reproduce:
1.  Enter sector F12
2. You should get the notification.
3. Go to the northern end of the road to verify that Hamous is indeed in F12.

**operating system**:
macOS Mojave 10.14.6

**Note**:
I think this topic was already discussed here, but I haven't been able to find it

**Note 2**:
I have already visited Sector F12 before but didn't receive the notification either.

**Comment by ja2-derek** [comment]
There is no prompt if the squad is on the heli. It works if the squad enters on foot. The corresponding code segment below. The check if skipped if the squad is in heli:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/bae4a7e949ff0ee4327f8cf7c8c2d92c91f7aefc/src/game/Strategic/Strategic_Movement.cc#L3560-L3594

I don't know if this (noticing NPC on heli) is vanilla behaviour or added feature in 1.13.

**Comment by ja2-derek** [comment]
Let us know if you have further questions.
