### ISSUE TITLE
Fredo refuses to repair extended ears

### ISSUE THREAD

**Issue by JRF-github** [ja2-stracciatella/ja2-stracciatella#1309]
With the attached saved game, ask Fredo to repair Steroid's extended ears and he'll refuse, telling you that he only works on electronics.

git bisect points the finger at commit 296189384a378af94ceb4d31a0196e6a98d66f31.
[QuickSave.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5816171/QuickSave.sav.gz)

**Comment by ja2-derek** [comment]
I will take a look. Thank you for reporting and tracking this down.
