### ISSUE TITLE
Linking fails on gentoo/amd64

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#1316]
### What is wrong
Tried to compile the latest version on gentoo on AMD64 machine.
It failed with 
```
Linking CXX executable ja2
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/libSDL2.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ja2.dir/build.make:5989: ja2] Error 1
make[1]: *** [CMakeFiles/Makefile2:747: CMakeFiles/ja2.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

The thing is - the right version of SDL is in /usr/lib64. After I manually edit the linker command line to change that, the build succeeds.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  310e2403a | eg. JA2 En  |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Well, what installed SDL2 into /usr/lib/ then?

**Comment by akdjka** [comment]
There's the 32-bit variant. I suppose something needed it.

**Comment by lynxlynxlynx** [comment]
Looks like our lookup will need some work, it looks like it just takes the first thing it finds: 
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/cmake/FindSDL2.cmake

**Comment by akdjka** [comment]
Now that you posted the link for the file, I could try to implement architecture detection.

**Comment by lynxlynxlynx** [comment]
I wonder why we have our own file at all, since cmake has an internal FindCMake since some version (might need to bump the minimum required).

**Comment by misanthropos** [comment]
I have tried to compile a quite recent HEAD and it worked to compile in gentoo.
What exactly are your referring to by latest? There is an official gentoo build for 17.0

**Comment by lynxlynxlynx** [comment]
Closing old report, please reopen if you still have build issues.
