### ISSUE TITLE
Game hanging after an attack

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#1318]
To reproduce:
1. Load the attached save.
2. Johny runs in the direction of an enemy. Run to hit him with a crowbar.
3. As Johny proceeds with the attack, he notices another enemy farther away and stops to ask ask what to do. Continue and hit the enemy.
4. The enemy gets damage, but the cursor turns to a clock and stays like that.

Note that if I save the game after Johny stops to ask what to do and then reload - the issue doesn't appear.

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5900397/s.zip)

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  310e240 | JA2 EN  |    ?    |    ?     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
This should happen whenever a merc is halted from sighting ([HaultSoldierFromSighting](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/464b568a64e6b823500fced9bc9e66b38b5f6ac1/src/game/Tactical/Soldier_Control.cc#L7379)) right at before a melee attack. 

The "attack busy count" was incremented once at step 2, incremented again at step 3, and then decremented once at step 4. After step 4 we have busy count of 1, and so the game gets stuck in the "busy" state.

**Comment by ja2-derek** [comment]
This is very similar to the issue address by Unfinished Business [PATCH201](https://github.com/ja2-derek/ja2-ub-comparison/commit/f523161d), but for punching/crowbar.
