### ISSUE TITLE
Make save game location configurable on Android

### ISSUE THREAD

**Issue by nedsed** [ja2-stracciatella/ja2-stracciatella#1337]
I have tested JA2S version 0.17.1 on Android 9 on a Galaxy S8 and while it ran pretty well, I noted that there is no way to access the savegames on a non-rooted device. This is kind of unfortunate because that way you cannot move your game progress back and forth between PC and smartphone, old savegames cannot be continued etc.

I'm not a Android developer but couldn't you add an option for a user defined folder for savegames just like the chooser for the game data directory? That way savegames could be stored and loaded from an unprotected location.

Thanks for keeping this game alive!

**Comment by selaux** [comment]
Yes I think making it configurable on Android should be possible.
