### ISSUE TITLE
Keyboard & mouse buttons for Android

### ISSUE THREAD

**Issue by nedsed** [ja2-stracciatella/ja2-stracciatella#1338]
Still testing JA2S version 0.17.1 on Android 9 on my Galaxy S8, I found myself struggling with not having access to the inventory in the tactical screen. Main problem is that there is no mouse right-click possible, but also that there is apparently no way to open the keyboard to use the shortcut instead.

Since the screen format is 4:3 for the game there would be plenty of screen space left to add some buttons for right-click and toggling the keyboard, what do you think?

**Comment by selaux** [comment]
Yeah. The controls haven't been touched yet for the Android version, so basically right now a keyboard and mouse are required to control it. I will close this nonetheless as we already have a bug open where we try to find a good concept, see #1250. I will add your feedback there.
