### ISSUE TITLE
Feature request: Is it possible to move launcher configuration and saves under user accessible location for Android version.

### ISSUE THREAD

**Issue by krukhlis** [ja2-stracciatella/ja2-stracciatella#1340]
Hi guys, 
One of the earliest versions of Stracciatella for Android was keeping launcher config and savefiles under user accessible location (e.g. close to Data folder). So everyone can access it and change( copy savegames from another locations, edit configs, etc). 
Unfortunately, modern version keeps everything under private application storage in Android which is not accessible without Root permissions. Is it possible to change Android Launcher and Game to keep configs and savegames under user accessible location? Or at least make it configurable through Android Launcher UI. 

Version tested: 0.17 release and 0.17.x nightlies

**Comment by selaux** [comment]
Thanks for your feedback. I would go with making it configurable through the Launcher UI which would be #1341. Savegame location is in the backlog as well and tracked in #1337. So I would close this one if you don't mind. If you do, please reopen.
