### ISSUE TITLE
Amazing code size comparison

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1342]
Just an interesting point from a chat with the 1.13 discord guys. It made me wonder how much the project bloated / how much we improved. As a proxy, here are the line numbers (c, c++, rust):

ja2s: 851,152
1.13: 2,184,310

So we're more than twice as lean! 🥇 

Ran `find src/ sgp/ rust/ -type f -regextype egrep -iregex ".*.(cpp|cc|c|h|rs)$" | xargs wc -l | awk '{ a+=$1 } END { print a }'` for us and a similar one for their repo, excluding their ext/ with external deps.

**Comment by ja2-derek** [comment]
Also there are many 1.13 features and mods released but not maintained since. We must think about future maintenance as we add new fixes and improvements.

**Comment by lynxlynxlynx** [comment]
Yes, 1.13 has been plagued by a lack of coordination and vision for a long time. We are lucky to have a simpler job, but the same perils are present.

**Comment by lynxlynxlynx** [comment]
Pulled the original down from:
https://github.com/videogamepreservation/jaggedalliance2

Result:
1222384

So even with all the new features, we're still 31% LOC lighter than vanilla. :)

I'll go put these stats somewhere on the site — too good not to share.
