### ISSUE TITLE
Use a Rust FFI library

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1343]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

I just came across this library: https://github.com/dtolnay/cxx

It is a wrapper around Rust FFI. It can generate binding on both C++ and Rust side, shares data structures across and handles the some of the memory management.

### Advantages

- The code seems to be cleaner and more idiomatic on both sides - no more `RustPointer<VecCString> args(VecCString_create());`
- Less binding / wrapper code 
- May reduce the amount of `unsafe` Rust code
- Not exactly related to cxx, but if we can automate the binding generation, we can liberally use Rust crates in C++.

### Example

- The Rust Vec wrapping we have: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/stracciatella_c_api/src/c/vec.rs
- `Vec` has a pre-defined binding in the cxx library: https://cxx.rs/binding/vec.html

### More links

- [Context](https://cxx.rs/context.html) of cxx 
- Auto-generation of cxx bindings : [autocxx](https://github.com/google/autocxx)

**Comment by lynxlynxlynx** [comment]
Still looks a bit in flux, so I only worry we don't switch ourselves into a corner.

**Comment by selaux** [comment]
I had a look at cxx as well when it was first released, as I dislike the C-style and all the manual stuff we have for FFI right now as well. I would like to keep the clear separation between (mostly) idiomatic Rust code and FFI interface that we have right now though. So basically the two crates `stracciatella` and `stracciatella_c_api`. This is afaik currently not supported by cxx right now, but should be some time in the future: https://github.com/dtolnay/cxx/issues/496.

Currently we also only have one direction of FFI calls: C++ to Rust. I'm not sure if it is a good idea to make it usable both ways, as it might lead to too much coupling between the two (C++ calls Rust which calls C++ which again calls Rust and so on).
