### ISSUE TITLE
Feature Request: Multiple IMP's minimod and other select features of the 1.13 megamod as minimods

### ISSUE THREAD

**Issue by kinkock** [ja2-stracciatella/ja2-stracciatella#1344]
I would like to have a mod to create multiple IMP mercs, with the maximum being either the portraits or voice lines varying dynamically on whichever is lower (the default without other mods would be 6 like in the 1.13 megamod).

I think it would also be nice to include other select features as minimods as well, maybe even the megamod itself.

Apparently, only contributors are authorized to change labels on github rather than both them and the submitter.

**Comment by lynxlynxlynx** [comment]
1.13 is way out of scope, so no chance.

Multiple IMPs: sure, possible, but since it requires code changes, it can't be a mod.

**Comment by lynxlynxlynx** [comment]
Closing in favour of  #1516, which has more info.
