### ISSUE TITLE
Launcher: preload all mods

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1352]
Now it looks like only one mod is packaged, but actually all are available, one just has to click on Add first.

EDIT: hmm, that affects the save dir name, even if the mods are not enabled. Not sure if it matters.

**Comment by selaux** [comment]
I think it is just the UI that is confusing here. As far as I remember all mods in the list are enabled, the checkbox is only there for moving / removing mods in / from the list. See [here](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/launcher/Launcher.cc#L152).

**Comment by lynxlynxlynx** [comment]
I guess it would be better if it was a different type of widget. Don't know if FLTK has it, but just an expanded dropbox, so you could still select lines for the buttons to work, but there'd be no confusion about the checkboxes.
