### ISSUE TITLE
AppImage does not start in Debian 10 => libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by christianbaun** [ja2-stracciatella/ja2-stracciatella#1360]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
When trying to start the AppImage of ja2-stracciatella 0.18 in Debian 10 (stable), it results in the error message that the library libstdc++.so.6 lacks support for GLIBCXX_3.4.26.

```
$ ./ja2-stracciatella_0.18.0-git+ebc73ce_x86-64.AppImage 
./ja2-stracciatella_0.18.0-git+ebc73ce_x86-64.AppImage: 
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' 
not found (required by ./ja2-stracciatella_0.18.0-git+ebc73ce_x86-64.AppImage)
```

### Some system information:

```
$ cat /etc/debian_version 
10.9
```

I use Debian stable (buster = 10). Just the kernel is from the buster backports:

```
$ uname -r
5.10.0-0.bpo.5-amd64
```

```
$ gcc -v
...
gcc version 8.3.0 (Debian 8.3.0-6) 
```

```
$ dpkg -l | grep libstdc++6 | grep amd64
ii  libstdc++6:amd64          8.3.0-6          amd64        GNU Standard C++ Library v3
```

```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
...
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by lynxlynxlynx** [comment]
As you have found out, your stack is too old. Installing gcc9 should fix it, while on our end we could consider building the image with an older gcc. We're using c++17 features, so that may not be ideal though.

**Comment by ja2-derek** [comment]
But that is AppImage not the .DEB. Shouldn't everything be self-contained?

And we may need to check if the .deb has the correct libc++ version requirements.

**Comment by lynxlynxlynx** [comment]
Like with static binaries, glibc version still matters.

**Comment by ja2-derek** [comment]
These might help: 
- https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#libstdcso6
- https://github.com/darealshinji/AppImageKit-checkrt/

**Comment by lynxlynxlynx** [comment]
Sounds a bit over the top, so I still suggest we just try building with gcc8.

**Comment by christianbaun** [comment]
Maybe it works. 

C++17 support in gcc8 looks good (complete?). 

[https://gcc.gnu.org/projects/cxx-status.html#cxx17](https://gcc.gnu.org/projects/cxx-status.html#cxx17)

**Comment by ja2-derek** [comment]
We upgraded to C++17 for `std::variant` and Lua support via Sol (v3). These should work with GCC 8.

We added usage of `<filesystem>` recently. It is implemented in GCC 9, but we also have the `<experimental/filesystem>` fallback for GCC 8.

**Comment by ja2-derek** [comment]
@christianbaun, could you try out the AppImage build with gcc-8 (#1361)? It is in the artifacts of this [build](https://github.com/ja2-stracciatella/ja2-stracciatella/actions/runs/801254042).

**Comment by christianbaun** [comment]
The new `ja2-stracciatella_0.19.0-1361pullrequest+bec5d9a_x86-64.AppImage` works fine in Debian 10. I installed Jagged Alliance 2 from a CD (two decades old I think) with wine and told ja2-stracciatella to use the folder `/home/<username>/.wine/drive_c/Program Files (x86)/Ja2` as JA2 Game Direcory.
