### ISSUE TITLE
Crash when doing aimed burst to certain NPCs

### ISSUE THREAD

**Issue by MrMaggot** [ja2-stracciatella/ja2-stracciatella#1365]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
I consistently get a crash when using the aimed burst (hold B then drag mouse while holding LMB) in a line to damage civilians. In vanilla 1.12, there is no crash and NPCs go hostile. I get the rust error `Command_execute "D:\\Program Files\\JA2 Stracciatella\\ja2.exe" []: exited with status code -1073741819`
This has been present for years in Stracciatella in various release/nightly builds and makes the aimed burst unusable. Playing on Windows 10 and here is a link to a save file where the issue can be replicated quickly. https://cdn.discordapp.com/attachments/615653794079965204/841232788539572234/SaveGame03.sav

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release |  JA2 Gold   |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Thanks for the report, I didn't even know this feature of a deliberate spread was there in the first place.

**Comment by ja2-derek** [comment]
This feature is new to me too.

Are there any other steps needed to reproduce? I loaded up your save, held down the B key and then drag around. That places a number of red "targets", and then I am able to burst fire when I release the LMB. There was no crash or errors in the logs.

**Comment by lynxlynxlynx** [comment]
Should we try to get the info from `tgt` instead? Since this wasn't individually aimed, it makes sense for target to be null.

**Comment by ja2-derek** [comment]
I am inclined to just do a NULL check on `pFirer->target`. If wasn't individually aimed, we don't need to count it in `usShotsHit`.
