### ISSUE TITLE
Game temporarily hangs (stopwatch) when spotting an item mid movement

### ISSUE THREAD

**Issue by MrMaggot** [ja2-stracciatella/ja2-stracciatella#1367]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
When spotting an item during a squad member's movement, you are forced to wait an extra 10-20 seconds as a stopwatch appears before you can continue issuing any orders. Playing on Windows 10 and I have uploaded a save where the issue can be replicated by sending Razor north past the corpse at the corner of the hospital about 10 tiles above him.  https://cdn.discordapp.com/attachments/615653794079965204/841833910820012062/QuickSave.sav

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release | JA2 Gold   |    no    |   unknown     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by Stephen-Cronin** [comment]
I get this as well, on Win 10, with 0.18.0. Never happened in 0.16.1. 

That said, I turned on `drop_everything`, so maybe that had something to do with it? Currently just started a new game with `all_drops_visible` turned on, hoping it would fix it because squad members won't notice items mid turn and so far it hasn't happened, but it's early in the save.

**Comment by ja2-derek** [comment]
It should be related to #1325, that the `UnSetUIBusy` is not called when the soldier is stopped by spotting an item.

I will take a deeper look.
