### ISSUE TITLE
Feature Request: Chance-to-hit feature improvements

### ISSUE THREAD

**Issue by DSeyka** [ja2-stracciatella/ja2-stracciatella#1368]
Hello again! :) Glad to see the project is in active development.
Regarding the new CTH on 'f' hotkey feature (huge thanks for implementing that, @dariusk!), I humbly propose it being enhanced slightly.

1) Is it being tied to a hotkey really necessary? I mean, if user enables it, they probably want to see their hit chances regularly. I'll also admit that I've pressed 'd' (end turn) instead of 'f' more than once while playing with this feature, too. :D So I propose just displaying your chance-to-hit next to the aiming cursor when it is enabled in json.
2) While we're at it, why not take aiming clicks into account while displaying CTH? It's pretty counter-intuitive that it doesn't happen already.

Thanks for considering it, and again -- for not abandoning the project, playing good old JA2 has been helping me out quite a bit lately.

**Comment by ja2-derek** [comment]
My opinions:

I personally do not like the idea of the persistent text on screen as that would distract me. Of course we can implement it as an option.

Instead I think the aiming crosshair should be doing that. We had a half-done implementation of the "accurate aim circle" (#1178), which the size of the crosshair circle indicates the chance-to-hit.

Or, maybe can we steal the OCTH crosshair from 1.13? It has a bar that displays the CTH, like this:
![image](https://user-images.githubusercontent.com/63151803/117984141-272b8180-b36a-11eb-98e4-4e2baefeae90.png)

**Comment by DSeyka** [comment]
> persistent text on screen
It could only show up when aiming at the enemy, much like that bar thing in 1.13 (which is better than nothing, but obscures enemy sprites, as seen in the screenshot). Honestly, I'd prefer chance % being shown instead of circles/bars since that gives you much more precise readout, plus we already have these calculations done; I just don't like pressing an extra button and looking at text in the bottom left, is all. :)

**Comment by MrMaggot** [comment]
Is it possible to disable the cth% entirely in the current build?

**Comment by lynxlynxlynx** [comment]
What do you mean?

**Comment by MrMaggot** [comment]
I mean the text that gives you the hit percentage chance when you press F. The first post mentions a user enabling it as if you can opt out but I didn't see any options to toggle it in the configs.

**Comment by DSeyka** [comment]
It can be disabled with ```"extra_hotkeys": false``` in game.json.

**Comment by lynxlynxlynx** [comment]
The extra keys are documented here btw:
https://ja2-stracciatella.github.io/how-to-run/#extra-hotkeys

**Comment by DSeyka** [comment]
@lynxlynxlynx The 'f' hotkey explanation is missing in game.json though.

**Comment by kraftwer1** [comment]
Maybe one of the already existing texts could be reused:

Torso (39%)

...or...

46 / 39%

... or the 46 could be swapped with 39% and back again every 1 sec or so.

**Comment by FluffyQuack** [comment]
Not sure how this should be handled visually, but I'm randomly fiddling with this feature right now:
![ja2 2021-05-22 22-19-47-182](https://user-images.githubusercontent.com/14843529/119241924-3a083800-bb5a-11eb-963a-e494500ba5b0.png)

**Comment by DSeyka** [comment]
Exactly what I had in mind, looks good. :)

**Comment by FluffyQuack** [comment]
After a bit more work:

![ja2-hit-chance](https://user-images.githubusercontent.com/14843529/119253489-c265f780-bbb1-11eb-9398-ca0e045d21ba.gif)

I'm thinking, maybe just remove the aim circle with this system? Could render the AP cost with a different colour once you've reached max aim.

**Comment by kraftwer1** [comment]
True, or put the % in the existing text, e.g. with round brackets like: „Torso (85%)“?

**Comment by FluffyQuack** [comment]
Here are some variations:

Body location (hit chance):
![ja2 2021-05-23 11-44-40-399](https://user-images.githubusercontent.com/14843529/119255682-67d29880-bbbd-11eb-805c-1e262f8400f5.png)

I don't think I'm a huge fan of that as the hit chance's horizontal location keeps moving as you move the mouse over other body locations, and also, there are targets where you never get the body location text. Like this:
![ja2 2021-05-23 11-44-43-984](https://user-images.githubusercontent.com/14843529/119255710-8a64b180-bbbd-11eb-8583-99cbb2d35b0e.png)

Hit chance (body location):
![ja2 2021-05-23 11-45-26-158](https://user-images.githubusercontent.com/14843529/119255734-9cdeeb00-bbbd-11eb-8286-d18374846365.png)

Again, not a fan of how the hit chance keeps changing position horizontally as you move the mouse over other targets or body locations.

Hit chance
Body location:
![ja2 2021-05-23 11-50-24-949](https://user-images.githubusercontent.com/14843529/119255782-cf88e380-bbbd-11eb-882a-a78d8808539d.png)

That looks okay, I think.

**Comment by kraftwer1** [comment]
Thanks so much for your screenshots, amazing 💯 

Here‘s how XCOM is doing it:
![Uploading F877F84C-EF76-4CAF-862C-B01500C3875D.png…]()

**Comment by FluffyQuack** [comment]
Another variation: The percentage is shown to the right of the cursor, and I've made it so the aim circle decreases in size based on hit percentage (decreases in size for every 20%).

![aim-test_00000](https://user-images.githubusercontent.com/14843529/119392664-562de580-bcd0-11eb-85ab-91a52851540f.gif)

**Comment by FluffyQuack** [comment]
This is what it would look like without the aim circle:

![ja2 2021-05-24 20-58-21-730](https://user-images.githubusercontent.com/14843529/119394834-f71da000-bcd2-11eb-880b-f983029e03b2.png)

**Comment by kraftwer1** [comment]
I like! It‘s true, the aim circle becomes somewhat obsolete. But if it‘s generating more work (= more bugs), maybe just leave it there? One of the critics of 1.13 is that the CtH causes glitches…

After looking at the animated gif, I wonder what it looks like when the % is on the left side of the cursor (instead of the right side) so the % will always stay at the exact same pixel position even when the number changes from 1% to 100%.

Another thought: what if the CtH appears in red (same color“Healthy“)?

Thanks again for the gifs. Simply by looking at them makes me want to play.

**Comment by FluffyQuack** [comment]
Red and on left side.

![ja2 2021-05-24 21-24-09-405](https://user-images.githubusercontent.com/14843529/119397544-91cbae00-bcd6-11eb-8af0-b4e661c65c35.png)

Not a big fan of that style. Maybe it's just me, but I find the red text harder to read. I'm also thinking it's more natural to have the number on the right side or bottom, but maybe I'm saying that just because I'm used to seeing it like that.

**Comment by kraftwer1** [comment]
True, white is easier to read.

Why is „Healthy“ in red in the first place? It looks more like „Dying“ to me…

About the position, I have no preference. Probably a matter of time to get used to.

**Comment by lynxlynxlynx** [comment]
I'd just go for the bottom positioning and not touch the circle itself. Maybe it looks even better if the chance is below the body part label, not above, since it'll be more symmetric that way.

**Comment by FluffyQuack** [comment]
So, I should aim for this? I can try to make sure the hit chance works for every kind of aiming (I've only tested this for shooting, but there's other actions to consider, like throwing and punching) and then prepare a PR.

![ja2-aim-test2](https://user-images.githubusercontent.com/14843529/119410249-d6f8db80-bce8-11eb-8155-231808141d3f.gif)

**Comment by lynxlynxlynx** [comment]
Looks great to me, but I'm just one dude in a thread of 6 people, so let's wait for some more comments.

**Comment by kraftwer1** [comment]
My personal preference in order:

1. CtH left to the cursor (tidy and calm because the % doesn‘t move)
2. CtH right to the cursor (still tidy, but not as calm)
3. CtH to the bottom (having three lines of text below of each other somehow neither looks tidy nor calm to me because it’s hard to align them horizontally and at the same time have the % stay in place (pixel wise)

But I definitively prefer all three to hitting the F button :)

**Comment by FluffyQuack** [comment]
Throw knife:
![ja2 2021-05-26 00-59-31-646](https://user-images.githubusercontent.com/14843529/119579350-7e940d80-bdbe-11eb-949e-20fea4173be5.png)

Punch:
![ja2 2021-05-26 00-59-38-502](https://user-images.githubusercontent.com/14843529/119579397-95d2fb00-bdbe-11eb-89b8-1bdd80799ee1.png)

Throw rock/grenade/etc:
![ja2 2021-05-26 01-02-07-417](https://user-images.githubusercontent.com/14843529/119579413-9c617280-bdbe-11eb-9aa5-72de1e9837fe.png)

Stab:
![ja2 2021-05-26 01-02-47-744](https://user-images.githubusercontent.com/14843529/119579446-aaaf8e80-bdbe-11eb-965f-e2aaa497f767.png)

**Comment by lynxlynxlynx** [comment]
@kraftwer1 I don't know why you're so fixated on the % sign placement. It can only change in the case when the number is a single digit, otherwise it's consistent in all configurations.

**Comment by DSeyka** [comment]
> Why is „Healthy“ in red in the first place?
The color of text is simply denoting that this is a hostile character. It'd be in white if you'd mouse over a militia, for example.
@FluffyQuack These look absolutely perfect to me. 👍

**Comment by FluffyQuack** [comment]
I noticed one bug. The number you get when pressing 'F' is off by about 10%. The bug is affecting my display as well as I'm using the same function for calculating the chance to hit. The weird thing is that the game uses the same function for calculating the chance to hit when shooting. Hopefully, it's easy to figure out the cause of it.

**Comment by kraftwer1** [comment]
Out of curiosity: how did you notice it‘s off?

**Comment by FluffyQuack** [comment]
> Out of curiosity: how did you notice it‘s off?

I added a breakpoint for when it was called. It's usually lower by about 10% when firing compared to the number you see when pressing F. Just as you fire, there has to be some variable change that affects hit chance.

**Comment by DSeyka** [comment]
I seem to remember this being discussed in 1.13 forums, there isn't an ACTUAL hit chance per se, just what game assumes it is. Bullets traverse though walls in this game. This just can't be accounted for.
I have a save game where there's a downed civilian, F key reports chance of shooting her being 99% but you'll never hit her, because she's in a "dying" position and is at a weird angle related to the shooting mercenary. I can provide it if needed.

**Comment by FluffyQuack** [comment]
> I seem to remember this being discussed in 1.13 forums, there isn't an ACTUAL hit chance per se, just what game assumes it is. Bullets traverse though walls in this game and change angles, those things just can't be realistically accounted for.
> I have a save game where there's a downed civilian, F key reports chance of shooting her being 99% but you'll never hit her, because she's in a "dying" position and is at a weird angle related to the shooting mercenary, with obstacles in the way. I can provide it if needed, but not sure if those edge cases are really all that much interesting, the point of this FR is not about that.

At least, the game tries to take the chance-to-hit at face value.

This is near the start of the shooting routine:
```
int uiHitChance = CalcChanceToHitGun( pSoldier, sTargetGridNo, pSoldier->bAimTime, pSoldier->bAimShotLocation, true );
int uiDiceRoll = PreRandom( 100 );
bool fGonnaHit = uiDiceRoll <= uiHitChance;
```

But I guess it becomes more complicated because the game calculates a proper path for bullets, right? I assume that means you can get the reverse to happen, where the bullet is supposed to miss but the path it takes when missing ends up hitting the target anyway.

Calculating the real hit chance that takes into account the possible paths the bullet can take seems like it would be a big challenge. But at least the current hit chance is a pretty good indication of what the result will be, even though the bullet path can end up changing the outcome.

**Comment by DSeyka** [comment]
Hey, if the game reports that this is the hit chance, it's fine. Just as long as I don't need to press 'd' instead of 'f' again. :)
