### ISSUE TITLE
ChanceToHit not increasing with precise aim?

### ISSUE THREAD

**Issue by kraftwer1** [ja2-stracciatella/ja2-stracciatella#1371]
Example: when I press the F button on a certain tile (with an enemy on it), I get a CTH of 39%. However, when I add more action points by right clicking in order to aim more precisely, and hit F again, the CTH is still 39%.

Now my question: is CTH ignoring the more precise aim or is my character so bad that adding more action points doesn't help at all?

**Comment by lynxlynxlynx** [comment]
Yes, it doesn't care. See #1368
