### ISSUE TITLE
Create packages for Linux

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#138]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

It would be great to create packages for popular Linux distributions, so Linux users don't have to compile the game.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/138

**Comment by fedya** [comment]
i made RPMS
x86_64 https://abf.openmandriva.org/build_lists/110066
aarch64 https://abf.openmandriva.org/build_lists/110067
i586 https://abf.openmandriva.org/build_lists/110064
