### ISSUE TITLE
When setting special movement cost for fences, check that tile after the fence is not blocked

### ISSUE THREAD

**Issue by sevenfm** [ja2-stracciatella/ja2-stracciatella#1389]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
This code may cause AI deadlock when AI controlled soldier tries to jump over fence in north direction, if there is unpassable structure blocking fence from north direction (so when AI soldier tries to jump over the fence into something unpassable).
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/d6482fb04b5a338a17eed18a636d9f6d09a25e9a/src/game/TileEngine/WorldDef.cc#L527-L535

Should be
```c
// set values for the tiles EXITED from this location
if (gubWorldMovementCosts[usGridNo - WORLD_COLS][NORTH][0] < TRAVELCOST_BLOCKED)
 FORCE_SET_MOVEMENTCOST(usGridNo - WORLD_COLS, NORTH, 0, TRAVELCOST_NONE);
ET_MOVEMENTCOST( usGridNo - WORLD_COLS + 1, NORTHEAST, 0, TRAVELCOST_OBSTACLE );
SET_MOVEMENTCOST( usGridNo + 1, EAST, 0, TRAVELCOST_OBSTACLE );
SET_MOVEMENTCOST( usGridNo + WORLD_COLS + 1, SOUTHEAST, 0, TRAVELCOST_OBSTACLE );
if (gubWorldMovementCosts[usGridNo + WORLD_COLS][SOUTH][0] < TRAVELCOST_BLOCKED)
 FORCE_SET_MOVEMENTCOST(usGridNo + WORLD_COLS, SOUTH, 0, TRAVELCOST_NONE);
SET_MOVEMENTCOST( usGridNo + WORLD_COLS - 1, SOUTHWEST, 0, TRAVELCOST_OBSTACLE );
SET_MOVEMENTCOST( usGridNo - 1, WEST, 0, TRAVELCOST_OBSTACLE );
SET_MOVEMENTCOST( usGridNo - WORLD_COLS - 1, NORTHWEST, 0, TRAVELCOST_OBSTACLE );
```

This was fixed in 1.13 main trunk r8640 by silversurfer.
> Fix: Incorrect movement cost calculation for jumping over fences with obstacles behind them

https://github.com/aimnas/ja2-1.13-source-mirror/blob/b7adaf802ae85df4b7631e81997c2d0fc57781f0/TileEngine/worlddef.cpp#L1002-L1017

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|    |    |    yes   |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Thanks for these, it's really helpful!
