### ISSUE TITLE
Crash after cutscene

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#139]
Originally reported by: **Robs Soie (Bitbucket: [Robsoie](http://bitbucket.org/Robsoie), GitHub: [Robsoie](http://github.com/Robsoie))**

---

In Early game, using regular mercs (no IMP) , i went to meet Miguel at the hideout in Omerta and recruited Ira , that joined the team 2 as team 1 was full.

I assigned team1 to travel to the airport sector of Drassen, while i moved Ira to behind some sandbags close to the rebels hideout just in case.

The "Meanwhile" screen appeared , launching the cutscene with Deidranna 

Then back into the game i moved out of the pause to get my team moving to Drassen and JA2 just crashed there with the error popup :
ERROR : caught unhandled exception:
Palette creation failed, soldier has invalid animation
Creating an emergency savegame succeeded (error.sav)
Please report ....

using JA2 with only stracciatella from the version : ja2-v0.12.352-win  and no other mod
on winxp sp3 

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/139

**Comment by derSteFfi** [comment]
when trying to load the savegame, i get this
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000508719 in IsSectorDesert (x=0, y=0) at Build/Strategic/StrategicMap.cc:3569
3569		return SectorInfo[SECTOR(x, y)].ubTraversability[THROUGH_STRATEGIC_MOVE] == SAND;
(gdb) backtrace
#0  0x0000000000508719 in IsSectorDesert (x=0, y=0) at Build/Strategic/StrategicMap.cc:3569
#1  0x00000000006449af in SectorTemperature(unsigned int, short, short, signed char) () at ./sgp/UTF8String.h:51
#2  0x0000000000644683 in GetTimeOfDayAmbientLightLevel() () at ./sgp/UTF8String.h:51
#3  0x00000000006440d1 in EnvironmentController(unsigned char) () at ./sgp/UTF8String.h:51
#4  0x0000000000449d8b in MainGameScreenHandle () at Build/GameScreen.cc:390
#5  0x000000000044863d in GameLoop () at Build/GameLoop.cc:299
#6  0x00000000006ae50b in MainLoop (msPerGameCycle=25) at sgp/SGP.cc:252
#7  0x00000000006aecb1 in main (argc=2, argv=0x7fffffffe098) at sgp/SGP.cc:515
```

GetTimeOfDayAmbientLightLevel:
```C
INT8 GetTimeOfDayAmbientLightLevel()
{
	if ( SectorTemperature( GetWorldMinutesInDay(), gWorldSectorX, gWorldSectorY, gbWorldSectorZ ) == HOT )
...
```
SectorTemperature calls IsSectorDesert:
```C
INT8 SectorTemperature( UINT32 uiTime, INT16 sSectorX, INT16 sSectorY, INT8 bSectorZ )
{
	if (bSectorZ > 0)
	{
		// cool underground
		return( 0 );
	}
	else if ( IsSectorDesert( sSectorX, sSectorY ) ) // is desert
```
Since IsSectorDesert is called with (x=0, y=0), gWorldSector[XY] is actually 0. Maybe, because it's this early in the game, they are not initialized correctly?

**Comment by derSteFfi** [comment]
from my experience with anoter SEGFAULT, this is misleading i guess. the error.sav loading fail can be caused because on loading, the game tries to re-execute an strategic event that was only partially executed when the original crash happened.

**Comment by lynxlynxlynx** [comment]
Closing stale issue without a reproducer.
