### ISSUE TITLE
Incorrect target level when calculating throw params

### ISSUE THREAD

**Issue by sevenfm** [ja2-stracciatella/ja2-stracciatella#1397]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
In HandleItemPointerClick(), we prepare params for throw
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/a9d87360d0d89bbbda2e54246875df69b9c06153/src/game/Tactical/Interface_Items.cc#L3710-L3711
But ubLevel param of CalculateLaunchItemParamsForThrow is for target level, not soldier's level
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/a9d87360d0d89bbbda2e54246875df69b9c06153/src/game/TileEngine/Physics.cc#L1826
so it should be
```c
// Given our gridno, throw grenate!
CalculateLaunchItemParamsForThrow(gpItemPointerSoldier, sGridNo, gsInterfaceLevel , gsInterfaceLevel * 256 + sEndZ, gpItemPointer, 0, ubThrowActionCode, target);
```

In other places this function call uses pSoldier->bTargetLevel, but it may not be set yet here.

This fix should improve throwing grenades on different level.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|    |    |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Thanks for all these great reports @sevenfm!
