### ISSUE TITLE
Error when building on MSYS2 system on windows

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1398]
### What is wrong
Cannot build the latest git version on MSYS2 system on Windows 10.

It seems that on MSYS2 the build created a libstracciatella_c_api.a file but expects a stracciatella_c_api.lib which does not exist. 

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

cmake -G "MSYS Makefiles" ../ja2
make

### Result:

note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -ladvapi32 -lwinapi_advapi32 -lwinapi_cfgmgr32 -lwinapi_gdi32 -lwinapi_kernel32 -lwinapi_msimg32 -lwinapi_ole32 -lwinapi_opengl32 -lwinapi_shell32 -lwinapi_user32 -lwinapi_winspool -ladvapi32 -lws2_32 -luserenv

Finished release [optimized + debuginfo] target(s) in 30.91s
Built target cargo-build-release
Error copying file (if different) from "C:/msys64/home/askon/repo/ja2-build/dependencies/lib-stracciatella/target/x86_64-pc-windows-gnu/release/stracciatella_c_api.lib" to "C:/msys64/home/askon/repo/ja2-build/lib-stracciatella/lib/libstracciatella.a".
make[2]: *** [dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/build.make:76: lib-stracciatella/include/stracciatella.h] Error 1
make[2]: *** Deleting file 'lib-stracciatella/include/stracciatella.h'
make[1]: *** [CMakeFiles/Makefile2:930: dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by askondro** [comment]
This patch fixes it for me.

[MSYSBuild.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/7138348/MSYSBuild.zip)

**Comment by lynxlynxlynx** [comment]
The fix LGTM, but it also makes me wonder why we link statically by default there.

**Comment by ja2-derek** [comment]
Does this fix also applies to MinGW? (https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1296)

**Comment by lynxlynxlynx** [comment]
Yes, looks like a duplicate report in the sense that it has the same root issue.
