### ISSUE TITLE
Tactical UI layout on wide screens

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1399]
The tactical UI doesn't look great on wide screens, e.g. the screenshots in #1330 and #537. 

Here I propose an update to the bottom panel in tactical screen. It doesn't address all the problems with screen resolution, but this could be the basis to support more - specifically increased squad sizes. 

Below I have a couple of mock-ups, and would appreciate your feedback.

## 0. Current UI layout
This is how it looks currently:
![Original](https://user-images.githubusercontent.com/63151803/133866152-cda2bd80-0001-4a0e-bc90-0dfa6efc512f.png)

## 1. Centered
If we align the bottom bar to the center. This is more straight-forward to implement, and is more consistent with the current strategic screen.

![Centered](https://user-images.githubusercontent.com/63151803/133866150-79f92bc7-b171-4cb2-b8d8-7286b66b0869.png)

## 2. Aligned to corners (JA2'005 style)

Here is a screenshot of JA2'005: [[link]](https://jagged-alliance.pl/images/photoalbum/album_42/ja2005c.jpg)

In the next one, the bottom bar is split and aligned to the corners. This might be the better-looking one as there are no more useless black space. We may need a better filler texture, though. Maybe this is harder to see and use? The widget is now spread out to the two corners.

![WithFiller](https://user-images.githubusercontent.com/63151803/133868056-d3ecc576-bf12-4906-aa4c-0c019dd119cb.png)

Let me know how you want it to look like.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master | -  |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
## DevilutionX style (bottom panel as an overlay)

Also looking nice, but need extra polishing, like a drop shadow effect.

See screenshot posted in https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1330#issuecomment-851620750 

![Overlay](https://user-images.githubusercontent.com/63151803/133867351-00ba00d7-ae26-4329-8a1b-c7c791f9ae90.png)

**Comment by lynxlynxlynx** [comment]
I'd go for plain centering.
