### ISSUE TITLE
Stuck at automatic first aid screen

### ISSUE THREAD

**Issue by Demiu** [ja2-stracciatella/ja2-stracciatella#1407]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
The automatic first aid screen never disappears (or changes from stop to done) and doesn't respond to any actions, making the game effectively stuck. No errors in the console except the Structure.cc warnings.

It happened randomly so I can't provide a save or a reproduction steps, but it _might_ have something to do with one of my mercs going ctrl-pickup from a stack of items after the fight; maybe that window got stuck under the first aid window, so they blocked each others' input, making the game stuck.

OS: Win10 64

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.18.0-git+ebc73ce | JA2 Gold English (GOG)  |    maybe    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
JA2-1.13 just has a fix for a similar with Auto Bandaging https://github.com/aimnas/ja2-1.13-source-mirror/commit/20335041f7e053dee4f5e07ead79317600de1043

The fix in 1.13 is about the conversation dialogues, but the root cause is probably the same.

**Comment by lynxlynxlynx** [comment]
We made similar fixes already, since popups don't interact well.
