### ISSUE TITLE
Truncated error message when failing to build virtual file system (VFS)

### ISSUE THREAD

**Issue by Sal3m** [ja2-stracciatella/ja2-stracciatella#1433]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
I'am not a programer but i know basics about compiling code on various operation systems.
In the moment i'am trying to make JA2 straciatella run on a Raspberry Pi 4 and a Raspi Zero W. 
I succesfully compiled the code with rustc version 1.48.0 and unziped the DATA file from the GOG Installer (German Version 1.12) to "/home/pi/Downloads/ja2"
I also setup the ja2.json file with the following content
            {
            // Put the directory to your original ja2 installation into the line below.
            "game_dir": "/home/pi/Downloads/ja2",
            "res": "1280x720",
            "resversion": "GERMAN",
            "fullscreen": false,
            "debug": true,
        }

When i try to launch the game it gives me an error message:

2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Initializing Memory Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Initializing Game Resources
**2021-10-29T06:59:42 [ERROR] sgp/SGP.cc: Game has been terminated due to an unrecoverable error: Failed to build virtual file system (VFS): Vfs_init_from_engine_options EngineOptions { stracciatella_home: "/home/pi/.ja2", vanilla_game_dir: "/home/pi/Downloads/ja2", assets_dir: "/usr/local/bin",** 
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Button System
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Sound Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Video Surface Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/Video.cc: Shutting down the Video Surface manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Video Object Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Video Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/Video.cc: Shutting down the video manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down Memory Manager
2021-10-29T06:59:42 [DEBUG] (1) sgp/SGP.cc: Shutting Down SDL
Abgebrochen

I think it has to do something with the DATA folder of JA2. Has anyone encountered the same error?

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.18 | eg. JA2 GOG Deutsch (1.12)  |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by Sal3m** [comment]
Yes the path contains the Data folder with all the  .slf .npc etc. files. I extracted them with innoexctract from the GOG installer

**Comment by selaux** [comment]
Sounds good. Looking at the logs again the `asset_dir` is set to `/usr/local/bin`. So `/usr/local/bin` should contain `externalized` and `mods` directories (which does not sound right). It can be set at compile time with the `EXTRA_DATA_DIR` option. Usually we set it to `/usr/share/ja2`.

**Comment by Sal3m** [comment]
Thank you very much. That solved the problem. JA2 now running on the raspi 4. Next step Raspi Zero :)

**Comment by selaux** [comment]
Nice. I will reopen, so the truncated error message can be fixed.

**Comment by selaux** [comment]
@Sal3m By the way: How well does it run on the Raspberries? I always wanted to test running on one, but never got around to it.

**Comment by Sal3m** [comment]
It's running good on the raspi 4 (4gb RAM version). But i have only tested it with xrdp access. Performance in Omerta was good. Haven't tested the sound yet. More tests will follow when the case is ready and when an extra keyboard and mouse has arrived.

On the raspi Zero it failed to compile. Or its crashing the raspi Zero during the process. Haven't found out yet.

**Comment by Srandista** [comment]
@Sal3m can you please share, under which OS on RPi did you compiled JA2 Stracciatella?

**Comment by Sal3m** [comment]
Raspberry Pi OS
Release Date May 7th. 2021
I Installed rustc, cmake, libsdl2-dev and libboost-filesystem-dev

Edited the CMakeList.txt and added 
set(CMAKE_INSTALL_PREFIX "/usr/local")
set(DEXTRA_DATA_DIR "/usr/local/share/ja2)
Before the project( line

After that i ran 
cmake .
make -j4
and
sudo make install
