### ISSUE TITLE
Compiling JA2S 0.18 with Raspberry Pi failed

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#1436]
### What is wrong
When I try to compile the JA2S 0.18, I successfully went through the cmake part of the process, but when I try to compile using make command, after a few successful lines I got following error:

Building stracciatella
Scanning dependencies of target cargo-build-release
cargo build --verbose --release --all
    Updating crates.io index
Segmentation fault
make[6]: *** [dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/build.make:58: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release] Error 1
make[5]: *** [CMakeFiles/Makefile2:916: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:923: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/rule] Error 2
make[3]: *** [Makefile:303: cargo-build-release] Error 2
make[2]: *** [dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/build.make:63: lib-stracciatella/include/stracciatella.h] Error 2
make[1]: *** [CMakeFiles/Makefile2:1159: dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

My Raspberry Pi is 3B+ running stock, without any OC, with latest Raspberry Pi OS (former Raspbian) based on Debian Buster (Bullseye based OS is still not officially released for RPi).

I also tried source code release for 0.16.1 and 0.17, with the same result. I also tried latest source code by downloading current Git repository, but Buster is shipping with older cargo, and current repo requires higher version.

As for the rustc and cargo for 0.18 version, they should be fine (at least according to the logs)

-- Found Cargo: /usr/bin/cargo (found suitable version "1.42.1", minimum required is "1.40.0")
-- Found Rustc: /usr/bin/rustc (found suitable version "1.41.1", minimum required is "1.40.0")

I don't know, if I'm missing any dependencies, but I kinda hope, that system would ask for them, if they aren't present. Anyway, before compiling, I download these packages via apt: cargo rustc cmake libsdl2-dev libboost-filesystem-dev 

If any more logs or other files are needed to analyze, just ask, I can provide anything required.

Thanks for help.

**Comment by selaux** [comment]
Dependency wise you should be ok. The `Segmentation fault` indicates that this might have something to do with your system, rather that ja2-stracciatella itself. We cannot cause a segfault in cargo (I hope). One issue I found was [this one](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918854) related to segfaults of cargo in Debian, but it looks like it is fixed (question is in which version though and whether that fix is also applied to Raspberry Pi OS).

Have you tried installing rust via [rustup](https://rustup.rs/) instead? Maybe that provides working versions of cargo/rust on your system.

**Comment by Srandista** [comment]
I tried newly installed Raspberry Pi OS on separate SD card, but I haven't got too much further.

Scanning dependencies of target stracciatella-update-stamp
Scanning dependencies of target gtest
Scanning dependencies of target lua
Scanning dependencies of target smacker
[  0%] Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lapi.c.o
[  1%] Building CXX object lib-gtest/build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  2%] Building C object dependencies/lib-smacker/CMakeFiles/smacker.dir/libsmacker/smacker.c.o
[  2%] Built target stracciatella-update-stamp
[  2%] Building C object dependencies/lib-smacker/CMakeFiles/smacker.dir/libsmacker/smk_hufftree.c.o
[  2%] Building C object dependencies/lib-smacker/CMakeFiles/smacker.dir/libsmacker/smk_bitstream.c.o
Scanning dependencies of target stracciatella-build
[  3%] Building stracciatella
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Scanning dependencies of target cargo-build-release
cargo build --verbose --release --all
    Updating crates.io index
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lauxlib.c.o
Segmentation fault
make[6]: *** [dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/build.make:58: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release] Error 1
make[5]: *** [CMakeFiles/Makefile2:916: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:923: dependencies/lib-stracciatella/CMakeFiles/cargo-build-release.dir/rule] Error 2
make[3]: *** [Makefile:303: cargo-build-release] Error 2
make[2]: *** [dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/build.make:63: lib-stracciatella/include/stracciatella.h] Error 2
make[1]: *** [CMakeFiles/Makefile2:1159: dependencies/lib-stracciatella/CMakeFiles/stracciatella-build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lbaselib.c.o
Linking C static library libsmacker.a
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lbitlib.c.o
Built target smacker
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lcode.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lcorolib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lctype.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ldblib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ldebug.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ldo.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ldump.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lfunc.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lgc.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/linit.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/liolib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/llex.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lmathlib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lmem.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/loadlib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lobject.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lopcodes.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/loslib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lparser.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lstate.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lstring.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lstrlib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ltable.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ltablib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/ltm.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lundump.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lutf8lib.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lvm.c.o
Building C object dependencies/lib-lua/CMakeFiles/lua.dir/__/__/lib-lua/src/src/lzio.c.o
Linking C static library liblua.a
Built target lua
Linking CXX static library ../../../lib/libgtest.a
Built target gtest
make: *** [Makefile:152: all] Error 2

Btw, OS is 32-bit one, can't this be an issue?

I'll probably just wait for their Bullseye release, since it shouldn't be too far.

**Comment by Srandista** [comment]
Alright, so at the end, it seems that it IS a problem with rustc from official Debian repositories. I did install rustc from rustup and currently I'm compiling the code. Will post the result, once it'll finish and will try to play it for a bit.

Thank a lot for help @selaux!

**Comment by Srandista** [comment]
So after I spend this weekend compiling this code to infinity, I came to the following conclusions. 
For some reason, on my RPi 3B+, I'm only able to compile JA2S up until the version 0.17. That version will compile fully (when I'm using rustup instead of rustc and cargo from Raspberry Pi OS repositories) and I'm able to run it without issues.
With both version 0.18 and current Git repo clone the compilation will stuck at Building CXX object CMakeFiles/ja2.dir/src/externalized/scripting/ScriptingExtensionsLua.cc.o and will not continue no mater what (just to be sure I let the compilation run through the night and it made no difference). RPi is running, OS didn't crash, it's just stuck at that point of compilation.
Anyway, since 0.17 works without issues, I'll be testing that version and will let you know, what the performance is with 3B+ and also Zero 2 W, which I should receive in about a week.

**Comment by ja2-derek** [comment]
`ScriptingExtensionsLua` uses a lot of templates (via sol2) and generates a very large object output. Is it possible to build on a more high-power machine - i.e. cross-build from a laptop or PC?

Otherwise we probably need implement a flag to turn off Lua support.

**Comment by Srandista** [comment]
@ja2-derek yeah, performance of RPi 3B+ is certainly to blame here, since RPi 4 can compile even the latest code without issues, but I don't own one.

Regarding cross-build, that's certainly possible, I have a good desktop PC with Linux VMs, where I also compiled JA2 binary according to the guide. But I have no idea how to set compilation in a way, that'll create a binary for another architecture.

**Comment by Srandista** [comment]
I did some testing yesterday, and performance wise, JA2S is running perfectly on my RPi 3B+. Besides a bit slower map loading times (it's running from SD card at the end), I wouldn't be able to tell, that it isn't running on my main PC. You did excellent work guys, I'm saluting you! :)

**Comment by selaux** [comment]
Good to hear. If you have some more spare time, compiling current master should give you a bunch of improvements regarding load times.

**Comment by selaux** [comment]
This seems fixed. Will close.
