### ISSUE TITLE
Crash in SoldierGiveItemFromAnimation after winning in fight in San Mona

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#144]
Originally reported by: **Lukas Jirkovsky (Bitbucket: [stativ](http://bitbucket.org/stativ), GitHub: [stativ](http://github.com/stativ))**

----------------------------------------

After winning a fight in San Mona, Darren is supposed to give the winner money. When this happens, the stack gets corrupted so badly that it is impossible to obtain stacktrace from gdb.

By using a signal handler and gcc's backtrace() function, I was able to track it down to:

    Handle_Items.cc:2311

The problematic line itself is:

    TempObject = *pSoldier->pTempObject;

Running it through gdb has shown that the SoldierGiveItemFromAnimation() is called twice, which looks fishy to me. The second call causes the crash.

### Steps to reproduce ###
1. Load the attached saved game
2. End turn
3. Wait for the dialog whether you want to continue fighting to appear
4. Any answer causes the crash

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/144

**Comment by derSteFfi** [comment]
cannot reproduce anymore, i think this was solved in 3e5bb412?

**Comment by lynxlynxlynx** [comment]
Right, this is a duplicate of #199. Too bad I didn't see this one, there is more info here. More incentive for a proper fix.

**Comment by derSteFfi** [comment]
close because it was fixed. ( 3e5bb41)
