### ISSUE TITLE
Game crash in P3 basement

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1443]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)
Reported on [Discord](https://discordapp.com/channels/348449397308391426/883987395484200970/908994850957979710).

### What is wrong

> hello! somebody handed me this discord link after hearing my story
> I am stuck in Meduna Palace Underground, as everytime I hit D to end my turn or go back through the transition to the surface, the game crashes. Kinda salty to be stuck so close to Deidranna.
> Stracciatella's console tells me 2021-11-13T06:49:39 [ WARN] game\Tactical\Tactical_Save.cc: SynchronizeItemTempFile() Reported 0, should be 3 ; Windows Event Viewer says there's Access Violation Error.
> 
> I know little about programs and stuff. Any idea what I can do?
> I am using JA2 Gold from Steam, on Windows 10, the file integrity tool says it's all fine. So I guess the issue must be on Stracciatella's side?

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.18.0-GIT-EB73CE |   JA2 Gold from Steam  |    no?    |    not sure     |

Saved game: [SaveGame05.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/7565012/SaveGame05.sav.gz). Press `d` and the game crashes.

------

The game crashes here:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c75a2773eb1905c82111b9bb294ca7ecf5fb5bb0/src/game/Tactical/TeamTurns.cc#L400-L404

`LatestInterruptGuy()` returns `NULL`, probably because it's the first turn in sector. Then inside [AdjustNoAPToFinishMove](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/69cdce824d93435cb72fdf2658ba76c9192a0f52/src/game/Tactical/Soldier_Control.cc#L212) the game tries to deference the null `pSoldier` pointer.

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Considering from how many places this can get called, I suggest we just patch this over.

**Comment by lynxlynxlynx** [comment]
ifing that out works nicely, but if you move out of the sector, you get stuck in the same hidden interrupt. Asdow thinks it wasn't supported in vanilla, so perhaps we should just disable it. A separate issue though.
