### ISSUE TITLE
Replying to Mike crashes the game

### ISSUE THREAD

**Issue by Schwalbe1728** [ja2-stracciatella/ja2-stracciatella#1444]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### Replying to Mike crashes the game.
I have encountered Mike in Grumm factory sector. Alas, I have nothing to DELETE him out of existance in one turn, which means that after his turn, the combat is stopped and you engage in dialogue with him. If you choose any of the reply options, the game immediately crashes:
[This should be an imgur link to a screenshot of error message.](https://imgur.com/a/k0RZyM8)

Given it's nature, this prevents me from continuing the game, lest I find a way to kill Mike in one turn - and the prick is as we all know exceptionally armoured.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
| Stracciatella v0.18.0-git+ebc73ce | JA2 1.12, EN, GOG  |    no    |   no idea (first stracciatella playthrough)     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)
[SaveGame08.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/7576174/SaveGame08.zip)

**Comment by selaux** [comment]
Hmm, I tested the save game, but it seems to work fine for me. Mike starts talking to me on the first encounter, I can answer and he then shoots me dead. From your logs I can see `invalid profile id 200`, which is certainly the [cause of the crash](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/Tactical/Soldier_Profile.h#L18). I think the profile id 200 is out of range, but I don't know why it is even used. Do you have any mods enabled or any special options set?

**Comment by Schwalbe1728** [comment]
> Hmm, I tested the save game, but it seems to work fine for me. Mike starts talking to me on the first encounter, I can answer and he then shoots me dead. From your logs I can see `invalid profile id 200`, which is certainly the [cause of the crash](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/Tactical/Soldier_Profile.h#L18). I think the profile id 200 is out of range, but I don't know why it is even used. Do you have any mods enabled or any special options set?

Mods - certainly not. Unless we count that at the beginning of 2021 I used v1.13 on this same machine, although I am unsure how that would interfere.

Special options - depends on how would you define them. I... _don't think_ I've set anything beyond vanilla. If there is a file that could be used to cross refer, let me know - I'll fetch it.

This entire setup was supposed to be for the review of the game for my YouTube channel - we all know how stable JA2 is to use normally on modern systems, not to mention record clips off of it. Intention was to keep the game as vanilla as possible for that purpose, so 1.13 was out of the question.

Looking at the source you provided, looks like the fucker should be id 149... hm.
The initial dialogue part with Mike plays as it should, like I mentioned, the crash commences once I choose any of the replies. I would test all options in that dialogue, but I'm **very** busy with IRL right now...

**Comment by lynxlynxlynx** [comment]
1.13 modifies data, so it's important that you use ja2s on a clean install. But I guess that's true already?

**Comment by Schwalbe1728** [comment]
Miniature update: Actually, pressing "Done" button (of which I somehow forgot) actually allows to bypass the error. So at least it's not as disruptive as I thought it to be.

> 1.13
Yeah, the 1.13 modified version of the game was uninstalled back in... May? not entirely sure, but I did uninstall it, and this should be a clean install.

**Comment by ja2-derek** [comment]
The logs you posted seems to indicate some data errors - e.g. secret not defined, unexpected item class. Did you you upgraded Stracciatella mid-game or changed the JSON files? 

Maybe you can try copying over all the files from the `externalized` directory from the release package again, to ensure it is all clean and up-to-date.

**Comment by Schwalbe1728** [comment]
> The logs you posted seem to indicate data errors - e.g. secret not defined, unexpected item class. Did you you upgraded Stracciatella mid-game or changed the JSON files?

General rule of thumb with me is "if it happened longer than a week earlier, I am an unreliable source". That said, I believe I reinstalled JA2 after the tip from a mate that Stracciatella exists and keeps things more vanilla - so I'm pretty sure that I didn't upgrade mid-game, for what these assurances are worth.

> Maybe you can try copying over all the files again from the `externalized` directory in the [release package](https://github.com/ja2-stracciatella/ja2-stracciatella/releases/tag/v0.18.0), to ensure it is all clean and up-to-date.

I will, although not sooner than in the weekend. I've just learnt that on top of my in-life shitshow this week I'll experience at-work shitshow as well, resulting in truly a horrifying conflux of faeces.

**Comment by ja2-derek** [comment]
No worries. Take your time and take care.

**Comment by Schwalbe1728** [comment]
Like I mentioned though - I _did_ manage to circumvent the issue. I'm embarrassed to admit, that despite having played JA2 semi-regularly since 2007, I keep forgetting that "Done" button exists. xd

Have a good one. I'll try not forgetting about it, and I'll let you know of the results once I test them.

**Comment by lynxlynxlynx** [comment]
Closing, since it still looks like it was an installation problem.
