### ISSUE TITLE
Incorrect condition, || instead of &&

### ISSUE THREAD

**Issue by sevenfm** [ja2-stracciatella/ja2-stracciatella#1463]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/432ee5b6398b5dca72529129c7cfd0476a5689dc/src/game/Tactical/OppList.cc#L3517

Probably should be
if ((ubSourceTerrType >= FLAT_GROUND) && (ubSourceTerrType <= DEEP_WATER))
or else any ubSourceTerrType will pass the check, including NO_TERRAIN and NUM_TERRAIN_TYPES:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/432ee5b6398b5dca72529129c7cfd0476a5689dc/src/game/TileEngine/TileDef.h#L41-L56
[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|    |    |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Good catch, thanks!
