### ISSUE TITLE
Minor regression of VFS case-insensitivity

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1465]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

We used to allow mods to have data directory of either `$MOD_NAME/Data` or `$MOD_NAME/data`. Just tried on master build and the former is no longer working on case-sensitive filesystems.

> sgp/SGP.cc: Game has been terminated due to an unrecoverable error: Failed to build virtual file system (VFS): Vfs_init_from_engine_options: Error initializing VFS for "$HOME/.ja2/mods/unfinished-business/data": No such file or directory (os error 2) (St13runtime_error).

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  master |   |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
Can reproduce. Sorry, I think that comes from my `ModManager` change. Its easy to fix as you can see in https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1466. But I want to add some regression tests, so this doesn't happen again in the future.
