### ISSUE TITLE
crash in chitzena

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1476]
After clicking OK @ "You cannot train the militia in Chitzena any further". 

[Thread 30960.0x9828 exited with code 0]
[New Thread 30960.0x1664]

Thread 1 received signal SIGSEGV, Segmentation fault.
SquadIsEmpty (bSquadValue=20 '\024') at C:/msys64/home/askon/ja2-stracciatella/src/game/Tactical/Squads.cc:271
271     C:/msys64/home/askon/ja2-stracciatella/src/game/Tactical/Squads.cc: No such file or directory.
(gdb)

**Comment by ja2-derek** [comment]
Which JA2S version are you playing on?

**Comment by askondro** [comment]
the latest git version

**Comment by askondro** [comment]
$ git show
commit 6506b7dfe841747cd8aff01662f8f99dfbdb5039 (HEAD -> master, origin/nightly, origin/master, origin/HEAD)
Merge: e17fbcb52 2a9374c4b
Author: Jaka Kranjc <smgl@lynxlynx.info>
Date:   Sat Mar 19 20:34:13 2022 +0100

    Merge pull request #1462 from ja2-stracciatella/reduce-direct-item-id-references

    Reduce direct references to item ids

**Comment by ja2-derek** [comment]
Do you have a save game for this? I can't think of what cases would cause this.

**Comment by ja2-derek** [comment]
This should be the line for the crash:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/d56dbfcd0ff1cdad1c4e94e9190acc711ed3c675/src/game/Tactical/Squads.cc#L200

`iCurrentTacticalSquad` should be `20`, i.e. `NO_CURRENT_SQUAD`

**Comment by askondro** [comment]
I don't have a save game for this issue right now.
