### ISSUE TITLE
Chat boxes sometimes don't fit the text

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1477]
### What is wrong

From discord. Sometimes chat boxes dont seem to fit (see screenshot) in current master.

![image](https://user-images.githubusercontent.com/848854/159740134-e04a411b-43b5-4e6a-9b87-8d8fa308f572.png)

I am pretty sure this worked before (as the height is dynamically calculated).

Possible culprits are:

- https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1445: Chinese translation touched some text formatting code
- **https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1450: I changed some text formatting code to make save game warning dialogs format nicely

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git | German (in the screenshots case)  |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Looks like an off-by-1 error somewhere. A pixel or two more of workable space and `einen` would fit on the first line and everything else would fall into place.

**Comment by lynxlynxlynx** [comment]
This is visible with English as well — the first time you speak to the rebels, with Carlos's short first comment.

**Comment by lynxlynxlynx** [comment]
Found a way to force this one relatively easily, you just have to press w when down there:

```
diff --git a/src/game/Tactical/Turn_Based_Input.cc b/src/game/Tactical/Turn_Based_Input.cc
index ec2466d07..0af5f7438 100644
--- a/src/game/Tactical/Turn_Based_Input.cc
+++ b/src/game/Tactical/Turn_Based_Input.cc
@@ -1488,7 +1488,12 @@ static void HandleModNone(UINT32 const key, UIEventKind* const new_event)
                        DisplayGameSettings();
                        break;
                case 'w':
-                       ToggleWireFrame();
+                       //ToggleWireFrame();
+               {
+                       const SOLDIERTYPE* const pNPCSoldier = FindSoldierByProfileID(CARLOS);
+                       if ( !pNPCSoldier )     return;
+                       TriggerNPCRecordImmediately( pNPCSoldier->ubProfile, 1 );
+               }
                        break;
 
                case 'x':
diff --git a/src/game/TacticalAI/NPC.cc b/src/game/TacticalAI/NPC.cc
index 90910569b..0bfd42e4a 100644
--- a/src/game/TacticalAI/NPC.cc
+++ b/src/game/TacticalAI/NPC.cc
@@ -1124,6 +1124,7 @@ static UINT8 HandleNPCBeingGivenMoneyByPlayer(UINT8 const ubNPC, UINT32 const ui
 
 static UINT8 NPCConsiderQuote(UINT8 const ubNPC, UINT8 const ubMerc, Approach const ubApproach, UINT8 const ubQuoteNum, UINT8 const ubTalkDesire, NPCQuoteInfo* const pNPCQuoteInfoArray)
 {
+       return TRUE;
        //This function looks at a quote and determines if conditions for it have been met.
        // Returns 0 if none , 1 if one is found
        NPCQuoteInfo *                          pNPCQuoteInfo;
```

**Comment by lynxlynxlynx** [comment]
That nicely allowed for a quick bisect, which led to 8cd27238, which indeed has some wrapping related changes.

**Comment by lynxlynxlynx** [comment]
The changes to src/game/Utils/WordWrap.cc don't matter, so it's the change to src/game/Utils/MercTextBox.cc. Will check what's so different about the two functions. @selaux do you remember why you changed it to use IanDisplayWrappedString?

**Comment by lynxlynxlynx** [comment]
I was right, it is an off-by-1 problem, this fixes it for me:
```diff
diff --git a/src/game/Utils/WordWrap.cc b/src/game/Utils/WordWrap.cc
index aaea38aea..d33568b76 100644
--- a/src/game/Utils/WordWrap.cc
+++ b/src/game/Utils/WordWrap.cc
@@ -333,7 +333,7 @@ UINT16 IanDisplayWrappedString(UINT16 sx, UINT16 sy, UINT16 max_w, UINT8 gap, SG
                                                && *i != U'\0');
 
                                // can we fit it onto the length of our "line"?
-                               if (line_w + word_w >= max_w)
+                               if (line_w + word_w > max_w)
                                { // can't fit this word!
                                        // Display what we have up to now
                                        IanDrawTextToScreen(line_buf, x, y, cur_max_w, cur_font, cur_foreground, background, justification, flags);
```

**Comment by selaux** [comment]
I used `IanDisplayWrappedString` because it supports manual linebreaks while `DisplayWrappedString` does not. Also it seemed more similar to `IanWrappedStringHeight` which is actually used to calculate the height for the messagebox.

**Comment by lynxlynxlynx** [comment]
Ok, then we just fix that function and be done with it. Might actually be a vanilla bug manifested through a non-vanilla one.
