### ISSUE TITLE
Game speed / walking speed

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#148]
Originally reported by: **Andrey Tuzov (Bitbucket: [Kokkolar](http://bitbucket.org/Kokkolar), GitHub: [Kokkolar](http://github.com/Kokkolar))**

---

Setting **ms_per_game_cycle** below **25** has no effect

If i set **100** - game will very slow
but
if i set **5** - game speed is equal to **25**

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/148

**Comment by lynxlynxlynx** [comment]
Sounds like the processor changing sleep states leading to a speed boost.

So what remains is to check if walk speed really is independent of the cycle setting. Also see #99 .

**Comment by lynxlynxlynx** [comment]
Investigation by Derek:
> The game speed is somehow tied to system clock. If you really want to speed up the game so it feels like running Vanilla on a modern computer. You can change the below line:
> 
> https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7d66aa47554c125a250db5d27dd4f77acb513ae8/src/game/Utils/Timer_Control.cc#L139
> 
> to:
> 
> ```c
> g_timer = SDL_AddTimer(BASETIMESLICE / 2, TimeProc, 0); 
> ```
> 
> Then the game will run twice as fast (or as fast as your CPU can handle). You may also need `"ms_per_game_cycle": 1`. Hope that helps your hacking.

**Comment by derek9gag** [comment]
We can implement something like  "ms_per_time_slice" for this. I think this time slices affects mostly UI (e.g. laptop load speed) and animations (run speed)

**Comment by ja2-derek** [comment]
We can implement something like "ms_per_time_slice" for this. I think this time slices affects mostly UI (e.g. laptop load speed) and animations (run speed)

**Comment by lynxlynxlynx** [comment]
Sounds good.

And we can remove CALLBACKTIMER, since it's a useless define.
