### ISSUE TITLE
Trouble debugging aborts

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1489]
It looks like I can't break on the syscall, as `abort` from rust overrides it
```gdb
terminate called after throwing an instance of 'ST::unicode_error'
  what():  Invalid UTF-8 sequence byte

Thread 1 "ja2" received signal SIGABRT, Aborted.
0x00007ffff792418b in ?? ()

(gdb) b abort
Breakpoint 6 at 0x555555693b61: file library/std/src/process.rs, line 1975.
(gdb) b abort
abort
abort@plt
crossbeam_utils::atomic::seq_lock::SeqLockWriteGuard::abort
panic_abort::__rust_start_panic::abort
std::process::abort
std::sys::unix::abort_internal
```

So I can't catch the abort as it happens, which is very annoying.

**Comment by selaux** [comment]
Have you tried commenting out the `TerminationHandler` catch and `GameLoop` catch in `SGP.cc` and `GameLoop.cc` respectively? This has helped me in the past to catch masked errors, because it does not try to do the additional error save stuff, which itself triggers other errors sometimes.

**Comment by lynxlynxlynx** [comment]
What does work is breaking directly on __GI_abort.

**Comment by lynxlynxlynx** [comment]
It works again, without having updated any software. 🤷🏾 Breaks on both the normal and rust version.
