### ISSUE TITLE
Numlock in save screen

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#150]
Originally reported by: **Andrey Tuzov (Bitbucket: [Kokkolar](http://bitbucket.org/Kokkolar), GitHub: [Kokkolar](http://github.com/Kokkolar))**

----------------------------------------

Numlock numbers work inadequate in save screen. Looks like they work both ways: as a number and as an arrow. So it makes impossible to set save name by digital keyboard.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/150

**Comment by derSteFfi** [comment]
can not confirm on current master. works fine for me. can someone else reproduce this?

**Comment by lynxlynxlynx** [comment]
Same here (both modes work), so I suspect the reporter had hw issues. Closing.
