### ISSUE TITLE
Newer Android release cant be installed over older Android release

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1503]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Currently it's not possible to install `0.19.0` APK while having `0.18.0` installed in Android. I don't think this is release-breaking, as the Android Port is not officially advertised yet. Workaround is to uninstall the old version and then installing the new version, but uninstalling the App (at least for me) also deletes associated config data / saves which is annoying.

My current guess on why that is happening: We currently sign the APKs in the CI with auto-generated developer keys, which are probably different for each CI machine. We should have a consistent keystore from which to pull the signing keys instead.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.0 | irrelevant  |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
I agree, let's postpone this instead of the release. I know android also became much more strict about storage, since I was following the hoops oruxmaps had to jump through to be compliant with recent releases.
