### ISSUE TITLE
Should the launcher fork?

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1507]
It's not receiving updates, so it's easy to create artefacts:
![image](https://user-images.githubusercontent.com/121515/163581901-198b176b-10d8-4b43-a7fe-2f06b0bf2004.png)

So it'd be better if it launched other programs in their own processes with perhaps some controls disabled.

**Comment by selaux** [comment]
Yep. Ideally it would capture the log messages as well, so they can be displayed somewhere in the launcher.
