### ISSUE TITLE
Small issues with the new Save Game screen

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1508]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.0  |  1.12  |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)
1. Open the save game screen
2. Click on any empty space in the main panel, to deselect any selected game slot
3. Click "Save"
4. Crashes with error:
   ```
   terminate called after throwing an instance of 'ST::unicode_error'
     what():  Invalid UTF-8 sequence byte
   Aborted (core dumped)
   ```

   The crash should be coming from this line, `header().sSavedGameDesc` being NULL:

    https://github.com/ja2-stracciatella/ja2-stracciatella/blob/8769f9bce12a8f2a9ff8f00ed974dae7c7ac6902/src/game/SaveLoadScreen.cc#L725

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by ja2-derek** [comment]
A couple more small issues with the new save screen:

1. There should be a button to delete old saves.
2. Small issue with empty save game description - when you save new file without description, the "Save Game" mouse button does not respond, but you can still save with "enter" on the keyboard.

**Comment by lynxlynxlynx** [comment]
1. is an enhancement and 3. I wouldn't consider a bug.

**Comment by selaux** [comment]
1. Should be already implemented (it's the delete key)
2. Agreed
3. I agree that it's different than before. Do you think it is better to hide it? I think it's good to give the players the possibility to pick up where they left, even if it sometimes does not work (maybe highlighting via a message that it sometimes might not work would be good).

**Comment by ja2-derek** [comment]
Aha. I didn't know I can use the delete key.

Actually the `Error.sav` has a description ""error savegame". That should be good enough.

**Comment by ja2-derek** [comment]
Delete also crashes, if there are no slots selected.

**Comment by lynxlynxlynx** [comment]
Perhaps easiest to disallow deselection.

**Comment by ja2-derek** [comment]
> Perhaps easiest to disallow deselection.

Also disable the button and hotkey when the list is empty.

**Comment by selaux** [comment]
When doing deselection with the escape key, disabling the button and hotkey already seems to work, so it should be a matter of comparing those code paths.

**Comment by ja2-derek** [comment]
Can I change the save game description when I overwrite an existing file?

**Comment by selaux** [comment]
No that is currently not possible. Do you think it makes sense to add?

**Comment by lynxlynxlynx** [comment]
That's a quite typical feature, so I also think it makes sense.

**Comment by ja2-derek** [comment]
Quick save used to be always the first entry in the list. Now it seems to be sorted by modified time instead. Should we still reserve the first slot for it?

**Comment by lynxlynxlynx** [comment]
I think it's fine to leave quick- and autosaves sorted as the rest, so it's easier to tell how old they are (when I think how sequentially I usually save).

**Comment by ja2-derek** [comment]
Agreed. The important ones are fixed, so maybe we can close this now?
