### ISSUE TITLE
Extract hardcoded translations from C++ to JSON

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#1511]
There are some translations that are hardcoded in C++, e.g. in [`_GermanText.cc`](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/ddc2b5e1d3ac3b95477369151214b71d234f3e1b/src/game/Utils/_GermanText.cc). We should migrate them to JSON, as the current implementation comes with [unneccessary risks](https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1504) and they are not moddable.

**Comment by lynxlynxlynx** [comment]
Closing as implemented.
