### ISSUE TITLE
The game crashes when assigning a merc to a new squad from the strategy screen

### ISSUE THREAD

**Issue by manuelseeger** [ja2-stracciatella/ja2-stracciatella#1512]
### What is wrong
The game crashes when assigning a merc to a new squat from the strategy screen, at the very beginning of the game. 

I started a new game just to meet Hamous to hear his dialogue / responses. So I sent my group immediately out of Omerta and wanted to split them up to search Hamous spawn location. The game crashes immediately when from the strategy game I try to assign a merc to a different squat.  

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.19.0-git+27afbca | JA2 Gold English from steam  |    no?    |    yes     |

Steps to reproduce: 
- Hire mercs (tested with different mercs from AIM, no IMP with/without equipment)
- Leave Omerta immediately (no combat, no pickups, just leave to B09 or B10)
- On the road to Drassen, from the strategy screen, assign a merc to squat 2 from squat 1
- The game exits (exited with status code -1073741819)

I could not reproduce the problem in Omerta, but everytime on B09 or B10. 

Activated mods: From russia with love, generous rebels

Tested with different mercs on B09 and B10. 

Windows 10 21H1

Savegame (completely fresh start, expert, tons of guns, realistic, save anytime): 
[2022-04-20t10-48-21z-s1.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8520947/2022-04-20t10-48-21z-s1.zip)

**Comment by ja2-derek** [comment]
Thank you for the report. I can reproduce the crash with 0.19.0.

**Comment by ja2-derek** [comment]
It crashes at SquadIsEmpty:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b6cdadfbd5904b0145d125ce54bb9426a6e5e890/src/game/Tactical/Squads.cc#L268-L276

And `bSquadValue` was `20`. It should the same crash as #1476.
