### ISSUE TITLE
Most of the "sleep" button for 18th merc acts like start/stop time

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [ja2-stracciatella/ja2-stracciatella#1517]
Trying to click the sleep button for 18th merc instead acts like start/stop time (space), except for the very left and right edge where it works normally. The mouseover tooltip even says so, see attached screenshots (which are darker than actual game for some reason). The place where this button should be is inert to clicking.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19  | JA2 Gold English  |   no    |    ?     |

Win 8.1, resolution 1366x768, I've tried all scaling options with same results.
![bugJA1](https://user-images.githubusercontent.com/43598424/164892042-6f8e4c92-6b0e-4f3e-beaf-d3f039c08293.jpg)
![bugJA2](https://user-images.githubusercontent.com/43598424/164892043-348865eb-5362-4d81-950d-8fdbaa77476e.jpg)

**Comment by lynxlynxlynx** [comment]
Thanks, it's most likely a problem with the hardcoded regions/coordinates the engine is using.

**Comment by NoFreeUsernameDammit** [comment]
> 

Ask and you shall receive, dude :D.

Mods: Generous rebels, From Russia with love, IMP honest answers. 
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8548466/QuickSave.zip)
