### ISSUE TITLE
Ice Cream truck out of fuel crash?

### ISSUE THREAD

**Issue by Bdan720** [ja2-stracciatella/ja2-stracciatella#1537]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
I think there could be a bug with the icecream truck when it runs out of fuel. (I notice the XX warning) When reaching its destination, the game hard crashes. Refueling the van delays this crash. Leaving the truck and travel on foot is stable.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.1 | JA2 from GOG  |    yes?    |    ???     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)
To reproduce bug? Move the truck around.

Windows 10 Home.

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

2022-05-07T09:15:22 [WARN] game\Tactical\Tactical_Save.cc: SynchronizeItemTempFile() Reported 0, should be 45
2022-05-07T09:15:24 [ERROR] sgp\SoundMan.cc: Could not commit read pointer for channel 1: At end
2022-05-07T09:15:27 [ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: Parameter index out of range
Creating an emergency savegame succeeded (Error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame. (class std::runtime_error)
2022-05-07T09:15:29 [ERROR] launcher\Launcher.cc: Command_execute "L:\\Games\\JA2 Stracciatella\\ja2.exe" []: exited with status code -1073740791

Here are some of my save files. Hope this is ok. 
[2022-05-07-d38 save files.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8644800/2022-05-07-d38.save.files.zip)

**Comment by momoko-h** [comment]
So, this crashes in `ReportVehicleOutOfGas`. The format string is `"The %s has run out of gas and is now stranded in %c%d."` but we are providing only two arguments.

**Comment by selaux** [comment]
Might be an oversight from the sector refactoring. It should only require the one argument `sMap.AsShortString()` and `%s` instead of `%c%d` in the format string. It needs to be changed for all translations though...
