### ISSUE TITLE
Assertion failed FPS drop with display cover key

### ISSUE THREAD

**Issue by MrMaggot** [ja2-stracciatella/ja2-stracciatella#1548]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Framerate drops to single digits when using the display cover key directly south/southwest of the player's squad. The error ```[ERROR] game\Tactical\DisplayCover.cc: Assertion failed in C:\projects\ja2-stracciatella\src\game\Tactical\DisplayCover.cc, line 170``` repeats in the log for as long as the key is held. Bug encountered on Windows 10 and the save can be downloaded at https://drive.google.com/file/d/1UYMNWIP1Ir5DWAauXfx5QMv-1DTA05NY/view?usp=sharing

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.20.0-20220519+12a919a | JA2 Gold  |    don't know    |    don't know     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by MrMaggot** [comment]
Tested this bug on Arch instead of Windows 10 and there was no framerate drop, but the assertion errors still occur. The first couple of cover values being checked by the assert on line 141 are within the bounds, but afterwards they go into the negatives and fail the assertion. I also noticed that some of the cover tiles being drawn were different between Windows 10 and Linux as some cover tiles were not being drawn on W10 that are present on Arch.

**Comment by momoko-h** [comment]
DisplayCover.cc:332 was `bPercentCoverForGridno = 100 - __min(iTemp, 100);` but is now `bPercentCoverForGridno = std::min(0, 100 - iTemp);` which is simply not the same thing when iTemp is greater than 100.

**Comment by MrMaggot** [comment]
Is there a reason it was changed from min between iTemp and 100 to 0 and the difference between iTemp and 100? The commit where it was changed doesn't mention anything about it https://github.com/ja2-stracciatella/ja2-stracciatella/blame/1abcb4e7d89d0bcd5acbbe02518f4e2f1bc3351c/src/game/Tactical/DisplayCover.cc#L332 @lynxlynxlynx

**Comment by lynxlynxlynx** [comment]
`std::clamp` will be cleaner.
