### ISSUE TITLE
JA2 Stracciatella on Mod DB

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#155]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

I have created a page on Mod DB for JA2 Stracciatella to promote the project and attract some more people to it.

[http://www.moddb.com/mods/ja2-stracciatella](http://www.moddb.com/mods/ja2-stracciatella)

Comments? Ideas?

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/155

**Comment by derSteFfi** [comment]
since this is a proposal that was done, should we close it?

**Comment by lynxlynxlynx** [comment]
Yes, it  is also already up to date. :+1:

**Comment by selaux** [comment]
Sweet thanks. :+1:
