### ISSUE TITLE
break lights disappear ?

### ISSUE THREAD

**Issue by Trokinos** [ja2-stracciatella/ja2-stracciatella#1556]
Using Stracciatella 0.19.1 on window 10

Not sure if it's a bu though, but it sounds like one.

Most of the time when a break light is thrown at your location during a night battle, you're faced with interesting choice :  
- use your action point to shoot as if nothing happened (and hope there's no more enemy in range but out of your sight that is able to fill you with bullets as they see you now clearly)
- lose some AP point but run away from the location to get back into the shadows (but you can't shoot back)
- waste your precious action points to pickup the break light and throw it elsewhere (but you can't move or shoot then)

But from what i regularly experience, nearly half of the time the enemy throw a break light to your position, the item itself will "disappear" while the light is created and will stay,  none of your mercs can pick up anything where the break light is supposed to be.

**Comment by selaux** [comment]
So, from the [code](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/TileEngine/Physics.cc#L2218) perspective there should be three cases:

- Enemy throws break light at you -> break light "fails to explode" -> item is created on the floor (invisible to mercs)
- Enemy throws break light at you -> break light "explodes" -> light is created, no item should be on the floor
- Enemy throws break light at you on a roof -> engine cant handle lights on roofs -> item is created on the floor (visible to the mercs)

So the case that a light source is created AND an item is created should not be possible. I've tested it with a merc and got behavior 2. Lets assume that the behaviors described above are the expected ones, can you confirm that it's actually none of those?
