### ISSUE TITLE
Doreen Harrows under attack animations not playing properly

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#157]
Originally reported by: **L C (Bitbucket: [LCJr](http://bitbucket.org/LCJr), GitHub: [LCJr](http://github.com/LCJr))**

---

When attacking Doreen(sweatshop manager) in Drassen in HtH combat the only animation that plays is the cowering/crouching civilian.  Never falls unconscious and her body disappears on death.  Key and money show up so purely cosmetic issue.

Arch Linux 64-bit
ja2-stracciatella-git-7410.97316b5  https://aur.archlinux.org/packages.php?ID=81474
Jagged Alliance 2 Stracciatella version 14.XX  

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/157

**Comment by lynxlynxlynx** [comment]
Sounds like wrong body type. Would be interesting to compare to original and perhaps do a git bisect.

**Comment by JAsmine-ja2** [comment]
Really funny stuff going on here. First off all, I remembered that I have seen this case (Doreen dying without proper animation and leaving no corps behind) before. No matter, if she was killed in HtH combat or with a bullet.

In my JA2 v1.12 English Vanilla on Windows, I managed to make Doreen die in two ways :)

![doreen1](https://cloud.githubusercontent.com/assets/17213795/20014745/8d61d0fc-a2b8-11e6-8ea2-0b4b2d264e5b.jpg)
![doreen-a1](https://cloud.githubusercontent.com/assets/17213795/20014746/8d625cf2-a2b8-11e6-8191-aa759913b391.jpg)
![doreen-a2](https://cloud.githubusercontent.com/assets/17213795/20014747/8d63b8b8-a2b8-11e6-8df2-aa3e8d7622a8.jpg)
![doreen-a3](https://cloud.githubusercontent.com/assets/17213795/20014744/8d61a186-a2b8-11e6-890b-8e4cd6b4b531.jpg)

Savegames for both situations: In one save, Doreen is severly wounded and needs only one final punch. **This leads to a proper animation!**
In the other save, she is not hurt (not hostile) yet. Attacking her bare-handed (she takes about 4-5 hits) **leads to missing death animation.**
I can reproduce it this way all the time.

Maybe, this needs some more testing. Maybe, this is enough. We'll see ;)

[SavedGames.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/572141/SavedGames.zip)

**Comment by flaviojs** [comment]
When Doreen dies and disappears the warning "Generic hit not chained" appears in the log:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/2f870b539ab6e97c452cc1864e89e8cbc797e291/src/game/Tactical/Soldier_Ani.cc#L3185

`pSoldier->usAnimState` is `CIV_COWER_HIT`, which came from `EVENT_SoldierGotHit`:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/2f870b539ab6e97c452cc1864e89e8cbc797e291/src/game/Tactical/Soldier_Control.cc#L2960

Cowering is kinda like crouching, but civs don't have the `FALLFORWARD_FROMHIT_CROUCH` animation so instead they need to use the standing animation.

Before the switch with the warning there is code to handle standing hit animation so a possible fix is to also use it for `CIV_COWER_HIT`.

This fixes the issue for me: [fix-157.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3482570/fix-157.txt)

**Comment by lynxlynxlynx** [comment]
LGTM, any particular reason you didn't directly open a PR?

**Comment by flaviojs** [comment]
The fix is based on targeted analysis, starting from the warning and going backwards.
I don't know enough about the animation code to judge if it's a proper fix.
I'll make a PR. :)
