### ISSUE TITLE
Crash at 20:55-6, Day 32

### ISSUE THREAD

**Issue by a-l-e-x-w-i-l-s-o-n** [ja2-stracciatella/ja2-stracciatella#1580]
### Unknown Crash
Hi everyone, thanks for making this mod, it's great! My game is crashing repeatedly at 20:55 or 56 on day 32, or at least that's what I'm able to replicate. The program exits to Win 10 with status code 1073740791. Crepitus has recently been trigged by Deidranna and about to find them in the mine.

I've attached the log, error message and a save file. First time posting a bug report so forgive me if there's more info I need to give, happy to oblige.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.19.1 | JA2 1.12 standalone installed from GOG  |       |         |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)
[savefile.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8954115/savefile.zip)
![error message](https://user-images.githubusercontent.com/107784560/174935667-3e0bd069-65f6-4749-a939-9e7cc5c600cb.png)
[error log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8954120/error.log.txt)

**Comment by ja2-derek** [comment]
This looks very similar to #1559.

@a-l-e-x-w-i-l-s-o-n  can you try the save with the latest nightly build (from [here](https://storage.googleapis.com/ja2-builds/index.html#nightlies/))? It might have been fixed already.

**Comment by a-l-e-x-w-i-l-s-o-n** [comment]
Thank you, that appears to have fixed it!
