### ISSUE TITLE
Militia trained in SAM sites sometimes not appearing on tactical map

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#159]
Originally reported by: **L C (Bitbucket: [LCJr](http://bitbucket.org/LCJr), GitHub: [LCJr](http://github.com/LCJr))**

---

Second occurance of this out of several games.  Once at NE(Drassen) SAM and again at NW(Chitzena) SAM.  Have yet to see happen in a town sector only SAM sites.  After training militia they are not being placed on the tactical map.

Workaround:  March all mercs out of sector and on return militia will be placed on the tactical map.  Save game attached.

Arch Linux 64-bit
ja2-stracciatella-git-7410.97316b5  https://aur.archlinux.org/packages.php?ID=81474
Jagged Alliance 2 Stracciatella version 14.XX

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/159

**Comment by LonCJ** [comment]
Ran into this one again so new savegame.

![missing_militia](https://cloud.githubusercontent.com/assets/17031358/14388597/dbdc190e-fd7c-11e5-875d-5cc7132c34a5.jpg)
[missing_militia.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/210397/missing_militia.zip)

**Comment by lynxlynxlynx** [comment]
closing, dupe of #292, but that one is a tiny bit better explained.
