### ISSUE TITLE
Random crashes when opening emails on the in-game laptop

### ISSUE THREAD

**Issue by oxisto** [ja2-stracciatella/ja2-stracciatella#1591]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### Random crashes when opening emails on the in-game laptop

Not many details unfortunately, I cannot cleanly re-produce this. It seems to be creep up from time to time. Seems to occur after a fight and when new emails arrive.

```
/Users/runner/work/ja2-stracciatella/ja2-stracciatella/ci-build/lib-string_theory/include/string_theory/st_utf_conv.h:263: String data buffer is too large
[1]    67228 abort      ./ja2
```

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.19.1 | JA2 Gold English  |   ?    |    ?    |

Operating system: macOS 12.3.1 (21E258), Apple M1

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Can you try the nightly build to see if it is present in the latest code as well?

**Comment by oxisto** [comment]
> Can you try the nightly build to see if it is present in the latest code as well?

Unfortunately it is a bit hard to test since I get a lot of drassen airport crashes with the latest build (see https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1589)

**Comment by selaux** [comment]
@oxisto FYI Next daily should fix the drassen airport bug.

**Comment by lynxlynxlynx** [comment]
@oxisto Have you managed to reproduce this with more recent code?

**Comment by oxisto** [comment]
> @oxisto Have you managed to reproduce this with more recent code?

Sorry I didn’t have time to test / play recently unfortunately but I’ll try :)

**Comment by ja2-derek** [comment]
I had a crash too after the first battle in Omerta. It happens right after the fight when I went back to laptop and click Email. But I can't reproduce it either. I didn't have debug on during the crash and the logs weren't helpful either.

**Comment by selaux** [comment]
I tried to reproduce this as well, but no luck here either. Even with address sanitizer. Should we remove this from the `0.20` milestone, if its not reproducible?

**Comment by lynxlynxlynx** [comment]
Yeah, no point in delaying.

**Comment by momoko-h** [comment]
It's hard to tell if this is the same issue, but loading the save from #1871 produces an ASAN crash in https://github.com/ja2-stracciatella/ja2-stracciatella/blob/385f718b4059e567bd86ae4083790a443c325e32/src/game/Laptop/EMail.cc#L2439 

I reported it as a [bug in string_theory](https://github.com/zrax/string_theory/issues/29).

**Comment by magras** [comment]
Reproduction:
1. Open any email
2. Close the laptop (without closing the email)
3. Save game
4. Load game
5. Try to open the email client in the laptop
6. Game crashes due to an abort signal

Reason: Global variable `CurrentMail` points to the deleted object.

I have a fast and dirty fix, but I'd like to better understand the code before PR.
