### ISSUE TITLE
Current Android target API set to Oreo (API 26)

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#1592]
It's not so much a bug, rather then question.

Is there any specific reason, why the current target API is set to just an Oreo? That's already a quite old Android version, and it sits there for as long as I can remember with Android releases. It's not that is some big issue or something, but if you would push Stracciatella one day to Play Store, this would need to be changed and push higher, since such an old API is no longer accepted by Google.

As far as I know, target API is independent on minimum API, so it can be changed without needing to push the minimum Android OS requirement higher.

Again, not a bug, I'm just curious about it, since JA2 Stracciatella is one of the "oldest" app in my phone (old as a app targeting such an old API).

**Comment by lynxlynxlynx** [comment]
Yeah, that scoped storage is a PITA, so I also wouldn't bump the API. Is there something still to do here or can we close?
