### ISSUE TITLE
Unable to run under AppImage - 'terminated by a signal' error

### ISSUE THREAD

**Issue by superuser-does** [ja2-stracciatella/ja2-stracciatella#1595]
Every time I attempt to launch, it seems Stracciatella fails to read the files in /usr. I have noticed I cannot open them directly through Dolphin though I can read the folder structure.
This is on a recent, standard install of Kubuntu Linux 22.04 (albeit under LUKS). I have [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) running though this shouldn't affect function to my understanding.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19 | GOG  |    N/A    |    no - initial attempt     |

Error log:
```
~/.local/bin/AppImages> ./ja2-stracciatella_0.19.1-git+6ad1b6f_x86-64.AppImage -debug
[DEBUG] (1) sgp/SGP.cc: Initializing Memory Manager
[DEBUG] (1) sgp/SGP.cc: Initializing Game Resources
[DEBUG] (1) stracciatella::mods: Found mod `from-russia-with-love` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/from-russia-with-love")`
[DEBUG] (1) stracciatella::mods: Found mod `generous-rebels` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/generous-rebels")`
[DEBUG] (1) stracciatella::mods: Found mod `imp-quiz-honest-answers` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/imp-quiz-honest-answers")`
[DEBUG] (1) stracciatella::mods: Found mod `o-fortuna` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/o-fortuna")`
[DEBUG] (1) stracciatella::mods: Found mod `simplified-chinese-localization` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/simplified-chinese-localization")`
[DEBUG] (1) stracciatella::mods: Found mod `test-json-dialogs` at `Path("/tmp/.mount_ja2-st5RdV6w/usr/share/ja2/mods/test-json-dialogs")`
terminate called after throwing an instance of 'std::out_of_range'
  what():  Parameter index out of range
[ERROR] launcher/Launcher.cc: Command_execute "/tmp/.mount_ja2-st5RdV6w/usr/bin/ja2" []: terminated by a signal
```
The string after `mount_ja2` changes every time.

**Comment by lynxlynxlynx** [comment]
Why do you think it has problems with paths? Everything looks fine in the log. The key question is why you get a runtime exception ... 
The image works for me on more recent kubuntu (I don't remember if our release was after I upgraded, but I might have tested with the same version as well).

**Comment by selaux** [comment]
We build on Ubuntu 18.04, so any version above should work. Are you using a unmodified version from GOG?

**Comment by superuser-does** [comment]
> Are you using a unmodified version from GOG?

There was a bit of a story to this honestly, where I was taking the installed version on an external Windows drive from years ago. It may not have been unmodified.

I did a clean install via Wine, and Stracciatella now just runs

I had the idea the paths were wrong because I cannot edit `game.json` in the `externalized` folder, getting an error `execvp: Permission denied`. I don't plan to anyway so I'm satisfied with that.

Now to resolve a major visual glitch that happens! (turns off my second monitor and then flickers the background upside down - really bizarre!) But that's for another issue and probably a system problem.

**Comment by selaux** [comment]
Editing json files within the AppImage directly does not work unfortunately, as the AppImage itself is read-only. But you have those two options:

- creating your personal mod in your `~/.ja2/mods/` directory and put the `game.json` into `~/.ja2/mods/custom-mod/data/`
- putting the `game.json` into `~/.ja2/data/` directly
