### ISSUE TITLE
Combatant counting in autoresolved combat is wrong

### ISSUE THREAD

**Issue by horenmar** [ja2-stracciatella/ja2-stracciatella#1625]
### What is wrong

When I autoresolve combat, the final count of mercs is wrong. (I ran into this when playing around with reproducing #1624)

This is what the initial count looks like, this makes sense

![autoresolve-start](https://user-images.githubusercontent.com/9026413/181725443-5e9b4bb0-1886-4656-a49b-f1e9db8f30e3.png)

-----

But the final count is very obviously wrong:
![autoresolve-end](https://user-images.githubusercontent.com/9026413/181725434-b2ad7767-f536-4e1d-9638-d19f3e05efb1.png)

----

And interestingly, it doesn't always go wrong (but it does most of the time, this was single run out of almost 20):
![autoresolve-end-correct](https://user-images.githubusercontent.com/9026413/181726396-2cffc023-3020-42b9-8033-85f4210c2635.png)

(Yes, this run was with an extra merc, but the same team can give the same 254 vs X result as below)

----

and when it goes wrong, the final result can still differ:
![autoresolve-end-2](https://user-images.githubusercontent.com/9026413/181725440-0d7c077a-68bd-43dc-9e6c-22b7d88e1c5e.png)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.1 release | JA2 Gold Pack from Steam|    maybe (see below)   |    no idea     |

I enabled 3 of the built-in mods, "Generous Rebels", "From Russia with love" and "Imp quiz honest answers", but I doubt this is related to them.

**Comment by ja2-derek** [comment]
I would guess it is counting the EPCs (escortable characters) wrongly.

**Comment by horenmar** [comment]
Yep.

I played with this a bit more, and from the outside (I am not checking the code, I am playing JA2 to have a break from writing code :smiley:), it seems that I get correct count if mercs die first, which cleanups the EPCs instantly. If EPCs die before mercs, then things break.

**Comment by momoko-h** [comment]
Do you have a saved game you would be willing to share? I don't have one where I am anywhere near John and Mary ATM.

**Comment by horenmar** [comment]
@momoko-h
[2022-07-29t14-51-49z-repro-1625.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/9220996/2022-07-29t14-51-49z-repro-1625.zip)

if you let the time run, it should deposit 1 merc + John and Mary into sector with enemies.
