### ISSUE TITLE
Change name of the user folder?

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#164]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

At the moment, relevant data like savegames etc. is stored in a folder called "JA2". Maybe, it would be more appropriate to rename the folder to "JA2 Stracciatella", since the folder is exclusively related to JA2 Stracciatella?
Of course, this is only a trivial aspect...

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/164

**Comment by selaux** [comment]
Maybe we could also make `ja2.ini` a json-file so we can drop the ini parsing library.

**Comment by derSteFfi** [comment]
That sounds great. We should tackle this as soon as v0.15 is out.

**Comment by lynxlynxlynx** [comment]
As for the folder name, I'd keep it, except perhaps on windows. On linux it should also be moved eventually, to respect XDG paths.
