### ISSUE TITLE
Crash on pressing the advance time button

### ISSUE THREAD

**Issue by arnodick** [ja2-stracciatella/ja2-stracciatella#1646]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Crash with the error message
`"Command execute folder_path\ja2.exe exited with status code -1073740791"`
The console says
`sgp\SoundMan.cc: SoundLoadDisk Error: pFilename is an empty string.`
Game is on day 5 with Chitzena and Chitzena SAM site taken. Pressing the time advance button causes the crash immediately.
2 mods are active, the IMP Honest Answers one, and my own which is just some value changes to weapons.json, no added or removed weapons, just some numerical changes to damage, range etc of guns. I've tried turning off both or one of the mods but the crash still occurs.

I don't believe this is a vanilla bug, as I've never had this crash before in previous versions of JA2 or Stracc.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

I've attached this save file.
[2022-07-30t01-57-04z-new-version.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/9334456/2022-07-30t01-57-04z-new-version.zip)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.19.1-git+6ad1b6f | eg. JA2 Gold English  |    no    |    yes     |

To reproduce, press time advance button, and it should crash 100% of the time.

 Windows 10, version 21H1

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
Most likely the same problem as #1559. You can work around it by going into tactical in D2 first before you advance time.

**Comment by arnodick** [comment]
> Most likely the same problem as #1559. You can work around it by going into tactical in D2 first before you advance time.

Yes that looks exactly like is happening with me. Thanks for the workaround!
