### ISSUE TITLE
game.json is not editable on Linux using the AppImage launcher

### ISSUE THREAD

**Issue by bcdrme** [ja2-stracciatella/ja2-stracciatella#1651]
Hello !

The AppImage seems to be mounting its files, meaning there's no way of modifying game.json anymore. Or there is a way and I can't find it ?

![image](https://user-images.githubusercontent.com/54471255/186526268-dca06e74-e0e7-41fb-b403-89fa966b85bb.png)

**Comment by lynxlynxlynx** [comment]
Create one in ~/.ja2 instead and it will have precedence. Images are readonly.

**Comment by bcdrme** [comment]
Thanks !
Wouldn't it make sense to create this file automatically at first launch so we don't have to do it manually ?

**Comment by lynxlynxlynx** [comment]
Oh, you meant game.json. Create that in ~/.ja2/data

**Comment by bcdrme** [comment]
That was it thanks.

**Comment by lynxlynxlynx** [comment]
added this FAQ to the page: https://ja2-stracciatella.github.io/how-to-run/#extra-configuration-and-modding
