### ISSUE TITLE
FileRepMalware?

### ISSUE THREAD

**Issue by Martin83SK** [ja2-stracciatella/ja2-stracciatella#1653]
Hello,

i don´t know if this is the right place to ask, but Avast detected FileRepMalware in Uninstall.exe in installed Jagged Alliance 2 Stracciatella Release 0.19.1

Is this the real threat or false alarm?

Has anyone of you this issue?

Thank you and wish you good day,

Martin

**Comment by lynxlynxlynx** [comment]
False alarm, but you can uninstall manually if it worries you — it's not hard.

**Comment by Martin83SK** [comment]
Hi,

I scanned the file with nod (file ok), malwarebytes (file ok), sended it to virustotal.com (1/69 positive), youtubers and you said it's ok. Uninstaller work's fine. Stracciatella is great ressurection for great (but dead) game, but didn't work under Windows XP, there I used only working (patch/mod) I found:

https://www.moddb.com/mods/ja2-113-mod/downloads/ja2-113-april-2008-english-release-v2085   

I buyed this game for 0.99E in action on gog (22.8. - 5.9.2022), hoping there will be working (like on youtube) patch/mod for modern resolutions (like Fallout Fixt) and I found it (Stracciatella for Win 10 and JA2 1.13 Mod for Win XP), so I'm glad.

Why there is no official release for this game like Jagged Alliance 2 HD? For example Stronghold HD has it. 

What do you think about Jagged Alliance 3 coming?


Thank you and have a nice day,

Martin

**Comment by lynxlynxlynx** [comment]
Good to have some confirmation. :)

WinXP might still work as a host actually, but that's a separate issue and I'm not sure anyone would like to bother.

There's nobody to make official game releases, the companies and publishers have gone under.
