### ISSUE TITLE
Runtime error when saving D6.dat

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#166]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

Map D6 crashes the map editor, when trying to save it. This happens even when nothing was changed. The map loads normally and can be edited, but always generates a runtime error when saving.
This happens to a unchanged map from Vanilla JA2 Gold v1.12 (attachment).

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/166

**Comment by JAsmine-ja2** [comment]
[D6.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2798947/D6.zip)

I attached the file from the original report. It is map D6 from vanilla JA2. It can be loaded in the editor, but saving it (without any changes) crashes the editor.

**Comment by lynxlynxlynx** [comment]
I vote for closing this then, thanks for the inspection.
