### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lunaryorn** [ja2-stracciatella/ja2-stracciatella#1660]
Is there a chance to get a new release?  I'd love to have the changes from https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1526 in a stable release to be able to package this code.

**Comment by guijan** [comment]
I think solving this issue #1599 before a release is important for the same reason of not downloading dependencies and using the system provided ones.

**Comment by lynxlynxlynx** [comment]
A new release is around the corner, so no point in an intermediary point one.

**Comment by lynxlynxlynx** [comment]
Closing in favour of #1680.
