### ISSUE TITLE
Can't save game

### ISSUE THREAD

**Issue by Bezimienny111** [ja2-stracciatella/ja2-stracciatella#1662]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
So the problem is I can't save game.  Don't know what to write more, as most important info are on screenshoot,

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.0         | From GOG            |    yes           |    no problems on 0.18.0     |

The error says "Cannot move file to another disk".

![obraz](https://user-images.githubusercontent.com/51023022/193637434-29032bca-0316-46a9-b64a-932afd43737e.png)

**Comment by ja2-derek** [comment]
I think this is already fixed in #1553. Can you try again with a nightly build? Download the latest nightly here:  https://storage.googleapis.com/ja2-builds/index.html#nightlies/

**Comment by Bezimienny111** [comment]
Thank you. It works now.
