### ISSUE TITLE
If Cambria recaptured by hostiles, you will get full amount of money like it is 100% yours every day

### ISSUE THREAD

**Issue by wertyzp** [ja2-stracciatella/ja2-stracciatella#1670]
vanilla, master branch
If Cambria recaptured by hostiles, you will get full amount of money like it is 100% yours every day
Savegame is attached
[2022-09-25t15-23-24z-random.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/9792809/2022-09-25t15-23-24z-random.sav.gz)

**Comment by momoko-h** [comment]
This looks like a vanilla bug to me, the code is still pretty much unchanged since then. I guess most players don't let mines fall back to the queen again, so this bug went unnoticed.
