### ISSUE TITLE
Invalid psycho behaviour

### ISSUE THREAD

**Issue by wertyzp** [ja2-stracciatella/ja2-stracciatella#1675]
master branch, 0.20

> Psycho also causes the merc to occasionally go on a small shooting rampage: if firing on single-shot, they will spontaneously switch to full auto, and when firing in full auto, they will spontaneously add more shots, often emptying the entire magazine in a single, sustained burst. If the weapon isn't able to fire in either burst or auto, the merc will instead suffer a small drop in morale.

This doesn't work as expected in ja2-straciatella
I remember that in vanilla game psycho worked like described above, also, when you have not enough action points to do a burst fire, you will still be able to do a burst, but your AP will drop to negative value

so, what doesn't work:
- no random burst when not enough AP 
- no additional bullets fired
- no morale drop if gun doesn't support burst fire when psycho burst triggered

**Comment by wertyzp** [comment]
also in original game psycho burst try with non-automatic weapon causes negative phrase by merc like "dammit"

**Comment by momoko-h** [comment]
What is the origin of this claim about psycho behavior? I see nothing like it in [the original source](https://github.com/dariusk/ja2/blob/876ccf5dfdad7e6821c5b26d6d783132ea1ab7a2/ja2/Build/Tactical/Handle%20Items.c#L419). [Our version](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/d95d98d42bd581cef449141eb348334cba74d5be/src/game/Tactical/Handle_Items.cc#L368) looks identical apart from formatting changes.

**Comment by wertyzp** [comment]
ok please pause this issue until I will find original ja2 and test it
This claim is based also on my own game experience 10 years ago

**Comment by momoko-h** [comment]
Maybe the text you quoted describes 1.13's behavior? Firing until the clip is empty would fit, they have this "fire until you run out of APs" mode. Also, [this line](https://github.com/1dot13/source/blob/62f3fc845359c467425b2d29de6e52c98ad5adac/Tactical/Handle%20Items.cpp#L656) matches your claim about a small drop in morale.

**Comment by wertyzp** [comment]
> Maybe the text you quoted describes 1.13's behavior? Firing until the clip is empty would fit, they have this "fire until you run out of APs" mode. Also, [this line](https://github.com/1dot13/source/blob/62f3fc845359c467425b2d29de6e52c98ad5adac/Tactical/Handle%20Items.cpp#L656) matches your claim about a small drop in morale.

ok this explains everything, thanks
it looks like vanilla game doesn't have such mechanics
the issue can be closed
