### ISSUE TITLE
Can't steal weapon from enemy on roof

### ISSUE THREAD

**Issue by wertyzp** [ja2-stracciatella/ja2-stracciatella#1676]
vanilla, master branch 0.20
This bug is from vanilla game
When on roof, you can't steal enemy weapon - it always returns nothing

Another bug was introduced somehow by one of latest commits - now if you fail to steal weapon, you get text like:
IGOR FAILED TO STEAL IGOR - the placeholder for weapon name always contains character name

**Comment by momoko-h** [comment]
Save to test this issue:
[2022-10-18t06-37-59z-steal-on-roof.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/9807396/2022-10-18t06-37-59z-steal-on-roof.zip)
