### ISSUE TITLE
0.19.1 AppImage ignores ~/.ja2/data/game.json

### ISSUE THREAD

**Issue by stackric** [ja2-stracciatella/ja2-stracciatella#1678]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
I downloaded ja2-stracciatella_0.19.1-git+6ad1b6f_x86-64.AppImage and unlike the previous version 0.19.0 it does not honor the game.json settings in my ~/.ja2/data/

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.1-git+6ad1b6f_x86-64 | JA2 Gold English  |    yes   |    yes     |

reproduction: create a custom game.json with different settings, start, check which settings are used
os: linux mint 20.3

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
I've just tested this and for me it reads `~/.ja2/data/game.json`. Do you have logs available for this?

One eventuality I can think about is that currently mods have higher priority in the VFS than `~/.ja2/data`. Are you maybe using mods that modify the `game.json`?

**Comment by stackric** [comment]
Thanks for looking into this. Only active mod is honest IMP quiz answers. How do I create a log?Am 21.10.22, 10:16 schrieb Stefan Lau ***@***.***>:

   
  I've just tested this and for me it reads ~/.ja2/data/game.json. Do you have logs available for this? 
  One eventuality I can think about is that currently mods have higher priority in the VFS than ~/.ja2/data. Are you maybe using mods that modify the game.json?

**Comment by selaux** [comment]
On linux, it should be a matter of starting the AppImage from the terminal. The honest answers mod should not affect it.

**Comment by stackric** [comment]
Ok, this is embarassing, but while getting the logs from 0.19.0 and 0.19.1 I didn't have the problem either - so please close this bug again, I'm sorry, no idea what I did there.
