### ISSUE TITLE
Picking up items underground

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#168]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

Barry can't pick up items in the STRATEGIC map although he is in the same sector, out of combat and the items are within reach.
I am not sure if this was possible in Vanilla JA2. I am very sure it is possible in JA2 v1.13.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/168

**Comment by derSteFfi** [comment]
but Barry is at an invalid location. If you're going into tactical, Barry is not painted correctly and can reach none of the tiles.
