### ISSUE TITLE
Game crashes in strategic view with SoundMan SoundLoadDisk error

### ISSUE THREAD

**Issue by theHexagoner** [ja2-stracciatella/ja2-stracciatella#1687]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

After playing the game for some time (in both cases maybe 6 or 7 hours), the game will hard crash when advancing time in the strategy screen. The ja2-Launcher window reports:

```
Timestamp [ERROR] sgp\SoundMan.cc SoundLoadDisk Error: pFilename is an empty string
Timestamp [ERROR] luancher\Launcher.cc Command_execute "~myPathTo\ja2.exe" []: exited with status code -1073740791
```

I haven't found anyway to directly reproduce it, but once it starts happening, I can reload the most recent save and it crashes at that spot every time. In both cases, I had just saved a game... maybe within 5 or 10 seconds of it blowing up when I advance time.

In both cases I had tweaked settings in game.json.  In the second case I had tweaked some stuff in some other json files.  The game ran "fine" for many hours in both cases.

I'm happy to send all files from the second instance, or attach them or whatever else somebody needs to look into this.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.19.1-git_6ad1b6f | JA2 Gold English  |    Yes   |    Yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Well what were the timestamps? It's unlikely this would be a sound issue.

**Comment by ja2-derek** [comment]
Doesn't it sounds like same [issue](https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1559) fixed by https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1560?

@theHexagoner can you try if the crash is still there with the latest [nightly build](https://storage.googleapis.com/ja2-builds/index.html#nightlies/)?

**Comment by theHexagoner** [comment]
@lynxlynxlynx The timestamp is my local time right before the crash. I agree it is probably not a sound issue. I truncated it because I didn't feel like typing it out by hand.

@ja2-derek I will go look at that issue and if the nightly build is downloadable as a windows exe I will try it and report back.

FWIW, I loaded Stracciatella with -debug option to see if I could get more information and the game does not explode anymore with that save point.

HOWEVER:  the game seems stuck in debug mode now.  Running it again _without_ the option, it is still very bad performing and seems to be logging continuously to the console.

**Comment by theHexagoner** [comment]
OK, nevermind about it not blowing up in "debug" mode.  I realized I'd done some different things, possibly changing the flow of the game, when I was trying that before.

It _does_ remain in debug mode, somehow, apparently, though.  Right before the crash it reports:

```
2022-10-23T18:04:52 [DEBUG] (1) game\Tactical\Points.cc: Deduct Points (14 at 25601) 0 -600
2022-10-23T18:04:52 [DEBUG] (1) sgp\SoundMan.cc: playing random Sound: ""
2022-10-23T18:04:52 [ERROR] sgp\SoundMan.cc: SoundLoadDisk Error: pFilename is an empty string.
2022-10-23T18:04:53 [ERROR] launcher\Launcher.cc: Command_execute "myPathTo\\ja2.exe" []: exited with status code -1073740791
```

I'm getting the latest build loaded up now.

Is there a way to turn debug mode off?

**Comment by theHexagoner** [comment]
Also discovered that turning off the option to play sounds causes it to not crash anymore.

**Comment by theHexagoner** [comment]
[log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/9847256/log.txt)

Here is the entire log from when it crashes.

**Comment by theHexagoner** [comment]
Oh nice, you have a way to see the log in the launcher now, LOL.

It's blowing up trying to load the game.json from the previous version.  I'll have to hand-jam my changes to it which will take a moment.

Looks like ja2.json has a setting for debug = true.  Did this get set by the new version, or can I set it to false for better performance?

**Comment by theHexagoner** [comment]
The game save does not crash at the same point with the new build.  Congrats! 

Remarkable that this game gets love still after so many years!  Thank you for all your hard work.

I set debug = false and it seems to be fine with that.
