### ISSUE TITLE
Warn if 1.13 is installed

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1693]
We get clueless users often enough that it would be cool if the launcher detected a 1.13 install and warned about it. I'm sure we can create a list of let's say 3-5 marker files that are likely to be installed in any configuration and test for them.

Perhaps our `assets/externalized/resource_packs` mechanism can be reused?

**Comment by ja2-derek** [comment]
Found a repo for the 1.13 game dir: https://github.com/kitty624/JA2-v1.13-7609-GameDir

Some obvious files to look for:
- Ja2.ini
- Data-1.13/
- Data/Ja2Set.dat.xml
- Data/Ja2_Options.INI

**Comment by hypertexthero** [comment]
Is 1.13 support planned or actively being worked on by someone?

**Comment by lynxlynxlynx** [comment]
No. To quote the website:

> Stracciatella walks a fine line between preserving the original gameplay, adding ease-of-life improvements and providing new inobtrusive optional features.

**Comment by hypertexthero** [comment]
Understood, thank you!

**Comment by lynxlynxlynx** [comment]
From what I can tell our ResourcePack stuff in guess.rs relies on archives and their hashes. For this we can't use hashes or sizes, since the contents will be arbitrary. A simple existence check is enough.
