### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [ja2-stracciatella/ja2-stracciatella#1700]
Would love to see a flatpak of this to make getting it running on the steamdeck easier!

**Comment by lynxlynxlynx** [comment]
What's wrong with the appimage?

**Comment by lunaryorn** [comment]
Flatpak provides sandboxing, shared runtimes, and desktop integration which app images can't provide.

I'm working on a Flatpak manifest at <https://github.com/lunaryorn/io.github.ja2-stracciatella>. It's mostly ready, but needs more testing, and still lacks some metadata.  

You can build it yourself with flatpak-builder, but I don't think it can be submitted to the flathub store.  Flathub requires a clear licensing situation, and if I understand things correctly the situation for stracciatella isn't clear.

**Comment by lynxlynxlynx** [comment]
It's clear, it's a shit license. 🤷🏾 
There is desktop integration for appimages as well, but like flatpak, it requires more to run.

**Comment by lunaryorn** [comment]
> It's clear, it's a shit license. 🤷🏾

I don't think flathub would object to the SFI license.  As far as I can see it allows redistribution and that's all flathub cares for.  But I think they'd object to this part:

> It is not known under which license Tron released his changes. All we know, the source codes were publicly available in his svn repository.

> There is desktop integration for appimages as well, but like flatpak, it requires more to run.

I know, e.g. appimagelauncher, but personally I think these are a bit of a hack.   But that's just my opinion, we don't need to discuss this 🙂   I just like flatpak more, so I tried to make a manifest.  I don't have much time of late, and it works for me, but if there's more interest I can try to polish it and even check out whether flathub would accept it.

**Comment by lynxlynxlynx** [comment]
Hmm, good point, never realized that. It can only be as good as the SFI one to be legal, but it could hypothetically be worse. Anyway, he's still reachable if someone wanted to clear it up.

**Comment by lunaryorn** [comment]
@lynxlynxlynx It'd be great to have this clarified… with the license clarified I could easily submit JA2 to flathub.  I'd love to do this.

However, I'm not familiar with the JA2 history; I only found out about this project a few month ago when digging through my old games.  I don't even know who "Tron" is to be honest 😇

**Comment by Ronald-Diemicke** [comment]
I echo that this would be awesome to get it submitted to the flathub
discover app - would likely help with discoverability by steamdeck owners!

**Comment by lynxlynxlynx** [comment]
You can learn about our history here, by looking at the three ja2s entries:
https://ja2-stracciatella.github.io/history/

I personally don't mind it being submitted, I'd just like to avoid the need to maintain it.

**Comment by lunaryorn** [comment]
> I personally don't mind it being submitted, I'd just like to avoid the need to maintain it.

I don't mind maintaining it; I'd just like to have some kind of "okay" from the team here.  Flathub prefers to have applications by upstream, or with explicit consent from upstream 🙂

**Comment by lynxlynxlynx** [comment]
You have my ok and I doubt others would disagree, but pinging them nonetheless: @selaux @ja2-derek @momoko-h.

**Comment by lunaryorn** [comment]
Thanks for your support.  I'm fine with maintaining the manifest.

I've submitted it to flathub at https://github.com/flathub/flathub/pull/3666; let's see what flathub has to say about its license.

**Comment by lunaryorn** [comment]
Meanwhile I've setup Github actions to build a flatpak bundle, see https://github.com/lunaryorn/io.github.ja2_stracciatella.JA2-Stracciatella/releases/tag/v0.20.0-1

You can download the flatpak file and install it with `flatpak install --user io.github.ja2_stracciatella.JA2-Stracciatella.flatpak`.

I'd appreciate testing 🙂

**Comment by monreal** [comment]
Having ja2 on flathub would be great but seeing how that review discussion went, it doesn't look like it will be there anytime soon :(

**Comment by swsnr** [comment]
@lynxlynxlynx I think you can close this issue 🙂

**Comment by swsnr** [comment]
@lynxlynxlynx See https://flathub.org/apps/io.github.ja2_stracciatella.JA2-Stracciatella 🙂

**Comment by lynxlynxlynx** [comment]
Thanks, it's up. :)

**Comment by swsnr** [comment]
@lynxlynxlynx Cool 🎉 would you like to have access to the repor which controls the flatpak build?  Just in case, don't expect you tomdo anything, just feels right that you folks have some control there 🙂

**Comment by swsnr** [comment]
@lynxlynxlynx I'm watching releases on this repo, and update the manifest accordingly when a new release is out 😉 

Jokes aside, it depends on the kind of update.  Normally, you just update the source URL and its associated SHA checksum in the manifest, add the new release in the appdata.xml, push the change to a new pull request, and merge that once the flathub build bot confirms that the manifest still builds.

But for this project, a new release likely involves updates in the Rust dependencies, so you'll need to run [a Python script](https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo) to convert the `Cargo.lock` file into a manifest for flatpak which allows flatpak to download all Cargo crates in advance.  That's necessary because the actual build process runs air-gapped, and has no access to the internet; everything needs to be downloaded in advance, which effectively enforces that all dependencies are declared in the manifest.

**Comment by lynxlynxlynx** [comment]
Thanks, that's good enough for me. If anyone on the team is interested in getting access, they will chime in themselves.
