### ISSUE TITLE
Inaccessible area in tactical view (SAME PROBLEM AS ISSUE #125)

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#171]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

This bug has a very negative impact on gameplay.
To understand it, look at the pictures.
The first one is from vanilla JA2 Gold:
![SCREEN2.jpg](https://bitbucket.org/repo/6zkzG5/images/2364441947-SCREEN2.jpg)

And here the same situation (same map file) in JA2 Stracciatella
![SCREEN1.jpg](https://bitbucket.org/repo/6zkzG5/images/2181310021-SCREEN1.jpg)

As you can see, there is way more area visible in the south of the map. On both screenshots, I scrolled down south as much as possible.

And now comes the bad thing about this: the "new" area in the Stracciatella map is inaccessible for the player. But enemies can (and will) end up there if invading the map from south.

If an enemy ends up in this area, he is stuck and invisible (SCREEN062 and SCREEN063) and cannot be hurt without cheat codes.

Apart from the problem with the enemies, most maps are not designed to be looked at in this area and as a result, they look a bit weird (roads ending before map border etc.)

This happens on ALL maps.
(SAME PROBLEM AS ISSUE #125)

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/171

**Comment by lynxlynxlynx** [comment]
This San Mona Brothel screenshot is a good test area:
http://pds15.egloos.com/pds/200912/19/94/f0092894_4b2cb1afca61f.jpg

My testing shows that we only show one extra line, independent of resolution.

**Comment by JAsmine-ja2** [comment]
I created a test map which shows quite well, what exactly is going wrong in Stracciatella vs Vanilla JA2.

Note that I scrolled to each corner as much as possible.

Showing Vanilla JA2 1.12 Gold vs. Stracciatella 0.16.0 (JA2 data from the same as vanilla) on the exact same map.




![vscreen000](https://user-images.githubusercontent.com/17213795/34689588-545e00d6-f4b6-11e7-8c30-aae3f6abca6f.jpg)

![screen000](https://user-images.githubusercontent.com/17213795/34689513-0fee618e-f4b6-11e7-8614-b1335da6521d.jpg)


![vscreen001](https://user-images.githubusercontent.com/17213795/34689524-15f0ab64-f4b6-11e7-9d4b-e4f15bbeee1d.jpg)

![screen001](https://user-images.githubusercontent.com/17213795/34689514-1018e8a0-f4b6-11e7-8b78-6101758cf86f.jpg)


![vscreen002](https://user-images.githubusercontent.com/17213795/34689526-167acbb4-f4b6-11e7-8f74-4267528d8119.jpg)

![screen003](https://user-images.githubusercontent.com/17213795/34689516-1066d984-f4b6-11e7-8748-75e20859f640.jpg)


![vscreen003](https://user-images.githubusercontent.com/17213795/34689528-16a1d5c4-f4b6-11e7-8bf2-b964d4c1a800.jpg)

![screen002](https://user-images.githubusercontent.com/17213795/34689515-1041709a-f4b6-11e7-9f28-2364be2ae619.jpg)


## savegames for vanilla and stracciatella:

[stracciatella.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1612869/stracciatella.zip)
[vanilla.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1612870/vanilla.zip)

**Comment by lynxlynxlynx** [comment]
This would be perfect for a new report, since it has everything. ;) It's also about display, less about the accessibility, though the saves will help test.

so if I'm reading this right, the results are:
left: 1 too many displayed
right: 1 too many displayed
bottom: 3 too many displayed
top: 3 too many displayed? Not sure if the top-left and top-right are equal there

**Comment by JAsmine-ja2** [comment]
left: 1 too many displayed **-> agree**
right: 1 too many displayed **-> agree**
bottom: 3 too many displayed **-> could be 2.** would need to check more closely to say for sure.
top: 3 too many displayed? Not sure if the top-left and top-right are equal there -> **no!** 2-3 too few.

**Comment by Manuel-K** [comment]
Note: Every change is from vanilla to stracciatella.

I don't see the left changes if I open the _top-left corner_ pictures in two tabs. When I switch between them, I see the change along the y-axis, i.e. some rows are missing. Focus on the dirt at the bottom of the barrel. It's visible in both pictures.

If I look at the _bottom-left corner_ pictures, I can see more columns and more rows.

_top-right corner_: Less rows, more columns.

_lower-right corner_: More rows, more columns.


We seem to have several edge case problems.

**Comment by lynxlynxlynx** [comment]
And when we did display one more row at the top, it showed too much already. So it's extra confusing.

**Comment by Manuel-K** [comment]
Vanilla has the same visible space regardless of which border you're looking at.

@JAsmine-ja2 Can you add some decorations to the non-edge borders of the test map. Something easily distinguishable would be great, i.e. something like
```
x
x x
x x x
x x x x
```
for the top border.

**Comment by JAsmine-ja2** [comment]
decoration on every side. even more stuff in the top-left corner

[vanilla.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1613258/vanilla.zip)
[stracc.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1613262/stracc.zip)

**Comment by Manuel-K** [comment]
You forgot the map file.

**Comment by JAsmine-ja2** [comment]
[a3.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1614286/a3.zip)

**Comment by chmallon** [comment]
Has anybody actually tried bisecting which commit introduced the change?
I see some candidates, but confirmation would be good.
It will probably just take a dozen steps to locate the culprit.

BTW: I'm losing overview of which one is the main issue.
Could all except one be closed as duplicate?

**Comment by lynxlynxlynx** [comment]
Not me, as I'm in the middle of a test run and keep losing the configuration with each rebuild.

I asked for a separate report for the same reason. But we have potentially two issues — one being the display and the other traversability.

**Comment by Manuel-K** [comment]
> But we have potentially two issues — one being the display and the other traversability.

If I remember my previous tests correctly we have both problems.

Anyhow. I'm too tired to do this now without a rather large chance to miss anything important.

**Comment by maxrd2** [comment]
This should be improved (fixed?) with commit aeba89a (#733).

Have added scroll padding to maps so unusable map areas wont get rendered in viewport. I haven't tried it with test map and savegame submitted above. Code can be tweaked to draw correctly without side effects just by changing values of 4 newly added defines.

I've noticed a code that modifies gsTLY, gsTRY. For example InitRenderParams() in RenderWorld.cc does
```
gsTLY += ROOF_LEVEL_HEIGHT
```
If I'm not wrong ROOF_LEVEL_HEIGHT is used to display roof level parts of the map, which would otherwise be hidden since the terrain level drawn behind it is inaccessible. Since gsTLY/TRY/CY and similar globals seem also to be used to figure which parts of the map are valid for soldier placement, this might be cause of #125. Maybe would be better to drop ROOF_LEVEL_HEIGHT completely from code and compensate it with scroll padding.
