### ISSUE TITLE
LMB doubleclicks on Android version after introducing touch controls

### ISSUE THREAD

**Issue by Stelcio** [ja2-stracciatella/ja2-stracciatella#1710]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

As title states, left mouse button always doubleclicks, making entering some menus or toggling some options troublesome. I use my tablet with mouse and keyboard, playing the game just like on a PC, but this change broke that, and I don't really want to switch to touch controls. 

I assume it's related to new touch controls. I'm currently using 0.20.0-20221009+10b3516, which is the most recent nightly version I found without this issue, and it doesn't seem to have those new controls either. 0.20.0-20221012+4e06cac already has both new controls and the issue. 

If it's not easy to fix, it would be sufficient to at least add an option to disable new controls, maybe.

VIDEO
0.20.0-20221009+10b3516:
https://youtu.be/lNMc3PrFYew
0.20.0-20221012+4e06cac:
https://youtu.be/RLP86lJ3fQs

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.20.0-20221012+4e06cac onwards | GOG  |    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Should be fixed, you can verify with this new build:
https://storage.googleapis.com/ja2-builds/pull-requests/1711/ja2-stracciatella_0.21.0-1711pullrequest+cdf35c7_android.apk

**Comment by Stelcio** [comment]
> Should be fixed, you can verify with this new build: https://storage.googleapis.com/ja2-builds/pull-requests/1711/ja2-stracciatella_0.21.0-1711pullrequest+cdf35c7_android.apk

Works fine now. Great job, thank you!
