### ISSUE TITLE
Cannot shoot soldiers. Only mouth icons appears.

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1723]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Cannot shoot soldiers in san mona. Sometimes the target appears as target. But mostly only as a mouth/lips icon.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
release/git | eg. JA2 Gold English  |    no    |    yes     |

![image](https://user-images.githubusercontent.com/670935/205728367-7226eb18-54bb-4d32-9260-c634a8c47816.png)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by askondro** [comment]
[SavedGames_2.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/10157492/SavedGames_2.zip)

**Comment by misanthropos** [comment]
I have tried your supplied game status and if you indeed finish your move and becomes ravens I had the mouth icon first too - however: if you hover away and back it will become the default target circle and you can shoot the guy :D

**Comment by askondro** [comment]
Yeah, this how I hit them, but it is annoying. Is this then the normal behavior? If it is I'll close the bug.

**Comment by misanthropos** [comment]
No - this is a bug, clearly.
