### ISSUE TITLE
Coolness of Tony's inventory

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#173]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

I'm just on day 2 and Tony is selling ammo with coolness 8. I've modded magazines.json among other stuff, but this should not be happening, should it?

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/173

**Comment by legolegs** [comment]
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/Tactical/ArmsDealerInvInit.cc#L97 

> // the following staple items are always deemed highly suitable regardless of player's progress:
> (bunch of ammo being added to shops)

If you just retextured one of standart magazines (and it is not for CAWS, P90, RR or G11) it should appear in shops. That's vanilla feature.

**Comment by lynxlynxlynx** [comment]
Good find, thanks, there are indeed some with coolness 8 in there.

**Comment by JAsmine-ja2** [comment]
Wow, nice find!! This game (and its devs) never stops to surprise!!
