### ISSUE TITLE
strategic map view of D15 Drassen SAM lacks information

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#1745]
The strategic map view of D15 Drassen SAM lacks information such as
- Controlled
- Militia
- Civilian Training

Compare with:
- D2 Chitzena SAM (has more info than D15)
- B4 outdoor sector (has same info as D15

It could be that D15 is treated as outdoor sector instead of a SAM sector. 

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.20.0-git+439a6d3| JA2 Gold English GOG  |    no    |    yes     |

How to reproduce the bug:
1. Enter strategic map view
2. Right-Click on D15

Operating system: Ubuntu 22.04.1 LTS

Save game:
[bugreport.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/10318117/bugreport.zip)

![D15](https://user-images.githubusercontent.com/39365524/209916544-6c643927-561c-41ad-a9b9-b9e112cf974a.png)
![D12](https://user-images.githubusercontent.com/39365524/209916547-a39c355c-455c-444b-a94c-804fe7b8e68b.png)
![B4](https://user-images.githubusercontent.com/39365524/209918266-0f4c1f36-7f0b-4dcf-b94b-67f2d3ec6dfb.png)

**Comment by momoko-h** [comment]
Two bugs in [one line](https://github.com/ja2-stracciatella/ja2-stracciatella/blame/master/src/game/Strategic/Map_Screen_Interface_TownMine_Info.cc#L361) :laughing: 

`if (bSamSiteID > 0 && IsSecretFoundAt(ubSectorID))`

should be
`if (bSamSiteID >= 0 && !IsSecretFoundAt(ubSectorID))`

The missing = is why you're getting the info for the D2 SAM site, the missing ! is why you're not getting info for D15 and I8.
