### ISSUE TITLE
Mercs "bored/resigned - low morale" quotes are not beign played when selecting merc 

### ISSUE THREAD

**Issue by ja2forever** [ja2-stracciatella/ja2-stracciatella#1757]
JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64 | JA2 Gold 1.12 English CD  |    no    |    yes in vanilla     |

While your mercs morale are dropping to some degee they will start changing quotes when ordered to go somewhere or when you select them and make them feel like they are annoyed by your commandship. 

This works while you order merc to ex go somewhere they will play "annoyed quote" but they will not play annoyed quote when they are selected anymore regardless if you select couple of them at once or just one merc. Used to work ok in vanilla.

**Comment by momoko-h** [comment]
It took [almost 15 years](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/f2af9f522f55c75d96c81f6759e00bed6c731ffd/Build/Tactical/Soldier_Control.cc#L6271) for someone to notice this. :open_mouth: That assignment does not belong inside the if block.

**Comment by momoko-h** [comment]
I'm undecided whether the "Mute confirmations" option should also switch off the low morale variants. Yea or nay? In vanilla it does not if I read the code correctly.

**Comment by lynxlynxlynx** [comment]
I would match it out of principle.
