### ISSUE TITLE
No builds for arm64

### ISSUE THREAD

**Issue by ArchieFoxer** [ja2-stracciatella/ja2-stracciatella#1758]
The provided AppImage doesn't work on the 64bit Raspberry Pi OS
I'm using a Pi400

**Comment by lynxlynxlynx** [comment]
Which one?

**Comment by ArchieFoxer** [comment]
This one: 
https://github.com/ja2-stracciatella/ja2-stracciatella/releases/download/v0.20.0/ja2-stracciatella_0.20.0-git+439a6d3_armhf.AppImage

**Comment by ArchieFoxer** [comment]
> Which one?



> Which one?

This one:
https://github.com/ja2-stracciatella/ja2-stracciatella/releases/download/v0.20.0/ja2-stracciatella_0.20.0-git+439a6d3_armhf.AppImage

**Comment by lynxlynxlynx** [comment]
It's clearly marked for another architecture or are you saying you're running on a 64-bit ARMHF?

**Comment by ArchieFoxer** [comment]
I tried running it on a Pi400 which has ARM v8 CPU and with the 64 bit version of the Raspberry Pi OS installed

**Comment by lynxlynxlynx** [comment]
Or build it yourself.

**Comment by ArchieFoxer** [comment]
Can't get it to compile either. I'll try again later on a clean install since I think I messed up one of the dependencies

**Comment by misanthropos** [comment]
Have you tried: dpkg --add-architecture armhf
found it here:
https://unix.stackexchange.com/questions/625576/how-to-run-32-bit-armhf-binaries-on-64-bit-arm64-debian-os-on-raspberry-pi

**Comment by misanthropos** [comment]
ARM64 image is now available with 0.21.0. I took the liberty to try dpkg --add-architecture armhf and installing the missing libraries with some
dpkg -S missinglib and installing it via apt install missinglib:armhf.
after some iterations (fuse2, libz, sdl2..) it works.
However it is much slower in comparison.

**Comment by misanthropos** [comment]
aarch64 now available.
