### ISSUE TITLE
Crosshair doesn't change back to movement after hovering an enemy

### ISSUE THREAD

**Issue by Nindaleth** [ja2-stracciatella/ja2-stracciatella#1778]
### What is wrong

Hovering over a dying enemy in real-time mode switches the cursor to a crosshair, but moving the mouse cursor away doesn't change it back to movement - unlike the turn-based mode where it immediately changes back to the movement cursor.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.20.0, 0.21.0-dev | JA2 GOG English  |    no    |    yes, regression from 0.19.0 (broken by 3352e5d71d7db7b64eeb875c9aa74ae4fc21f559)     |

**Reproduction**

1. get an enemy into a Dying state
2. manage two turns without either them bleeding out or another enemy showing up
3. now in real-time, hover the mouse over the enemy

Here's a save to try it right away
[2023-02-03t22-24-08z-potentialdyingsave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/10609663/2023-02-03t22-24-08z-potentialdyingsave.zip)

**Env**
* Linux (Fedora 37)
* using the x86_64 AppImages

**Comment by momoko-h** [comment]
It is not just the crosshair cursor that gets stuck, if you for example tried to talk to the dying soldier you'd get stuck with the mouth cursor. This isn't only an interesting side note, it means fixing this only for the ACTION_MODE case in GetRTMousePositionInput() is not sufficient.
