### ISSUE TITLE
Alternate turn movement wont work

### ISSUE THREAD

**Issue by ja2forever** [ja2-stracciatella/ja2-stracciatella#1779]
| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64 | JA2 Gold 1.12 CD English  |    ?    |    ?    |

By clicking shift plus order movement for merc it seems like merc should display alternate path of movement but by pressing shift it only changes preview of movement and merc ignores this path and takes normal always. Plus shift movement is bottom screen.

![MOV NORMAL](https://user-images.githubusercontent.com/122088263/216839984-26295ef2-8857-4d2d-ba43-f6e84adb6a2e.png)
![MOV PLUS SHIFT](https://user-images.githubusercontent.com/122088263/216839986-ccee6907-d33e-4805-a554-f2310db59d30.png)

**Comment by ja2-derek** [comment]
This should be the same as #853.

**Comment by lynxlynxlynx** [comment]
Closing duplicate.
