### ISSUE TITLE
Attempt to remove dead merc from list results in CTD

### ISSUE THREAD

**Issue by ja2forever** [ja2-stracciatella/ja2-stracciatella#1788]
| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64 | JA2 Gold 1.12 English CD  |    no   |    ?    |

Tried to remove my dead merc from list to make space for other but it crashes instantly after clicking "remove merc" button. Unfortunately cant reproduce this as it seemed to happen when i was trying to add mercs using ctrl+g so there was full 18 merc squad and one dead in it. Dont know what was real cause
![Desktop_2023_02_13_08_39_58_465](https://user-images.githubusercontent.com/122088263/218518857-4c32eb6d-718b-4ac5-8de2-72cf19d7336e.png)

**Comment by lynxlynxlynx** [comment]
So the same scenario didn't cause the problem? Anything useful in the log?

**Comment by ja2forever** [comment]
Yes same scenario didnt caused anything - happened some time after save IIRC. I was just playing with teleporting and adding alt g mercs and hurting them ctrl+h and i think thats all.

Log just in case.
![Desktop_2023_02_13_08_40_45_745](https://user-images.githubusercontent.com/122088263/218548895-536357d7-dd2e-4e0e-bf62-42fdeb114622.png)

**Comment by momoko-h** [comment]
It's a null dereference in `RemoveMercMenuBtnCallback`, global variables strike again.

**Comment by momoko-h** [comment]
On a side note, the way the launcher presents error codes is awful. -1073741819 is 0xC0000005, a number that probably easier to recognize for Windows programmers as the code for an access violation.

**Comment by momoko-h** [comment]
> Maybe a more generic error message like "JA2 Stracciatella has crashed unexpectedly." would be less confusing. Or would you resolve know error codes to messages?

I don't think it has to be too fancy, just the error code in hex would be enough. After all, Microsoft trained Windows users for decades to recognize such numbers when they displayed HRESULTs in their error messages, before they lost their senses and started this "Something went wrong, try again later" nonsense.
