### ISSUE TITLE
Strange corspes in strange places after auto-resolve

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#179]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

Enemy attacked the SAM site in D2. They came from D3. Biff and Flo retreated to let the enemy duke it out with the militia. After the battle, corpses ended up in strange places.
Here:
![SCREEN001.jpg](https://bitbucket.org/repo/6zkzG5/images/1943756554-SCREEN001.jpg)
And here:
![SCREEN002.jpg](https://bitbucket.org/repo/6zkzG5/images/261349096-SCREEN002.jpg)

It's a minor thing, but I guess that any items on enemy corpses are also lost if the corpses is "underwater"...

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/179

**Comment by derSteFfi** [comment]
shouldn't we first merge this? :)

**Comment by lynxlynxlynx** [comment]
Oops, you just ff-ed it to master. Done.
