### ISSUE TITLE
Launch Crash

### ISSUE THREAD

**Issue by PhillyVanHilly** [ja2-stracciatella/ja2-stracciatella#1805]
`###` Game crashed upon clicking launch in the stracciatella app
![image](https://user-images.githubusercontent.com/127447560/224156799-f849b94a-a324-44ab-9e79-f6f482a0366c.png)

error log: 

 

> 2023-03-09T21:00:39 [INFO] stracciatella::logger: Logging to file "C:\\Users\\hilbe\\AppData\\Local\\Temp\\ja2.log"
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 24: DirFs { "C:\\Program Files\\JA2 Stracciatella\\externalized" }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 23: DirFs { "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 22: SlfFs { source: DirFsFile { "fonts.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 21: SlfFs { source: DirFsFile { "tilesets.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 20: SlfFs { source: DirFsFile { "loadscreens.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 19: SlfFs { source: DirFsFile { "npc_speech.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 18: SlfFs { source: DirFsFile { "maps.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 17: SlfFs { source: DirFsFile { "battlesnds.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 16: SlfFs { source: DirFsFile { "interface.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 15: SlfFs { source: DirFsFile { "anims.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 14: SlfFs { source: DirFsFile { "npcdata.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 13: SlfFs { source: DirFsFile { "sounds.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 12: SlfFs { source: DirFsFile { "binarydata.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 11: SlfFs { source: DirFsFile { "speech.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 10: SlfFs { source: DirFsFile { "laptop.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 9: SlfFs { source: DirFsFile { "data.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 8: SlfFs { source: DirFsFile { "bigitems.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 7: SlfFs { source: DirFsFile { "radarmaps.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 6: SlfFs { source: DirFsFile { "ambient.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 5: SlfFs { source: DirFsFile { "intro.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 4: SlfFs { source: DirFsFile { "cursors.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 3: SlfFs { source: DirFsFile { "music.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 2: SlfFs { source: DirFsFile { "mercedt.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] stracciatella::vfs: VFS item with priority 1: SlfFs { source: DirFsFile { "faces.slf" in "D:\\Spiele\\Steam\\steamapps\\common\\ja2_wildfire\\data" } }
> 2023-03-09T21:00:39 [INFO] externalized\DefaultContentManager.cc: JA2 Home Dir:                  'C:\Users\hilbe\Documents\JA2'
> 2023-03-09T21:00:39 [INFO] externalized\DefaultContentManager.cc: Root game resources directory: 'D:\Spiele\Steam\steamapps\common\ja2_wildfire'
> 2023-03-09T21:00:39 [INFO] externalized\DefaultContentManager.cc: Extra data directory:          'C:\Program Files\JA2 Stracciatella'
> 2023-03-09T21:00:39 [INFO] externalized\DefaultContentManager.cc: Saved games directory:         'D:\Spiele\Steam\steamapps\common\ja2_wildfire\SavedGames'
> 2023-03-09T21:00:39 [INFO] externalized\DefaultContentManager.cc: Temporary directory:           'C:\Users\hilbe\AppData\Local\Temp\ja2-stracciatella-iuVCSPY8'
> 2023-03-09T21:00:39 [INFO] game\GameLoop.cc: Version Label: Stracciatella v0.20.0-git+439a6d3
> 2023-03-09T21:00:39 [INFO] game\GameLoop.cc: Version #:     Build 04.12.02
> 2023-03-09T21:00:39 [ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: openGameResForReading: VfsFile_open "interface/b_map.pcx": entity not found (class std::runtime_error)
> 
> 

newest JA2 Wildfire Version from Steam
latest Stracciatelle version download 5min ago from official repo

 Win11 OS

**Comment by ja2-derek** [comment]
Wildfire does not work out of the box.

You can either use the JA2Classic directory coming with Steam version for vanilla gameplay, or you can install and use the [wildfire-maps](https://github.com/ja2-stracciatella/mod-wildfire-maps#how-do-i-install-the-mod) mod to use the new maps.
