### ISSUE TITLE
Incorrect random number

### ISSUE THREAD

**Issue by sevenfm** [ja2-stracciatella/ja2-stracciatella#1810]
### What is wrong

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/42628dc4dba47991dda3f8501372ac4785bafbb2/src/game/Tactical/Soldier_Init_List.cc#L485-L488

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/42628dc4dba47991dda3f8501372ac4785bafbb2/src/game/Tactical/Soldier_Init_List.cc#L499-L502

PreRandom(X) returns value between 0 and X-1
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/42628dc4dba47991dda3f8501372ac4785bafbb2/src/sgp/Random.cc#L76-L78

So PreRandom(1) will always return 0.
The original intention of code was probably to randomize left/right and up/down, so it should use PreRandom(2) instead.
```
PreRandom(8) * (PreRandom(2) ? -1 : 1) +
PreRandom(8) * (PreRandom(2) ? -1 : 1) * WORLD_ROWS;
```
```
PreRandom(30) * (PreRandom(2) ? -1 : 1) +
PreRandom(30) * (PreRandom(2) ? -1 : 1) * WORLD_ROWS;
```
[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  | |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
Yes, and I also wonder why this is using `PreRandom`, seems unlikely that anyone would try to reload until the goons are distributed to their liking. Also, strictly speaking, multiplying with WORLD_ROWS is wrong, that should be WORLD_COLS, it just doesn't matter here because the two values are identical.

**Comment by momoko-h** [comment]
The code that tries to handle Madame's employees is also pointless because they are not part of Kingpin's civilian group.
