### ISSUE TITLE
Compiling with clang on mingw64

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1816]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Cannot compile JA2 with clang 16.0.1 on mingw64 environment.

$ ninja -j1
[2/287] Building CXX object CMakeFiles/ja2.dir/src/externalized/scripting/EnumCodeGen.cc.obj
FAILED: CMakeFiles/ja2.dir/src/externalized/scripting/EnumCodeGen.cc.obj
C:\msys64\clang64\bin\c++.exe -DINSTALL_LIB_DIR=\"lib\" -DMINGW_STDTHREADS_GENERATED_STDHEADERS -DWITH_UNITTESTS -IC:/msys64/home/askon/ja2-stracciatella/src -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/army -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/content -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/internals -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/json -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/mercs -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/policy -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/scripting -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/strategic -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/strings -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/tileset -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/tactical -IC:/msys64/home/askon/ja2-stracciatella/src/externalized/ui -IC:/msys64/home/askon/ja2-stracciatella/src/externalized -IC:/msys64/home/askon/ja2-stracciatella/src/game/Editor -IC:/msys64/home/askon/ja2-stracciatella/src/game/Laptop -IC:/msys64/home/askon/ja2-stracciatella/src/game/Strategic -IC:/msys64/home/askon/ja2-stracciatella/src/game/Tactical -IC:/msys64/home/askon/ja2-stracciatella/src/game/TacticalAI -IC:/msys64/home/askon/ja2-stracciatella/src/game/TileEngine -IC:/msys64/home/askon/ja2-stracciatella/src/game/Utils -IC:/msys64/home/askon/ja2-stracciatella/src/game -IC:/msys64/home/askon/ja2-stracciatella/src/sgp -IC:/msys64/clang64/include/SDL2 -IC:/msys64/home/askon/ja2-stracciatella-build/lib-sol2/src/single/include -IC:/msys64/home/askon/ja2-stracciatella-build/lib-lua/src/src -IC:/msys64/home/askon/ja2-stracciatella/dependencies/lib-smacker/libsmacker -IC:/msys64/home/askon/ja2-stracciatella-build/lib-miniaudio/src -IC:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include -IC:/msys64/home/askon/ja2-stracciatella-build/lib-stracciatella/include -IC:/msys64/home/askon/ja2-stracciatella-build/lib-string_theory/include -IC:/msys64/home/askon/ja2-stracciatella-build/lib-mingw-std-threads/src -IC:/msys64/home/askon/ja2-stracciatella-build/lib-mingw-std-threads/build/cmake_stdheaders_generator/cmake_stdheaders_generator -isystem C:/msys64/home/askon/ja2-stracciatella-build/lib-gtest/src/googletest/include -isystem C:/msys64/home/askon/ja2-stracciatella-build/lib-gtest/src/googletest -Wall -Wtype-limits -Wignored-qualifiers -O2 -g -DNDEBUG -std=gnu++17 -MD -MT CMakeFiles/ja2.dir/src/externalized/scripting/EnumCodeGen.cc.obj -MF CMakeFiles\ja2.dir\src\externalized\scripting\EnumCodeGen.cc.obj.d -o CMakeFiles/ja2.dir/src/externalized/scripting/EnumCodeGen.cc.obj -c C:/msys64/home/askon/ja2-stracciatella/src/externalized/scripting/EnumCodeGen.cc
In file included from C:/msys64/home/askon/ja2-stracciatella/src/externalized/scripting/EnumCodeGen.cc:1:
In file included from C:/msys64/home/askon/ja2-stracciatella/src/externalized/scripting/EnumCodeGen.h:4:
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value -1 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 4294967295 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 4294967295 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  constexpr auto custom_name = customize::enum_name<E>(V);
                                                       ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value 257 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 257 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 257 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  constexpr auto custom_name = customize::enum_name<E>(V);
                                                       ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value 256 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 256 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 256 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
  constexpr auto custom_name = customize::enum_name<E>(V);
                                                       ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 256 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 256 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value 129 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 129 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 129 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
  constexpr auto custom_name = customize::enum_name<E>(V);
                                                       ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value 8 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 8 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:335:56: error: integer value 8 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
  constexpr auto custom_name = customize::enum_name<E>(V);
                                                       ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:371:12: error: integer value 9 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
    return static_cast<E>(static_cast<int>(i) + O);
           ^
C:/msys64/home/askon/ja2-stracciatella-build/lib-magic_enum/src/include/magic_enum.hpp:361:30: error: integer value 9 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
  return n<E, static_cast<E>(V)>().size() != 0;
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.

**Comment by momoko-h** [comment]
I can't build with clang16 either unless I use the -Wno-enum-constexpr-conversion compiler switch. Looks like we need the magic-enum 0.8.2 update.

**Comment by ja2-derek** [comment]
You can skip magic_enum with the `WITH_MAGICENUM` option.

**Comment by askondro** [comment]
```
C:/msys64/home/askon/ja2-stracciatella/src/sgp/SoundMan.cc:168:6: error: reference to 'mutex' is ambiguous
std::mutex mutexBuffersNeedService;
     ^
C:/msys64/clang64/include/c++/v1/__mutex_base:35:78: note: candidate found by name lookup is 'std::__1::mutex'
class _LIBCPP_TYPE_VIS _LIBCPP_THREAD_SAFETY_ANNOTATION(capability("mutex")) mutex
                                                                             ^
C:/msys64/home/askon/ja2-stracciatella-buid/lib-mingw-std-threads/src/mingw.mutex.h:476:24: note: candidate found by name lookup is 'std::mutex'
using mingw_stdthread::mutex;
                       ^
C:/msys64/home/askon/ja2-stracciatella/src/sgp/SoundMan.cc:169:6: error: reference to 'condition_variable' is ambiguous
std::condition_variable conditionBuffersNeedService;
     ^
C:/msys64/clang64/include/c++/v1/__mutex_base:275:24: note: candidate found by name lookup is 'std::__1::condition_variable'
class _LIBCPP_TYPE_VIS condition_variable
                       ^
C:/msys64/home/askon/ja2-stracciatella-buid/lib-mingw-std-threads/src/mingw.condition_variable.h:552:24: note: candidate found by name lookup is 'std::condition_variable'
using mingw_stdthread::condition_variable;
                       ^
C:/msys64/home/askon/ja2-stracciatella/src/sgp/SoundMan.cc:542:25: error: reference to 'mutex' is ambiguous
                std::unique_lock<std::mutex> lk(mutexBuffersNeedService);
                                      ^
C:/msys64/clang64/include/c++/v1/__mutex_base:35:78: note: candidate found by name lookup is 'std::__1::mutex'
class _LIBCPP_TYPE_VIS _LIBCPP_THREAD_SAFETY_ANNOTATION(capability("mutex")) mutex
                                                                             ^
C:/msys64/home/askon/ja2-stracciatella-buid/lib-mingw-std-threads/src/mingw.mutex.h:476:24: note: candidate found by name lookup is 'std::mutex'
using mingw_stdthread::mutex;
                       ^
C:/msys64/home/askon/ja2-stracciatella/src/sgp/SoundMan.cc:1049:25: error: reference to 'mutex' is ambiguous
                        std::lock_guard<std::mutex> lk(mutexBuffersNeedService);
                                             ^
C:/msys64/clang64/include/c++/v1/__mutex_base:35:78: note: candidate found by name lookup is 'std::__1::mutex'
class _LIBCPP_TYPE_VIS _LIBCPP_THREAD_SAFETY_ANNOTATION(capability("mutex")) mutex
                                                                             ^
C:/msys64/home/askon/ja2-stracciatella-buid/lib-mingw-std-threads/src/mingw.mutex.h:476:24: note: candidate found by name lookup is 'std::mutex'
using mingw_stdthread::mutex;
                       ^
2 warnings and 4 errors generated.
[437/443] Building CXX object CMakeFiles/ja2.dir/src/sgp/Video.cc.obj
ninja: build stopped: subcommand failed.
```

Why not get rid of the mingw thread specific library.
I there any reason that this library is needed?

**Comment by momoko-h** [comment]
Does it build and run correctly (without any sound related problems) if you switch the option `MINGW_STDTHREADS_GENERATE_STDHEADERS` to off  in `dependencies/lib-mingw-std-threads/CMakeLists.txt? ` According to the library's github page C+11 threading support is still a bit problematic with mingw-GCC.

**Comment by askondro** [comment]
Unfortunately not.

3 warnings generated.
[442/443] Building CXX object CMakeFiles/ja2.dir/src/sgp/SoundMan.cc.obj
In file included from C:/msys64/home/askon/ja2-stracciatella/src/sgp/SoundMan.cc:44:
C:/msys64/home/askon/ja2-stracciatella-buid/lib-miniaudio/src/miniaudio.h:90256:37: warning: result of comparison 'drmp3_uint64' (aka 'unsigned long long') > 18446744073709551615 is always false [-Wtautological-type-limit-compare]
            if (newFramesBufferSize > (drmp3_uint64)DRMP3_SIZE_MAX) {
                ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/home/askon/ja2-stracciatella-buid/lib-miniaudio/src/miniaudio.h:90307:37: warning: result of comparison 'drmp3_uint64' (aka 'unsigned long long') > 18446744073709551615 is always false [-Wtautological-type-limit-compare]
            if (newFramesBufferSize > (drmp3_uint64)DRMP3_SIZE_MAX) {
                ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
[443/443] Linking CXX executable ja2.exe
FAILED: ja2.exe
cmd.exe /C "cd . && C:\msys64\clang64\bin\c++.exe -Wall -Wtype-limits -Wignored-qualifiers -O2 -g -DNDEBUG  @CMakeFiles\ja2.rsp -o ja2.exe -Wl,--out-implib,libja2.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && cmd.exe /C "cd /D C:\msys64\home\askon\ja2-stracciatella-buid && C:\msys64\clang64\bin\cmake.exe -E copy_directory C:/msys64/home/askon/ja2-stracciatella/assets/externalized C:/msys64/home/askon/ja2-stracciatella-buid/externalized && cd /D C:\msys64\home\askon\ja2-stracciatella-buid && C:\msys64\clang64\bin\cmake.exe -E copy_directory C:/msys64/home/askon/ja2-stracciatella/assets/unittests C:/msys64/home/askon/ja2-stracciatella-buid/unittests && cd /D C:\msys64\home\askon\ja2-stracciatella-buid && C:\msys64\clang64\bin\cmake.exe -E copy_directory C:/msys64/home/askon/ja2-stracciatella/assets/mods C:/msys64/home/askon/ja2-stracciatella-buid/mods""
lld: error: unable to find library -lgcc_eh
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by momoko-h** [comment]
Well, at least it compiles now...  gcc_eh is added in https://github.com/ja2-stracciatella/ja2-stracciatella/blob/0fa963e2d3e78a351d8b362c791f51ee23b0e2f3/dependencies/lib-stracciatella/CMakeLists.txt#L111

Does it link successfully if you remove gcc_eh from that line?

**Comment by askondro** [comment]
I have disabled the MINGW_STDTHREADS_GENERATE_STDHEADERS and removed the gcc_eh library in the MSYS2 Clang64 environment.
And it is working normally and without any sound issues.

**Comment by lynxlynxlynx** [comment]
Ok, closing  then.
