### ISSUE TITLE
Should we bump the cmake_minimum_required value?

### ISSUE THREAD

**Issue by momoko-h** [ja2-stracciatella/ja2-stracciatella#1828]
So [it looks like](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8274) CMake 3.27, which is due out in two weeks will deprecate versions < 3.5. Our main CMakeLists.txt currently uses 3.4, so we either have to increase that or live with the new warning.

I'd suggest we bump this to 3.20. That version was released two years ago and I don't think it's too much too ask that anyone who'd like to build the game themselves uses tools that are not completely outdated.

The github runners and AppVeyor are all at 3.26, but I'm not sure what the Android build uses.

**Comment by lynxlynxlynx** [comment]
Sure, let's do it.

**Comment by ja2-derek** [comment]
Debian stable (bullseye at the moment) has cmake [3.18](https://packages.debian.org/bullseye/cmake), but backport is available at [3.25](https://packages.debian.org/bullseye-backports/cmake). So I think it's good.
