### ISSUE TITLE
Nordic keyboard layout. equal key to select all mercs does not work

### ISSUE THREAD

**Issue by mrbentarikau** [ja2-stracciatella/ja2-stracciatella#1844]
<html>
<body>

JA2S version | Game version | Vanilla bug? | Used to work?
-- | -- | -- | --
ja2-stracciatella_0.20.0-git+439a6d3 | JA2 Gold 1.12 Steam | no | no
Win 10 x64

</body>
</html>

On tactical map, if my keyboard layout is Nordic then pressing the key where in English layout the equal sign = is supposed to be does not select all the mercs - I have to change keyboard layout to English for it to work. In JA2 vanilla, 1.12 edition the same key does select all mercs. 

With Nordic layout this key produces a backtick ` on pressing twice the key. Also hitting equal as on Nordic layout does nothing.

**Comment by lynxlynxlynx** [comment]
What does the key produce on a single keypress?

**Comment by mrbentarikau** [comment]
> What does the key produce on a single keypress?

first keypress is a dead key, nothing is produced... 
key code is 192... on my layout I have to press twice to get backtick `

agree with the tag minor, and thanks for seeing this : )

**Comment by lynxlynxlynx** [comment]
That is perhaps SDLK_KP_E then.

**Comment by opleks** [comment]
same issue with swiss-german keyboard layout:
unshifted key function for equal is "0" as in zero.
shifted key of upper row 0 digit is "equal" sign.

**Comment by momoko-h** [comment]
This key has the scancode SDL_SCANCODE_EQUALS and what keycode that translates to is pretty much unpredictable because it's used for many different purposes with different keyboard layouts. I believe we need to give this key special treatment and use its scancode (normally we're using keycodes).

**Comment by momoko-h** [comment]
So I had another look at https://github.com/ja2-stracciatella/ja2-stracciatella/blob/641b6559f554cfab93f589ce7c3cd3ccb4af513c/src/game/Tactical/Turn_Based_Input.cc#L1330

and I guess this isn't the only problematic key if one doesn't use the US keyboard layout. @mrbentarikau , do the '`' key to toggle the panels or the '/' key to center the selected merc work for you or do you have any other key to trigger these?

Another bug: we're checking for '*' to toggle the red item glow in this function, but * is Shift-8 on US keyboards, so we never reach this function.

**Comment by mrbentarikau** [comment]
forward slash "/" key works from Keypad, but not from "standard" keyboard and the other one ("backtick?") to switch between inventory, merc selection panels does not work
