### ISSUE TITLE
is there a combat/event log or way to view history.dat log file?

### ISSUE THREAD

**Issue by opleks** [ja2-stracciatella/ja2-stracciatella#1847]
This is not explicitly an issue but generic question:

is there a combat/event log or way to view history.dat log file in files generated by Straciatella?
► C:\Users\User\AppData\Local\Temp\ja2-stracciatella-UzFUpKZF

![image](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/12021793/975faf25-503b-48da-9641-52652496f64a)

**Comment by lynxlynxlynx** [comment]
If there are no readers for ja2 in general, then no. JA2S doesn't provide anything extra for this.

You can look at src/game/Laptop/History.cc around line 340 to see the format. It's just the quest log, the combat log doesn't get saved.
