### ISSUE TITLE
Performance issues on top 1% AMD CPU/GPU system

### ISSUE THREAD

**Issue by opleks** [ja2-stracciatella/ja2-stracciatella#1849]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### 

**Performance issues on top 1% AMD CPU/GPU system:**
- Tactical and especially realtime mode shows extreme stuttering/skipping to the point where mouse-clicks are missed and gameplay experience is at least strongly annoying, but basically unplayable.
- Game seemed to run much better at the very beginning; But already deteriorated when reaching farm NW of Drassen sectors or during first combat freeing Drassen mine sector.

- Debug with FPS enabled shows around 40FPS and looptimes of 20-30
- However gameplay and problem is present without debugging mode enabled

These yellow marked game settings have been tested, enabled/disabled to no avail:
(except for glowing items, 4th from bottom right and probably also treecrowns)
![image](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/12021793/c8d6c842-879a-466a-a4e6-50ca9b751296)

- Both JA2.exe and JA2-Launcher display at 0% CPU use in detailed Task Manager view.
- Their RAM use ranges from 100-112'000K (JA2) and 20'000-60'000K (JA2-Launcher)

- IIRC all 3 interpolation methods have been tested with/without fullscreen setting and by manually increasing windowed size to "fullscreen" to no avail in 640x480 and 1920x1080:
Linear interpolation, Near perfect with oversampling, Pixel Perfect centered
- Different Win/Display-Projection modes have been tested/excluded: Primary vs. Duplicate Display as well

- JA2 Game version is from GOG:
setup_jagged_alliance_2_1.12_(17794).exe
- German Language Pack used is:
https://www.compiware-forum.de/downloads/file/461-jagged-alliance-2-german-patch/
- Straciatella installer and version is from 1-2 days ago from the website:
ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64-142.exe
- Vanilla game files were not installed in a system/programfiles folder but straight to C:\GOG-Games
- No 1.13 or Straciatella default mods have been previously or are enabled, or mingled/installed. This is the first installation.  

System:
![image](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/12021793/5d03b17c-6d2f-4a0f-bc0f-ed856cae579e)
![image](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/12021793/42cf8686-6443-47fa-adf8-4adb823f01ce)

It's a an overclocked, watercooled Sapphire Toxic 6900XT that runs in a system with idle GPU tmp of 35 degrees and CPU of 58 degrees celcius. But obviously not running the CPU or GPU overclocked anyways. Not that it matters for JA2 anyways. No virtualization for this application, all baremetal.

The only user-behaviour potentially worth mentioning is that I'm an extreme, almost neurotic "save-scummer". So I already have high number of saves. currently total of 58 savefiles, to be precise. Any other AMD-GPU users experiencing similar issues?

**Comment by momoko-h** [comment]
If the debug FPS display shows 40 FPS this means you still have the default value of 25 for ms_per_game_cycle in your game.json settings file. 20-30 for the game loop however is very strange, that should really be the value of ms_per_time_slice, which defaults to 10. If this value is in the 20-30 range, then yes, the game is essentially running at between ½ and ⅓ its intended speed. It's unlikely your GPU has anything to do with that.

For a start, try lowering the value of ms_per_game_cycle, something in the range 10-16, and see if that helps. 

As an alternative you could also try the nightly build which has some significant changes to the timings-related code. You also don't need to enable debug mode to see your FPS with this build; just Control-F is enough.

**Comment by opleks** [comment]
thank you for your swift reply:

I have tested your suggested values, which did not seem to change much. Also noticed that I potentially still had debugmode running due to editing back on a copy.

However after changing both of your suggested values in game.json to 5ms gameplay visuals seem way better and more fluid/playable. Hard to compare without much comparison to what "optimal/max performance" should look and feel like.
While still on stable, non-nightly this seems to be way closer to what one would consider, if not being dead on optimal/expected performance and visual feedback.

Therefore if things stay this way the issue can be considered resolved.

Thank you for this swift resolution. Perfect. :)
