### ISSUE TITLE
AI: 2 break lights thrown in the same place

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#185]
Originally reported by: **Agatae Tsag (Bitbucket: [Agatae](http://bitbucket.org/Agatae), GitHub: Unknown)**

---

I just got an enemy throwing a light in an already lightened place. Looks like a bad move. However, I'm not certain that the merc that was hit was the target. The enemy might have thrown it at another one, inaccurately. Still, it's suspicious and may deserve investigation.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/185

**Comment by JAsmine-ja2** [comment]
At least in JA2 v1.12 (with or w/o Stracciatella), enemies throw break lights rather often. I've not seen them throw a break light twice at the same tile, however.

**Comment by JAsmine-ja2** [comment]
In my recent campaign, I've had another battle where the enemy soldiers spammed breaklights at me. The behavior didn't appear broken to me. I think we can close this issue.

**Comment by lynxlynxlynx** [comment]
Thanks Jasmine!
