### ISSUE TITLE
Error: No burst sound firing RPK-74

### ISSUE THREAD

**Issue by JSh-git** [ja2-stracciatella/ja2-stracciatella#1859]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Firing the RPK-74 in burst mode doesn't produce a sound and console outputs:

> 2023-07-29T12:56:39 [ERROR] sgp\SoundMan.cc: SoundLoadDisk Error for "sounds/weapons/5,45 burst 5.wav": openGameResForReading: VfsFile_open "sounds/weapons/5,45 burst 5.wav": entity not found

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  Stracciatella v0.20.0-git+439a6d3 Build 04.12.02 | JA2 Gold engl/steam |    no    |    not sure     |

Windows 10

**Comment by ja2-derek** [comment]
Probably same as #1714.

**Comment by JSh-git** [comment]
Yep, looks like its been fixed back in december
