### ISSUE TITLE
[Windows] Change Stracciatella config dir location to AppData

### ISSUE THREAD

**Issue by ChristianKaeser** [ja2-stracciatella/ja2-stracciatella#1864]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### Proposal for a better Stracciatella configuration directory location on Windows

On Windows, Stracciatella's configuration directory defaults to `dirs::document_dir()` (via `find_stracciatella_home()`).
This seems suboptimal to me.

For one, most users probably never/super rarely need to interact with this directory. Stracciatella's launcher application can be used to modify the settings which are stored there.
Furthermore, the save game directory can be customized anyway, and then the "SavedGames" subdirectory there seems to be unused (any potentially confusing).
So the folder is simply cluttering the all-important Documents location, without an option to avoid this while using Stracciatella.

While many games traditionally seem to have selected the user's Documents directory for their save and configuration data, Windows plattform recommendations rather seem to prefer %APPDATA% as the place for application configuration data.
This is also reflected in the utilized Rust "dirs" crate, which provides `config_dir()`, which points to just that.

But the most important reason for me are Windows' security defaults, which nowadays give special protection to the user's Documents and similar directories - but not to %APPDATA%: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders

This means for me there is a security notification popup the first time JA2 Stracciatella is used, and the Launcher/Game simply exits/is not working without any indication as to what happened. This seems to be due to the processes trying to write in the config location, which Windows does not allow without the user having to give an admin-rights-protected exception with multiple clicks: https://support.microsoft.com/en-us/windows/allow-an-app-to-access-controlled-folders-b5b6627a-b008-2ca2-7931-7e51e912b034

I see this as a big hurdle for many casual users, which probably will simply give up on Stracciatella right there and then.

Of course a change would mean that a migration fallback code path would have to be introduced, so existing installations continue to work.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.20.0-git+439a6d3_win-msvc64-142 | all  |    -    |    -     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
[Saved Games](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid#FOLDERID_SavedGames ) is not on this list of protected directories either. Do you know if it's used by other games? Where do modern games usually store their saves?

Known Folders were only introduced with Vista, but that is probably not much of a problem these days. Does the Windows 32-bit .exe even still run on Windows XP?

**Comment by selaux** [comment]
I dont think anything runs on Windows XP right now. I would be fine with changing the config dir. We just have to find a good process, so it also works for users that already have the data in their documents folder.

**Comment by lynxlynxlynx** [comment]
Some games do use the global save dir. As for the migration, the easiest approach is just to look into both paths (new dir first) for a few releases, with a warning if we had to resort to the old one. After some time, we can make it fatal and remove the fallback.

**Comment by ChristianKaeser** [comment]
@momoko-h: "Saved Games" could be used, that seems sensible, yes. Although it would probably be more work compared to %APPDATA%, as it seems the "dirs" crate does not support it out-of-the-box, and therefore the WinAPI call has to be done some other way?
So not sure if it is worth the extra effort (especially as the SaveGames location can be customized anyway, and users that are interested could set that manually).

**Comment by ChristianKaeser** [comment]
@lynxlynxlynx: I agree with your proposal, that does sound like a good solution.
I am not all that familiar with the architecture (plans) of this project. I assume the Rust-for-configuration and C++-for-the-rest split should be kept? If so, it probably would be best to add something like a `EngineOptions_getStracciatellaLegacyHomeDir[s]()`?

**Comment by selaux** [comment]
I dont think a new interface would be necessary. There is a rust function that sets up the stracciatella_home variable [here](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/stracciatella/src/config/stracciatella_home.rs). So proabably the logic should be in there and could do the two checks and return the new one if the old one does not exist, otherwise return the old one.

**Comment by selaux** [comment]
@ChristianKaeser Could you check whether the build from here helps with anything: https://storage.googleapis.com/ja2-builds/index.html#pull-requests/1903/.

https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1903 changes the logic so the game prefers the `%APPDATA%` directory if nothing exists or is readable in `Documents`.

**Comment by ChristianKaeser** [comment]
I started up the Win64 build from that pull request, and everything looked good. In the console log it mentioned the new location in APPDATA, and no warning from Windows Defender appeared.

**Comment by lynxlynxlynx** [comment]
Thanks for checking, this will be the new default from now on.
