### ISSUE TITLE
You can't speak to a character between index 164 and 169.

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1887]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

In Prof.dat index, there are several free places for new characters between 164 and 169. I made some new persons and in vanilla JA2 everything works fine, but when I want to do this in Stracciatella, then you just can't speak to these persons in game, because mouth is not working. In mercs-profile-info.json, I change the number of 168 to a proper value. Could you verify this situation. Thanks.

Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  stable 0.20.0 | JA2 Gold 1.12 ENG  |    no    |    In vanilla yes     |

[//]: # I made an example. I copied the Father Walker data to an index number of 168 and put him next to a Fatima in A9. In vanilla JA2  you can speak with him, but in stracciatella you just can't. https://www.mediafire.com/file/uwd3bj85dljwn7s/Father_Walker_example.7z/file
[//]: # Windows 10

**Comment by momoko-h** [comment]
Your guys can only talk to NPCs; to use profile IDs that weren't used in vanilla, you also must set their type to NPC in mercs-profile-info.json.

**Comment by Inveriss** [comment]
It seems that it works. Mouth has appeared and characters are responding to my talking in every variant. Thank you very much. Regards.
