### ISSUE TITLE
Think about implementing the launcher

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#19]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

Which is a GUI program that will allow the user to select necessary settings easily, without using command line or shell scripts, and start the game.  It can also do some basic validation, for example check that the game resources are really present.

See [Drawing Board, Launcher](https://bitbucket.org/gennady/ja2-stracciatella/wiki/Drawing%20Board)

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/19

**Comment by selaux** [comment]
Here is a proposal for a launcher built in fltk: https://github.com/ja2-stracciatella/ja2-stracciatella/tree/stracciatella-launcher. Currently it requires libfltk to be installed on the system. Doesnt look too fancy but also has minimal dependencies. Could be a goal for `0.16.0/1.0.0`.

**Comment by derSteFfi** [comment]
nice work until here. Minimalistic but portable is generally a good idea for us, i guess. And the look isn't too bad (if you're used to consoles... :) )

**Comment by JAsmine-ja2** [comment]
Since there is another issue about the launcher #270 ,
maybe we can close this one and do the discussion there?

**Comment by lynxlynxlynx** [comment]
This one is more general, so I'd leave it open until #270 (pure implementation) is resolved.

**Comment by selaux** [comment]
So this is solved, we could use the mockups for #607

**Comment by lynxlynxlynx** [comment]
Jasmine's list is still relevant, so no need to close yet.

**Comment by Manuel-K** [comment]
I've added the list to the other issue.
