### ISSUE TITLE
Android build failing to find libSDL2.so

### ISSUE THREAD

**Issue by jsyang** [ja2-stracciatella/ja2-stracciatella#1910]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hi, I'm trying to create an Android build for arm64 and have been able to get the compilation to produce an APK which does install and run. However when I start a game, I get a "dlopen failed" error that mentions `libSDL2.so` wasn't found. I looked inside the built APK under `lib/arm64-v8a` and there only seems to be the `libja2.so` library that was put into my build artifact.

I've tried running the debug CI build process, the SDL2 library isn't being included. Am I doing something obviously boneheaded? I've changed `stracciatella_home` to be  `PathBuf::new("/storage/emulated/0")`. I wouldn't have thought that the SDL2 lib would be placed there... 

That's probably my issue right?

**OS**: MacOS
Not using Android Studio just running `.ci/ci-build.sh` from current `master` branch (commit `6882b174`).

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | JA2 English  |    yes    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
The location the `libSDL2.so` should end up in is the same as `libja2.so`, so `lib/arm64-v8a/libSDL2.so`. Why it does not end up there, I can only guess. Are you using the cmake version shipped with the Android SDK?

**Comment by jsyang** [comment]
I'm running 3.27.7:

```
$ cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Can only see that there's a cmake min version of 3.18.1 in the `CMakeLists.txt`. I cleared the `ci-build` directory and then ran another build with `CI_TARGET=android .ci/ci-build.sh`, after it finished I wasn't able to find that missing `.so` file in there.

```
$ find ci-build/ -type f -name "libSDL2.so"
$
```

but I did find it in the `.cxx` directory:

```
$ find android/ -type f -name "libSDL2.so"
android//app/.cxx/Debug/5d1b641p/arm64-v8a/dependencies/lib-sdl2/builder/sdl2-prefix/src/sdl2-build/libSDL2.so
android//app/.cxx/Debug/5d1b641p/arm64-v8a/lib-sdl2/lib/libSDL2.so
android//app/.cxx/Debug/4il3ln3v/armeabi-v7a/dependencies/lib-sdl2/builder/sdl2-prefix/src/sdl2-build/libSDL2.so
android//app/.cxx/Debug/4il3ln3v/armeabi-v7a/lib-sdl2/lib/libSDL2.so
android//app/.cxx/Debug/4il3ln3v/arm64-v8a/dependencies/lib-sdl2/builder/sdl2-prefix/src/sdl2-build/libSDL2.so
android//app/.cxx/Debug/4il3ln3v/arm64-v8a/lib-sdl2/lib/libSDL2.so
```

**Comment by jsyang** [comment]
Seems like the master and nightly build has been failing since GitHub CI #2611. So I'm gonna at least try rolling back to the commit before that one. I'm going to check my local parity with what the GitHub Actions CI build steps as well.

**Comment by lynxlynxlynx** [comment]
I triggered another run; let's see if it was a temporary hick-up, but I doubt it. Still, eating up 14G is no small feat. In the worst case we could use something like this: https://github.com/marketplace/actions/maximize-build-disk-space

Also warned CMake 3.19 might be slightly better, which is another signal to bump our minimum if it is available in the image.

**Comment by jsyang** [comment]
Just tried compilation on my Ubuntu machine and it works fine, even with my simple modifications to `stracciatella_home`. Not sure where I'm going wrong on MacOS but it's likely more trouble than it's worth to figure that out considering nobody else seems to have run into this weird issue other. 

No matter! I'm very grateful for this project, thanks to your continual dev support I'm currently playing through the Drassen crepitus parts on Desktop atm and am able to keep moving on mobile. Closing issue
