### ISSUE TITLE
MinGW unit test errors with __FILENAME__ in Logger_unittest.cc

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#1916]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

`__FILENAME__` preprocessor def returns the absolute path name, as I would expect.

Error while building with MSYS2 mingw64:

It does not matter if used with gcc or clang.

$ cmake -G "MinGW Makefiles" ../ja2-stracciatella

$ ming32-make

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold English  |    no    |    yes     |

```
[ 10%] Building CXX object CMakeFiles/ja2.dir/src/sgp/Logger_unittest.cc.obj
C:\msys64\home\askon\ja2-stracciatella\src\sgp\Logger_unittest.cc:17:16: error: static assertion failed due to requirement 'std::basic_string_view<char,
      std::char_traits<char>>((ToRelativePath<(GetSourcePathSize("C:\\msys64\\home\\askon\\ja2-stracciatella\\src\\sgp\\Logger_unittest.cc"))>("C:\\msys64\\home\\askon\\ja2-stracciatella\\src\\sgp\\Logger_unittest.cc")))
      == "sgp/Logger_unittest.cc"'
   17 |         static_assert(std::string_view(__FILENAME__) == "sgp/Logger_unittest.cc");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
mingw32-make[2]: *** [CMakeFiles\ja2.dir\build.make:5941: CMakeFiles/ja2.dir/src/sgp/Logger_unittest.cc.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:715: CMakeFiles/ja2.dir/all] Error 2
mingw32-make: *** [Makefile:155: all] Error 2

```

**Comment by lynxlynxlynx** [comment]
`__FILENAME__` contents depend on how the preprocessor was invoked. In your case apparently with absolute paths, unlike on our build bots. It's a problem in that particular test — you can see we explicitly ifdef MINGW out to the unix path.

**Comment by momoko-h** [comment]
Does removing `&& !defined(__MINGW32__)` in line 20 in Platform.h help?

**Comment by askondro** [comment]
I have just committed the changes you suggested (Cmakes).

And the CI system is trying to build all systems, which is nice.

I will inform you of the other suggestions proposed.
