### ISSUE TITLE
Enemy items status bugged

### ISSUE THREAD

**Issue by ja2forever** [ja2-stracciatella/ja2-stracciatella#1924]
| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.21.0-20231019+a1fb0d8_win-msvc32-142 (WIP-dev version) | JA2 Gold 1.12 ENG CD  |    no    |    rather new bug?     |

Enemy dropped items status behaves strange - very often it can become over 100% or just 1%
I noticed that it is the most common behavior on items which status can be changed by damaging so magazines for weapons usually are unaffected  but sometimes during testing mags had 1/max ammo in them.
"Items in items" are freaking too so if enemy dropped armor with plates then armor can have 1% and plates have 125% condition. 

How to reproduce? 
- just spawn some enemies and kill em then look for their items and either pick them up or check on global map view.
- or teleport to sector with enemies and repeat above

Seems like this can happen during using cheats. Played through couple of sectors "legally" and it seems like during normal gameplay this is not happening (will try to track this bug through longer gameplay later)

Some screens:

Sector where most enemy equipment have 1% condition
![3](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/122088263/b832cad6-5c57-4c0c-8f69-bfd51d1d8d95)
Picked up item over 100% condition
![4](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/122088263/f94988fc-0d84-4729-be43-c2d97628d9f0)
Mix of item with 1% condition and 125% plates
![5](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/122088263/d72e934c-ee7e-478f-8c45-cbc1162e4dd9)
![6](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/122088263/63acc24b-2fc4-4116-9630-c57963d47c5b)
Vanilla 1.12 without issue using cheats
![vanilla same sector](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/122088263/37895442-18d3-4478-a223-ac36d77463fd)

**Comment by momoko-h** [comment]
Since you mentioned cheats: you can see the status of the enemy's items on the soldier debug page 4 while they're still alive. Is the status already bugged then or just when they drop their stuff?

**Comment by ja2forever** [comment]
Sry for that but is there full list of key combinations using cheats? I had it somewhere but lost and cant remember every combination. Or maybe straciatella have them changed from vanilla since ALT+ENTER wont work well during testing?
Would be hellpful :)

**Comment by momoko-h** [comment]
With cheats enabled, mouse over an enemy and press Q, then page up/page down to switch between pages.

**Comment by ja2forever** [comment]
Just checked and it bugs in real time?
While hovering on enemy his items status looks ok like 80% 90% etc
but while information is displayed and you kill alt+o enemy then these values drops to 1%

**Comment by momoko-h** [comment]
That's because alt+o does 10,000 damage to an enemy, which means plenty of it spills over to his inventory. ctrl+h only does 20 or 25 damage, so item degradation is far less likely. This is something that was changed from vanilla, where alt+o didn't always do enough damage to kill everything.

**Comment by ja2forever** [comment]
Well if that is the case then ok. Didnt know that. Just my side note that IMO even while using cheats this should work just like in vanilla since using cheats to play is still a way to play. I understand this change you described was necessary but one flaw with that change is side effect with that dmg spill for testing purposes it makes use cases slightly more difficult to reproduce.

So my example is that:
-i am testing behavior of enemy for mod that takes into account which items on ground enemy will pick up when for example runs out of ammo or loses weapon or have jammed etc.

-when i will spawn some enemies and kill them with alt+o then of course this bug occurs (and manual dmg is kinda lenghty process)

-then i am spawning other group of enemies and make them to pick up these items whatever is best based on factors like condition/ammo

-and now "my mod" have difficulties to work properly since almost all items of previous enemies group on ground are in odd 1% or 157% condition and for example "my mod" takes into account condition values from eg: 20-100% then 157% wont work and mod could freeze or something

-so now i would have to dig into straciatella itself instead of "my mod" which is not convenient.

*Im not making any mod - it was just an example

Anyway sry for bringing up unnecessary issue.

**Comment by momoko-h** [comment]
The problem that status could exceed 100% should get fixed by the second commit in #1926. Those items will all be at 1% (or destroyed in the case of magazines). I'll let other team members weigh in with their opinions whether alt+o should leave items alone.

**Comment by lynxlynxlynx** [comment]
Since it's impeding content creation, I'm for disabling damage to equipment on alt+o.

**Comment by momoko-h** [comment]
Ok, should be easy enough to implement.
