### ISSUE TITLE
The game crashes when a merc is fired

### ISSUE THREAD

**Issue by Thedkm86** [ja2-stracciatella/ja2-stracciatella#1928]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

After the death of a mercenary, (regardless of the mercenary or the sector in question) as soon as I click on "Remove Body" in the menu with the general map of the country, the game crashes.

Error 
JA2 stracciatella crashed wiht exit code: 1073741819
You will be taken to the logs tab, where you can investigate the error.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.20.0-git+439a6d3                    NO               Yes
Build 01.12.02  | 1.12

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system) Windows 10 Pro 64 bits
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
Sounds like issue #1788, could you please try the 0.21 release candidate? You can find it here: https://storage.googleapis.com/ja2-builds/index.html#releases/v0.21.0-rc1/

**Comment by Thedkm86** [comment]
After testing your version, I no longer have the bug, it's gone, thank you very much for your help. :)
