### ISSUE TITLE
[Feature Request] Multiple I.M.P Character + Face Replacement of Ira for Android Version

### ISSUE THREAD

**Issue by Stogie87** [ja2-stracciatella/ja2-stracciatella#1934]
Hi there.
I really appreciate your Android Version of JA2 and i like to play the game on my Tab S8.
The only thing i miss is the possibility to activate mods on Android.
Currently i just replace the JA2 files with the Mini-Mod files and it actually works, but i loose the possibility to remove them easily.

But what i specifically miss is the possibility to create multiple I.M.P. characters and the possibility to replace the ugly Ira face with the wildfire version (or something else). Is there any chance, that these features will be implementet permanantly in the straciatella version or through a kind of mod-selector on android?
Thanks in advance and kind regards.

**Comment by lynxlynxlynx** [comment]
Closing, since this is covered by existing reports: #1341 and #1516 (and the ones for WF support)
Please search first next time.
