### ISSUE TITLE
Question: Save game compatibility with vanilla UB

### ISSUE THREAD

**Issue by mschuessler** [ja2-stracciatella/ja2-stracciatella#1945]
I know this might be the wrong place but I don't know were else to ask, since I tried searching on google already. First let me say that I really appreciate this work. JA2 is my all time favourite game and now I am able to play it for hours on my M1 Mac Book while on the train (its just so much more battery efficient then emulating it). Absolutely love it! 

Since I had this situation with 1.13 before: Will I be able to import my merch via the save games created by Stracciatella to Vanilla unfinished business, or is there any other way I can play unfinished business with my Mercs after I completed the campaign in Stracciatella?

From the issues I see that Stracciatella does not support UB yet (but some progress is made every now and then). I tend to play the JA2 campaign for a year or so. So this time I want to make sure I can use my Mercs in UB which I never finished.

**Comment by lynxlynxlynx** [comment]
I doubt that's possible without hexediting the saves; we changed the format slightly and more data is appended at the end. But why ask, when you can quickly test it yourself?

**Comment by Danf96** [comment]
Yes, UB's save converter will work on Stracciatella saves. I've done it on a previous playthrough years ago and just tested it again and it still works.

**Comment by lynxlynxlynx** [comment]
Cool, thanks, we can close this then.
