### ISSUE TITLE
In map editor, in character inventory, the bottom boxes are almost inactive.

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1946]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

Hello

In map editor in character inventory, we can change items in hands, armors and four big slots. Boxes for legs armor and last bottom big slot are almost inactive.

If you want to change them, you have to click directly only at left upper corner of these boxes. Remaining space won't work.

Regards

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
| 0.21.0 | JA2 Gold 1.12 ENG  |    NO    |    YES     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
The problem seems to be that the mouse region for this panel does not extend far down enough. It ends at the same line as the items panel, but that panel has an extra row of buttons above the main tabs.

And it's indeed a stracciatella specifc bug (looks like a copy & paste issue), in vanilla that region extends 20 lines further down.

**Comment by Inveriss** [comment]
Whole space is now full active. It's so easy to change them now. Thank you very much.
