### ISSUE TITLE
JA2S 0.21 doesn't work in headless configuration (over VNC)

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#1949]
### What is wrong

I'm using my RPi 3B+ in headless configuration, so it's not connected to the monitor. Previously (in Raspberry Pi OS based on Debian 11 Bullseye), I was able to test and play JA2S with this setup. Unfortunately now, with latest Raspberry Pi OS based on Debian 12 Bookworm, this is no longer possible, the game won't start and I get following error message:

"[ERROR] sgp/Video.cc: SDL_CreateTexture for ScreenTexture failed: Parameter 'renderer' is invalid"

I did testing with clean installation of both Debian Bullseye and Buster, and I can confirm, that I can reproduce it in Bookworm right after clean installation, while on Bullseye it works as expected.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.21 aarch64 | JA2 Gold English  |    no    |    yes     |

I'm attaching the screenshots from Bullseye and Bookworm, as well as the log from Bookworm. Also, I can confirm, that on both operating systems, I'm using X11, and not the Wayland (even in Bookworm, because Wayland is not being used on RPi 3 and older).

One last thing. When I'm connected to monitor (in this case via HDMI), the game will start even is the monitor is showing different input (like DisplayPort from my main PC) and I'm connected to RPi via VNC. Once I disconnect HDMI cable from RPi, the issue is back.

![JA2S_021_Bullseye](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/5399824/8ac20b9d-bafa-4983-9a89-83170c11aadf)
![JA2S_021_Bookworm](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/5399824/65e69bf1-e47a-4a4c-a9e6-096dcc8c302b)
[JA2.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/13823692/JA2.log)

**Comment by momoko-h** [comment]
For this to happen, either SDL dislikes the renderer it just created or GameRenderer must be null. The second option seems far more likely, given the lack of proper error checking in `InitializeVideoManager()`. That would mean SDL cannot create the window or a renderer with the default options for the window it just created.

Do you have any other program that uses SDL and that works in this configuration?

**Comment by Srandista** [comment]
Alright, I've done some more testing, because I'm aware, that testing on just RPi is really limited.

I tried to run JA2S over VNC on Windows and I found it also doesn't work (although the presentation of an issue is a bit different).

On PC with fully updated Windows 10, I installed TigerVNC server, and then connected from the laptop in same network. JA2S can be run, and if the monitor on PC is on, the game starts without issues and can be seen on laptop, controlled and also played. If however the monitor on PC is off, game seems to start (there is no error message in status window like on RPi), but you can see only white filled window (see attached screenshot). If I turn on monitor then, window start to showing actual game content, and it can be played on laptop without an issue. If I again turn off monitor then, window stop refreshing and it only show last image before the monitor was turned off.

Hopefully this make testing and troubleshooting a bit easier (since RPi might not be required).

![TigerVNC_JA2S](https://github.com/ja2-stracciatella/ja2-stracciatella/assets/5399824/d2cec984-0b66-4072-ae09-d49cc7ef8353)

**Comment by momoko-h** [comment]
Does VNC support OpenGL? What happens if you try to start the game with the environment variable SDL_RENDER_DRIVER set to software, `env SDL_RENDER_DRIVER=software ./ja2` ? (Performance will be terrible if that works, but that's expected).

**Comment by Srandista** [comment]
@momoko-h thanks for a reply. I tried other games on my RPi (with Debian 12 Bookworm), that previously worked (on Debian 11 Bullseye) I'm getting errors in them as well. 

Vanilla-Conquer (source port of C&C1) have similar status window like Stracciatella, and it it shows following error:

ERROR: SDL_CreateWindow failed: No available displays
DEBUG: C&C95 - Failed to set video mode.

DevilutionX (source port of Diablo 1) shows error windows with following content:

ERROR: SDL Error
No available displays
The error occurred at: Source/utils/display.cpp line 311

**Comment by Srandista** [comment]
> Does VNC support OpenGL? What happens if you try to start the game with the environment variable SDL_RENDER_DRIVER set to software, `env SDL_RENDER_DRIVER=software ./ja2` ? (Performance will be terrible if that works, but that's expected).

Tried that environment variable on RPi, and it won't run with the same error message like before.

**Comment by momoko-h** [comment]
Thought so. So looks like SDL doesn't play nicely with VNC, which means there's nothing we can do, unless there is a workaround somehow.

(We should definitely improve our error handling, though).

**Comment by Srandista** [comment]
I looked a bit more over internet and I found this bug report:

https://github.com/libsdl-org/SDL/issues/8054

With "env SDL_VIDEO_X11_XRANDR=0 ./ja" the error in status window is bypassed, game tries to start, but I'm stuck on blinking SirTech logo.

**Comment by lynxlynxlynx** [comment]
Ok, closing then.
