### ISSUE TITLE
Enemy in the northmost sector on the map can't be shot in the head

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#195]
Originally reported by: **Agatae Tsag (Bitbucket: [Agatae](http://bitbucket.org/Agatae), GitHub: Unknown)**

---

Depending on his direction, enemy may or may not be headshottable because the head may be out of screen.
In the attached save, Johny sees an enemy who can't be shot in the head. If he shots elsewhere, the enemy turns and his head can be targeted.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/195

**Comment by lynxlynxlynx** [comment]
Just a small update — haven't digged in much yet. From testing it seems these problems were there from svn times.

For the top, 61 is exactly enough of an offset there, while for the bottom, 20 is enough (not exact). The way the whole thing is set up, it would be hard to come up with a non-hardcoded solution (vs magic constant), so I believe the problem is elsewhere. GridNoOnScreen also uses some padding of its own.

**Comment by lynxlynxlynx** [comment]
This was a problem in the original too, so it's not a regression nor tied to the other bugs tracked in the master bug.

There are some better candidate constants by name (eg. PRONE_HEIGHT), but they're used in a different context and the standing one is too high.

**Comment by lynxlynxlynx** [comment]
Just to keep it all here: the fix was reverted because showing more tiles exposed bad map design. So currently this is more of a WONTFIX situation.

We could potentially show a popup akin to the door/container one, to choose the targeted body part.

**Comment by selaux** [comment]
So should we move it out of the `0.16.0` milestone? As we basically have currenly no concrete plan on how to fix?

**Comment by lynxlynxlynx** [comment]
Yep, done.

**Comment by maxrd2** [comment]
This one is related to #171
Commit aeba89a (#733) fixes this issue.
