### ISSUE TITLE
The button for creating radar maps seems missing from map editor

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1959]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hello

Maybe I'm blind, but every time when I search this, I just can't find it.

In original JA2 UB editor or JA2 1.13 editor in OPTION tab, there was always button responsible for creating radar maps, but I can't find it in Stracciatella editor.

Thanks

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  Stable 0.21.0 | JA2 Gold 1.12 ENG  |    NO    |    YES    |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
I remember that this was removed at some point, maybe as it was not working correctly...

This is probably the related PR: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1300

**Comment by momoko-h** [comment]
At least in the source code provided by the Wildfire CD the only way to enter the MapUtility screen was to have a JA2BETAVERSION build and start it with a `-DOMAPS` command line. The editor toolbar had the same buttons as Stracciatella: [Editor Taskbar Creation.c](https://github.com/dariusk/ja2/blob/876ccf5dfdad7e6821c5b26d6d783132ea1ab7a2/ja2/Build/Editor/Editor%20Taskbar%20Creation.c#L670)

Reverting #1300 and adding one line to `InitEditorOptionsToolbar` wouldn't be much work but I have not checked how much additional effort would be required to  get that screen functional.
