### ISSUE TITLE
Firing mode is not updated when stealing a gun

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#196]
Originally reported by: **Agatae Tsag (Bitbucket: [Agatae](http://bitbucket.org/Agatae), GitHub: Unknown)**

---

I just stole a Dragunov from an enemy.
It's switched to auto.
Either it inherited the auto mode from my FA-MAS or the enemy managed to turn auto on or something else weird happened.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/196

**Comment by derSteFfi** [comment]
when loading the savegame, dragunov is still in auto-mode as described. When I switch the Dragunov and the Famas, Famas is in AutoMode and Dragunov is back to single shot. Seems like this mode is sticked to the main hand and not properly updated on stealing. I'm looking into it.

**Comment by JAsmine-ja2** [comment]
I investigated this issue a bit.

1) Have a gun with burst fire in the main hand and switch burst mode on.
![SCREEN000](https://user-images.githubusercontent.com/17213795/56342583-ad3f6300-61b8-11e9-8a01-40e275a23cdc.jpg)

2) Put the gun away. Notice how burst mode stays enabled. This might be a design choice. For example, if you put your gun away temporarily to throw a grenade, it might be convenient if it is in the same firing mode as before, when you take it back into your main hand. Might also be an oversight...
![SCREEN001](https://user-images.githubusercontent.com/17213795/56342584-ad3f6300-61b8-11e9-8ce6-c77e6c1b1d63.jpg)

3) Now the bug. If you just switch to another gun without burst-mode, the game automatically disables burst-mode for you. However, if you steal a gun without burst-mode, it "inherits" the burst-mode from your old gun.
![SCREEN003](https://user-images.githubusercontent.com/17213795/56342585-ad3f6300-61b8-11e9-8eb7-8115f5746ed5.jpg)

Trying to use the gun can lead to undesired behavior, including lock-up.

> Seems like this mode is sticked to the main hand and not properly updated on stealing.
Seems definitely true.

Steal the enemies' gun in this save and get a .38 colt in (not working) burst mode.
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3093120/QuickSave.zip)

**Comment by ja2-derek** [comment]
In Vanilla, in step 2, the burst mode on merc is disabled once the gun is put away. 

This should issue should be specific to Stracc.
