### ISSUE TITLE
ja2-0.21.0 fails to be built when linking against musl libc

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#1968]
As maintainer of gentoos ja2-stracciatella I have been informed about this:
https://bugs.gentoo.org/928627

This line:
```
/usr/lib/gcc/x86_64-gentoo-linux-musl/13/../../../../x86_64-gentoo-linux-musl/bin/ld: /var/tmp/portage/games-strategy/ja2-stracciatella-0.21.0/work/cargo_home/gentoo/getrandom-0.2.6/src/util_libc.rs:117:(.text._ZN9getrandom9getrandom17h056e21e14da38d0fE+0x231): undefined reference to `open64'
```

looks to me it is related to a cargo package. Is there a way we could fix that?

[musl](http://musl.libc.org/) libc is a replacement for glibc.

**Comment by momoko-h** [comment]
See the [getrandom changelog](https://github.com/rust-random/getrandom/blob/master/CHANGELOG.md). Looks like we'd need to switch from v2.6 to at least 2.9.
