### ISSUE TITLE
When you enter load game screen while clock is spinning, then you can't return to the game

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1972]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hello

When we are fighting with enemies and it's their turn, we are waiting for our turn and the clock is spinning. When in such situation we open load game screen, we won't be able return to the game. We will have to load any game or quit the game. Instead of returning to the game, the option screen is appearing. 

Thanks

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.21.0 stable | JA2 Gold 1.12 ENG  |    NO    |    YES     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
Just to clarify, you're talking about pressing Ctrl+L during the AI's turn and then trying to get back to the game by choosing "Cancel", correct?

This is fairly old bug, introduced by commit https://github.com/ja2-stracciatella/ja2-stracciatella/commit/7e15db75bf28d097b7e82d7c7b3814bd4ecabba6 . Looks like nobody really tested the cancel option.

**Comment by Inveriss** [comment]
Yes, CTRL+L, and then no matter what you choose, CANCEL button or ESC key, the game won't let you return to the game.
