### ISSUE TITLE
When you give a weight above 25,6 kg to the item, then the game starts counting its weight again from zero.

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1973]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hello

Let's take a gun for an example with weight of 25 kg. If we attach to this gun attachment which weight is 1 kg, then the game should show overall weight as 26 kg. But instead of that, its showing us 0,4 kg and its taking this weight as real one. 

Thanks

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.21.0 stable | JA2 Gold 1.12 ENG  |    YESY    |    NO     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Sounds like it's stored as an unsigned byte, in hektograms.

**Comment by momoko-h** [comment]
Correct, both ItemModel::ubWeight and OBJECTTYPE::ubWeight uses units of 0.1kg.

Changing the type of OBJECTTYPE's ubWeapon would be problematic for savegame compatibility. However, this member is really not that useful; it's just the cached value of the object's total weight, which we could also compute on demand.

**Comment by lynxlynxlynx** [comment]
That could work, yeah, especially since it doesn't sound like something that would be on a hot path.

**Comment by momoko-h** [comment]
I just had a look at the 1.13 sources, they nuked that member back in 2008... It's really just used for display purposes and to compute the soldier's encumbrance.
