### ISSUE TITLE
ALT+ENTER doesn't work anymore in the cheat mode

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1977]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hello

In the cheat mode (CTRL+GABBY), function ALT+ENTER was responsible for skipping enemy turn or ending infinite clock spinning. It was very helpful for testing changes purposes.

In Stracciatella ALT+ENTER is now switching windowed mode to full screen and vice versa. Could you give us some alternative keyboard shortcut for skipping enemy turn.

Thanks

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.21.0 stable | JA2 Gold 1.12 ENG  |    NO    |    YES     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
Not a huge problem except that there are not  that many simple key combinations left unused. Do you have any preference? The 2 to 5 keys in combination with ALT already have some other cheat functionality, 1 and 6 to 0 are still free, for example.

**Comment by Inveriss** [comment]
Number six is more or less in the middle of the keyboard, so it would be easy to hit with both left and right ALT. It is also continuation for that enumeration.

So I think the six number would be the best option.

Thank you
