### ISSUE TITLE
Segfault if you watch the whole cut scene - it works if you skip or ESC out of it.

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#198]
Originally reported by: **misanthropos (Bitbucket: [misanthropos](http://bitbucket.org/misanthropos), GitHub: [misanthropos](http://github.com/misanthropos))**

----------------------------------------

Just FF the attached savegame and the cut scene will start.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/198

**Comment by derSteFfi** [comment]
i can confirm that this fixes the crash
