### ISSUE TITLE
In map editor if you press space key when you are in civilian "merc att" tab, then the game crashes

### ISSUE THREAD

**Issue by Inveriss** [ja2-stracciatella/ja2-stracciatella#1981]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Hello

This problem refers only to characters whose statistics are hard coded in map editor obtained from "prof.dat". For example if we mark Fatima in A9 and go to "Merc ATT" tab, then the map editor will show her statistic that are unchangeable.

When we are in such "Merc Att" tab and press space key, (that should us move to the next civilian), then the map editor crashes without any logs.

Thanks

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.21.0 stable | JA2 Gold 1.12 ENG  |    NO    |    YES     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
That looks like a null pointer dereference of gpActive in [RemoveChars()](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/61938e179a4233209727a96be79c7cb8043fe2b3/src/game/Utils/Text_Input.cc#L852), something I believe I fixed in #1952. Would you mind switching to the latest nightly build?

**Comment by Inveriss** [comment]
I implemented #1952 fix and space key starts working fine with "Merc ATT".

Thank you

**Comment by momoko-h** [comment]
Thank you for confirming that it was the same underlying problem. This issue can be closed then.
