### ISSUE TITLE
Our GitHub actions require some attention

### ISSUE THREAD

**Issue by momoko-h** [ja2-stracciatella/ja2-stracciatella#1994]
The Android runner is failing constantly and for the others problems are already on the horizon. [This announcement](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) warns about the deprecation of the v1 to v3 versions of the upload artifacts. Both https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/.github/workflows/coverity-scan.yml and https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/.github/workflows/github-ci.yml still use v2.

Maybe this would also be an opportunity to update the GCC version on the Linux runner, which is still using 8.4? It would be nice to have adequate C++20 support on all runners; MacOS with Apple Clang 13, mingw with GCC 10 and AppVeyor with MSVC 19.29 are already there.

**Comment by lynxlynxlynx** [comment]
We're still on c++17, so there's not much to gain with updating the compilers unless we hit an upstream bug. I find it good to be a bit more modest, so porting to various potatoes is easier.

As for the deprecation, it looks like it should be a trivial bump. We have until the start of July.

**Comment by momoko-h** [comment]
I understand your motivation not to exclude more systems if we don't have to, but on what OS is Rust 1.63 (released August 2022) available but not GCC 10.2 (released July 2020)?

**Comment by lynxlynxlynx** [comment]
Likely none, but what's there to gain?

**Comment by momoko-h** [comment]
Quite a bit; C++20 is a major update. The big ticket items are concepts and ranges, but there are also lot of smaller changes that are probably more  impactful for this code base, at least in the short term.

std::span would be nice, for example. We have lots of occurences of the classic C style pair of pointer to array +  integer indicating the number of items used in the array.

**Comment by lynxlynxlynx** [comment]
Ah, so you're proposing a switch to c++20 as well. Best to have a separate discussion about that, since it's not about our build bots.

**Comment by momoko-h** [comment]
Well, I thought I should suggest it now that we have to update the builders anyway. Nobody seems to like to touch them unless it's absolutely necessary; we could  as well make them ready for C++20 at the same time.
