### ISSUE TITLE
Error message "JA2 Stracciatella quit unexpectedly" on boot. (MAC)

### ISSUE THREAD

**Issue by Simmooooo** [ja2-stracciatella/ja2-stracciatella#2007]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### Error message "JA2 Stracciatella quit unexpectedly" on boot.

Hello, I installed JA2S and everything was fine, I then installed the JA2 game files as required, then for some reason JA2S completely stopped working, giving the error message "JA2 Stracciatella quit unexpectedly" every time I try to open it. Pressing Re-Open opens terminal and displays the following message:

__/Applications/JA2\ Stracciatella.app/Contents/MacOS/JA2\ Stracciatella ; exit;
running /Applications/JA2 Stracciatella.app/Contents/MacOS/JA2 Stracciatella
BUNDLE: /Applications/JA2 Stracciatella.app
RESOURCES: /Applications/JA2 Stracciatella.app/Contents/Resources
2024-06-11T22:51:15.693245Z [INFO] stracciatella::logger: Logging to file "/var/folders/xs/3m6gmsgj06dgqxr_pvdkj20r0000gp/T/ja2-launcher.log"
2024-06-11T22:51:15.69533Z [ERROR] stracciatella_c_api::c::config: Error loading JSON configuration: Error parsing ja2.json config file: EOF while parsing a value at line 1 column 0
thread '<unnamed>' panicked at 'assertion failed: !ptr.is_null()', stracciatella_c_api/src/c/mod.rs:119:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap: 6_
logout_

 I have tried uninstalling, re-installing, restarting my laptop. Nothing seems to work. I am on MacOS Big Sur version 11.7.10.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release v0.21.0 (2023-11-06) |  Jagged Alliance 2 - version 1.12  |    yes             |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
Seems like something broke your configuration file. Could you paste the contents of `~/.ja2/ja2.json`?

**Comment by Simmooooo** [comment]
Apologies I'm new to all this, Can't find it in finder, should I be looking elsewhere? Thanks.

**Comment by selaux** [comment]
You can use `Go -> Go to Folder` in finder and type in `~/.ja2`. There should be a file called `ja2.json`. Please paste the contents and delete the file afterwards. After deleting starting the application should work again. Pasting it is only so we can see what went wrong there.

**Comment by Simmooooo** [comment]
Ah yep, ja2.json is totally blank, which I'm assuming is causing the crash, as for what went wrong I have no idea how it's ended up without any text, I've not altered the file in any way.

**Comment by Simmooooo** [comment]
Deleted ja2.json and started the application, all working fine now, thanks for the help mate.
