### ISSUE TITLE
Figure out what to do with Coverity testing

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#201]
Originally reported by: **Jaka Kranjc (Bitbucket: [jaka_kranjc](http://bitbucket.org/jaka_kranjc), GitHub: Unknown)**

----------------------------------------

As you may know, Coverity provides a static code analyzer, free for open source projects. Apparently the SFI license is not too dodgy for them and one fork of this repo is already using it:
https://scan.coverity.com/projects/ja2-stracciatella

Since it's from an inactive fork, it's not tracking upstream - this repo - and so can't be used to detect regressions quickly. (Cov can actually be integrated with Travis). The past fixes have hopefully already made it here.

I suggest the author be contacted and the source url changed to this repo.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/201

**Comment by derSteFfi** [comment]
how is the standing here for coverity?

**Comment by lynxlynxlynx** [comment]
We're waiting for Agatae to avoid the need to resubmit.
