### ISSUE TITLE
Compiling on MSYS2

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#2016]
> The instructions are in COMPILATION.md, but if you've never done anything similar, it can understandably be daunting.

I tried option bulid on MSYS2 on windows yet I am stuck on ja2-stracciatella, cd into it, and build the package. I cd'd into it and ran command yet last step fails:
cmake .. "-GMSYS Makefiles" -DCPACK_GENERATOR-ZIP
-bash: cmake: command not found
First steps went ok but last command throws this. Cmake is installed, Git bash is installed, everything is there. So dunno really.

_Originally posted by @ja2forever in https://github.com/ja2-stracciatella/ja2-stracciatella/issues/2014#issuecomment-2184917820_

**Comment by lynxlynxlynx** [comment]
@ja2forever use the full path to where you installed cmake in that call then.

**Comment by momoko-h** [comment]
The Windows installer gives you the option to add cmake to your path but by default that option is off. You probably skipped over it.
