### ISSUE TITLE
Icecream Truck follows squad without driving it

### ISSUE THREAD

**Issue by revragu** [ja2-stracciatella/ja2-stracciatella#2037]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Icecream Truck follows one of my squads without driving it. This has the side effect of causing the squad which has the Icecream Truck attached to it to only be able to move a single tile before stopping, even if a waypoint is set several tiles away. Additionally, the Icecream Truck dot shows on a different tile, and entering the Icecream Truck has strange effects.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.22.0-20240719+E43A127   | JA2 GOG 1.12         |    no           |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

Windows 11 Pro Version 10.0.22631 Build 22631

If you enter the truck from inside the tile, it seems driveable from that tile, but you can't add units to it from the map screen. You have to drive a tile away, then back, in order to fill it with units from the map screen. If I put a unit in the truck from the map on the tile it appears to reside on, the truck is not driveable and appears as an empty squad on the tile which contains the unit the truck is following. There were a number of other strange behaviors I've witnessed, but that I haven't been able to replicate.

In the saved game, I've set two squads to move from Alma to Cambria. One will move as expected, and the other will stop on the next tile. If you go into the tile, you'll see the Icecream Truck is there, but on the map it shows on a different tile.

The only mod that's being used is the "IMP quiz honest answers" mod

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

[2024-07-20t17-10-58z-ice-cream-truck-follows.zip](https://github.com/user-attachments/files/16321819/2024-07-20t17-10-58z-ice-cream-truck-follows.zip)
[confs.zip](https://github.com/user-attachments/files/16321849/confs.zip)
[log.zip](https://github.com/user-attachments/files/16321858/log.zip)

**Comment by momoko-h** [comment]
The truck is in two different groups (id 32 and 51), something that should never happen. A vehicle should always be in its own persistant group (id 51 in this case).  It's not that surprising that all sorts of weird behvior follows.

It might be difficult to figure out how we ended up in this mess, but an attempt to fix the situation while loading the game could be made.

**Comment by momoko-h** [comment]
@revragu , do you need a fixed save file to continue your campaign?

**Comment by revragu** [comment]
> @revragu , do you need a fixed save file to continue your campaign?

It would be helpful, thanks! Here is my current save file:

[2024-07-21t00-11-51z-tixa-on.zip](https://github.com/user-attachments/files/16324875/2024-07-21t00-11-51z-tixa-on.zip)

**Comment by momoko-h** [comment]
You will probably get a warning about different mods used, which you can just ignore. It will go away the next time you save. Also, the first time you want to use the truck you might have to enter it from the tactical screen and drive it to another sector. After that you should be able to assign passengers from the map screen. Let me know if you encounter more strange behavior.
[2024-07-21t14-46-30z-tixa-on-repaired.zip](https://github.com/user-attachments/files/16325013/2024-07-21t14-46-30z-tixa-on-repaired.zip)
