### ISSUE TITLE
Unit test failures related to the externalized dir

### ISSUE THREAD

**Issue by ShishkinP** [ja2-stracciatella/ja2-stracciatella#2039]
PR #2029 can't pass these checks:

<code>[  FAILED  ] 6 tests, listed below:
[  FAILED  ] TempFiles.createFile
[  FAILED  ] TempFiles.writeToFile
[  FAILED  ] TempFiles.writeAndRead
[  FAILED  ] TempFiles.append
[  FAILED  ] TempFiles.deleteFile
[  FAILED  ] ExternalizedData.readEveryFile</code>
All with the same error:

> unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.

On my local windows machine launching with -unittests argument shows:

<code>[  FAILED  ] 14 tests, listed below:
[  FAILED  ] TempFiles.createFile
[  FAILED  ] TempFiles.writeToFile
[  FAILED  ] TempFiles.writeAndRead
[  FAILED  ] TempFiles.append
[  FAILED  ] TempFiles.deleteFile
[  FAILED  ] ExternalizedData.readAllData
[  FAILED  ] ExternalizedData.readEveryFile
[  FAILED  ] Items.weaponsLoading
[  FAILED  ] Items.bug120_cawsAmmo
[  FAILED  ] Items.bug120_12gAmmo
[  FAILED  ] Items.bug120_cawsDefaultMag
[  FAILED  ] Items.bug120_spas15DefaultMag
[  FAILED  ] Items.ValidAttachment
[  FAILED  ] Items.Invalid_ItemIndex_Exception</code>
All with the same error:
>unknown file: error: C++ exception with description "Failed to build virtual file system (VFS): Vfs_init_from_engine_options: Error initializing VFS for "externalized": The system cannot find the path specified. (os error 3)" thrown in the test body.

The story is the same with pre #2029 builds. Despite these errors I didn't notice any problems with how the game works.

**Comment by momoko-h** [comment]
Building your PR with GCC and running it under a debugger I get a segmentation fault in free(). Something about your memory management is wonky; instead of trying to figure out exactly what I just changed the new DefaultContentManager members to use unique_ptr:
```
	std::map<std::pair<uint8_t, uint8_t>, std::unique_ptr<NPCQuoteInfo const []>> m_scriptRecordsMeanwhiles;
	std::vector<std::unique_ptr<NPCQuoteInfo const []>> m_scriptRecords;
	std::unique_ptr<NPCQuoteInfo const []>  m_scriptRecordsRecruited;
```
and made the few changes this necessitated (quite easy because NPCVQuoteInfo::deserialize already used make_unique). This also makes your new deleteElements not needed.
