### ISSUE TITLE
dialog dialog flickering

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#205]
Originally reported by: **Jaka Kranjc (Bitbucket: [jaka_kranjc](http://bitbucket.org/jaka_kranjc), GitHub: Unknown)**

---

In the attached save talking to the brothel npcs starts flickering the dialog. Perhaps it goes into a cycle between states? Only a cosmetic regression.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/205

**Comment by derSteFfi** [comment]
i can confirm this is still present, but i have no idea ho to debug it...

**Comment by JAsmine-ja2** [comment]
This issue is the exact same thing as #428
