### ISSUE TITLE
Proposal: Migrate to SDL2

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#206]
Originally reported by: **Stefan Lau (Bitbucket: [selaux](http://bitbucket.org/selaux), GitHub: [selaux](http://github.com/selaux))**

----------------------------------------

Hi,

I have made efforts to migrate ja2-straciattella to SDL2 here: https://github.com/ja2-stracciatella/ja2-stracciatella/tree/sdl2. It's not done yet but most of it works.

## Rationale ##
* SDL 1.2 is outdated
* SDL2 brings an accellerated 2D render API (which we would then have to use)
* SDL2 has better fullscreen support (scaling!)
* SDL2 allows compilation for Android and iOS

## Current Status ##
* Builds with SDL2
* Rendering works
* Audio works
* Mouse works
* Gameplay works (minus undiscovered bugs)

## Issues ##
* [x] Does not build on OS X (because of `SDL_putenv`)
  - no3btnmouse is not necessary anymore on mac, ALT + LMB works fine, CMD + LMB is used as right-click alternative
* [x] Keyboard works only partially
* [x] Graphical corruption when scrolling upwards on tactical map
* [x] Mouse moves outside of fullscreen
* [ ] Not using dirtyRectangles anymore but doing a full screen refresh every time (not sure if that is an issue)

## Moving forward ##
Please feel free to test this branch and tell me your oppinions about the migration and if you want squish the bugs listed above.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/206

**Comment by lynxlynxlynx** [comment]
It seems the packaging stuff (_build) currently relies on SDL1, so that would have to be changed too. I think SDL2 is common enough now that we don't need to support both versions.

**Comment by derSteFfi** [comment]
+1
builds fine here, is playable. the upscrolling in tactical is quite unfancy indeed. didn't test keyboard but audio and video work as described, mouse too.
I also like that mouse moves out of fullscreen, i am on a multiscreen setup and this way i can switch to other windows. With master (SDL1) i can't even alt+tab out of the game, now i can.

**Comment by derSteFfi** [comment]
OK, I have experienced some troubles now. While the scaling is fine (of course stuff is quite low-res for modern displays), the interface only scales when no resolution is given, but the game ist started with '-fullscreen'. '-fullscreen -res 1920x1080' (the res is fullscreen too, and yes, it makes no sense) does start the game on the complete screen but doesn't scale.

It also seems like the scaling doesnt scale hitboxes. Neither for shooting, talking, giving objects or anything. This is quite unintuitive.
For me, scrolling with the mouse is quite strange. Mouse to the right has no effect, mouse to the left scrolls right. Mouse top scrolls up, Mouse down scrolls down.
Last, the mouse seems to dissappear to the right and at the bottom:
I move the mouse right -> it reaches the corner of my first screen (second is at the right of it) -> move the mouse further -> mouse is nowhere -> move further -> mouse appears on second screen
Scrolling down also only gets triggered after you keep moving the mouse after it disappeared at the bottom.
I guess locking the mouse to fullscreen properly will fix this and alt+tab (see previous comment) should still work...

**Comment by selaux** [comment]
@derSteFfi: The issue that it doesnt scale hitboxes might have something to do with the possibility to move the cursor outside the fullscreen. Somehow the game might not realize that it is in scaled fullscreen mode.

@lynxlynxlynx Yes the build stuff depends on SDL 1.2. I didn't update that yet so you need a system version installed.

**Comment by selaux** [comment]
I pushed a new commit to master that should fix the mouse issues. Please test.

**Comment by derSteFfi** [comment]
mouse works fine for me. but i need to set the resolution manually. if i start the game with '-fullscreen', the ui gets scaled up and the mouse is dead. if i start it with '-fullscreen -res 1920x1080' UI doesnt get scaled and everything works fine.
Only keyboard key working until now is ctrl.

**Comment by derSteFfi** [comment]
correction: '-fullscreen' works fine. both scaling and mouse. had a version fuckup here...

**Comment by selaux** [comment]
Keyboard Input should now work as well.

**Comment by selaux** [comment]
Using dirtyRectangles again, scrolling upwards is still broken though.

**Comment by selaux** [comment]
The issue I identified causing the scrolling up to be corrupted was the `ScreenBuffer` blitting onto himself, which seams not to work anymore in SDL2. My resolution was to create a copy of the screen buffer before blitting that back onto the screenbuffer. Not sure if that is a performant solution though. Nevertheless this issue should not exist anymore after this fix.

**Comment by selaux** [comment]
The dirty rectangle updating seems to work only partially, there seems to be some kind of one-off error.

**Comment by selaux** [comment]
I investigated the dirty rectangle updating some more and can give you an update based on https://github.com/ja2-stracciatella/ja2-stracciatella/commit/1d0b6d74547f8ea14461910b79520920775aada6.

- currently the dirty rectangles ars used to update the `ScreenBuffer` from the `FrameBuffer`
- Then a texture is created from the `ScreenBuffer` and the dirty rectangles are again used to copy parts of the texture to the screen, or a full copy is done e.g. when there are too many dirty rectangles
- The issue is that when copying the full texture to the screen, the result is slightly offset from the parts that are copied using the dirty rectangles afterwards
- My assumption is that this happens because of issues with SDL2 scaling. This was experienced by others as well:
 - http://stackoverflow.com/questions/27737076/resizing-texture-scaling-issue-using-pngs-opengl-sdl2-0
- The only solution would be to always copy the full `ScreenBuffer` to the screen, the performance impact of this was not noticeable on my machine, but some further testing needs to be done

**Comment by derSteFfi** [comment]
i can confirm keyboard and scrolling up working fine with the latest patches.
But i have artifacts left and right of the game (in menu). The menu itself gets artifacted when I alt+tab out and back in. gets repainted fine though (under the mouse cursor as well as when changing screens) I guess a repaint of the game needs to be triggered when regaining focus and the background needs to be invalidated (also when gaining or regaining focus)

**Comment by lynxlynxlynx** [comment]
Is the dirty rect problem only present on non-default resolutions?

**Comment by selaux** [comment]
So there are two issures currently with dirty rects:

- Flickering (which occurs on all resolutions), happens on my Linux and OS X machines
- Scaling artifacts (which occur only in non-default resolutions)

My proposal would be to benchmark the fullscreen refresh solution and se if it really impacts performance that much.

Another issue that I have is that I cannot find a tgz for the OS X library. There is only a dmg and I dont know how it is structured.

**Comment by lynxlynxlynx** [comment]
The flickering is gone if you do full screen updates? Then perhaps we just need to clear the renderer manually now and then. And definitely after any scaling op.

By scaling we all mean just the -res option, not sdl2's arbitrary extrapolation (if the right window flags are passed)?

**Comment by chmallon** [comment]
> The issue I identified causing the scrolling up to be corrupted was the ScreenBuffer blitting onto himself, which seams not to work anymore in SDL2.
> My resolution was to create a copy of the screen buffer before blitting that back onto the screenbuffer.

This is a bug in SDL2 up to 2.0.4 and fixed in 2.0.5:
https://bugzilla.libsdl.org/show_bug.cgi?id=3096
So this workaround can be removed.

**Comment by Manuel-K** [comment]
We still have SDL2 2.0.4 in the repo.

**Comment by lynxlynxlynx** [comment]
Which can be updated. We use the system one when available, but many people won't have access to .5 yet, so it's best if this remains ifdefed (if possible) or deferred..

**Comment by chmallon** [comment]
2.0.5 is almost a year old. (2016-10-20)
Maybe you confuse it with 2.0.6, which is just a few days old.

**Comment by Manuel-K** [comment]
Debian stretch has 2.0.5. 
Ubuntu Xenial (16.04, LTS release) has 2.0.4. This is definitely a blocker.

**Comment by Manuel-K** [comment]
We can't change something that would break the game on the latest Ubuntu LTS release.

**Comment by lynxlynxlynx** [comment]
That's why I mentioned ifdefing (SDL_VERSION_ATLEAST), so we could maintain compatibility while also supporting the more efficient drawing. If it doesn't end up too ugly.

**Comment by selaux** [comment]
The question for me would be how much this actually impacts performance and memory. JA2 is an old game and should run fine on most systems, even with this workaround included. I would only introduce additional code for optimization when it is really needed (especially something targeting different versions of a dependency).

Long story short: We should decide what we see as the "minimum system requirements" for our version of the game and optimize accordingly. Could be something like: Should run fine on a Raspberry Pi 1 or should run fine on a system that fits the minimum requirements of the originial game.

**Comment by janisozaur** [comment]
Just to add a data point and argument for SDL2: SDL2 introduced something called "Dynamic API" that lets users swap libsdl2 on their end, even if statically compiled in.

See discussion in https://www.reddit.com/r/linux_gaming/comments/1upn39/sdl2_adds_dynamic_api_magic_to_allow_updating_it/

**Comment by Manuel-K** [comment]
@janisozaur Pardon? We already use SDL2. And I've written the Stretch thing 15 hours ago.

**Comment by janisozaur** [comment]
Whoops, my bad for not reading the whole discussion properly, sorry.

Are you shipping your custom SDL2 then?

**Comment by lynxlynxlynx** [comment]
No, I think it's bundled just for crosscompilation.

**Comment by selaux** [comment]
It is bundled for Windows and macOS builds. On linux we use system SDL2.
