### ISSUE TITLE
crash with error when autoresolving in sectors attacked by sodiers and defended by militias and mercs (27 august nightly build)

### ISSUE THREAD

**Issue by az75199** [ja2-stracciatella/ja2-stracciatella#2068]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues for each one!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold Dutch  |    yes/no    |    yes/no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by momoko-h** [comment]
I take it you're talking about the crash at the end of Auto Resolve, when you click on the "Done" button?

**Comment by az75199** [comment]
Yes, on autoresolve when you hit the DONE button the game crashes.
You have a quicksave attached for reproduction.

Although we wish them well, we hereby warn the ocular trespassers that they shall be frozen by arctic or antarctic cold if ever seen eying on our stuff
________________________________
De la: momoko-h ***@***.***>
Trimis: marți, 3 septembrie 2024 22:00
Către: ja2-stracciatella/ja2-stracciatella ***@***.***>
Cc: az75199 ***@***.***>; Author ***@***.***>
Subiect: Re: [ja2-stracciatella/ja2-stracciatella] crash with error when autoresolving in sectors attacked by sodiers and defended by militias and mercs (27 august nightly build) (Issue #2068)


I take it you're talking about the crash at the end of Auto Resolve, when you click on the "Done" button?

**Comment by zbikk** [comment]
can replicate
