### ISSUE TITLE
Team JA2 Stracciatella

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#207]
Originally reported by: **JAsmine-ja2** [here](https://bitbucket.org/gennady/ja2-stracciatella/issue/207)

----------------------------------------

Let's get together in a mail chat and see what will happen :)

ja2stracciatella _at_ gmail _dot_ com

This is supposed to be some kind of basis so that we can discuss the status/future of this project.

----------------------------------------
Setup:
- [x]   count ourselves
- [x]  schedule a meeting or just do it here
  - [x]   see who's up to what
  - [x]   see who's up for what
- [x]   create the bitbucket team / give access (migrated to gh instead)
- [x]  update bitbucket README
- [x]  update github README
- [x]  notify remaining pull requesters
- [x] ~~close original github mirror~~
  - [x] point travis to this repo
    - [x] update travis widget link in readme if needed
- [x] push old branches here too (only master was imported)?
  - @selaux: I pushed the other branches and tags as well. Should be everything now.
- [x]  leave the wiki in the old place?
- [x] update [moddb entry](http://www.moddb.com/mods/ja2-stracciatella)
- [x] point coverity to new repo (tracked separately in #201 )

What now?
- [x]  decide how much chocolate we want and how (eg. how to handle 1.13 / feature creep vs. cleanup & stability)
- [x]  merge outstanding fixes, sensible PRs
  - [x] all PRs migrated
  - [x] vxx's cutscene fix
- [x]  triage old bugs
  - retest tag was added - start there or with "Least recently updated" issue sorting
 - [x]  create a master bug for all the AP problems
 - [x]  create a master bug for all the placement issues
- [x] report to Bear's Pit
- [x] investigate the android port (pelya's sdl1? yes) and consider merging: [notes](http://paste.debian.net/393679/), [rc2 download](https://www.copy.com/s/t%3AUOjZjhDpGZlC%3Bp%3A%252Fja2android_rc2_patch.tar.bz2%3Boid%3A2)
  - looks like it's best to finish the sdl2 port first
  - sensible stuff can be cherry-picked
- [x]  new release (now tracked via milestone)
  - [x] check git log for the changelog entry
  - [x] document the process (tests, builds, news in readme+wiki+bp+moddb)
  - [x] semi-automate the process (tracked via #219)

**Comment by selaux** [comment]
I pushed the remaining branches and tags from bitbucket, as well as my bugfix branches and recreated my pull requests from Bitbucket.

**Comment by selaux** [comment]
I would leave the Wiki and create a new one here. It doesn't seem to contain much useful info.

**Comment by lynxlynxlynx** [comment]
I agree, we just have to hunt down as many backlinks as possible then.

**Comment by lynxlynxlynx** [comment]
@derSteFfi : what was your username on bitbucket? Just so I can see who else to ping.

**Comment by derSteFfi** [comment]
dRp3pP3r

**Comment by lynxlynxlynx** [comment]
Thanks. I now wrote to JAsmine, misanthropos, Agatae Tsag, drm00 and vxx (indirectly).

**Comment by gennady** [comment]
In the old BitBucket repo I've switched the landing page to Wiki and made the announcement about the move to GitHub.  https://bitbucket.org/gennady/ja2-stracciatella

It is now the official home of JA2 Stracciatella

**Comment by lynxlynxlynx** [comment]
Thanks. I'll migrate the wiki contents later. With travis taken care of, we don't have to touch the original mirror.

**Comment by JAsmine-ja2** [comment]
Hi. I'm here. Let's hit it :)

**Comment by wvx** [comment]
Hello, thank you for contacting me (vxx). I have added my fork, but there is nothing new. 

It is great to see the new activity and SDL2.

**Comment by selaux** [comment]
@gennady: Can you add the "move" notice to you github repo as well?

**Comment by lynxlynxlynx** [comment]
By now I've heard from everyone except Agatae. And lots of work has been done already. Which is funny, since the meeting was supposed to be the first item to clear things up.

There was no comment on the medium (here, mail, irc...), so I'll just write my thoughts here:
1. Release 0.14something in March. With a few extra fixes, but otherwise nothing major (sdl2, build system, android, 1.13 stuff). We end up with a documented process, quicker turn around and more visibility. I volunteer to spearhead this. We then do releases any time enough progress has accumulated.
2. I have no problem with smaller changes from 1.13 getting in, as long as they are disabled by default (as with everything else now). Invasive things like their new inventory system and similar have no place here.
3. I'm not really interested in long-term development, but I can continue to be the release guy and help with reviews/tracker.

**Comment by selaux** [comment]
Do we still want to do the meeting. Or do we settle everything Herr. I m pro meeting. Im licing in CET. But if not here are my points.

- The release plan from @lynxlynxlynx sounds good
- My goal for stracciatella is to have a version that runs and behaves well on all modern devices and is easily and thoroughly moddable
- I would try to hide any feature changes from vanilla behind a flag except for really small ones
- I m interested in long term development, but not the strongest programmer in C++

**Comment by JAsmine-ja2** [comment]
I agree with what you @lynxlynxlynx @selaux write here.

What I would like Stracciatella to be like:
- Fix bugs (from both Vanilla and Stracciatella)
- Improve moddability (= externalize lots of stuff)
- Be more comfortable to use (e.g. #19 ; messing with command lines is not very "sexy")
- Maybe add some small changes from 1.13, but nothing big.
- Make new features and game-changing fixes optional (should not end up with an INI with 5.000 options like v1.13... ;)

What I can/can't do:
- I can mod, playtest, take care of moddb profile, write stuff like readme, wiki or faq
- I can't do any coding at all

My future plans:
- I'm interested in sticking around this project for a long time

**Comment by derSteFfi** [comment]
Seems we are on the same page.
I agree with:
- Release plan of @lynxlynxlynx 
- the goal for Stracciatella of @selaux 
- fixing bugs but not adding to much
- hiding gameplay changes behind config switches but avoiding the mess of 1.13
- externalise more of the content

What I am up for:
- Of course i can test, write stuff like jasmine
- I can code, but I am much more used to smaller projects (i am a hardware engineer)
- My motivation except fun is learning new stuff (like it's already happening, thx btw)

I'm also still in favor of the meeting (living in CET, too) simply because sorting out priorities and the plan for the next few weeks would help a lot I think.

**Comment by lynxlynxlynx** [comment]
Great, thank you all for chiming in. I'm also in CET and while it's clear we are already on the same page, I have no objection to a meeting for some details. I'm pretty flexible when it comes to timing, so I'll just throw tomorrow at 17:00 CET as a suggestion (start a doodle if one of you is very limited).

**Comment by derSteFfi** [comment]
works for me.

**Comment by lynxlynxlynx** [comment]
oh, please also state any preferences for the way we meet (irc, jitsi, skype ...).

**Comment by selaux** [comment]
Sweet. I'd prefer something like Google Hangout or Skype as a meeting place, since I prefer talking. The time is not as much an issue for me, I could take some time off work if necessary.

**Comment by lynxlynxlynx** [comment]
Seeing the edit, how about Friday at 1600 or 1700? If you all have hangouts or skype set up, that's fine with me, otherwise I prefer jitsi (in-browser).

**Comment by derSteFfi** [comment]
i'm fine with hangout and fine with friday afternoon. I don't know jitsi, but i guess i can arrange that.

**Comment by JAsmine-ja2** [comment]
I have hangouts and skype set up. 
Could arrange other means if needed.
Any time on friday is fine.

**Comment by lynxlynxlynx** [comment]
https://meet.jit.si/ it's open source and you just create a room and pass the link to others. No registration required.

**Comment by lynxlynxlynx** [comment]
Just so it will be easier to start: https://meet.jit.si/ja2sm1

**Comment by lynxlynxlynx** [comment]
The meeting was a success and we ironed out most of the issues. Some are tracked by other bugs anyway, so I'm closing this one (checklist is checked). With that, the migration is "officially" complete! 

Good job everyone! :+1:

**Comment by JAsmine-ja2** [comment]
Should we get in touch with Kermi and ask him to upload Stracciatella Continued on his FTP repository?
http://kermi.pp.fi/

There is already lots of Stracciatella stuff there, but it's all old stuff.
http://kermi.pp.fi/JA_2/Stracciatella/

Kermi's repository is the biggest and most complete collection of JA2-stuff online.

**Comment by selaux** [comment]
Maybe its better to add some kind of link from there to our repository, so the stuff will not be outdated at any time, but generally I think it's a good idea, why not make ja2-stracciatella a little more prominent :smile:
