### ISSUE TITLE
PickBurstLocation never called in real-time mode.

### ISSUE THREAD

**Issue by Danf96** [ja2-stracciatella/ja2-stracciatella#2072]
### What is wrong

In real-time mode when attempting to do an aimed burst by holding B, clicking and dragging across the screen, the selected merc only fires at the ending location of the spread pattern. After stepping through the code, it looks like this block is never entered as gpItemPointer is always null when releasing left click after drawing out the burst pattern.

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7b415954d71a9058162f5bbccb50337fcb81957e/src/game/Tactical/Real_Time_Input.cc#L393

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git | JA2 Gold |    no    |    yes     |

**Comment by Danf96** [comment]
Removing the gpItemPointer to match the turn-based input check seems to fix the issue, but this check is part of the original source code. Anyone know why this check was added in the first place? I thought gpItemPointer was only for when you selected an item with the cursor to move.

**Comment by Danf96** [comment]
After disabling the gpItemPointer check, I've also discovered and verified a vanilla bug when doing an aimed/spread burst with the minimi due to a check added that never allows the sixth round of the minimi to be aimed in a spread burst and causes the last round to come out at the start of the spread instead of the end.
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/20c090ba53de0350d977bcedd913420517cc014e/src/game/Tactical/Weapons.cc#L490

**Comment by momoko-h** [comment]
> Removing the gpItemPointer to match the turn-based input check seems to fix the issue, but this check is part of the original source code. Anyone know why this check was added in the first place? I thought gpItemPointer was only for when you selected an item with the cursor to move.

I doubt anyone besides the original author knows why the check is there but it could well simply be a mistake. After all, this is from the same team of programmers that used a BOOLEAN value to store FALSE, TRUE and 1 to 6.
