### ISSUE TITLE
When exiting the game with keyboard shortcut from the strategic screen, some graphics are missing

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#2119]
### What is wrong

When you're on the strategic screen and you pres Alt+X fro exiting the game, message for confirmation will appear. But you see, that with that message in foreground (before you confirm and exit the game), some graphics in the background (like sector coordinates and buttons bellow the map) are now missing. The vanilla behaves correctly.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  latest nightly | JA2 1.06 EN  |    no    |    ?     |

![JA2_Exit_1](https://github.com/user-attachments/assets/12f55884-66e6-4a9e-9ef9-e70f420b265a)
![JA2_Exit_2](https://github.com/user-attachments/assets/c26feb93-de42-4fd3-a225-dfc92803efd3)

**Comment by momoko-h** [comment]
It's not just the Exit Game dialog, this dismiss confirmation dialog has the same problem. I didn't check them all but I suspect all instances of message box screens on top of the map screen are bugged.
