### ISSUE TITLE
Hidden switch on the map with scientist won't work, if you're dropped to the sector by the helicopter

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#2120]
### What is wrong

Since I know, in which sectors scientist with robot usually is, I tried to save some time and look for him with helicopter. After I find the correct map (by its content, but I didn't receive the usual message about something interesting the sector), used the hidden switch as usual, but it didn't open the hidden door in the barn. I had to drop my merc in the neighboring sector and walk there on the foot, only then I received the usual message, that I find something interesting in the sector and the switch then worked correctly.

I'm playing game on the Windows 10 with 64-bit binaries.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  latest nightly | JA2 1.06 EN  |   ?   |    ?     |

**Comment by momoko-h** [comment]
Do you still have a save game for this? Unfortunately I currently don't have one where the Madlab quest is active and in the save for #2118 the secret door is already open.

**Comment by Srandista** [comment]
I find older saves, but I can't reproduce it now. I'll close the issue in the mean time, if I'll be able to reproduce it again, I'll reopen.
