### ISSUE TITLE
release builds through Travis?

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#219]
Travis also has osx hosts and can be connected with bintray and others to automatically copy over release builds.
So, we could get osx builds with little effort (tests would be harder though), linux binaries (potentially as rpm/deb) and could perhaps ditch the whole _build/. Thoughts?

**Comment by selaux** [comment]
Sounds like a good idea. More automation in the build process would be appreciated i think.

Could we also build binaries after every commit with a solution like that? Then we would have a easy way for people to verify that the bugs they reported were fixed, without needing the skills to compile the application themselves.

**Comment by derSteFfi** [comment]
definite +1 on that! I know jenkins can do this, i guess travis can, too. Having builds for at least Win, Lin and Mac would of course ease distribution...

**Comment by lynxlynxlynx** [comment]
Bintray no, but other things would work. Eg. gemrb has a sourceforge project and they don't mind buildbot uploads. Probably hard to get with this shitty license (I think we even tried before), but any ftp would be ok.

Travis unfortunately doesn't do windows builds.

**Comment by selaux** [comment]
But we could cross-compile for Windows in a Linux environment maybe? Travis also supports OS X workers, so building for Win, Linux and Mac could be done with travis. Where to upload the binaries is another question.

**Comment by lynxlynxlynx** [comment]
Crosscompiling could be avoided - Appveyor provides a similar service, but for windows hosts.

**Comment by lynxlynxlynx** [comment]
At least Appveyor builds also pushed tags, not just commits. Don't know about Travis. Now with the nightlies, is there anything left to do here?

**Comment by selaux** [comment]
I would keep this open. Next steps would be as you said building releases and building pull requests for easier testing.

**Comment by lynxlynxlynx** [comment]
I guess only PR building (saving of the build result) is left.

**Comment by selaux** [comment]
Nope, already works. They are here: http://builds-ja2.stefanlau.com/pull-requests/. Closing.
