### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#227]
![we have a problem](http://i.imgur.com/vOWAAUK.png)

Do we fix it in one swoop or just as we go along. I fear that for a project as mature as this, the latter, usually better way, will never resolve it.

**Comment by selaux** [comment]
+1 for whitespaces and fixing everything in one go...

**Comment by derSteFfi** [comment]
+1 too. how does one fix that in one go? are there scripts for that?

**Comment by lynxlynxlynx** [comment]
It's easy to script with regex, but it does require oversight and review. From the README:

    display tab as 2 spaces
    indent with spaces

Most files, lines (93%) use tabs, so I suggest we reverse the previous policy.

**Comment by wvx** [comment]
Please do this. Either way is good. My vote for indent with spaces and convert tabs to 2 spaces, just because it will look the same everywhere. Well with fixed width font anyway.

**Comment by Manuel-K** [comment]
@selaux @lynxlynxlynx @derSteFfi @RinneT Can we bring this up again?

I'd prefer spaces, but either way is fine with me.

**Comment by lynxlynxlynx** [comment]
Most of the code uses tabs, so maintaining that would mean a much less invasive change.

**Comment by Manuel-K** [comment]
True. 39155 lines with more than one consecutive space versus 266431 lines with tabs.

**Comment by derSteFfi** [comment]
I personally prefer tabs anyway... my impression is, most of them are 8 characters wide, but that could be subjective.

**Comment by Manuel-K** [comment]
Minor issue – huge amount of work to do it in a controlled way.

**Comment by derSteFfi** [comment]
Nice! I'm gonig to review the start tomorrow. For now, thanks for the effort :)

**Comment by Manuel-K** [comment]
> Nice! I'm gonig to review the start tomorrow. For now, thanks for the effort :)

At the moment only `src/sgp` is done.

The other commits will probably be amended.

**Comment by Manuel-K** [comment]
Again: **The current method is indent with tabs and display tabs as four spaces.**

**Comment by lynxlynxlynx** [comment]
indent with tabs, the rest is up to the reader — I don't care if you display them as 2, 8 or something else.

**Comment by derSteFfi** [comment]
Should me might close this since we merged #556 ?
