### ISSUE TITLE
Crash when modding itemindex 63

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#235]
"itemIndex": 63, in weapons.json.
In vanilla JA2, this index is the unfinished and unusable flamethrower. While working on #100, I tried to mod this index into a different weapon.
I changed weapons.json accordingly and provided all data files necessary. In the game, the weapon makes the game crash as soon, as I try to fire it. Here is the error:
![flame](https://cloud.githubusercontent.com/assets/17213795/13348906/8cfcf4c4-dc76-11e5-9ab7-24a54972b7fc.jpg)

And here's a savegame before the crash and the error savegame.
[flame-error-saves.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/147958/flame-error-saves.zip)

This is a bug from vanilla JA2, as it was already not possible to mod this itemindex back in the old days. I guess, it is because there is more hardcoded stuff going on with this particular index.

At the moment, this seems impossible to mod this weapon with the externalized data only. This makes this issue a severe drawback for making Stracciatella a modding platform.
Note, that modding other weapons works fine.

**Comment by selaux** [comment]
Can you add your modified `weapons.json`? I can replace the flamethrower just fine, but when I load the save the MERC has a MAC-10 in his hands.

**Comment by selaux** [comment]
I debugged this for some time and it seems to me that the assets for the flamethrower dont exist completely. It is trying to load `tilecache/flmthr2.sti` which does not exist in my assets.

**Comment by JAsmine-ja2** [comment]
The best solution for this problem would be to leave every hardcoded weapon in place and not change or delete anything here.
The only reason for a modder to change an existing item index is because it is not possible at the moment to add more item indices. If it was possible (like in v1.13), there would be absolutely no reason at all for a modder to change the flamethrower or any of the vanilla weapons.
He could just remove them from his mod.
In order to make Stracciatella a stable (and potent) platform for modding, it is inevitable do allow for more item indices sooner or later.

**Comment by Manuel-K** [comment]
@JAsmine-ja2 I think this was solved/avoided in #525. At least it does avoid the crash.

**Comment by JAsmine-ja2** [comment]
Okay, I will test it.

**Comment by JAsmine-ja2** [comment]
Yes, #525 solves the crashing problem with this item index. The situation is safe now.
