### ISSUE TITLE
support JA2 Demo?

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#238]
I just tried to run the JA2 Demo with Stracciatella. It failed. It seems, like Stracciatella is very restrictive when looking for specific data-files. The JA2 Demo comes with almost all data files missing, because it doesn't need them.
Would it be possible to make Stracciatella run in a "Demo" mode (maybe an extra .bat)?
Are there more problems when trying to run the JA2 Demo with Stracciatella?

I was thinking that if (and only _if_) making Stracciatella support the JA2 Demo is an easy task, it would be a very good thing. Maybe we could then inlcude the Demo as part of the Modpack or a seperate Download, so that people could try out Stracciatella more easily.

What do you think?

JA2 Demo can be found here: http://kermi.pp.fi/JA_2/Other_Stuff/Demo/

**Comment by derSteFfi** [comment]
I definitly like the idea. But I have no idea how much work this is... :)

**Comment by JAsmine-ja2** [comment]
I tried to replace all the data files in the Demo with data files from the full version, but this didn't lead to any useful results and crashes the game as soon as I try to hire someone from AIM.

**Comment by selaux** [comment]
There is a `JA2TESTVERSION` flag to compile with that builds the demo. The resulting code is broken though and doesnt compile. Building-in the demo mode is probably a matter of fixing these compilation errors and replacing the `#ifdef JA2TESTVERSION`s and `#ifdef JA2BETAVERSION` by a command line flag.

**Comment by lynxlynxlynx** [comment]
Old stuff, #10

**Comment by JAsmine-ja2** [comment]
Okay, so it's NOT an easy task to make Stracciatella support the JA2 Demo, right? It's probably better to leave it as it is... at least, for now.

**Comment by selaux** [comment]
Will close this in favor of #10.

**Comment by chmallon** [comment]
> Okay, so it's NOT an easy task to make Stracciatella support the JA2 Demo, right?

Back then I made it work the the demo data.
You just had to compile it with JA2DEMO.
It seems somebody broke and/or removed this feature here.

**Comment by midzer** [comment]
@chmallon I've moved your port https://github.com/chmallon/ja2-stracciatella to SDL2 and got the Demo working in the browser as well https://midzer.de/wasm/jaggedalliance2/
