### ISSUE TITLE
Release minutiae

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#242]
Pre-release:
- triage newer bugs and open PRs, fixing, reverting and delaying the release if necessary

Release:
- ~~test a clean build~~ (handled by travis)
- runtime check
- update changes.md
- bump version
- tag and push tag
- build packages
- github release
- announce to website, README, wiki, bp, moddb

- [x] version scheme?? I propose increasing to 0.2 when the SDL2 port is done and similar for other big changes
- [x] contributors.txt - archive and just point people to the shortlog?
- [x] put the final instructions in a file

Did I miss anything? What do you guys think about the above two?

**Comment by selaux** [comment]
- The version scheme should be 0.14.x -> 0.15.x -> eventually 1.0.x to comply with http://semver.org/ imho
- I would keep contributors.txt since some of the contributing information got lost converting the repo from svn to git
- :+1: for documenting the release process in a file. Additionally we could add a file that documents the testing process before a release (basically what needs to be done to do a runtime check and to assure that everything works correctly)
- Tagging is already done by creating a github release so creating a tag manually is not neccessary

**Comment by lynxlynxlynx** [comment]
- version: 0.2.0 is compatible.
- contributors: yes, that's what I meant by archive - leave it be and don't bother updating it, just put a link to the online contributor list (and a git shortlog note); before it was manually updated now and then which I consider a waste of time
- we can never check everything - what do you suggest for a passing "runtime check"? I'd say fresh game up to recruting Ira
- tagging is separate just to make it easier, since you can do it on your box, then do the builds and finally just upload them to the release (skips the need to pull first)

**Comment by derSteFfi** [comment]
- i think it should be 0.15 -> 0.16 -> ... and we should start thinking about what we need to call it 1.0
- fresh game until Ira seems legit

**Comment by lynxlynxlynx** [comment]
As discussed, the runtime check should be more detailed, at least:
- playing up to leaving Omerta (including the first cutscene)
- imp
- buying from bobby ray's
- extending contracts
- spy report
(be mindful of any drawing glitches)

**Comment by selaux** [comment]
Another thing I thought about after the meeting is having a bunch of savegames somewhere as a shortcut to e.g. after Drassen so buying from bobby rays is possible...

**Comment by lynxlynxlynx** [comment]
Re contributors.txt: we actually have a makefile target for the update, but it does manual deduplication. I'm still for just adding a pointer to the file and leaving it be forever, but we could also just update the regexes at release time and keep it updated at release time.

**Comment by selaux** [comment]
What is actually missing for the release? Should we fix the npcs outside of accessible tiles being visible and merge the PR for #125 and that's it?

**Comment by lynxlynxlynx** [comment]
Besides some of the trivial updates in the milestone, that's the only thing remaining now — as far as I'm concerned. We can postpone the rest from the placement meta bug.

**Comment by selaux** [comment]
What about reverting the headshot PR, because currently I'm not able to find a solution and for me it's not a must have for `0.15`.

**Comment by lynxlynxlynx** [comment]
Sure, I'm still pretty swamped with work.

**Comment by derSteFfi** [comment]
As seen by my activity in the last 2 weeks, I'm quite fed with work, too. So I'd be fine with that.

**Comment by JAsmine-ja2** [comment]
I don't contribute any code anyway, but I'm pro releasing 0.15 rather sooner than later (of course without rushing anything or anybody). It already has some very, very nice changes and I'm kinda holding back my next thorough playthrough until the next release.
