### ISSUE TITLE
Stracciatella logo

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#246]
![stracc](https://cloud.githubusercontent.com/assets/17213795/13548440/c017f2f2-e2f0-11e5-9aec-be5cea7cfe76.jpg)
Since selaux mentioned a logo in #244, I had this idea.
I'm not much of a painter + this was a quick job done in ms paint.

I wanted to do something that is more like a pictogram or a symbol. A very simple shape with few colors. The red from the background is taken directly from the original JA2 logo, as is the color of the cone.
![logo-orig](https://cloud.githubusercontent.com/assets/17213795/13548467/728a1276-e2f1-11e5-8fd0-b71bc7faee78.jpg)

Now, I do not think that this should be the official logo for Stracciatella. But what do you think of the general style?

**Comment by lynxlynxlynx** [comment]
simple designs are best (easily vectorizable), since we'll need to use it at various scales - from tiny favicons, perhaps icons, to using it as an element in bigger things. And we want it to look good everywhere, so it either needs to be good enough as a monolith or separable/simplifiable.

So I like this one — it's squarish and would resize well. The only thing that comes to mind is that it's not at all clear that this wouldn't lead you to something about icecream, but murder, death and misery. How could we convey the JA2 part too?

Maybe some barbed wire as in the AI logo or perhaps a stylized bullet instead of the cone ...

**Comment by selaux** [comment]
Thanks for putting some work into this, looks nice right from the start. I like the idea of the ice-cream cone made out of a bullet. I think this would be very unique and recognizeable.

**Comment by JAsmine-ja2** [comment]
![ice-bullet](https://cloud.githubusercontent.com/assets/17213795/13554380/9a8bf266-e3a6-11e5-8c4a-0ff61089e285.jpg)

- It's a perfect square
- More or less same colors as before (to resemble the original JA2 logo)
- Same art-style (pictogram/symbol - few colors, simple shape)
- The brown chocolate pieces got a small black frame. But I think that wasn't a god idea.
- The cone IS a bullet. Maybe it could also be a cone morphing into a cone. Idea sounds cool. But it would be hard to do a morphin cone and have the end result still be a pictogram/symbol.

**Comment by JAsmine-ja2** [comment]
![ice-guns](https://cloud.githubusercontent.com/assets/17213795/13555669/356507ee-e3c7-11e5-84bf-1ec3573c283c.jpg)
What about this idea? Again the Stracciatella ice (like it ;) but this time with your generic m16 and ak47.
Probably too much detail on the two guns. Not much like a symbol. But the dimension (ice vs. "cone") seem more fitting here compared to the bullet...

**Comment by lynxlynxlynx** [comment]
I think there'd have to be more bullets for that to work. But the second one gave me an idea — doesn't the icecream look like a helmet? Just add a strap and it would be pretty obvious. In bigger versions there's room for a JA2S below too.

**Comment by selaux** [comment]
Nice to see some ideas come together. So here are my two cents: In the first one the bullet is too narrow to be a cone, so it kind of looks weird. The second one imho has too much detail. But I like the idea of a bullet transforming into a cone so I applied a perspective transform to the bullet in the first logo, which makes it look like a cone (but unfortunately not as much as a bullet anymore).
![9a8bf266-e3a6-11e5-8c4a-0ff61089e285](https://cloud.githubusercontent.com/assets/848854/13555843/59fbfadc-e3cb-11e5-89cb-7f2ccf232702.jpg)

**Comment by lynxlynxlynx** [comment]
yeah, I guess something like a mortar shell would look better, since it is "naturally" curvy and the top can be replaced by the icecream.

**Comment by selaux** [comment]
I have a short mockup of the helmet idea whilst still keeping the ice cream cone.
![2](https://cloud.githubusercontent.com/assets/848854/13725161/eae7e54c-e899-11e5-941d-035a0cc73015.jpg)

**Comment by lynxlynxlynx** [comment]
Worksforme. On smaller scales the skull will contract into a cone and all will still be well.

**Comment by derSteFfi** [comment]
i also think this one is nice. whats the standing on the black adges of the chocolate pieces?

**Comment by lynxlynxlynx** [comment]
I think they're redundant — even at this scale almost unnoticable.

**Comment by JAsmine-ja2** [comment]
I like this idea, too.
Maybe:
- remove the black frame for the chocolate pieces, since it doesn't help at all.
- add a strap to the helmet?
- replace the skull with a more simplistic version?

**Comment by selaux** [comment]
I asked a friend of mine (who knows photoshop) to create a refined version of this logo, let's see what we're gonna get...

**Comment by JAsmine-ja2** [comment]
Cool. Definitely something better than me messing with paint :)

**Comment by selaux** [comment]
Here are the proposals:

![More logos.](https://cloud.githubusercontent.com/assets/848854/14043681/27bfb980-f287-11e5-92c2-cd53ee2b7dfa.png)

**Comment by derSteFfi** [comment]
i'm pro bottom left.

**Comment by lynxlynxlynx** [comment]
I'm for up-right, the cone ones are too subtle (imagine smaller sizes).

**Comment by derSteFfi** [comment]
that's a point. But then I actually think @selaux' idea before was better. Anyway selaux: please thank your friend for his (?) input :)

**Comment by JAsmine-ja2** [comment]
I vote for up-right.
I like how the shape of the ice here represents a helmet.

I also think the cones are too subtle.
The one up-middle reminds me of somethig like the Wolfenstein games.

I've gotta admit that I would probably like a mix betwenn the up-right version and selaux' idea even better.

**Comment by derSteFfi** [comment]
up right is fine for me.

**Comment by selaux** [comment]
I reported back to her and she agreed to do some more, les subtle versions. Then I would say we can decide. We can also combine the different cones/scoops.

**Comment by selaux** [comment]
Last propsal, lets vote!

![screenshot from 2016-04-06 18-51-44](https://cloud.githubusercontent.com/assets/848854/14325241/b5c9ce28-fc28-11e5-8f8c-1e66dedfd30d.png)

**Comment by lynxlynxlynx** [comment]
I would like it more cone-y, the rest is great. This is the same with a small perspective transform to narrow the bottom:
![ja2s](https://cloud.githubusercontent.com/assets/121515/14326127/dd0c4368-fc2c-11e5-82fe-24d079ee6a42.png)

**Comment by derSteFfi** [comment]
i'm fine with both since ice cream occasionally comes in rounder waffles. the skull itself (eyes, mouth, nose) is great. helmet is fine as discussed before. so half, half on those two from me.

**Comment by selaux** [comment]
I'm also for the more conic version, which means we have a decision. I asked her to improve it and send the svg. I also asked her if she wants to be included in the contributor list, and she said yes, so I will open a PR when this is done.

**Comment by derSteFfi** [comment]
Cool. On top, issue our thanks to her :)

**Comment by JAsmine-ja2** [comment]
Looks very promising. It'll be a great icon! :+1:

**Comment by selaux** [comment]
Final Version:
![logo-final](https://cloud.githubusercontent.com/assets/848854/14469382/9e4021c4-00e4-11e6-8373-fd7b81bb1c75.jpg)

Everybody ok with this?

**Comment by JAsmine-ja2** [comment]
Yeah! Looks very good. Be sure to thank your friend for putting some work into this!

**Comment by lynxlynxlynx** [comment]
Now ask her for a 32x32px favicon. *whistles*

It's great!

**Comment by derSteFfi** [comment]
very much.

**Comment by JAsmine-ja2** [comment]
I've got some questions regarding the logo:
- is there some kind of license for the logo?
- can it be modified and used in related projects like a mod for Stracciatella or the Mod DB profile?
- who is to be credited for it?

**Comment by selaux** [comment]
- It should be the same license as all the other source files (SFI Source Code license agreement)
- yes
- The design was done by Rebekka Bais

**Comment by lynxlynxlynx** [comment]
Why the restrictive license? There's no need to use that crap for original content.

**Comment by selaux** [comment]
Thats actually what I thought. Should we introduce a new license for new files / changes?

**Comment by lynxlynxlynx** [comment]
I don't think we can for derived code. Not sure if it matters for completely new, but GPL sounds nice. As for assets, I'd say CC-BY-SA or CC-BY.

**Comment by selaux** [comment]
Maybe we can use GPL for everything in `src/` since all of that seems to be new code not derived from anything else and implement new stuff there.

**Comment by lynxlynxlynx** [comment]
But we'd need to get tron's permission for any relicensing — we can choose only for our own stuff.

**Comment by selaux** [comment]
Does `src`contain work from tron? I thought it's only @gennady and @misanthropos work.

**Comment by lynxlynxlynx** [comment]
Partly right, it's mostly Gennady and one commit each by Czcibor and sam.
