### ISSUE TITLE
Use reactions for pull request merging

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#257]
Now that Github supports reactions for pull requests, we can use them for merging possibly? Proposal: When a PR has two or more :+1: by members of the team, it can be merged.

**Comment by lynxlynxlynx** [comment]
Dunno, would it help with anything? Now we merge on consensus and thumb-upping is just one way of expressing it, so forcing ourselves to use reactions sounds like overhead.

**Comment by JAsmine-ja2** [comment]
This is probably a good thing for teams with lots of members. Since we're only a handful here...

**Comment by selaux** [comment]
All right. We can revisit this when we have problems maybe.
