### ISSUE TITLE
What to do with `EXTREME_MEMORY_DEBUGGING`

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#258]
This is a follow-up for #252.

"EXTREME_MEMORY_DEBUGGING" turns on a beast that logs everything that happens with Memory.

Lets decide if we want to keep it, replace it or remove it.

**Comment by lynxlynxlynx** [comment]
I'm sure this was helpful when developing the game, but we have better tools if we ever need to lower the memory footprint or debug leaks (eg. from valgrind). So I'm for removal. Unlike AI, this area has little potential for changes too.

**Comment by derSteFfi** [comment]
I'm also pro delition. Looks like an overkill and very unlikely to be useful
