### ISSUE TITLE
Ideas on things to externalize

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#289]
Having certain aspects of the game externalized heavily increases moddability. Without externalized data, the possibilities are very limited (unless the modder touches the sourcecode).

In this issue, we can discuss what/why/how/... to externalize and create some sort of overview.

The first question should probably be if we think that externalizing data is a good idea (now or in the near future) or if we don't want to spend time on this.

**Comment by selaux** [comment]
Imho externalizing should be an essential part of this project. A few things I would externalize to improve moddability:

- Merc profiles (for all mercs and npcs)
- Dialogues

Notably externalizing is not the only thing that needs to be done to ensure moddability. Eventually some of the game logic needs to be moved into scripts, especially the story and quest related stuff. But this is talk for the future...

**Comment by JAsmine-ja2** [comment]
Other things that could be externalized are:

Arulcan Army:
- garrison groups (permanent presence in certain sectors)
- patrol groups (mobile squads moving around)
- army composition (details on the groups like number and probability of being replaced)

Mapping:
- sector names
- sector loadscreens
- cities (location, size, name ...)
- movement costs (moving from one sector to another)
- accessibility of setors ("borderland", ocean...)
- SAM sites (sector, location of the computer)
- air control table (the area that is defended by each SAM site)
- BR shipping destination
- Bloodcats (sectors, number, chance to encounter)
- Coolness (per sector)
- underground sectors (increase max. no.)

Items:
- all weapons (including "special" stuff like flamethrower) -> possibility to increase max. no. of weapons
- armor
- other items
- attachments (increase max. no.)

Misc. stuff:
- delivery methods of BR (cost, time)

Of course, the list could go on and on.

**Comment by lynxlynxlynx** [comment]
- chopper refuelling stations / bases (it's annoying that he can't use the meduna airport)

**Comment by derSteFfi** [comment]
Can we maybe make this a meta-issue and add achecklist with shared ideas to have a kind of todo-list?

**Comment by JAsmine-ja2** [comment]
> Can we maybe make this a meta-issue and add achecklist with shared ideas to have a kind of todo-list?

Don't know how to do this.

Anyway, scrolling through https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/Build/Tactical/Campaign.cc#L1042 gave me some more ideas on things to externalize:

- Possibility to increase stats with lvl 0 (zero) --- this may make the game too easy, but the original setting can be quite restricting
- No. of mercs (AIM, MERC) that can die while "on assignment" per difficulty --- same as above
- Progress %'s when Madlab, Mike and Iggy are made available --- having these earlier can make the encounters more helpful and in case of Mike more dangerous

**Comment by JAsmine-ja2** [comment]
Regarding  #173, it might be very helpful to externalize:

- items, that are always available regardless of their coolness vs player's progress 

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/Tactical/ArmsDealerInvInit.cc#L97

**Comment by JAsmine-ja2** [comment]
This issue has been superseded by #665
