### ISSUE TITLE
Tracona map in the map editor

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#29]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

Map editor shows the Tracona map instead of Arulco.
The map is taken from editor.slf - it is OMERTA.STI

Need to think about how to solve the problem.
Probably we can make Arulco map, include it into the distribution and show it instead of OMERTA.STI

Reported by https://bitbucket.org/alex_weil

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/29

**Comment by JAsmine-ja2** [comment]
Maybe leave it as it is (Tracona map in the editor) and just add the correct Arulco map as an optional mod to the game?
