### ISSUE TITLE
Support multiple data paths

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#290]
To ensure maximum moddability, I would change the way we load game resources (images, sounds, etc.). Currently all game resources are loaded from the data directory. For us to be able to provide patching functionality I would suggest changing the logic in the following way:

When a game resource is loaded (lets say from `Loadscreens` for example), locating it should
- First look for a `Loadscreens` library/dir in the current mod directory and look if it includes the resource then use that
- Second look for a `Loadscreens` library/dir in the `externalized/data` folder and look if it includes the resource then use that
- Finally look for the `Loadscreens` library/dir in the `data` folder and use the resource from there

This would allow the following things:
- Ship e.g. a free version of `editor.slf` mentioned in #30 with the application
- Allow modders to overwrite single resources of the game without the need to provide vanilla data, which is not allowed to be distributed, in their mods
- Allow us to provide resources that we might want to use somwhere (e.g. our shiny new logo)

BTW: This is somehow linked to https://github.com/ja2-stracciatella/ja2-open-toolset. My first goal for the open toolset would be to compose a free `Editor.slf` for Stracciatella

**Comment by JAsmine-ja2** [comment]
If I understand it properly, we could with this method also make sure that the official patches are applied to the game. So, the user wouldn't have to worry about the version of the game he has.

**Comment by selaux** [comment]
True, but this would require us to ship the patches with the application, which is illegal :smile:. But it would for example allow us to provide our own patches and you as a modder to e.g. change the face of a single merc (or is this already possible and I dont get it?)

**Comment by lynxlynxlynx** [comment]
We use multiple search paths and separation for unhardcoded and overriden files to great effect in GemRB. But I'd never call it patching. I think it will just confuse people, as you're talking about swapping assets, not modifying them.

**Comment by derSteFfi** [comment]
I like the idea, not only for modding but also for the editor for example. If documented clearly and properly, this is really good.

**Comment by ja2-derek** [comment]
I think this is all done.
