### ISSUE TITLE
ja2.ini: move to json

### ISSUE THREAD

**Issue by derSteFfi** [ja2-stracciatella/ja2-stracciatella#291]
If we move to a JSON we could drop the libIni as dependency. We had the idea somewhere else but I can't find it right now.

**Comment by lynxlynxlynx** [comment]
Come to think of it again, what would be the benefits? Because we could just as well dump json.

Inis are more readable to humans, support comments and one level of nesting (only one afaik). JSON can has no depth limits, but also no true comments. We don't appear to be using it more than two levels deep, which could still map to ini nicely.

**Comment by selaux** [comment]
Imho these files should only be touched by the launcher so end users will never see it anyways. Also JSON support other useful stuff like data-types, json-schema to validate stuff.

**Comment by JAsmine-ja2** [comment]
Letting the launcher handle json or ini files: +1
That is a huge step forward in user-friendliness :)

**Comment by lynxlynxlynx** [comment]
Copying @geca's note here:

> as of 2016-8-25 rapidjson supports comments. Using kParseCommentsFlag single-line and multi-line C-style comments are now possible so it seems no hacking would be necessary for game.json as long as we stay with rapidjson lib.

In other words, one problem less. :)

**Comment by geca** [comment]
How do you guys plan to deal with this issue? Just moving `data_dir` (plus resolution and full screen toggle as per #298) from `ja2.ini` to `game.json` or making a separate JSON file for it?

**Comment by lynxlynxlynx** [comment]
I'm for a separate file. It will be a persistent config we won't be able to update once it's in $HOME, so better keep it short and robust.

Maintaining a separate game.json would also mean people could pre-package configs for others.

**Comment by lynxlynxlynx** [comment]
Yeah. We should maybe print a big fat warning if we find only the ini and/or create a blank ja2.json with some instructive comments in.

**Comment by lynxlynxlynx** [comment]
The bundled rapidjson has been updated, so now any comments can be added freely.
