### ISSUE TITLE
Not all militia appearing and incorrect training level at SAM site.

### ISSUE THREAD

**Issue by LonCJ** [ja2-stracciatella/ja2-stracciatella#292]
Related to #159 ?

Sector should have 20 trained(blue) militia.   When going to tactical screen or during battle only 10 green militia are appearing.

Selecting autoresolve for the elite counterattack shows the correct number and training level of militia even with mercs present.  Have all mercs leave and then return to sector corrects the militia count/level.

![screen009](https://cloud.githubusercontent.com/assets/17031358/14499313/c5c4fbca-016b-11e6-9c13-cd87a6448a09.jpg)
![screen008](https://cloud.githubusercontent.com/assets/17031358/14499319/cfe24522-016b-11e6-8643-79f06e086eba.jpg)
[militia_bug2.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/217426/militia_bug2.zip)

**Comment by andreas12345** [comment]
I have the missing militia problem with 409ae2a in the same sector during the elite counterattack. Militia is shown in map, but there are zero militia in the battle in the tactical screen.

[SaveGame04.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/652581/SaveGame04.sav.zip)

**Comment by lynxlynxlynx** [comment]
Played through this bit with a fresh game — no such problems.
