### ISSUE TITLE
ContractBoxGlow(): empty

### ISSUE THREAD

**Issue by derSteFfi** [ja2-stracciatella/ja2-stracciatella#295]
this is one of the fixmes. I played around with it and wanted to ask for your opinions. This is ContractBoxGlow:
```C
static void ContractBoxGlow(void)
{
/* Why not?
	fResetContractGlow = FALSE;
*/
}
```
This Flag is initialised as false in ```Map_Screen_Interface.cc:245```. It is set to true in RestoreBackgroundFor{Contract, Sleep}GlowRegionList. (This looks strange and duplicated, but thats another issue)

It is never set to false again, except in ContractBoxGlow. Normally, the merc list in startegic looks like this:
![StratScreen](https://cloud.githubusercontent.com/assets/9593455/14767179/dd212214-0a1f-11e6-8311-daa89822ffc2.png)

Destination, Assignment and Sleep have a glowing red border when the mouse hovers over them.
When i reactivate the assignment to fResetContractGlow in ContractBoxGlow, the contract fields have the same glowing red border. Without the assignment, no glowing border is painted. Question is which way we prefer. Or what Vanilla did here.

**Comment by lynxlynxlynx** [comment]
For minute stuff like this, I'll always be for what makes the code simpler, cleaner, better.
