### ISSUE TITLE
setting options in ja2.ini 

### ISSUE THREAD

**Issue by MeisterP** [ja2-stracciatella/ja2-stracciatella#298]
Is it possible to set the options from https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/ja2_manpage#L13 in the .ja2/ja2.ini file? I'd like to start the game with `-res 1920x1080 -fullscreen` without altering the newly added .desktop file.

**Comment by selaux** [comment]
Currently this is not possible, I'm pro including this in the next (0.16) milestone though. Shouldn't be much work and the launcher will store it there anyway.
