### ISSUE TITLE
Free Editor.slf

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#30]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

In order to use the map editor, user should buy Unfinished Business version of the game and take Editor.slf from it.

Think about redrawing all the graphics from Editor.slf and including it into the distribution of JA2-Stracciatella.  Editor.slf from Unfinished Business will not be necessary this way.

It shouldn't be too much of the work since Editor.slf is quite small - only about 3.5 Mb.  It contains 79 sti files.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/30

**Comment by selaux** [comment]
I started creating a free editor slf using the [ja2-open-toolset](https://github.com/ja2-stracciatella/ja2-open-toolset) in a new repository: https://github.com/ja2-stracciatella/free-ja2-resources. First images were added, contributions (especially from artists) are welcome.

**Comment by lynxlynxlynx** [comment]
PR https://github.com/ja2-stracciatella/free-ja2-resources/pull/3 will implement this.
