### ISSUE TITLE
Idea - version no in main menu?

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#300]
Another cheap mockup from me :)
![main](https://cloud.githubusercontent.com/assets/17213795/15075861/e5b8d792-13a6-11e6-90d5-7e6593bf50ce.jpg)

Stracciatella could display the current version no in the game menu.
Of course, this would be purely eye-"candy" and had no real use, but I imagine it would make the Stracciatella-experience feel a bit more legit right from the start.

It's just an idea. What do you think?

**Comment by RinneT** [comment]
I'm with you on this one.
Only change proposal I have is to put the version number in the lower left corner, where it also is during the Intro.
