### ISSUE TITLE
integrate vxx's work

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#307]
In the old bb repo, wvx was working on porting minor improvements from 1.13:
https://github.com/wvx/ja2-stracciatella/commits/20160205

I remember there were some problems with the warning work, but the featurettes mostly look fine. We need to decide what to accept at some point, hence this reminder.

MOVED:
- mod: Import your old IMP merc into a new game; related/tracked in #32 
- recheck and extract extender fix #624

IGNORED:
WIP: extend pathing (needs more work)
WIP: skip sleep explanation (needs more work)
WIP: vehicle inventory (probably needs more work)
externalise: perpetual crepitus queen corpse (cheating)
mod: recruit militia to squad (scope)
Inventory Management Extras (several things at once, some wip, some odd; too much work)
mod: soldiers can have all skill traits (get *all* traits if you meet stat criteria)
mod: accurate aim circle (unreliable also from my experience)
allow realtime tactical saving in ironman (it was optional, but contradictory to the difficulty setting's purpose)
Wdelete-non-virtual-dtor (unresolved leaks)
Warray (looks pointless)

**Comment by derSteFfi** [comment]
most of it looks good at first glance. I'd definitly cherry pick the warning fixes and stuff like auto reload on alt+r (although I don't see the necessity to hide minimal, optional stuff like this behind a json switch).
What I also like is the enhancement to strategic view ('gui_extras') even though this changes the look obviously. vehicle inventory, modded ai and multiple interrupts are things i don't care for too much but I'm also not opposed to integrating them.

**Comment by JAsmine-ja2** [comment]
My humble opinion on this is:
As long as new features remain optional, everything is cool.
One additional aspect is that all the new stuff desperately needs to be properly documented.
Again, I draw a line to v1.13: TONS of new features, but the documentation is rather poor. Most documentation can even be found exclusively in the depths of the Bear's Pit. I'd go as far and say that there's probably only about two handful of people out there that know all the features of v1.13 and how to properly use them.
Of course, we are FAR from that situation and will propably never even get close.
But the core of the problem remains the same. If the game.json (or ini or whatever) has more than a few options, we need some kind of documentation. When we get to that point, I'll gladly help, of course.

**Comment by lynxlynxlynx** [comment]
my favourite is the multiple interrupt thing and not because I wrote it. It just didn't make any sense before.

Do you think just having lengthy-enough comments in the game.json is not enough for documentation?

**Comment by selaux** [comment]
I think lengthy comments would be sufficient (though json does not support them :frowning:). Additionally we could create a proper wiki which explains features, keymap and options in `game.json`.

**Comment by derSteFfi** [comment]
I'm very pro wiki, I already thought about bringing it up for hotkeys since I lose overview from time to time...

**Comment by lynxlynxlynx** [comment]
I've reviewed this up until "abstraction: getGamePolicy", oldest first. Redid some of the stuff, but this should all still be in the noncontroversial area. PR incoming.

IGNORED:
fix: autoreload crash with ROCKET_LAUNCHER (which item triggers this?)
fix: undefined behaviour: LOS.cc (already merged)
Wdelete-non-virtual-dtor (unresolved leaks)
Warray (looks pointless)

**Comment by JAsmine-ja2** [comment]
ROCKET_LAUNCHER is the LAW in-game. But I'm not aware of any crashes here.
This is connected to the ALT+R hotkey combination, that is part of the whole package?
https://github.com/wvx/ja2-stracciatella/commit/27ca6dcc309cdd5bfe7c5d410cea83d7d66045a4

**Comment by lynxlynxlynx** [comment]
Next part incoming, up until "accurate aim circle". Most things amended, so their switches are documented and DoD is taken into account.

TODO:
- use the new getGamePolicy abstraction where appropriate (no uses so far)
- merge SwitchHeadGear into a toggle, there's no need for two hotkeys
- merge new non-dodgy hotkeys into one game.json variable (eg. the ease-of-use ones we enable by default)

IGNORED:
allow realtime tactical saving in ironman (it was optional, but contradictory to the difficulty setting's purpose)
fix: undefined behaviour: LOS.cc (already merged)
Wdelete-non-virtual-dtor (unresolved leaks)
Warray (looks pointless)

**Comment by lynxlynxlynx** [comment]
Went through the rest. Even more subjective territory.

TORN:
- externalise: perpetual crepitus queen corpse (seems entirely cosmetic)
- noconfig: extra item combinations (would be ok with a switch, but that'd be annoying to implement — const array)
- mod: Import your old IMP merc into a new game

TODO:
- use the new getGamePolicy abstraction where appropriate (no uses so far)
- merge SwitchHeadGear into a toggle, there's no need for two hotkeys
- merge new non-dodgy hotkeys into one game.json variable (eg. the ease-of-use ones we enable by default)

IGNORED:
WIP: extend pathing (needs more work)
WIP: multiple interrupts (implemented properly instead)
WIP: skip sleep explanation (needs more work)
WIP: vehicle inventory (probably needs more work)
WIP: gui_extras (this is just the stat progress that we already merged a better way)
mod: recruit militia to squad (scope)
Inventory Management Extras (several things at once, some wip, some odd; too much work)
mod: soldiers can have all skill traits (get *all* traits if you meet stat criteria)
mod: accurate aim circle (unreliable also from my experience)
allow realtime tactical saving in ironman (it was optional, but contradictory to the difficulty setting's purpose)
fix: undefined behaviour: LOS.cc (already merged)
Wdelete-non-virtual-dtor (unresolved leaks)
Warray (looks pointless)

**Comment by wvx** [comment]
Thank you for going through all of this. I have not looked at it since. 

About the crepitus queen, it is not entirely cosmetic ;-)

Hope that it will not be too difficult to merge the remainder whenever I get a chance to play again. In a few weeks I will try and help if I can.

**Comment by lynxlynxlynx** [comment]
I guess you can somehow get more of that armor slime off her?

Thanks for tuning in, it'd be great if you could eventually look at "Inventory Management Extras" and split it into separate bits. And finish them if anything needs more attention.

**Comment by wvx** [comment]
Yes about the filling the jars - with IME enabled all your inventory jars would get filled automatically - and they stacked! (Such a cheater)

I will when I get a chance, maybe only around January. But I do hope too, much more now that you have done so much work. I like the game so much more with the extras.

I think IME was grouped together because of dependencies. If I can take anything out and make it optional I will try.

It is great all the work that has been done on the project and I hope to play the game again soon.

**Comment by wvx** [comment]
Finally got around to looking at it. The patches were copied and pasted over and some small changes made. The features were tested as I played last year, I still have to verify that everything works OK with all the progress that has been made. There might have been some items that were overlooked, for later.

If there is anything in IME that does not fit with the project I will try and separate it out.

**Comment by wvx** [comment]
added toggle to "extra item combinations"

**Comment by Manuel-K** [comment]
Does anybody want to include more of this in 0.16?

**Comment by lynxlynxlynx** [comment]
I'll look into it and at least the hotkey config needs a cleanup.

**Comment by lynxlynxlynx** [comment]
Ok, the last few things were rechecked and cleaned up, PRs open. Closing this.
