### ISSUE TITLE
New Game Mode Proposal: Dead is Dead

### ISSUE THREAD

**Issue by RinneT** [ja2-stracciatella/ja2-stracciatella#308]
Dear all,

I really enjoy playing the game and think that Iron Man mode adds nicely to the difficulty.
I have, however, often caught myself reloading and retrying a sector, especially when someone dies at the beginning of a fight.

To make the game even more of a challenge, I thought about a new game mode for a while, that doesn't allow just reloading after someone died. A sort of "Dead is Dead" game mode.

I've occasionally been playing around with the code to get the experience into the game and am wondering if there is general interest in taking such a mode into the main game.

What I have so far is quite little as I'm making slow progress, but as of now some features are present.

What is working:
- Select the new game mode: Dead is Dead from the init screen
- The game automatically saves:
 + On Exit to Desktop (Alt +x)
 + On loading of another savegame
 + On Exit to Main Menu
- Doing a Quick Save is redirected to the Dead Is Dead Save
- Savegame compatibility with Vanilla (Converts to Iron Man, thanks to the way booleans are handled in c++)

What I still have planned:
- [x] Save on "hard" Exit (Alt + F4 / Window closing)
- [x] Disable the regular Save Screen for Dead is Dead
- [x] New tab in the Save / Load Screen for Dead is Dead games
- [x] Allow the user to enter a Savegame name in the beginning of the game (Currently hardcoded as DiD)
- [x] New texts and translations for the mode (No clue how that works as of yet)

Also, as expected from my rather low experience, so far code quality is not the best.
I try to keep things mostly easily readable as I'm constantly changing stuff as I learn new mechanics of the game. Also I'm very likely doing a lot of stuff that works in the few scenarios I tested, but probably isn't a good way to do it. This is especially true for the whole Screen handling. (Which screen are we in etc.)

Open Questions:

What happens if you exit during:
- [x] an enemy turn
 + the game loads as "Enemy turn", but the player actually has control.
 + should be fixed to let the enemy turn continue. Make sure all APs etc. are correct.
- [x] a dialogue
 + The game seems to be stuck in an infinite loop (the 'waiting' clock is displayed)
 + My preference would be to start the dialogue from the beginning.
- [x] a cut scene
 + The cut scene continues, but is flawed. E.g. in Deidrannas palace you can not see into the room anymore (The roof is rendered).

**Comment by JAsmine-ja2** [comment]
I know that something like this was once mentionend by someone in the old BitBucket repository...

Ah, here it is: Take a look at this project!
https://steamcommunity.com/app/12370/discussions/0/619568793843283972/

**Comment by RinneT** [comment]
Thanks a bunch JAsmine, very nice find!
I've downloaded the mod.
The author mentions that it is based on Stracciatella, however he seems to only supply the compiled binaries. I've been looking for the sources but can't find them. That means anyone who uses it wouldn't get the benefits of the recent development.

Also he unfortunately only compiled it for windows (I'm on linux).
I'll take a look if I can find anything in the old bitbucket repo.

**Comment by JAsmine-ja2** [comment]
I guess I was wrong and the mod was only mentioned at the Bear's Pit Forum:
http://thepit.ja-galaxy-forum.com/index.php?t=msg&goto=337613&&srch=roguelike#msg_337613
Maybe you should get in contact with arnodick?

**Comment by RinneT** [comment]
I think I'll continue my implementation.
I'm learning a lot this way and feel like I'm making good progress at the moment.

I see that arnodick is on reddit though. I'll get in contact with him over there.
Thank you :)

**Comment by JAsmine-ja2** [comment]
And btw:
I really, really like your idea. The new gamemode will be a nice addition to JA2 and I will definitely play with it once it's done.
When I started JA2 back in the old days, I played with lots of quicksave/load abuse for a long time. It wasn't until much later that I realized how much more fun the game was without quicksave/load spamming.
Then I started playing some Ironman and it was very nice and a good challenge.

Since your new gamemode not only affects combat and life and death of the mercs, but the whole game (including stretegic decisions and stuff), maybe you want to consider a name which better reflects this?
Like "Super Ironman", "Rogue-like", "Marathon-Mode", "Grandmaster" or something? Just some quick ideas...
And again: nice idea!

**Comment by RinneT** [comment]
Thanks :)
I've left him a message, let's see if he shows by.

I completely share your experience.
I have also pondered about the name for a very long time. It started off as Iron Man Plus because I couldn't come with anything at all. I'm very open to collect ideas. I think depending on how this goes I'd put it up for a vote.

For now I'm keen on making progress.
I have actually managed to do the texts / translations (for english and german at least), much to my surprise it wasn't difficult at all.

**Comment by RinneT** [comment]
Save on Alt + F4 works. Actually just had to move the function to a different location.

**Comment by RinneT** [comment]
Save Screen is disabled for Dead is Dead

**Comment by RinneT** [comment]
Wrote down some open questions I had before going to sleep in the original post, but then decided to check on them immediately anyways.
So there is some critical behaviour in border cases. I hope I'll get to handle them.

Further unusual situations anyone can think of are welcome.

**Comment by JAsmine-ja2** [comment]
Maybe it would be a good idea to make the game create automated savegames which can be accessed if something went wrong ("unusual situations"). So, if the normal "dead is dead" save is messed up, the player can revert to a slightly older save.
There are many unpredictable situations. Impossible, to adress each individually.

Some ideas:
- the automated saves could be generated every n minutes or hours.
- there could be three automated save slots through wich the game cycles (1,2,3,1,2,3,1,2,3...).
- the automated savegames are inaccessible from within the game to reduce abuse.
- the automated savegames can only be loaded if the user renames them or moves them in the JA2 folder

I think v1.13 has automated savegames. Maybe, one could look into how they realized it?

**Comment by RinneT** [comment]
Hi JAsmine,
A backup system was definitely something I wanted to implement. Shouldn't be too hard.
I think I'd go for the solution to move them to a different folder.

Good hint with 1.13

I also rethought the saving system in general and think a few very simple changes can prevent most situations:

* Have predefined save situations
 * E.g. we could save when the player ends a round. The savegame would just be called before the turn is terminated. That way the player can't abuse the system e.g. by reloading when all APs are used up. He could, however quit when he has accidentally pressed D (happens to me more often than I like to admit). Same goes for the beginning of a player round.
 * We could also save when the cutscene dialog pops up, or a character dialogue starts.
* Additionally we could extend the CanGameBeSaved() function to cover more situations for DiD
 * We could introduce global properties, e.g. isDialogue, isCutScene, isNonPlayerTurn. They are set when certain situations start and unset when they end.
 * If either of these variables is true, the game cannot be saved, even on exit. However we can be sure that the load reverts to the time when the user last had control.

Sorry that I didn't continue for a while. Vacation ended and couldn't motivate myself after work.

**Comment by RinneT** [comment]
"Finished" the gui work. The "DiD" Button in the Load Screen to switch tabs looks ugly but is just meant to be functional as of now.

With the current implementation the following works:
- Start new Game in DiD mode
- Select a savegame slot in the "Dead is Dead" Tab.
- Automaticall saving the game to that slot - other slots cannot be accessed / The Save-Screen is disabled for the mode.
- Quicksaving to the correct slot via Alt + s
- Switching between normal games and "Dead is Dead" games in the load screen
- Loading the game
- New texts / translations describing the new game mode are displayed

In general, with a bit of care to avoid exiting at unspecified situations, the game mode should already be playable. Other game modes should work as expected, though I didn't yet check for bugs.

Next steps will be to implement a more intelligent savegame mechanism, a backup system and then to replace the ugly button in the load screen with a proper tab.

**Comment by RinneT** [comment]
The game mode is in a very usable state now. Basically only aesthetics and code documentation are left.
I managed to play a game until Day 22 with no problems (After having started like seven games before and getting all mercs killed by day 5 or so.)

I came along one bug so far which isn't related to the game mode. That was an infinite loop caused by having one merc open an action dialogue (e.g. break open a door / use key / whatever) and have another merc start a conversation at the same time. In that case I had to fall back to the backup.

Difficulty is extremely high and game progression very slow.
If anyone would like to try it I'd be happy. Be aware, however, that the game mode was forked quite a while ago and contains bugs that are already fixed in the main branch.

**Comment by RinneT** [comment]
The game mode is now feature complete.

I'd be willing to discuss better names right now.
"No mercy" has been floating around my head for a bit, though I liked the Grandmaster and Marathon proposals as well.

**Comment by JAsmine-ja2** [comment]
First of all, congratulations on your nice mod! I will definitely play with this new game mode and the idea is just great! :+1: 

Now some brainstorming on a possible name:

**Dead is dead** - as I wrote before, this name doesn't reflect the fact, that this game mode has an impact on the whole (!) game and not only on life and death of the mercs. Therefore, it's not a good one.

**Grandmaster**

**Marathon** - this is not a really fitting describtion, because you can still break the game into many, many small sessions and you can stop playing almost anytime.

Something like **Realistic** or **Reallife** comes to my mind, but it collides with the other gameplay setting (Realistic vs. Sci-Fi) and therefore probably isn't a good idea.

**No second chance** or the other way around **One chance** or **Only one chance**?

Technically, this game mode is a core-feature of so-called **Rogue-like** games. It could also be the name of this game mode.

**Hardcore**

...that's it for the moment.

**Comment by selaux** [comment]
I merged the initial PR. Do we still want to discuss about the name or is everyone fine with dead is dead?

**Comment by lynxlynxlynx** [comment]
The code is littered with it, so I'm for leaving it be.

**Comment by derSteFfi** [comment]
congratz :)

**Comment by selaux** [comment]
Yeah, nice one. Will close now 👍

**Comment by lynxlynxlynx** [comment]
@RinneT can you write a short blurb for our website "feature" section?

**Comment by RinneT** [comment]
Thanks a bunch all, for the support as well.
I'll write a bit up. I have started a new game on Monday and noticed some major bugs that weren't there before the rebase, though.
Mostly game crashes in the Map Screen, when arriving at an occupied sector and hovering the mouse over the Retreat button. The game doesn't remember where to retreat to and crashes.
Also currently getting a crash in tactical view in a fight. Similar error. Apparently a soldiers path data contains invalid data resulting in a crash.

My first guess was on #389 as it was introduced recently and affects the code responsible for crashing. Really just a wild guess though, and at least the path problem looks super complicated. The function it happens in is 1.4k loc

**Comment by RinneT** [comment]
@lynxlynxlynx 
I've had this lying around for quite some time and can't think of many ways to improve it, though I'm not fully happy with it, but won't make an artistic project out of it now. If anyone can come up with a better description feel free to alter it.

> Dead is Dead is a new gamemode for players looking for a new challenge, and who think IronMan doesn't cut it just yet.
With the Dead is Dead mode the game takes the burden of saving and savegame management from your shoulders so you can concentrate on the important bits.
You select one savegame slot at the beginning of a new game, and the game will stick to that slot throughout your playthrough.
The game will also make sure to save before you leave, so you can rest assured to always pick up at where you left.
With dead is dead there is no going back. If mercs die, there is no way of bringing them back. If you make a mistake, there is no way of reverting it.
So be careful, play it safe, and prepare to be frustrated.

I also realize I haven't been here in a while. Very nice to see the new frontpage :)

**Comment by selaux** [comment]
Sounds nice 👍 , lets put that on the homepage once `0.16.0` is released.
