### ISSUE TITLE
Windowed mode: move to the next sector in tactical view.

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#314]
When playing the game in windowed mode, I find it very hard to enter the next sector in tactical view. You need to move your mouse cursor to the edge of the screen. However, the it's extremely hard to get the "leave sector" cursor, because the mouse ends up leaving the JA2-window.
There is only a very, very small region in the window where you can get the "leave sector" cursor before actually going out of the window.
If we had an option to trap the mouse cursor inside the window when playing in windowed mode, it would be a big help!

**Comment by derSteFfi** [comment]
I'm contra trapping, but I have another solution:
In Build/TileEngine/RenderWorld.cc:2411 and following:
```C
		else
		{
			if (fOutRight  && gusMouseXPos >= SCREEN_WIDTH - 1)  gfUIShowExitEast  = TRUE;
			if (fOutLeft   && gusMouseXPos == 0)                 gfUIShowExitWest  = TRUE;
			if (fOutTop    && gusMouseYPos == 0)                 gfUIShowExitNorth = TRUE;
			if (fOutBottom && gusMouseYPos >= SCREEN_HEIGHT - 1) gfUIShowExitSouth = TRUE;
		}
```
this limits the area for the exit symbol to 1px. We could simply increase this to 5 or something. I'll wrap together a PR. (I already tried this out about a month ago but didnt mind the problem too much, so i threw it away again. Since someone else stumbled here too, we can just test it)

**Comment by lynxlynxlynx** [comment]
I'm pretty sure I saw that 1 made into a named constant and increased somewhere already (maybe vxx' branch?).

I thought sdl apps trap the mouse by default if you press scroll lock (iirc with ctrl).

**Comment by derSteFfi** [comment]
ok, this is a bit more messy.
First, for the cursor to show, there needs to be a scroll in action. I'm currently searching for the spot where the number of pixels at the edge for a scroll to be issued is defined. I think the number of pixels that issue a scroll and the number of pixels that show the exit cursor should be the same (as far as i can tell, both are 1 right now).
Second, in Build/Tactical/Handle_UI.cc:635:
```C
		if ( gfUIShowExitEast )
		{
			gfUIDisplayActionPoints = FALSE;
			ErasePath();

			if (OKForSectorExit(EAST_STRATEGIC_MOVE, 0))
			{
				if ( gfUIConfirmExitArrows )
				{
					guiNewUICursor = CONFIRM_EXIT_EAST_UICURSOR;
				}
				else
				{
					guiNewUICursor = EXIT_EAST_UICURSOR;
				}
			}
			else
			{
				guiNewUICursor = NOEXIT_EAST_UICURSOR;
			}

			if (gusMouseXPos < SCREEN_WIDTH - 5)     //this one is important!
			{
				gfUIShowExitEast = FALSE;
			}
		}
```
This is for the situation where you move the cursor a bit back, out of the scrolling area. I'm not sure about it's effect, I don't have the feeling the area where the cursor stays on 'exit mode' is 5px wide, but it reads like this. If that is the case, we should make that number match our number of pixels imho.

**Comment by derSteFfi** [comment]
Found it. I would create a PR but github doesn't have my branch although my git says it's there at remote/origin. I'm gonna wait a few minutes and see if it pops up...

**Comment by chmallon** [comment]
> If we had an option to trap the mouse cursor inside the window when playing in windowed mode, it would be a big help!

This is why I implemented that pressing Scroll lock captures the mouse in the window.

> I thought sdl apps trap the mouse by default if you press scroll lock (iirc with ctrl).

No, I explicitly added this in v0.3. (see Changelog)

**Comment by lynxlynxlynx** [comment]
Hey tron, renewed your interest in ja2? :)

**Comment by chmallon** [comment]
I just lost it again after seeing what nonsense is going on in #544.
