### ISSUE TITLE
Bad Performance in OS X

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#319]
Especially when playing on high resolutions the performance on OS X is low. While playing in 640x480 works fine, 1024x768 already shows performance issues (on a brand new Macbook Pro).

Maybe this will be fixed by SDL2. Another approach is to have a look at existing performance improvements for OS X and see whether they really improve or hurt performance.

**Comment by derSteFfi** [comment]
sounds like a SDL issue, but maybe also libboost can help. we should revisit this when we have the big stuff for 0.16 merged...

**Comment by selaux** [comment]
Just tested on the SDL2 branch, it's fixed there

**Comment by selaux** [comment]
Closed by SDL2.
