### ISSUE TITLE
Any objection to removing WITH_MODS?

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#322]
We manually set the define, so it has no effect. The code it supposedly toggles enables the use of the -mod switch to use a mod and nothing else. So it doesn't affect vanilla behaviour if you don't want any mods.

**Comment by derSteFfi** [comment]
I'm pro removing. Unneccessary 'complexity' in my eyes. Hiding -quicksave and -domaps (???) behind JA2BETAVERSION is also not neccessary imho.

**Comment by lynxlynxlynx** [comment]
Ok, thanks, I'll wait for the logging merge then, since there's logging in the context and an error in a message.
