### ISSUE TITLE
people dancing/spinning out of the screen

### ISSUE THREAD

**Issue by Popsch** [ja2-stracciatella/ja2-stracciatella#328]
If you load the attached Quicksave, then you will see Fox and a civilian dancing out of the screen in continuous pirouettes. 
[QuickSave.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/290143/QuickSave.sav.gz)

**Comment by vancv** [comment]
Having the same problem.

**Comment by selaux** [comment]
@derSteFfi Is it possible that this has to do with the direction type fixes from #277?

**Comment by derSteFfi** [comment]
surely seems like it.
The pathing data is already corrupt within the savegame (I breakpoint'd while loading Fox' profile). Is it possible this savegame was create while testing on the directionTypeFixes branch? It seems the data is off by one byte:
```
(gdb) print s->usPathingData 
$14 = "\n\277\177\000\204\262", '\000' <repeats 23 times>
```
This is somewhere during the load process.
```
(gdb) print d
$8 = (const BYTE *) 0x7fffffffa918 "\006\n\006\277\005\177\005"
```
This is at the begining of the extraction of usPathingData. Note that 6 and 5 are reasonable values for Pathingdata, the rest is not. We're missing the reasonable values by on byte and end up with garbage.

Was this savegame created on a different architecture? Different endianess maybe?

**Comment by Popsch** [comment]
It was created on Linux.

**Comment by derSteFfi** [comment]
Hm, proposal: We do plausibility checking for ```usPathingData``` during load. If we see values outside [0,7] we just put 0s in and set ```sDestination``` and ```sFinalDestination``` to the soldiers current location.
The mentioned soldiers pathingdata is lost this way, but I'd say thats not a big harm. If we would want to be really kickass we could also try to correct the pointer by one and retry (would solve the problem in this particular case)

**Comment by selaux** [comment]
@Popsch Was the save created on the same machine as you loaded it on?

@derSteFfi We could do this, but I would focus on finding the issue first.

**Comment by selaux** [comment]
Can you try with the branch from #353? The loading might still be buggy but the error should hopefully not occur anymore with new saves. Otherwise we might need to investigate some more.

**Comment by selaux** [comment]
Anyone has this issue with current master? Otherwise I will close this.
