### ISSUE TITLE
Build fail, MSVC, related to boost changes

### ISSUE THREAD

**Issue by wendles** [ja2-stracciatella/ja2-stracciatella#329]
Off current git, the following file-not-found errors occur on MSVC, breaking the build:
boost/config/abi/msvc_prefix.hpp
boost/mlp/aux_/preprocessed/plain/or.hpp
Build/Utils/Debug_Control.cc

I'm unsure how Debug_Control.cc fits in here, but it's not present in the tree. Maybe it's erroneously listed inside the SLN?

It may be necessary to bring in any msvc_*.hpp as well as the entire ./mlb/aux_/preprocessed/plain/ directory to make MSVC happy.

**Comment by selaux** [comment]
Will have a look into it.

**Comment by derSteFfi** [comment]
Debug_Control was removed in the logging rework. Removing it from the SLN should solve that.

**Comment by selaux** [comment]
Can you retry with the branch from #330

**Comment by wendles** [comment]
Verified fixed
Windows 10, MSVC 2015. Debug and Release configurations checked.
