### ISSUE TITLE
xcodeproj updates needed

### ISSUE THREAD

**Issue by wendles** [ja2-stracciatella/ja2-stracciatella#331]
After the debug rework, the following need to be added to the xcodeproj file for Mac to build using Xcode.
Build/Utils/Debug_Pages.cc
Build/Utils/Debug_Pages.h

**Comment by selaux** [comment]
@lynxlynxlynx @derSteFfi What about moving to a different build system. E.g. cmake can generate msvc and xcode solutions as far as I know. This way we would not need to keep them up-to-date manually.

**Comment by lynxlynxlynx** [comment]
I agree. We've done the same in GemRB and it seems to work fine. We do maintain a separate copy of the xcode project, since it's trickier and only one dev is using it (and never tracked it down).

But don't let the idea block this pr.

**Comment by derSteFfi** [comment]
I thought about that before, but didn't want to make a fuzz. CMake is fine for me.

**Comment by selaux** [comment]
So this issue should be closed with the branch from #334. I will open another one for the build system.

**Comment by wendles** [comment]
Verified fixed, Mac OS X 10.11.5, Xcode 7.3.1.

I am about to fill out one last issue on this, regarding the architecture settings in the project.
