### ISSUE TITLE
smacker.h not found [Mac OS X, Xcode]

### ISSUE THREAD

**Issue by wendles** [ja2-stracciatella/ja2-stracciatella#332]
After fixing #331 build will fail due to smacker.h not being found.

The project file is trying to find it in Build/sgp but it appears it may be moved to _build/lib-smacker?

If so, it may just require a path tweak in the xcodeproj.

**Comment by selaux** [comment]
Please try again with the branch from #334.

**Comment by wendles** [comment]
Verified fixed, Mac OS X 10.11.5, Xcode 7.3.1.
