### ISSUE TITLE
Move to another build system

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#335]
Rationale:

- Keeping the makefile structured is difficult since it is huge
- We also have other build projects to maintain (xcode, msvc)

Proposal: CMake

- Can generate xcode and msvc solutions
- Can find out if necessary libraries are installed
- Cross-platform builds through toolchains

**Comment by wendles** [comment]
I know I have little to do with the project beyond bug reports (hopefully that will change) but my vote is yes. Maintaining the various project files is an endless hassle.

**Comment by derSteFfi** [comment]
agree too. I have no experience with CMake, so I'm strongly for it (I can learn something new then :) )

**Comment by selaux** [comment]
You can have a look at the `cmake` branch, most of the stuff already works (flags, releases). It also uses cpack which allows us to easily create release packages.

Missing stuff:
- Creating solutions for msvc and xcode (or they dont build)
- OS X release building
- Contributor list rebuilding

Please notify me of other missing parts, so I can include them.

NB: With `cmake` out-of-source builds are prefered. So run cmake from outside (or inside a subdirectory) of the source dir, e.g. `mkdir _cmake_build && cd _cmake_build && cmake .. && make`.

**Comment by lynxlynxlynx** [comment]
* make uninstall

**Comment by selaux** [comment]
True. According to [cmake documentation](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F) this can either be done by including a snippet or by doing `xargs rm < install_manifest.txt`. What do you think is the better option?

**Comment by lynxlynxlynx** [comment]
Using cmake-native code will ensure portability:
https://github.com/gemrb/gemrb/blob/master/cmake/cmake_uninstall.cmake.in

**Comment by selaux** [comment]
Just a status update from me:
- uninstall should work
- rebuilding contributors list should work
- Visual Studio Solution can be compiled

Next steps:
- BSD compilation checks (I will add them to the build-releases step, so this step also ensures that bsd builds are ok)
- macOS stuff

**Comment by selaux** [comment]
The points listed above are done. Things still to do:
- Releases contain files from dependencies that are built with cmake
- Update `COMPILATION.md`
- deb packages are reported as not complying with specs
- grouped sources in xcode and msvc solutions
- Test releases

**Comment by selaux** [comment]
So a short update from me, that requires some input from you guys. I've two issues that can be solved in several ways and I'm not sure what is the right one:

###### Releases contain files from dependencies that are built with cmake
This can be solved by
- Removing the INSTALL commands from the dependencies `CMakeLists.txt`
  - Drawback: This needs to be done with each dependency update of dependencies that come with a `CMakeLists.txt`, which can be easily forgot.
- By writing a custom `CMakeLists.txt` in `_build`
  - Which then needs to be maintained by us and reflect changes to the dependencies build process.

###### Including Headers in xcode and msvc solutions
This can be solved by
- Listing the headers in the project source
  - Drawback: Doubles the amount of source files listed
  - Drawback: Forgetting to add the header to the source files does not actually break the build
- By globbing for headers and including them in the source
  - Drawback: Adding and removing headers might not be correctly registered by cmake, so it wont run automatically on build

**Comment by lynxlynxlynx** [comment]
1. Option A sounds better and we can do it in the top CMakeLists.txt file (akin to sed -i //d) to avoid the need for keeping the sub ones up to date.
2. This is something the generator doesn't do for us?

**Comment by selaux** [comment]
I will do Option A then. For 2 it seems like there is no other options.
