### ISSUE TITLE
On the Mac project branch, need x86

### ISSUE THREAD

**Issue by wendles** [ja2-stracciatella/ja2-stracciatella#344]
The project file (Xcodeproj) on the Mac side is currently set to build an x64 target.

If this is kept, linking will fail on the supplied libSDL libraries.

Changing the project to build x86 instead makes everything happy again.

(Build Settings > Architectures in Xcode, while viewing properties for JA2-Stracciatella project file)

**Comment by lynxlynxlynx** [comment]
this was changed to 64-bit with the last xcode pr.

**Comment by selaux** [comment]
Yes on my machine the x86 build did not work, not sure why. The xcode solution will be deprecated with the cmake build system anyway, so I would not put a lot of effort into fixing this.

**Comment by wendles** [comment]
Ok. Personally I'm good with closing as wontfix. In the meantime it's trivial to adjust the architecture if/when necessary.
