### ISSUE TITLE
Document new features

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#345]
It would be nice to have all new features (e.g. hotkeys) of JA2 Stracciatella documented. The documentation should be clear, complete and easily accessible. Maybe it would be best to ship a pdf file as some sort of manual for the new features?
I could write this documentation.

**Comment by lynxlynxlynx** [comment]
The major stuff is already mentioned in the main page. It should always have all the best _news_. The rest I think is ok on the wiki, so there's no version control hassle. Ideally all new feature additions would contain updates for the docs, but if we don't manage that, it's a task for release prep-time.

json doesn't support comments per se, but that can be hacked around (already discussed somewhere). If we pimp game.json that way, the main stuff will already be handled and we can just link to the file. We'd avoid synchronisation issues that way. For the rest, why not the wiki?

**Comment by selaux** [comment]
@JAsmine-ja2 I've discovered some of the work you did on moddb (which is awesome btw) and we could integrate that into the website. More documentation is always useful imho and the docs currently provided by the website could indeed use some improvement. Can you write some markdown docs and make a PR to the website repo (https://github.com/ja2-stracciatella/ja2-stracciatella.github.io)? I can give you some support on how to do this if you want.

**Comment by JAsmine-ja2** [comment]
Hey, I started working on a PR with some docs for the website. And thanks for the praise on the Mod DB profile ;)

**Comment by JAsmine-ja2** [comment]
[Jagged Alliance Timeline.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/439076/Jagged.Alliance.Timeline.zip)

Okay, this isn't a PR and no markdown text. But I came up with this and wanted to know what you guys think of it? This kind of stuff could be useful and entertaining info on the website.

Note: It's not fully fleshed out, yet. Also, the graphics are heavily compressed to save size.

**Comment by lynxlynxlynx** [comment]
Looks interesting, something for a separate JA2 history page. Btw, the original ja2s wasn't a patch, it was standalone from the start like all other porting efforts.

**Comment by JAsmine-ja2** [comment]
Yeah, a history page for JA. There might be some inaccuracies in this. So if you would like to point out more things, I will gladly look into it and try to correct them.

**Comment by JAsmine-ja2** [comment]
I know I'm asking stupid things here, but anyway...

I'm trying to make a PR for the website.

I have created something:
https://github.com/JAsmine-ja2/ja2-stracciatella.github.io/tree/JAsmine-ja2-patch-1

which is supposed to add a new history page
https://github.com/JAsmine-ja2/ja2-stracciatella.github.io/blob/JAsmine-ja2-patch-1/history.md

Now, I don't know what/how I'm screwing up, but I don't know, how to go on with making a PR...

**Comment by selaux** [comment]
You should be able to go to https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/pulls click "Create Pull Request". Then select `ja2-stracciatella/ja2-stracciatella.github.io` as base fork and your branch as head fork. Hope that helps.

**Comment by JAsmine-ja2** [comment]
I can't select 
ja2-stracciatella/ja2-stracciatella.github.io
as base fork. 
I can select
JAsmine-ja2/ja2-stracciatella.github.io
as either base fork or head fork.
Most probably I'm doing something wrong. Will tinker around a bit more...

**Comment by selaux** [comment]
I just invited you to access the https://github.com/ja2-stracciatella/ja2-stracciatella.github.io repo. There you can do the changes again and then for sure can create a PR.

**Comment by JAsmine-ja2** [comment]
I _think_, I've created a PR. ;)

**Comment by geca** [comment]
@lynxlynxlynx as of [2016-8-25](http://rapidjson.org/md__c_h_a_n_g_e_l_o_g.html) rapidjson supports comments. Using `kParseCommentsFlag` single-line and multi-line C-style comments are now possible so it seems no hacking would be necessary for game.json as long as we stay with rapidjson lib. If this is a go, ja2-stracciatella/externalized/readme.txt should probably be removed, with comments being added to ja2-stracciatella/externalized/game.json.

**Comment by lynxlynxlynx** [comment]
Cool, thanks, no need for dummy fields! A bump is in order then. As for the readme, only the game.json part should be removed. A sort of overview would be handy as well, so it's easier for modders/tweakers to start looking at.

**Comment by geca** [comment]
No problem. :) You're right, there's other stuff besides game.json in readme.txt. 

A quick checklist:
- [ ] Bump rapidjson lib to 1.1.0 so we can use comments
- [ ] Add comments to game.json
- [ ] Remove game.json section from readme.txt

**Comment by lynxlynxlynx** [comment]
Ok, I've split this mess of an issue into parts and will be closing it.
The hotkeys/misc website stuff is at https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/issues/4
The history part is already in a PR on the website repo.
The game.json part is now at https://github.com/ja2-stracciatella/ja2-stracciatella/issues/401
