### ISSUE TITLE
GOG and Steam

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#357]
On the ModDB page, someone wrote

> gog version requires a filepath change to work

I honestly don't know, what he means and he didn't write anything else. I was wondering, if someone know how/if Stracciatella works with JA2 from Steam and GOG. Maybe, information on running Stracc with GOG and Steam should be included?
I don't have JA2 on GOG or Steam and can't test.

**Comment by lynxlynxlynx** [comment]
I'm using the GOG one without trouble and don't remember changing anything. You have to set the path to the data in ja2.ini, but that's true for all installs.

**Comment by selaux** [comment]
I'm using different steam versions (I think I tried with JA2, JA2 Gold) and no problems either. Maybe a language specific issue?

**Comment by Manuel-K** [comment]
I assume that the author of the comment refers to the ja2.ini entry.

**Comment by lynxlynxlynx** [comment]
If we can't get a clarification, this should just be closed as invalid.

**Comment by derSteFfi** [comment]
agreed.

**Comment by JAsmine-ja2** [comment]
Okay, thank you for your input. I didn't really expect this to be a severe issue. The person was probably referring to the data-dir path in the ja2.ini .
