### ISSUE TITLE
Folder renames

### ISSUE THREAD

**Issue by derSteFfi** [ja2-stracciatella/ja2-stracciatella#360]
So, as discussed in the cmake PR, we all would like to change a few things regarding the folder structure. I copied Selaux' last list here as a starting point. I'm highly unsure about how git works with renamed files and rebasing changes onto that, so if we are unsure, we should do this as soon as nearly no PR is open....
- [ ]     _build/lib-\* -> dependencies
- [ ]     _build/buildboxes -> release
- [ ]     the rest of _build -> assets
- [ ]     externalized -> assets/externalized
- [ ]     Build -> src/game
- [ ]     src -> src/externalized
- [ ]     sgp -> src/sgp

**Comment by lynxlynxlynx** [comment]
I don't think it has much problems, though digging through logs becomes more tedius (--follow and -M). But yes, something for after the big PRs.

**Comment by selaux** [comment]
What do you think about removing the buildboxes after building releases through travis?

Advantages:
- Less code clutter
- Less maintenance effort

Disadvantages:
- No i386 deb can be built anymore
- We cannot ensure builds on *BSD anymore

**Comment by Manuel-K** [comment]
Another question: Is the examples subfolder in _build/lib-slog necessary? I does not provide more information than the example in the readme.

**Comment by selaux** [comment]
Agreed. Also slog is less of a dependency than tightly coupled with the project itself through tags...

**Comment by Manuel-K** [comment]
How about _build/lib-slog -> src/slog?

**Comment by Manuel-K** [comment]
I've tested the proposed changes in #455. It does look nicer, but I'm not completely happy. I've kept lib-slog in dependencies for now. 

I'd propose to move rust->src/rust and move the contents of its src subfolder one level up (i.e. to src/rust as well). Also _unittests->unittests.

**Comment by selaux** [comment]
I would keep the rust folder separate since it's an own project with its own build system. The rest looks fine. Only for `_unittests` I would rather use `assets/unittests`.

**Comment by derSteFfi** [comment]
agreed. for the buildboxes I'd keep those we can't replace with a travis build for now. i386 sounds like something we could set up in travis and for *BSD we could check whether anyone uses it. We currently do not offer a *BSD tarball anyway but we could and see whether anyone downloads it.

**Comment by Manuel-K** [comment]
`assets/unittests` sounds very good and seems to be the obvious choice. After you wrote it I'm not sure how I could have missed that.

I've missed some necessary changes in CMakeLists.txt – I will (hopefully) fix it and implement the other changes this afternoon.

**Comment by Manuel-K** [comment]
Okay. I hope that I haven't missed something in `CMakeLists.txt`. The game does compile and run on Linux. Copying the externalized folder was previously broken; that's fixed. 

Untested: installation, unittests (should work, I've taken care of the path change) and other operation systems.

I've flattened the slog folder while moving and dropped the `src/` prefix in all include directives. I think it's easier this way. Any objections?

**Comment by Manuel-K** [comment]
The different license of `src/slog/*` should probably be mentioned in `README.md`…

**Comment by Manuel-K** [comment]
Another remark: `dependencies/readme.txt` is incomplete and outdated.
