### ISSUE TITLE
Cant play through sector (law fabric)

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#361]
I compiled ja2 with the new cmake and tried to continue the mission to take over the law fabric.
ja2 segfaults after a number of battle rounds - and I tried several times now.

I noticed some things:
1. It takes quite long for the AI to make its move.
2. before the segault I get a grapical glitch... in the fight i throw any kind of smoke on the other side of the fence and it gets a partial "mirror" on my side.

Im sorry I cant supply a SavedGame because of the IronMan mode..  

[SavedGame06.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/403421/SavedGame06.zip)

[ja2.log.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/403415/ja2.log.zip)

**Comment by selaux** [comment]
The reason why the AI is that slow:

```
2016/07/07 14:51:53 ERROR   [AI              ] Enemies on team 1 prompted to go on RED ALERT!
2016/07/07 14:52:25 ERROR   [AI              ] Aborting AI deadlock for 21. Please sent LOG file and SAVE.
2016/07/07 14:52:46 ERROR   [AI              ] Aborting AI deadlock for 20. Please sent LOG file and SAVE.
```

Not sure where that comes from yet. I started a new game and it seems to happen in Omerta as well.

**Comment by selaux** [comment]
Can you retry using current master? AI Deadlocks should be fixed. Not sure about the other one though...

**Comment by misanthropos** [comment]
Much better - I managed to get a Deadlock in a different games some days ago but that happened only once.
