### ISSUE TITLE
Corrupted savegame: Skyrider spinning, enemies revealed

### ISSUE THREAD

**Issue by geca** [ja2-stracciatella/ja2-stracciatella#367]
Probably same as #328. Load "SaveGame01.sav" from the attached archive. Switch to tactical view. Skyrider will get spinning and all of the enemies are revealed. Might be reproducible through a prior savegame ("SaveGame02.sav" in the archive) I did in Skyrider sector.

The savegames were made using ja2-stracciatella_0.15.0-1_i386.deb.

[SavedGames.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/449644/SavedGames.zip)

**Comment by selaux** [comment]
Hm, I cannot load any of the savegames with current master. The loading screen starts hanging. We should look out for savegame incompatibilities as well...

**Comment by selaux** [comment]
Can reproduce it in v0.15.0. I would suggest revealing the enemy somehow correlates with the spinning,  since Skyrider is the one seeing the enemies.

**Comment by selaux** [comment]
I just fixed the infinite loading in master. This lets me load in master and afterwards Skyrider walks into the bottom right corner of the map. Was that what he was supposed to do?

**Comment by geca** [comment]
Aye, that was where Skyrider was supposed to go. Thanks!

**Comment by selaux** [comment]
Greal 👍 

@lynxlynxlynx @derSteFfi Should we make a bugfix release for this? Has been reported multiple times already.

**Comment by lynxlynxlynx** [comment]
From blame it looks like this was changed post-release.

**Comment by selaux** [comment]
According to Github this merge https://github.com/ja2-stracciatella/ja2-stracciatella/commit/7387c1d5130f31b0831cb6cea7efa79606950a63 is included in the 0.15.0 tag.

**Comment by lynxlynxlynx** [comment]
Ah, the previous bug. The way I see it, either we make a silent 0.15.1 release with just these type fixes or a proper release with everything up till now.

**Comment by selaux** [comment]
I'd rather do a silent 0.15.1 release since there are currently some issues in master (e.g. with a lot of failing asserts).

**Comment by derSteFfi** [comment]
also pro silent release. Maybe we build in a switch for the asserts to not let the game crash and turn it off for release versions. on the other hand, we get a lot of bug reports this way :)

**Comment by selaux** [comment]
Made #377 out of this.
