### ISSUE TITLE
Alternate IMP creation mod/patch

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#37]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

Think about integrating mgl's [Patch/Mod] Alternate IMP creation
http://www.ja-galaxy-forum.com/board/ubbthreads.php/topics/263053/Patch_Mod_Alternate_IMP_creati.html#Post263053

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/37

**Comment by lynxlynxlynx** [comment]
this is the fixed link: http://thepit.ja-galaxy-forum.com/index.php?t=msg&goto=264048
The actual diff links are dead, so either mgl would have to be contacted or the code ripped from 1.13.

**Comment by JAsmine-ja2** [comment]
Doesn't #307 make this one obsolete?

**Comment by lynxlynxlynx** [comment]
No, this is about skipping the quiz and assigning everything yourself. What was done by vxx (taken from 1.13) was only the externalised attribute point values:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/externalized/game.json#L113

**Comment by ja2-derek** [comment]
How about adopting the "Skill Traits" selection screen from Unfinished Business? 

That screen is a drop-in replacement for the personality quiz. It is standalone patch (https://github.com/ja2-derek/ja2-ub-comparison/commit/dc522ad9140ac60b7aa86c16c5a699cbdb13d316), that it does not depend on any other things in UB. So we can easily integrate it behind a feature flag switch. 

BTW I cannot download the screenshot or patch from the forum link. I assume it is the one integrated into 1.13.

Pros:
- Official, polished and clean UI
- True to the Stracciatella spirit, without too much featurism
- One small step towards running UB on Stracciatella

Cons:
- No personality traits in the new screen (vs Vanilla)
- Cannot customize appearance or gear (vs 1.13)

![image](https://user-images.githubusercontent.com/63151803/83973310-1a134080-a918-11ea-9304-c24eed2d1450.png)

**Comment by lynxlynxlynx** [comment]
Sounds good to me, with yet another game.json switch to toggle behaviour.

Attitude could be done via the same screen, but there's little motivation besides roleplaying for that — from memory only one attitude is positive, several are negative and the rest don't have any effect.
