### ISSUE TITLE
Screenshots don't show path APs and sometimes don't show path either

### ISSUE THREAD

**Issue by Agatae1** [ja2-stracciatella/ja2-stracciatella#376]
On the screen I can see both path and AP, but not on the screenshot
![screen002](https://cloud.githubusercontent.com/assets/22129145/18416495/f6a75694-7816-11e6-980f-3eb4d4d5fb10.png)
Here the screenshot shows path, but still not AP
![screen003](https://cloud.githubusercontent.com/assets/22129145/18416496/f6c13690-7816-11e6-9c69-1e71f45d4e59.png)
See the attatched save
[save.ZIP](https://github.com/ja2-stracciatella/ja2-stracciatella/files/465895/save.ZIP)

The missing path may be related with #375

**Comment by lynxlynxlynx** [comment]
@JAsmine-ja2 do you know if this problem was inherited from the original? Since it pertains to the inbuilt screenshotter.

**Comment by JAsmine-ja2** [comment]
AFAIR, APs are always shown in Vanilla Screenshots.
Here is an example from Vanilla 1.12 Gold ENG:
![vanilla](https://user-images.githubusercontent.com/17213795/31860871-087de798-b722-11e7-8d38-aad3895c86a4.jpg)

Here is a screenshot from Stracc 0.15.1 - NO APs shown!!
![stracc](https://user-images.githubusercontent.com/17213795/31860872-093a59e6-b722-11e7-93ac-00d4998874b2.jpg)

**Comment by ja2-derek** [comment]
No longer relevant as we have removed the screenshot function in #1327.
