### ISSUE TITLE
Release 0.15.1

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#377]
Roadmap for the Release 0.15.1. What still needs to be done.

- [x] Update Version number to `0.15.1`
- [x] Github prerelease and tags
- [x] Attach built versions to release
  - [x] Linux, Windows
  - [x] OS X
- [x] Runtime tests of release packages
 - [x] Linux
    - [x] Ubuntu 16.04 x64
    - [x] Ubuntu 14.04 i386
 - [x] Windows
 - [x] OS X
- [x] Make prerelase the release
- [x] Announce
  - [x] Website
  - [x] Bears pit
  - [x] Moddb

**Comment by selaux** [comment]
I only did short tests for loading saving, which should be enough since it's the only change.

**Comment by lynxlynxlynx** [comment]
As a side note, I've updated the ohloh/openhub project to use relevant info, so now some stats are also available: https://www.openhub.net/p/ja2s

**Comment by selaux** [comment]
Should we announce this release or rather do it silently (because basically nothing changed 😉 )

**Comment by selaux** [comment]
@JAsmine-ja2 Can you update moddb?

**Comment by lynxlynxlynx** [comment]
I just commented on the original announcement on the forum. Don't feel any need for more, besides bumping versions where necessary.

**Comment by JAsmine-ja2** [comment]
I'm sorry, but I'm not at home for the next few days. I can't update the ModDB profile before maybe thursday.

**Comment by selaux** [comment]
No problem, lets keep this open so we don't loose track...

**Comment by JAsmine-ja2** [comment]
Article posted on ModDB and files uploaded.
The news will go live as soon, as the article is authorized.

Sorry I couldn't do it earlier. :(

**Comment by selaux** [comment]
No worries. Thanks I will close this then.
