### ISSUE TITLE
Description box missing when opening "Deposit/Withdraw money" widget in Tactical screen

### ISSUE THREAD

**Issue by geca** [ja2-stracciatella/ja2-stracciatella#379]
Load this [savefile](https://github.com/ja2-stracciatella/ja2-stracciatella/files/473470/money-glitch.sav.zip) using 0.15.1 and bring up "Deposit/Withdraw money" widget (dollar icon). Description box is missing, only the buttons are displayed as shown on the screenshot bellow.

This looked like a perfect trivial bug for my first pull request. Boy was I wrong. :) What follows is my analysis of the bug with couple of suggestions/questions on how to fix it. I'd really appreciate your input.

![jagged alliance 2_003](https://cloud.githubusercontent.com/assets/1169266/18530253/f31da69c-7ad0-11e6-8fbf-2a56f11a003c.png)

It turns out the description box renders properly if you enter and exit strategic screen before clicking on the dollar icon in tactical. Let's call this "Scenario 2", "Scenario 1" is when we skip strategic screen and just open the money widget after loading the game.

If we want to render the entire description box, `fInterfacePanelDirty` must be set to `DIRTYLEVEL2` (so we re-render the whole interface as opposed to `DIRTYLEVEL1` which only re-renders bullets and status). 

Bellow code snippet from `Strategic_Turns.cc/HandleStrategicTurn() ` that eventually decides whether dirty level is set to 1 or stays 2:

```
if ( ( uiTime - guiLastTacticalRealTime ) > uiCheckTime ) 
{ 
  HandleTacticalEndTurn( ); 
  guiLastTacticalRealTime = uiTime; 
}
```
In Scenario 2 (where we toggle strategic screen before we open money widget) this evaluates to false, with Scenario 1 the condition is met however. These functions are then called in sequence: 

```
HandleTacticalEndTurn (Tactical_Turns.cc) 
EVENT_BeginMercTurn (Soldier_Control.cc) 
HandleEndTurnDrugAdjustments (Drugs_And_Alcohol.cc) 
```
Yep, all the way to drugs'n'alco. :) The following condition is met inside `HandleEndTurnDrugAdjustments` that sets `fInterfacePanelDirty` to DL1, meaning the rendering of the description box will be skipped later on. 

```
if ( pSoldier->bDrugSideEffect[ cnt ] <= 0 ) 
{ 
  pSoldier->bDrugSideEffect[ cnt ] = 0; 
  fInterfacePanelDirty = DIRTYLEVEL1; 
} 
```
The quick fix would be changing  `fInterfacePanelDirty` in the snippet above to `DIRTYLEVEL2` and calling it a day.

On the other hand, maybe we should be skipping `HandleTacticalEndTurn` altogether as we do in the second test scenario. Circling back to the first snippet --

```
if ( ( uiTime - guiLastTacticalRealTime ) > uiCheckTime ) 
{ 
  HandleTacticalEndTurn( ); 
  guiLastTacticalRealTime = uiTime; 
}
```
-- the reason why Scenario 1 executes `HandleTacticalEndTurn` and Scenario 2 does not is `giTimeCompressMode`. After loading the game, compression mode is set to `TIME_COMPRESS_X1`, later ensuring the condition `( uiTime - guiLastTacticalRealTime ) > uiCheckTime` is met. When we enter/exit map screen, compression mode is set to `TIME_COMPRESS_60MINS`, and therefore later skipping  `HandleTacticalEndTurn`.

What do you guys think should be the right approach in dealing with this bug? What is expected behavior (i.e. time compression mode) when we are in tactical screen and is it supposed to change if you enter/exit map screen which explicitly says it is being paused? Now that I think of it: none of the mercs in the savegame is "under influence" so `HandleEndTurnDrugAdjustments` should probably return immediately anyway. However, we would still probably get only partial money widget when bringing it up on drugged merc ...

**Comment by lynxlynxlynx** [comment]
First, it'd be interesting to know if this is a regression on our part or something older. Can you do a git bisect run to find the breaking point?

Secondly, what you described sounds completely nuts. I'm not saying I don't believe you though. In the end, drawing an ui element should be decoupled from strategic time modes, end of turn processing and similar. It appears like the execution flow wasn't cut of early enough.

Lastly, since DIRTYLEVEL1 redraws less than DIRTYLEVEL2, all fInterfacePanelDirty setting should probably ensure that lower levels don't override higher ones. IOW:
`fInterfacePanelDirty = DIRTYLEVEL1;` vs
`if (fInterfacePanelDirty < DIRTYLEVEL1) fInterfacePanelDirty = DIRTYLEVEL1;`

**Comment by geca** [comment]
Before I do a bisect, can you load the savegame on your machine and try reproducing the bug? If you can, I'll also appreciate if you could change `fInterfacePanelDirty = DIRTYLEVEL1; ` to `DIRTYLEVEL2` as described above and let me know if the bug is fixed that way. Just so I now I'm not hallucinating. :) Thanks!

**Comment by lynxlynxlynx** [comment]
I can't reproduce it with any of my saves, even in turn based mode. There is one other, imported from someone else, where something similar if not the same happens, but the problem there is wider — I can't view item descriptions either. Movement forces a redraw. Did you do anything special to get into that situation?

**Comment by geca** [comment]
> Did you do anything special to get into that situation?

Not that I'm aware of. :( Please try this with one of your 'good' savegames:
1. switch to tactical view if not there already
2. switch back to strategic view
3. have a single merc travel to some other sector
4. view that sector in tactical when (s)he arrives (meaning the view gets loaded afresh)
5. click on the money icon in tactical view

Do you see the whole GUI for money withdrawal after this steps?

**Comment by lynxlynxlynx** [comment]
I tried twice and first time it worked, the second time I could reproduce it. Your steps make the context more sensible though.

**Comment by geca** [comment]
Thanks. Had couple of savegames myself that rendered money widget properly so I was experimenting a bit and found these steps reproduced the bug.

**Comment by selaux** [comment]
I agree with @lynxlynxlynx. We should maybe introduce some `SetInterfacePanelDirty` function that get executed whenever the level is changed. I can't think of a situation where lowering the dirty level makes sense...

@geca BTW welcome to the weird world of ja2 code 😉

**Comment by geca** [comment]
How about completely encapsulating `fInterfacePanelDirty`? If we only have "setter" then nothing prevents me from doing `fInterfacePanelDirty = DIRTYLEVEL1` when it's already set to `DIRTYLEVEL2`.

This is as far as  `fInterfacePanelDirty` goes. We still have to figure out why time compression changes from `TIME_COMPRESS_X1` (by doing the steps above) to `TIME_COMPRESS_60MINS` after you enter/exit the strategic screen.

Thanks @selaux. It's been an interesting experience so far, as you can imagine. :smile:

**Comment by lynxlynxlynx** [comment]
Sure, you can convert it to an object.

As for the compression, is that even noticeable anywhere or is it just an architectural curiosity? It seems to be working fine.

**Comment by geca** [comment]
Well, it's the time compression difference that eventually causes wrong rendering of money widget. I get your point though, it doesn't seem to cause any other problems. I'll encapsulate fInterfacePanelDirty and close the issue after that. Thank you both!
