### ISSUE TITLE
Playable Characters Mod (PCM) support

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#39]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

User Scheinworld from BPF thinks it would be a great idea to support Playable Characters Mod (PCM)  together with 800x600 mod.

It can be done only in [ModPack](https://bitbucket.org/gennady/ja2-stracciatella/wiki/ModPack) project, not JA2-Stracciatella due to legal considerations.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/39

**Comment by derSteFfi** [comment]
What is our standing on the ModPack idea?

**Comment by lynxlynxlynx** [comment]
Like it's noted, it's a separate project (hosted in a branch).

**Comment by ja2-derek** [comment]
Looks like it works by just copying in the assets. Created https://github.com/ja2-derek/mod-playable-chars

There is an PCM_SV_B005.exe in the ZIP file. Any idea what is does?

![image](https://user-images.githubusercontent.com/63151803/86150597-32016d00-bb30-11ea-8e95-6de7bb1a62e0.png)

**Comment by lynxlynxlynx** [comment]
Maybe audio or image converter? Maybe it has a usage string, try -h or something nonsensical.

**Comment by ja2-derek** [comment]
And Darrel joins after marrying a female merc to the Hicks, despite what the README says about 1.13

**Comment by ja2-derek** [comment]
That EXE looks for `fmod.dll` and the icon looks like a replacement for JA2.exe. 

No idea how it is different.

**Comment by ja2-derek** [comment]
> And Darrel joins after marrying a female merc to the Hicks, despite what the README says about 1.13
> 
> EDIT: there is an assertion failure, could be related:
> 
> > 2020-06-30T16:29:53 [ERROR] game/Strategic/Strategic_Town_Loyalty.cc: Assertion failed in ...\ja2-stracciatella\src\game\Strategic\Strategic_Town_Loyalty.cc, line 214

Caused by `HandleTownLoyaltyForNPCRecruitment()`, and Darrel's Town ID is 0 (`BLANK_SECTOR`). Causes a Assertion failure, but safe to ignore.

**Comment by ja2-derek** [comment]
Migrated to https://github.com/ja2-stracciatella/mod-playable-chars

Closing this issue. We can follow up in the mod repo if needed
