### ISSUE TITLE
Shipping cost BR not redrawn properly

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#394]
![bobby1](https://cloud.githubusercontent.com/assets/17213795/18957369/0db758b0-865f-11e6-9052-498f4906b1bc.jpg)
![bobby2](https://cloud.githubusercontent.com/assets/17213795/18957368/0db3db04-865f-11e6-8c88-c37d36a69c54.jpg)

Notice how the numbers are somehow screwed up when changing the cheaper shipping cost. This can be triggered as well when changing around the destination (different destinations have diferent prices).

Interesting: This bug can be observed in vanilla JA2, too!

**Comment by lynxlynxlynx** [comment]
Doesn't look like a bug to me. What's screwed about the numbers? You chose shipment at half the previous price and the shipping cost halved.

**Comment by JAsmine-ja2** [comment]
You have to zoom in on the image quite a bit to see it.
The last digit in the 2nd and 3rd row in the red circle is messed up graphically.

**Comment by selaux** [comment]
I can reproduce this. My guess is that dirty rectangle updating does not work correctly here (dirty rectangle is too small).
