### ISSUE TITLE
Throwing knife flying animation messed up

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#395]
![throw](https://cloud.githubusercontent.com/assets/17213795/18958880/82e9bcb8-8664-11e6-9e97-d7536d2e348a.jpg)
Blood throws a knife at the enemy's head... and hits him!
However, the knife is drawn in a strange place and looks like it's gonna fly way over the enemy.
Red route: how it should be
Bue route: how it is drawn

It worked perfectly in different attempts before. But in this situation, it is always messed up.

Load the savegame and try for yourself!

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/500948/QuickSave.zip)

**Comment by lynxlynxlynx** [comment]
The way you drew it, it looks like throwing a grenade.

**Comment by JAsmine-ja2** [comment]
True. It's hard to see on the image but when you load the game and let Blood throw a knife at the enemy (head, torso, legs - doesn't matter) you'll see what I mean. The knife just travels FAR away from the line you would normally suspect.
