### ISSUE TITLE
Add comments explaining game.json variables

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#401]
Split from #345 
- [x] Bump rapidjson lib to 1.1.0 so we can use comments
- [x] Add comments to game.json
- [x] Remove game.json section from readme.txt

**Comment by JAsmine-ja2** [comment]
How do comments in a json work?
Seperated by semicolon?

; comment
; comment
"map_hotkey_ctrl_i": true,
; comment

**Comment by lynxlynxlynx** [comment]
// single-line comment
/* multi
line
comment */

**Comment by JAsmine-ja2** [comment]
[externalized.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/504266/externalized.zip)

I hope, I can save you some legwork with this.

**Comment by geca** [comment]
You should probably mention where one should put the file so it gets recognized by the game. Which is actually my question really. :) I tried with .ja2 dir (inside my home dir) as well as data_dir but the game didn't recognize "J" hotkey that I had enabled.

**Comment by lynxlynxlynx** [comment]
The file already exists under externalised/ . (But that's bound to change as per #360 )
However, that's the source, so good question. Dig into a package and find where it gets installed.

**Comment by geca** [comment]
It was under `/usr/share/ja2/externalized`. I'm kind of new to Linux and forgot packages get installed all over the place. 

@JAsmine-ja2, please ignore my comment. I'm working on first bullet (bump rapidjson). Will try testing with your modified game.json file and let you know how it goes.
