### ISSUE TITLE
Climbing makes mercs visible at night

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#402]
In this savegame I could capture a bug that I've already seen once or twice before.

First you see Barry in a dark place behind a building.
![barry1](https://cloud.githubusercontent.com/assets/17213795/18994448/2986949c-8728-11e6-9a35-98a95aabe2bf.jpg)

When he climbs the bulding, an enemy soldier gets an interrupt and shoots. Why/how can the soldier see Barry, when he's too far away and Barry isn't within a lightning source?
![barry2](https://cloud.githubusercontent.com/assets/17213795/18994490/5568aadc-8728-11e6-85f9-d1aba53711a4.jpg)

I suspect that either the jumping on roof makes Barry visible or maybe the lighting source within the building also lights the roof?
Anyway, something is wrong here, gameplay-wise.

Savegame before: Just select Barry and make him jump on the roof.
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/503126/QuickSave.zip)

**Comment by lynxlynxlynx** [comment]
Is vanilla the same? Perhaps it's just lighter than it appears.

**Comment by JAsmine-ja2** [comment]
The interesting thing here is, that the enemy can't see Barry (or any of the other mercs). You can also move Barry around for some tiles without being seen.
But the climbing on the roof reveals Barry. And the distance implies, that Barry is somehow within a very bright spot all of a sudden.

**Comment by lynxlynxlynx** [comment]
he's probably loud too.

**Comment by JAsmine-ja2** [comment]
I've done done some more testing around with this issue and I think I know what's going on here:
When a merc climbs a roof, he is in a different light level than his surroundings. I don't know the right term, but the "light-level" or "light-modifier" doesn't apply to him.
In daylight, this has no effect. But at night, he (the climbing merc) might become visible to enemies that couldn't spot him before because of the darkness.

I have a new example here:
![climb-light1](https://cloud.githubusercontent.com/assets/17213795/19107204/6fba7dfe-8aeb-11e6-897f-76d4ec8d40b6.jpg)
You can see the IMP on top of the roof. The enemies are revealed with ALT+E cheat. IMP can't see the nearest enemy and vice versa. Note that IMP has NO skill and NV goggles, which already gives him +2 vision distance. Everything is fine so far.

Now the IMP climbs down the roof and...
![climb-light2](https://cloud.githubusercontent.com/assets/17213795/19107299/d5bf5ebc-8aeb-11e6-80ee-04d25def782e.jpg)
the enemy sees him and turn-based mode starts.
Now you might wonder "maybe he is visible to the enemy because of his new position/tile"?

Simple to check:
![climb-light3](https://cloud.githubusercontent.com/assets/17213795/19107383/3d2bd724-8aec-11e6-8efe-acef961d1e3b.jpg)
No. If I just teleport ALT+T to the new position/tile, it is clear, that the new position is as safe as on the roof.

So, the position/tile isn't what makes the IMP visible to the enemy. The only thing left is the climbing.
Is it because of the loudness?
Can't be. Why? - First off all, I've tried it both in "normal" mode and in "stealth" mode. It made no difference. Second (and more important): Noise isn't a factor that can initiate a battle. Noises might give clues to the whereabouts, but noise can't initiate a battle. Correct?

So, the climbing somehow makes the player "more visible" to the enemy.
If I could, I would try to figure this out in the code myself, but I'm not capable of doing so ;)

btw, here is the savegame for testing:
[climbing-light.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/510541/climbing-light.zip)

**Comment by Tercus** [comment]
Old bug, but I remember this being a bug in vanilla as well. Sometimes climbing would also reveal and trigger enemies inside the building. This has ruined a lot of silent play-throughs for me.
