### ISSUE TITLE
IMP Attitude generation is broken

### ISSUE THREAD

**Issue by RinneT** [ja2-stracciatella/ja2-stracciatella#405]
After starting a few new games and noticing that my player characters always have the same attitude, no matter how I I answer the personality quiz, I took a look into the code and found it to be broken.

The code in question is the following:
`INT32 iDiceValue = Random(iNumAttitudesWithHighestHits + 1); // XXX TODO0008

```
// find attitude
INT32 iCounter2 = 0;
for (INT32 i = 0; i < NUM_ATTITUDES; i++)
{
    if (iAttitudeHits[i] == iHighestHits)
    {
        if (iCounter2 == iDiceValue)
        {
            // this is it!
            iAttitude = iCounter2;
            break;
        }
        else
        {
            // one of the next attitudes...
            iCounter2++;
        }
    }
}`
```

How it works is this:
The array iAttitudeHits represents the Attitude ENUM.
iAttitudeHits[0] represents the attitude Normal,
iAttitudeHits[1] represents the attitude Friendly,
etc...

Every Array Slot is assigned a number, how many times this attitude was selected in the quiz.
e.g. iAttitudeHits[0] = 2 means that an answer resulting in the attitude normal was selected twice.

iHighestHits represents the highest number of hits any attitude has received.
iNumAttitudesWithHighestHits tells us how many attitudes have received so many numbers of hits.

iDiceValue should theoretically be a random number between 0 and iNumAttitudesWithHighestHits+1, though it always seems to be 1.

iAttitude, of course, is the attitude that is selected in the end.

I think this is supposed to be a random attitude selector between the attitudes with highest hits.
But ultimately what happens here is, that the attitude is always either 0, or the number assigned to iDiceValue.

An easy first fix would be to just replace `iAttitude = iCounter2;` with `iAttitude = i;`.
That would, however, still leave the risk of assigning no value at all, depending on the value of iDiceValue. Having only one attitude that has received the highest hits, it is unlikely to ever result in an attitude, though, as I have never seen the dice receive the value 0.

I don't know how the original system was intended. My best guess (and what would make most sense in my eyes), would be to only utilize (a working) dice system if iNumAttitudesWithHighestHits > 1.

**Comment by lynxlynxlynx** [comment]
I suggest you either debug print the hits array or play with the included mod that shows choice results as you make them. That way you can be sure that you're selecting more than one candidate equally. IIRC not that many questions alter personality, so it's quite conceivable and expect that most mercs would be normal.

**Comment by lynxlynxlynx** [comment]
Yeah, works fine. Both Random and the whole process. Most questions don't affect attitude.

**Comment by akdjka** [comment]
I agree with the OP, it doesn't work.
First, TODO0008 seems actually right, the random range is off by one.

Second, the assignment should be
iAttitude = i;
instead of
iAttitude = iCounter2;
