### ISSUE TITLE
Auto-planning a route on strategic map

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#407]
Instead of travelling sector by sector, which is super-tedious, we can travel several sectors in one go and let the game decide the rute for us.

But how does this actually work?

I know that the game tries to look for the fastest route to travel from A to B. Since movementcosts between sectors can vary dramatically, the fastest route is more than often not the shortest route.

I also know that you can use SHIFT to show an alternate route, that is usually a bit more direct, but takes more time.

In my current game, I travelled from G9 (Cambria/Keith's shop) to I6 (Estoni). Everything worked fine. However, on my way back, the game suggested that I take a different route back, via I7 (Central SAM site).
![route1](https://cloud.githubusercontent.com/assets/17213795/19075621/052b3a5a-8a46-11e6-93e8-e115b63b00cf.jpg)

Since the central SAM site is not liberated, yet, this was definitely not the route I travelled on my way TO Estoni.
**_Pressing SHIFT doesn't display an alternate route._**

I can ofc plan the route manually, which I did. I take the same route that I've used (and that was auto-planed) on my way TO Estoni.
![route2](https://cloud.githubusercontent.com/assets/17213795/19075735/8c00cefa-8a46-11e6-84ae-6ee5ae5eb03e.jpg)
**_This route takes the same amount of time as the auto-planned route._**

It seems to me, that the way the game auto-plans the route doesn't work 100% as intended. Or at least, the alternate route (SHIFT) doesn't work that well.

I think, the auto-planned route should always be the fastest route.
If an alternate route is available, that is as fast or slightly slower, it should always be displayed with SHIFT.

Note, that this is all just about speed and not about other aspects, which makes one route "better" than another
(like e.g. the enemy presence in I8). These more complex decisions should be left to the player.

**Comment by lynxlynxlynx** [comment]
Maybe the path costs aren't symmetrical with direction. As for the shift thing — never heard of it, cool.

**Comment by JAsmine-ja2** [comment]
The shift thing is useful sometimes. But I think it's a bit crippled or at least not fully sleshed out. Maybe, the alternate route with shift can be made a bit more polished with a small effort?
Maybe, the "shift-route" could always be the 2nd fastest route besides the "normal auto-route"? Or the alternative route of the same time as in my example?
Right now, the "shift-route" is not always displayed.

**Comment by lynxlynxlynx** [comment]
To quote the manual:
> By default, a squad will take the q u i c k e s t route to a destination. If you’d like your mercs
> to take the most dire ct route instead, hold down the SHIFTkey while plotting the route.

Are your finding a regression or was it wanky already in the original?

**Comment by JAsmine-ja2** [comment]
Okay, I should have read the manual before. I thought, the alternate route was supposed to be the 2nd quickest route and not always the most direct route.
Everything works as it should.

The (rare) issue in my opening post just arises because there are two different routes, which take the same amount of time and are both "the" quickest route.
Nevertheless, one of these routes is way more desirable, because it doesn't lead through occupied sectors.
It's irritating that the game comes up with one (the good) route on the way from A to B and on the way back, from B to A, it comes up with the 2nd (bad) route.
But this is a rare issue and probably limited to very few instances, where two different routes are just as fast.

**Comment by selaux** [comment]
Closing then.
