### ISSUE TITLE
Stealing from enemies - long stopwatch

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#408]
Stealing from enemies is one of the not-so-well documented features of JA2.
Every time a merc steals from an enemy, the player gets a long stopwatch (ca. 20-25 seconds).
This longs stopwatch makes stealing feel kind of buggy and makes me fear, the game might end up in a endless-stopwatch-state.

Can anything be done about this?

Here's a savegame where an enemy soldier is ready to be robbed:
[stealing.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/508969/stealing.zip)

**Comment by geca** [comment]
I remember this from vanilla. Had a Pentium 200 back then. It took ages to get out of this loading state so I stopped stealing altogether. :) It's faster now in Stracciatella but annoying nevertheless. Besides stealing, I got the same bug while CTRL-clicking on a random tile by mistake. Couldn't reproduce it though.

**Comment by selaux** [comment]
I just tried the save and I'm not getting a long stopwatch. Anything special to do except `CTRL+LMB`?

**Comment by JAsmine-ja2** [comment]
No - nothing special to it.

I just tried it again. 5 times with Ivan and once with IMP and Blood. Each time I get the long stopwatch.
I'm running Stracc 0.15.1 on JA2 Gold 1.12 EN on Windows.

When I use the save on the same JA2 1.12 without Stracc - it's the same.
When I use the save on a CLEAN install of JA2 1.12 (no Stracc) - I don't get the long stopwatch.

I'm 100% confused.

**Comment by daviel** [comment]
Could not reproduce the long stopwatch ...

**Comment by lynxlynxlynx** [comment]
@JAsmine-ja2 can you still reproduce it or did we accidentally fix it at some point?

**Comment by JAsmine-ja2** [comment]
Yes and no ;)
Whit a fresh install of Stracciatella and JA2, I can NOT reproduce this. However, this is also true for a fresh Stracciatella 0.15.1 (same version as in 1st post).
I have an install of JA2 1.12 here, that seems to be messed up, because I can reproduce the long stopwatch with it all the time.
I guess, this issue is not from Stracciatella. Seems like I have messed up something in my JA2 install.
