### ISSUE TITLE
Free disk space is calculated wrong

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#413]
Playing a DiD game, the game reported too low disk space for a disk that has 123 GB free space. Probably had to do with autosave.

**Comment by RinneT** [comment]
Free space is indeed reported wrong.
I get ~1GB free space reported when I roughly 144GB free. (Linux)
What's interesting: I can debug into the function DoesUserHaveEnoughHardDriveSpace() in SaveLoadGame.cc, but can't jump into GetFreeSpaceOnHardDriveWhereGameIsRunningFrom() in FileMan.cc which is called from there. Neither setting a breakpoint in the function, nor chosing "Jump into" gets me in there. 
uiBytesFree = GetFreeSpaceOnHardDriveWhereGameIsRunningFrom( ); just results in
uiBytesFree = 1073741824. No idea why.
