### ISSUE TITLE
Can't type IMP code after saving via Save screen

### ISSUE THREAD

**Issue by RinneT** [ja2-stracciatella/ja2-stracciatella#419]
If you save the game via the save screen and hence select a text input field, you can't type the IMP access code on the IMP homepage.
This affects new Dead is Dead games as you are forced to select a savegame slot, but also works on normal games if you save before entering the code.
Other fields seem to be unaffected, like the florists message cards or shortcuts.

Only workaround is to completely close the game, restart and load the save.

[Edit]: Additionally if you put a text in the flower cards the IMP textbox doesn't work either.
You can select it and the blinking '|' will appear, but you can't type. So it seems to get the focus but somehow doesn't manage to bind the keyboard.

**Comment by RinneT** [comment]
The Text input in this screen is handled a bit differently than in other screens.
The keystrokes are recognized, but for some reason if a previous Text input has been used,
`wchar_t Char = Inp->Char;` is always 0. I can't figure out why, but would recommend unifying the text input generally. It seems quite complicated at the momen.t

**Comment by selaux** [comment]
There are also other issues with TextInputs. Try to type a number in the save screen for example. This comes from the SDL2 upgrade where now two events are fired for a type when a text input is enabled.
