### ISSUE TITLE
Autodetect version of the game resource

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#42]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

At the moment the user must select appropriate version of the game resources before starting the game by using -resversion command line key.

Need to implement automatic detection algorithm, so there will be no need for the user to do it manually.  That should improve usability of the program.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/42

**Comment by JAsmine-ja2** [comment]
Since this task is covered in #607, can we close this issue?

**Comment by lynxlynxlynx** [comment]
not sure, this code should also be in core, so it'd work when launching it directly.

**Comment by Manuel-K** [comment]
True. If we had automatic detection in the engine, we could completely remove the settings from the launcher, although some override functionality could be useful.

**Comment by flaviojs** [comment]
Looking at GameRes.cc, some versions have simple distinguishing features:

RUSSIAN -> files inside `russian` dir
POLISH -> files inside `polish` dir
ITALIAN -> files inside `italian` dir
DUTCH -> files inside `dutch` dir
GERMAN -> files inside `german` dir

but what about the other versions ENGLISH, FRENCH and RUSSIAN_GOLD?
How can they be distinguished?

**Comment by flaviojs** [comment]
An easy way to handle this is to gather a list of file-hash pairs for each version and then use it to compare.

**Comment by lynxlynxlynx** [comment]
File presence is a bit stabler approach, when possible, since I think there are multiple versions of the same locale games.

**Comment by flaviojs** [comment]
Another important note, are the russian/polish/italian/dutch/german directories and files inside SLF archives?
I only have the english version so I can't check.

**Comment by selaux** [comment]
I think we can close this with https://github.com/ja2-stracciatella/ja2-stracciatella/pull/820 and https://github.com/ja2-stracciatella/ja2-stracciatella/pull/856. I tested all versions available to me (German (Steam), French (Steam), Polish (Steam), Russian (Steam), Gold English (Steam), English (Steam)). :tada:
