### ISSUE TITLE
Selling attachments to Tony - strange prices

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#423]
Selling some stuff to Tony, I noticed a strange thing:
Tony pays different prices for attachments, if they are attached to a gun.
Look at the three pictures.
1) Selling a fully loaded Minimi with attached Talon - 2.946$
2) Selling a fully loaded Minimi with the same Talon extra - 2.914$
3) Selling an unloaded Minimi with the Mag and the Talon extra - 2.914$
![att1](https://cloud.githubusercontent.com/assets/17213795/19393547/66e33fbc-9235-11e6-90f1-b72644055279.jpg)
![att2](https://cloud.githubusercontent.com/assets/17213795/19393546/66e11da4-9235-11e6-9872-28a3762df10c.jpg)
![att3](https://cloud.githubusercontent.com/assets/17213795/19393548/66e9e420-9235-11e6-84ab-44ae8705b776.jpg)

So, the gun with attachment is more expensive than both items seperately. This is true for other attachments as well (can be tested in the savegame).

I was wondering if maybe the game doesn't take the status % for attached items into account when calculating their value? So, attached Talon is always treated as 100% Talon, even though it has less status % ??

Savegame:
[attachment_prices_tony.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/529886/attachment_prices_tony.zip)

**Comment by lynxlynxlynx** [comment]
A different option that comes to mind is that perhaps not everyone can attach a talon and so the price reflects it. Does it require a mechanics check like the merges?

**Comment by JAsmine-ja2** [comment]
No, everyone can attach a Talon. No skill check (afaik).

**Comment by JAsmine-ja2** [comment]
I just tested it with gun and attachment both at 100% status - the same phenomena can be observed.
Gun+attached add-on is more expensive than gun+seperate add-on.

**Comment by selaux** [comment]
You're finding the most edgy cases of all 😉 . It seems like this has to do with Flo doing the actual dealing. Flo (according to code and merc profile) gets discounts for weapons and it seems that the Talon attachment is not recognized as a weapon. Can you try if you have the same issue with a different merc?

**Comment by JAsmine-ja2** [comment]
Further testing shows:
Other mercs than Flo can trade the Talon attached or unattached with no change in price.
This is true in both vanilla (1.12) and Stracciatella.
So, it's indeed Flo, who makes a difference here.

I knew about her 10% discount. I didn't know, that she also get's more money when selling stuff. Nice ;)

I think that her 10% bonus should always apply when she's selling and buying stuff at Tony's. Would be more consistent.
