### ISSUE TITLE
Adding money with '+' key cheat not working?

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#426]
I just tried to use the cheat and it doesn't work. I strongly suspect this to be a problem on my side. Can someone confirm the cheat to be working in Stracciatella?

EDIT: Strange thing is, that the "removing money cheat" with '-' key works.

**Comment by lynxlynxlynx** [comment]
Where and how is this supposed to work?

**Comment by JAsmine-ja2** [comment]
In tactical view, press CTRL and type in 'GABBI' to activate cheat mode. In localizations other than english, the code might vary.
Then open the laptop.
The plus key '+' should add money to your account, the minus key '-' should remove money.

For some reason, only the minus key command works for me in Stracciatella.

**Comment by lynxlynxlynx** [comment]
could be related to the sdl2 port, since we know we have some input problems.

**Comment by selaux** [comment]
Looking at the code the `=`-char is used. But does not work for me either...

@JAsmine-ja2 Which version are you using?

**Comment by JAsmine-ja2** [comment]
I'm using JA2 1.12 (Gold) English and Stracciatella 0.15.1.

I can use the minus [-] key on my numpad to use the "substract money" cheat.
I can't use the plus key [+] on my numpad or on my keyboard to use the "add money" cheat.

The "add money" cheat with the plus [+] key works as intended in the same JA2 1.12 without Stracciatella.

**Comment by lynxlynxlynx** [comment]
maybe it assumed the us-ascii keyboard layout and that got ripped out during the initial port to SDL? Does it work if you use =? I don't know the German layout, but here it would be at shift+0. So not that likely to work, since it requires a modifier.
