### ISSUE TITLE
Audio quality in master

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#444]
Just tested 0.15.x (#442)

I hear a BIG difference in the audio quality of the main menu music.
To me (as a musician) it is very obvious, that the quality of the 0.15.x builds is inferior to 0.15.1 (true for both 32 and 64 bit).
I could do a recording for comparison, but when you listen to the beginning of the main theme and listen to the sound of the cymbals, it should be obvious to everyone, that the 0.15.x-cymbal sounds very "noisy, trashy, dirty" compared to the clean sound of 0.15.1 (and vanilla).

Could this be because of some drastic changes like sdl 2?

I'm on Windows 8.1 64 bit.

**Comment by lynxlynxlynx** [comment]
By 0.15.x you mean what we have in git, latest development stuff? Which revisions did you test (so it's easier to find potential culprits)?

**Comment by JAsmine-ja2** [comment]
I tested all the windows releases from nighlies:
http://builds-ja2.stefanlau.com/nightlies/
I tested both versions (20161103 and 20161109) in both, 32 and 64 bit.

**Comment by selaux** [comment]
While I can reproduce this on windows, on linux everything seems fine to me. I will have a look how a mingw build behaves, maybe it is a compiler specific issue.

**Comment by selaux** [comment]
Nope, also there with a MinGW build, seems to be a Windows specific issue though...can anybody confirm?

**Comment by JAsmine-ja2** [comment]
Just tested it. Can confirm that bad sound quality is present on MinGW builds.

**Comment by selaux** [comment]
So setting the output sample rate to 44100 seems to fix it but when the sounds are upsampled they consume significantly more ram, so we have to do that on the fly... I will try to implement that.

**Comment by selaux** [comment]
This is hard, after a few attempts I still cannot get audio streaming right... Take a look at [the fix-sdl2-audio branch](https://github.com/ja2-stracciatella/ja2-stracciatella/tree/fix-sdl2-audio), which is the one that consumes more memory right now. Suggestions are very welcome on how to continue 😉
