### ISSUE TITLE
No parallel movement of several mercs in real time

### ISSUE THREAD

**Issue by RinneT** [ja2-stracciatella/ja2-stracciatella#447]
With the current build I get the problem that I can't move several mercs at once in real time.
E.g. I have several mercs selected and give an order to move or change position.
The game then unselects all mercs other than the "primary" selected and only he/she moves.

In addition to that I get a stopwatch until the movement is done. Essentially the game behaves as if it were in round based mode.

**Comment by selaux** [comment]
Traced this down to https://github.com/ja2-stracciatella/ja2-stracciatella/commit/989f2d9d8bf7e03569fb649de75a966ad40f65c2. The commit looks good to me though @lynxlynxlynx any idea what is wrong there?

**Comment by lynxlynxlynx** [comment]
Hmm, peculiar. I'll take another look. One thing that comes to mind is operator precedence ... and yep, that's it. == is evaluated before &, so `gTacticalStatus.uiFlags & IN_TB_COMBAT == IN_TB_COMBAT` is equal to `gTacticalStatus.uiFlags & 1`. Sneaky.

**Comment by RinneT** [comment]
Soo, brackets?

**Comment by lynxlynxlynx** [comment]
Yep.

**Comment by RinneT** [comment]
Just to resolve any confusion my comment may have caused:
Will you fix it? Since you assigned it to yourself and know the solution.
Thanks for the detectives work you two btw. :)

**Comment by lynxlynxlynx** [comment]
I already did the bracketing, but it didn't fix the issue here. You can play with it yourself, since the function names are pretty self evident: 
http://sprunge.us/SAWj

I'll take a deeper look at the end of the week — won't manage sooner.

**Comment by RinneT** [comment]
Didn't really have time in the week either.
I've looked at it for a while today.
I don't think the condition checks are wrong, but rather the conditions.
It seems like the problem is that while INCOMBAT is properly set and unset, TURNBASED is not.
The same goes for REALTIME, although that doesn't seem to have much of an effect.

What bugs me is that setting and unsetting is never really done in this commit.
Except for line 1397 in Turn_Based_Input.cc, which only effects the button 'd' being pressed though.

**Comment by RinneT** [comment]
Checked the code again. TURNBASED is literally only assigned once during the init of Overhead.cc.

I have set and unset it in CommonEnterCombatModeCode and ExitCombatMode in Overhead.cc.
The interesting thing is that even if 
gTacticalStatus.uiFlags & TURNBASED == 0
&&
gTacticalStatus.uiFlags & INCOMBAT == 0,

gTacticalStatus.uiFlags & IN_TB_COMBAT == 4.

I don't understand why.

**Comment by Manuel-K** [comment]
Could it be the definition of `IN_TB_COMBAT` in `Build/Tactical/Overhead_Types.h`? Did you try it with brackets added to the definition i.e. `#define IN_TB_COMBAT (INCOMBAT|TURNBASED)`? I cannot test it at the moment.

**Comment by Manuel-K** [comment]
That should be the solution. It does at least explain your question, @RinneT:

gTacticalStatus.uiFlags & IN_TB_COMBAT == 
gTacticalStatus.uiFlags & INCOMBAT|TURNBASED ==  
(gTacticalStatus.uiFlags & INCOMBAT) | TURNBASED == 
0 | TURNBASED == TURNBASED == 4

**Comment by RinneT** [comment]
@Manuel-K Adding brackets did the trick. Thank you.

**Comment by lynxlynxlynx** [comment]
Nice work pinpointing it down. I just came back home and can finish it.

re TB: maybe it's just a development artifact, perhaps they considered realtime combat too at some point.

**Comment by JAsmine-ja2** [comment]
@lynxlynxlynx 
funny that you mention it. It seems that JA2 was 100% realtime in the beginning of it's develompment.
Ian Currie himself made a statement about this!

Source: https://web.archive.org/web/20160115053134/http://www.jagalaxy.com/index.php/news/ja-museum/3146-jagged-alliance-museum-tour-with-ian-currie-1997-ja2-section.html

(chek first paragraph. Actual JA Galaxy is being rebuild atm)

**Comment by lynxlynxlynx** [comment]
Yep, some remains are still there as commented out code. Meaning we can strip REALTIME out completely, as it is only ever unset by the editor. But that's for a different issue/pr, since it's only cleanup.

**Comment by RinneT** [comment]
@JAsmine-ja2 
Professional JA2 historician. Also an interesting article.
Additionally, that is good news!

**Comment by derSteFfi** [comment]
whoho. I'm kinda triggered (yes, I still read the mails, i currently don't have much time to spare).  As you guys might have noticed, I'm am a fan of cleanup :)
Solving this is a good one, cleaning out unnecessary stuff with 84 LoC (grep REALTIME | wc -l) too.

**Comment by lynxlynxlynx** [comment]
More like 40, since you included some unrelated lines. But then the commented out code can go, which will increase the count higher. Any single mentions of TURNBASED could go too. And ha, then the whole tb combat bitfield can be simplified back to a single value.

**Comment by JAsmine-ja2** [comment]
@RinneT 
Thank you, but that's too much praise. It's just that I fell in love with this game back in Nov.'98 and have played/modded/discussed and read about it a lot.

I have to say, that I'm really impressed by the amount and the _quality_ of work, you guys here are putting into this game. I'm proud to be a (small) part of this and I'm very happy with the great progress that's being made.
