### ISSUE TITLE
Documentation: slog license

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#458]
The different license of `src/slog/*` should probably be mentioned in `README.md`…

**Comment by selaux** [comment]
According to the slog license we are allowed to relicense. But we have to decide for a license regardless. Also for the externalized code parts.

**Comment by Manuel-K** [comment]
We explicitly mention the different license of the dependencies folder in the readme. That did cover slog before I moved it.

**Comment by selaux** [comment]
Slog is gone, closing...
