### ISSUE TITLE
Game hangs (stopwatch) after ending turn

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#460]
After ending the turn, stopwatch seems to spin forever (waited for several minutes). Savegame: [QuickSave.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/651519/QuickSave.sav.zip)

409ae2a on Mac.

**Comment by selaux** [comment]
I can reproduce with the savegame. Does this happen often or is that a one time issue?

**Comment by andreas12345** [comment]
I get "Aborting AI deadlock" several times in each turn, but this hanging forever hasn't happened again.

**Comment by momoko-h** [comment]
This should probably be closed. If you try to exit to the map screen you get the 'Abandon the fight' dialog box, which doesn't usually happen in this situation. In the savegame,  gTacticalStatus.bBoxingState is 6 (LOST_ROUND), despite the player still being far away from the point where he reaches San Mona.

I guess this was a case of memory corruption or an older version did not properly initialize its variables.
