### ISSUE TITLE
AI deadlocks

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#466]
Version 409ae2a2. Throughout my game, every battle has been slowed down by multiple AI deadlocks per turn. Example attached; end the turn, and you should get several AI deadlocks:

[SaveGame07.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/662343/SaveGame07.sav.zip)

2016/11/19 19:55:46 ERROR   [AI              ] Aborting AI deadlock for 26. Please sent LOG file and SAVE.
2016/11/19 19:56:10 ERROR   [AI              ] Aborting AI deadlock for 34. Please sent LOG file and SAVE.
2016/11/19 19:56:28 ERROR   [AI              ] Aborting AI deadlock for 36. Please sent LOG file and SAVE.

**Comment by andreas12345** [comment]
I noticed that this often happens when/after NPCs lie down.

**Comment by JAsmine-ja2** [comment]
NPCs lying down? Do you refer to NPCs who are proper characters (names above head) or nameless civilians or enemies?

**Comment by selaux** [comment]
I checked this and it seems to be related to going prone by enemies indeed. The action is always `CHANGE STANCE` and ǹext action `NONE` when the deadlock occurs, but further i couldn't debug.

**Comment by andreas12345** [comment]
I am referring to nameless enemies/militias, sorry if this was not clear.

**Comment by JAsmine-ja2** [comment]
Scanning through #469 leads to the _rough_ idea, that this might be connected to the current map and/or the orientation of the enemy soldier?

**Comment by andreas12345** [comment]
I just watched a longer battle, and it happens every single time when an enemy or militia goes prone.

**Comment by JAsmine-ja2** [comment]
When loading the savedgame from the initial post, I can observe the AI deadlocks when playing with 0.15.x-465pullrequest.

When I load the savedgame on 0.15.1, I almost don't notice the AI deadlocks, because they take MUCH less time.

When I load the savedgame from vanilla JA2, it loads, but the battle doesn't really go on (AI doesn't do anything).
