### ISSUE TITLE
Arrow points in wrong direction when moving squad in map view

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#467]
Moving from G8 to G9, but arrow points from G8 to G7:
![arrow](https://cloud.githubusercontent.com/assets/3011215/21403532/6f2b3edc-c7bd-11e6-9c62-62c7990aa7ac.png)

Version ec77c5e

[QuickSave.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/667177/QuickSave.sav.zip)

**Comment by JAsmine-ja2** [comment]
I can confirm this bug on Stracciatella.

Even more, when trying to move one sector to the north (from G8 to F8), the arrow doesn't appear at all!
![arrow-stracc](https://cloud.githubusercontent.com/assets/17213795/21740991/3a0a29f6-d4ca-11e6-828d-9b771d132bb4.jpg)

On Vanilla JA2, things (in the same savedgame) work as they should:
![arrow-vanilla1](https://cloud.githubusercontent.com/assets/17213795/21741001/6a6f120a-d4ca-11e6-9ba9-826fd70743f4.jpg)
![arrow-vanilla2](https://cloud.githubusercontent.com/assets/17213795/21741002/6a73806a-d4ca-11e6-9893-22ec7d54e4a2.jpg)
