### ISSUE TITLE
Remove #ifdef JA2

### ISSUE THREAD

**Issue by edwbuck** [ja2-stracciatella/ja2-stracciatella#471]
We are not on-the-hook to maintain the sgp code that doesn't apply to Jagged Alliance 2.

We should go through the code removing the JA2 pre-processor directives as if they were unconditionally set.

This would decrease the amount of conditional source code required to be processed by future maintainers, leading to a lighter mental carrying capacity.  Currently there are 12 instances of the JA2 pre-processor define.

**Comment by derSteFfi** [comment]
Strongly pro, as always when we have the chance to get rid of unused code. Some occurences (e.g. in src/game/cheats.cc) are mangled with JA2BETAVERSION, so we should merge #470 first

**Comment by derSteFfi** [comment]
I'm on it. :)
