### ISSUE TITLE
Glitchy opening of locked doors

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#475]
I stumbled upon this glitch/trick in the BP forum: http://thepit.ja-galaxy-forum.com/index.php?t=msg&th=23271&goto=348045&#msg_348045

Basically, you supposedly can open locked doors just by spamming "kick open". It doesn't matter, if your merc is strong enough and you can still kick the door, after the merc has collapsed from being out of energy.

Naturally, I had to test it immediately - **and it works.** I was able to kick open the locked door at the Drassen SAM site with Raven. Now, two problems are present here:

1) Raven with STR=68 shouldn't be able to open the door. It has a lock with lock ID 5 = metal door, which has a smashing difficulty of 80. 

2) (more importantly) A merc without any energy, who just collapsed, shouldn't be able to just get up and kick a door.

![door-test](https://cloud.githubusercontent.com/assets/17213795/21644820/b75c9502-d28f-11e6-9940-29caa2660b8d.jpg)

How to reproduce:
- position the cursor so that the hand cursor appears over the locked door (without pressing ctrl) and so that you can just left-click two times to use the "kick" option without having to move the cursor. There are only a few pixels where this works, but it does work. This makes the following process much easier.
- Now just spam "kick open".
- Raven complains, complains and complains even more until she eventually collapses. Everything okay so far. Keep spamming!!
- She gets up with 0 energy (!) and keeps kicking the door.
- Eventually (took me about 10-20 more kicks, the door opens !!!

The whole process should take less than 2 minutes.

Savegame:
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/684827/SaveGame10.zip)

**Comment by lynxlynxlynx** [comment]
This is handled in AttemptToSmashDoor. Also lock damage comes into play, but more importantly, some randomness. So really, this could all be explained by just giving it enough tries.

**Comment by JAsmine-ja2** [comment]
This might explain issue no.1 - being able to smash a door with insufficent strength seems not okay in an RPG-ish environment, but it can very well be an intended feature and not an oversight by the original devs.

But still the thing with being able to get up and keep on kicking the door although being totally out of energy remains. This is definitely a bug.

**Comment by JAsmine-ja2** [comment]
Some more testing:
This time, I created an IMP with STR=35. She shouldn't be able to ever open the locked door (again in D15). At least, if I understand SkillCheck.cc correctly (which might very well NOT be the case ;). It says that if a chance to succeed in smashing is <30%, then it should NEVER work.
However, after several kicks, I was able to open the locked door again. Took significantly longer as with Raven (STR = 68).

Savegame before and after opening the door:

This shot shows how the IMP is standing... with 0 energy (didn't capture the kicking animation)
![door1](https://cloud.githubusercontent.com/assets/17213795/21651556/58d866c2-d2a9-11e6-8ae8-356dc2d60a4f.jpg)

And the opened door:
![door2](https://cloud.githubusercontent.com/assets/17213795/21651555/58d6b05c-d2a9-11e6-90f6-a704b7a2ac3d.jpg)


[SavedGames.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/685384/SavedGames.zip)

**Comment by flaviojs** [comment]
For a chance of 0, `SkillCheck` returns -99 to 0.
In `AttemptToSmashDoor`, when you fail you also damage the lock if  `iResult > -10`.
Damage to the lock reduces the smash difficulty, which eventually makes the chance >= 30 and then you can succeed.

Doors with LOCK_UNOPENABLE can never be opened because the damage code is never reached.
Doors with OPENING_NOT_POSSIBLE receive damage so they can be opened with enough effort.

It works the same with a crowbar.

Shooting only causes damage if `ubPickDifficulty < 50` and `ubSmashDifficulty < 70`.
Maybe smash/crowbar damage should have the same restriction?

**Comment by flaviojs** [comment]
In `DeductPoints`, setting `bBreathCollapsed = TRUE` when the `bBreath` is 0 will make your soldier collapse when you try to kick the door, but the soldier still tries to turn towards the door.

This is not a real fix because `bCollapsed` is already set.
Maybe put an `Assert` that the soldier is not collapsed when `bNewBreath` is negative to catch invalid breath deductions like this one?

**Comment by flaviojs** [comment]
With #705 the buttons get disabled so it looks like a good fix, but it still tries to turn towards the door.
![705](https://user-images.githubusercontent.com/1009600/60828205-c64d2400-a1a9-11e9-987c-c511657a2d93.png)

**Comment by flaviojs** [comment]
In `InteractWithOpenableStruct`, if you just return when the soldier is collapsed then the menu will not appear.

The had cursor still "flashes red" (looks good) but the body does not "jerk" like when you try to move when you are collapsed.

**Comment by flaviojs** [comment]
Calling `EVENT_InitNewSoldierAnim( &s, PRONE_LAY_FROMHIT, 0 , FALSE );` before returning will make the soldier switch.

And my analysis of this is complete. :)
I'll let someone else fix it, since there are decisions that must be made.

**Comment by lynxlynxlynx** [comment]
Are you saying 705 still adjusts the orientation (or just tries)?

**Comment by flaviojs** [comment]
With only 705, it adjusts the direction.
With 705 + `bBreathCollapsed = TRUE` it tries and collapses in a direction not facing the door.

It's the `EVENT_SetSoldierDesiredDirectionForward(&s, direction)` in `InteractWithOpenableStruct` that makes the soldier try to face the door.
