### ISSUE TITLE
Build error - Win32 - MSVC

### ISSUE THREAD

**Issue by wendles** [ja2-stracciatella/ja2-stracciatella#479]
When building cleanly with either VS2015 or VS2017RC, the build fails due to linker errors against all functions listed in RustInterface.h:
```extern engine_options_t* create_engine_options(char **argv, int argc);
  extern void free_engine_options(engine_options_t *);
  extern char * get_stracciatella_home(const engine_options_t *);
  extern char * get_vanilla_data_dir(const engine_options_t *);
  extern UINT32 get_number_of_mods(const engine_options_t *);
  extern char * get_mod(const engine_options_t *, uint32_t index);
  extern UINT16 get_resolution_x(const engine_options_t *);
  extern UINT16 get_resolution_y(const engine_options_t *);
  extern GameVersion get_resource_version(const engine_options_t *);
  extern void free_rust_string(char *);
  extern bool should_show_help(const engine_options_t *);
  extern bool should_run_unittests(const engine_options_t *);
  extern bool should_run_editor(const engine_options_t *);
  extern bool should_start_in_fullscreen(const engine_options_t *);
  extern bool should_start_in_window(const engine_options_t *);
  extern bool should_start_in_debug_mode(const engine_options_t *);
  extern bool should_start_without_sound(const engine_options_t *);
```

Apparently, even though linker settings appear correct, the linker cannot find these functions defined in stracciatella.dll.lib.

Note that the same clean clone builds correctly on Ubuntu.

**Comment by lynxlynxlynx** [comment]
Did you install rust?

**Comment by wendles** [comment]
Rust is fully installed, the rust portion of the build stage runs completely and generates straciatella.dll.lib along with DLL and related files. The linker actually attempts to find the symbols in sdlmain.lib; I assume just because it doesn't know how to look properly in straciatella.dll.lib.

**Comment by lynxlynxlynx** [comment]
AppVeyor also uses VS2015 and it builds fine. I wonder if we rely on any specific version of rust, though I doubt you have a too old one.

**Comment by wendles** [comment]
Yeah, I admit that I did have 1.10.0 installed, and the build was failing, so I updated to latest.
```
rustc 1.14.0 (e8a012324 2016-12-16)

cargo 0.15.0-nightly (298a012 2016-12-20)
```

**Comment by wendles** [comment]
Fixed. Problem was on my end of course.

Lesson of the day: Ensure your rust toolchain hasn't reset to x86_64.
