### ISSUE TITLE
Assertion failed: Assert(intention != PURSUIT || SectorInfo[sector].ubGarrisonID == NO_GARRISON);

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#480]
Version 5e8749342476bc6ca3fa3a5c67a59fce8d0b1dad

Assertion failed in Strategic_AI.cc, line 4123:
```
/* Make sure that the group isn't moving into a garrison sector. These sectors
* should be using ASSAULT intentions! */
Assert(intention != PURSUIT || SectorInfo[sector].ubGarrisonID == NO_GARRISON);
```

Will try to reproduce.

**Comment by flaviojs** [comment]
For that assert to trigger, a group (of soldiers?) with PURSUIT intention needs to move to a sector that has a garrison.

I only see `InitStrategicAI` setting `ubGarrisonID`.
These should be all the sectors that have a garrison and can trigger the assert:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/3765264455801f6ed8f51ebc51117fcfeed2ed7b/src/game/Strategic/Strategic_AI.cc#L308-L379

**Comment by flaviojs** [comment]
The comment mentions the ASSAULT intention, but the only code that used it was removed because it was inside a JA2BETAVERSION block.

This probably means that the intention was part of a previous AI version, or the intention was part of the next version of the AI.

**Comment by flaviojs** [comment]
Looking at the file history of `Strategic_AI.cc` I found PR #735.

The PR fixes a situation where the assert is triggered.
Maybe we should consider this issue fixed?

**Comment by lynxlynxlynx** [comment]
Yes, looks like a duplicate.
