### ISSUE TITLE
Build fails on Linux x86-64

### ISSUE THREAD

**Issue by johndoe31415** [ja2-stracciatella/ja2-stracciatella#481]
I'm trying to compile git 5e874934. cmake works fine:

<pre>
reliant joe [~/ja2-stracciatella/_bin]: cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting extra data dir to
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
</FindSDL2.cmake>
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found Cargo: /usr/bin/cargo (found version "0.8.0") 
-- Compiling with unittests
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joe/ja2-stracciatella/_bin
</pre>

Building fails, however, almost instantly with some Rust/Cargo error I'm unfamiliar with and that I cannot decipher:

<pre>
reliant joe [~/ja2-stracciatella/_bin]: make
Scanning dependencies of target gtest
[  0%] Building CXX object dependencies/lib-gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  0%] Linking CXX static library libgtest.a
[  0%] Built target gtest
Scanning dependencies of target slog
[  0%] Building C object src/slog/CMakeFiles/slog.dir/slog.c.o
[  0%] Linking C static library libslog.a
[  0%] Built target slog
Scanning dependencies of target rust-build
failed to parse manifest at `/home/joe/ja2-stracciatella/rust/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:26:9 expected a key but found an empty string
Cargo.toml:26:9-26:10 expected `.`, but found `'`

rust/CMakeFiles/rust-build.dir/build.make:57: recipe for target 'rust/CMakeFiles/rust-build' failed
make[2]: *** [rust/CMakeFiles/rust-build] Error 101
CMakeFiles/Makefile2:716: recipe for target 'rust/CMakeFiles/rust-build.dir/all' failed
make[1]: *** [rust/CMakeFiles/rust-build.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

This is on Linux x86-64 4.5.2, the disto is Mint Sarah 18 (essentially Ubuntu 16.04 with a non-sucky window manager).

Please advise if I'm doing anything wrong or what I can contribute to debug the issue further.

**Comment by Manuel-K** [comment]
As a workaround, you could remove the last four lines of `rust/Cargo.toml`.

Could you tell us the version of Cargo (i.e. `cargo -V`) that you have? According to http://doc.crates.io/specifying-dependencies.html it should work with Cargo >= 0.9.0.

**Comment by johndoe31415** [comment]
Indeed solves the problem, thank you very much! My version comes with the distro and it is 0.8.0:

<pre>
$ cargo -V                                                                                                                       
cargo 0.8.0 (built 2016-03-22)
</pre>

Thank you again for your help, Manuel!

**Comment by johndoe31415** [comment]
Something that I wonder: cmake already figured out that I was using 0.8.0. So if 0.9.0 is required, wouldn't it be better if cmake already complained? That'd spare you tickets of rookies like myself :-)

**Comment by Manuel-K** [comment]
Yes, I think that would be a good idea. 

@selaux: This seems to be your issue. ;-)

**Comment by lynxlynxlynx** [comment]
It's a oneliner in rust/CMakeLists.txt as find_package can take a version parameter. :)

**Comment by Manuel-K** [comment]
Of course, but which version?

**Comment by Manuel-K** [comment]
@lynxlynxlynx: see #483

**Comment by Manuel-K** [comment]
That's annoying. Anyone using the newest Ubuntu LTS release is stuck with a version of rust/cargo that is too old (not in backports either). At least it is only a build time dependency.

**Comment by Manuel-K** [comment]
@johndoe31415  Can this be closed?

**Comment by selaux** [comment]
I will close this now. To get a more recent rust/cargo version use [rustup](http://rustup.rs/)
