### ISSUE TITLE
Mac OS Sierra Russian font bug

### ISSUE THREAD

**Issue by hackvanru** [ja2-stracciatella/ja2-stracciatella#485]
Hello. I use the compiled version ja2-v0.15.1-macos from your site and watch just such a problem (see screenshots in the attachment) with fonts in some places.

OS: macOS Sierra 10.12.2
![2017-01-22 20 43 27](https://cloud.githubusercontent.com/assets/2846505/22184539/d008781a-e0e4-11e6-9a76-dea86189b128.png)
![2017-01-22 20 42 59](https://cloud.githubusercontent.com/assets/2846505/22184541/d008ab28-e0e4-11e6-9b1f-27e5466f2f7e.png)
![2017-01-22 20 44 03](https://cloud.githubusercontent.com/assets/2846505/22184542/d0095c9e-e0e4-11e6-9816-ff6973463d4e.png)
![2017-01-22 20 43 12](https://cloud.githubusercontent.com/assets/2846505/22184543/d009907e-e0e4-11e6-931d-e10923c0d4dd.png)
![2017-01-22 20 43 17](https://cloud.githubusercontent.com/assets/2846505/22184540/d0087d9c-e0e4-11e6-868c-a73d9240b35c.png)

**Comment by selaux** [comment]
Do we actually have anybody on macOS who can have a look at this?

**Comment by flaviojs** [comment]
This probably has the same root cause as issue #487, `vswprintf` failing in mac if the runtime locale is different from the compile time locale: https://stackoverflow.com/a/15440423

**Comment by flaviojs** [comment]
After looking into lots of locale stuff, the issue is probably the encoding of the locale and how the locale handles characters that can't be represented.

As long as we use a locale that has an encoding that can represent unicode (like utf-8), everything should work.
