### ISSUE TITLE
"ERROR saving the game" after Ivan has arrived

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#487]
When Ivan arrives, the game log shows an entry "???":
![ivan](https://cloud.githubusercontent.com/assets/3011215/22186513/77d2dc5e-e0f7-11e6-8b7d-342b3b5e6f46.jpg)

At the same time, the console starts showing invalid character messages:
```
2017/00/22 22:59:11 ERROR   [Font            ] Invalid character given U+7FB5
2017/00/22 22:59:11 ERROR   [Font            ] Invalid character given U+0010
2017/00/22 22:59:11 ERROR   [Font            ] Invalid character given U+F4050170
```

And from this point on, saving the game fails with the message "ERROR saving the game", and the savegame slot where I attempted to save gets deleted.

How to reproduce: load the 
savegame:
[QuickSave.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/722304/QuickSave.sav.zip)

Fast forward time for a couple of hours, try to save.

**Comment by derSteFfi** [comment]
Hey,
thanks for reporting this.

This looks like the english version, right? If Yes, which one (gold, ...)? And which version of ja2-stracciatella are you on?

**Comment by andreas12345** [comment]
Yes, this is the English version from gog.com (https://cdn.gog.com/secure/jagged_alliance_2/mac/jagged_alliance_2_2.0.0.4.dmg).

Straciatella version is 5e8749342476bc6ca3fa3a5c67a59fce8d0b1dad.

**Comment by selaux** [comment]
Hm, might be GOG specific. For me Ivan reports his arrival (text contains some Russian characters).

What OS are you using (since we saw a lot of Sierra specific stuff)?

![screenshot from 2017-02-08 19-08-48](https://cloud.githubusercontent.com/assets/848854/22750711/19020aa4-ee32-11e6-9217-72ef528fb87f.png)

**Comment by andreas12345** [comment]
I'm using Sierra (10.12.3).

**Comment by flaviojs** [comment]
Can't reproduce in linux.
Those invalid character are probably from an uninitialized string (U+F4050170 is too big to be a valid codepoint).

Seeing `vswprintf` in Font.cc as a potential source of the unitialized string, I searched if it could fail and found this: https://stackoverflow.com/a/15440423
In mac it can fail if the runtime locale is different from the compile time locale.

There are two ways of fixing this:
1) record the locale at compile time and set it at runtime (maybe only in mac builds)
2) transition wchar stuff to utf8 stuff

**Comment by flaviojs** [comment]
I tried to transition code from wchar to utf8 but there are too many places that need to change for my taste.

I can't reproduce it here (not mac) so I can't try the locale approach.
Can someone add a runtime test for this that fails in the mac travis build?

**Comment by flaviojs** [comment]
Found a possible solution!
vim initializes the locale in mac by setting the `LANG` environment variable from CoreFoundation data and calling `setlocale(LC_ALL, "")`:

https://github.com/vim/vim/blob/4bd782339e370bde82c2a8976df9f335cc12eba9/src/os_mac_conv.c#L565-L585

https://github.com/vim/vim/blob/4bd782339e370bde82c2a8976df9f335cc12eba9/src/option.c#L369-L403

**Comment by flaviojs** [comment]
After looking into lots of locale stuff, the issue is probably the encoding of the locale and how the locale handles characters that can't be represented.

As long as we use a locale that has an encoding that can represent unicode, everything should work.
