### ISSUE TITLE
cant compile with linux / rust issues

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#493]
Hi there!

cmake .  spits out:

-- Setting extra data dir to
<FindSDL2.cmake>
</FindSDL2.cmake>
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Compiling with local RapidJSON libraries from /home/richard/src/JaggedAlliance2/ja2-stracciatella/dependencies/lib-rapidjson
CMake Error at CMakeLists.txt:108 (add_subdirectory):
  add_subdirectory given source
  "/home/richard/src/JaggedAlliance2/ja2-stracciatella/rust" which is not an
  existing directory.

-- Compiling with unittests
-- Compiling with local GTest libraries from /home/richard/src/JaggedAlliance2/ja2-stracciatella/dependencies/lib-gtest
CMake Error at CMakeLists.txt:159 (get_property):
  get_property could not find TARGET rust-stracciatella.  Perhaps it has not
  yet been created.

however creating the rust directory leads to:

<FindSDL2.cmake>
</FindSDL2.cmake>
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Compiling with local RapidJSON libraries from /home/richard/src/JaggedAlliance2/ja2-stracciatella/dependencies/lib-rapidjson
CMake Error at CMakeLists.txt:108 (add_subdirectory):
  The source directory

    /home/richard/src/JaggedAlliance2/ja2-stracciatella/rust

  does not contain a CMakeLists.txt file.

-- Compiling with unittests
-- Compiling with local GTest libraries from /home/richard/src/JaggedAlliance2/ja2-stracciatella/dependencies/lib-gtest
CMake Error at CMakeLists.txt:159 (get_property):
  get_property could not find TARGET rust-stracciatella.  Perhaps it has not
  yet been created.

So where to I get the CMakeLists.txt file in the rust directory?

**Comment by Manuel-K** [comment]
You don't have to create the `rust` subdirectory!

The subdirectory is part of source code. It should contain the necessary `CMakeLists.txt` and a `src` folder with `straciatella.rs`. Where did you get the source code? If it is a git clone, can you check `git status` to see if it has been removed accidentally?

**Comment by misanthropos** [comment]
That was exactly it... thank you.
