### ISSUE TITLE
ALT+O cheat can't damage tanks

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#503]
ALT+O cheat can't damage tanks - this is how it always worked. I guess, we'll never know if this was intended or if it is an oversight.
I think, this has some relevance, because the tanks are the most dangerous enemies, the player faces in the game (maybe together with stange biological experiment creatures and bloodcats). If the cheat is needed somewhere, then here, right?
What do you think - should the option for the ALT+O cheat to damage tanks be added to Stracciatella?

**Comment by selaux** [comment]
Imho killing tanks as well should be the default as it should kill all enemies...

**Comment by selaux** [comment]
@JAsmine-ja2  Can you provide a savegame with tanks in it?

**Comment by JAsmine-ja2** [comment]
[tank-test.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/848076/tank-test.zip)

Here you go. Savegames with tanks. :)

**Comment by selaux** [comment]
@JAsmine-ja2 Current master should now kill everything (tanks, creatures)

**Comment by JAsmine-ja2** [comment]
Great news! This is imo a very nice, useful and AFAIK Stracciatella-exclusive feature!
