### ISSUE TITLE
specific cheat not working?

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#505]
Quote from the JA2 manual cheats section:

SPACE while left-clicking merc Forces any “away” character to join team.

This is supposed to work in the Laptop. I can't remember ever using this cheat and I can't make it work in either vanilla JA2 Gold or in Stracciatella. Can someone confirm if this cheat works (or ever worked) as it should?

**Comment by lynxlynxlynx** [comment]
There's no code for that, closing.
