### ISSUE TITLE
can't load webpages

### ISSUE THREAD

**Issue by kavol** [ja2-stracciatella/ja2-stracciatella#510]
Except for the I.M.P. web, I cannot get past the homepage of individual services - cannot buy weapons from Bobby, cannot hire mercs at A.I.M. ...
Clicking on some option from the respective web homepage, I get "Downloading ..." but it stays on the homepage, and on subsequent clicks on the same option it says "Reloading" and doesn't get me anywhere.
[noweb.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/869389/noweb.zip)

**Comment by kavol** [comment]
reverting commit db7fa39972e61cbb58a39e6e210c23220cdb7c0b helps my issue

**Comment by kavol** [comment]
hm, now I see RinneT already mentions that in the commit comments ...

**Comment by lynxlynxlynx** [comment]
Yeah, pick one bug or the other.

**Comment by Manuel-K** [comment]
I'm working on another fix for the laptop mode crash that outputs a warning at problematic places, but so far I haven't managed to trigger the bug. I've only seen it once and never managed to recreate it. 

Any tips?

**Comment by Manuel-K** [comment]
It turns out that I had trouble to trigger the laptop crash because I was clicking too fast while thinking I was clicking too slow.
