### ISSUE TITLE
Game crash when inserting ceramic plates

### ISSUE THREAD

**Issue by elandesign** [ja2-stracciatella/ja2-stracciatella#516]
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Opening file 'sounds/ceramic armour insert.wav' failed
```
Is the sound file is missing or incorrectly named?
Save game file: [error.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/907429/error.sav.zip)

**Comment by Manuel-K** [comment]
I don't know anything about that specific file, but we should probably add a `try{} catch{}` block to `SoundLoadDisk`…

**Comment by Manuel-K** [comment]
@elandesign:

Could you test #518, please?

**Comment by lynxlynxlynx** [comment]
@JAsmine-ja2 can you please look up the real filename, if it exists?

The data is hardcoded in https://github.com/ja2-stracciatella/ja2-stracciatella/blob/409ae2a2f9c8ab03800a87bc9527d82534d81939/src/game/Utils/Sound_Control.cc#L237

**Comment by JAsmine-ja2** [comment]
The filename is
ceramic armor insert.wav (without "u")
in the sound.slf archive.

**Comment by selaux** [comment]
@JAsmine-ja2 Thx, I just right now wanted to write the same 🙂 . I dont know whether this is language specific. For some languages the sound might indeed be `armour`. In general in my oppinion we should be cautious with PRs like https://github.com/ja2-stracciatella/ja2-stracciatella/pull/518 as they will mask errors which we will probably seldomly rediscover. Maybe it would make sense to still do it, but with asserts, so we get at least notice the error in development builds?

**Comment by Manuel-K** [comment]
That's true, without the uncaught exception, we wouldn't have gotten the bug report, **but** the worst thing we can do is crash the game for some minor thing – that will make a bad impression and might make us lose users.

IMO we should add a test that checks if all hardcoded paths exist.

**Comment by lynxlynxlynx** [comment]
Yeah, on the same page as Manuel. It may be better for us as developers, but it would definitely suck for the user.

@selaux did you manage to trace it somewhere? IOW was the sound name ok in the original?

Armour is the British spelling, so it could be true that these things would actually need to be set per-language. However I think the list is so long it would have been noticed much earlier already. I guess a sound.sif dump of the russian, german ... version would be useful.

**Comment by selaux** [comment]
@Manuel-K Yes, I agree with you on this one as well. I mean I don't want the release version to crash on things like this either. But imho someone running on current master with `CMAKE_BUILD_TYPE=Debug` should not expect the same stability guarantees as someone running a release build. That is why I suggested the asserts appoach, which will run fine with `CMAKE_BUILD_TYPE=Release` but crash with `CMAKE_BUILD_TYPE=Debug`.

@lynxlynxlynx I did not search further as I had a look at the rust pr. Checking hardcoded paths sounds fine to me. This is where [ja2-stracciatella/ja2-open-toolset](https://github.com/ja2-stracciatella/ja2-open-toolset) could become useful again. We just need data files for all languages (should be possible via steam, idk if possible via GOG or something else).

**Comment by lynxlynxlynx** [comment]
GOG only has the English one.

**Comment by Manuel-K** [comment]
But there seems to be an unofficial german patch: https://www.gog.com/forum/general_de/sammelthread_zu_deutschmods_und_sprachpatches_fur_spiele_die_hier_nur_auf_englisch_erhaltlich_sin/post62

**Comment by JAsmine-ja2** [comment]
I'm 99% sure, that JA2 didn't see a special localization for British English.
I have german and english data files in my possession.

**Comment by selaux** [comment]
So maybe, just fix and wait for other complaints 😉 ?

@Manuel-K @lynxlynxlynx What do you think about the asserts idea? Maybe we can make the implications of `CMAKE_BUILD_TYPE` more transparent in compile docs, so people can decide more easily on how to build?

**Comment by lynxlynxlynx** [comment]
As long as something is still logged, sure. These paths belong to external/ too.

So we don't really know if this is our issue or if it was present in the original already?

**Comment by selaux** [comment]
I checked out one of the first commits (e01fa6f36583f39ef8491dcaf67f9e7bf7666784) and voila: `"SOUNDS\\Ceramic Armour Insert.wav"`. So this seems to be there from the beginning...

**Comment by selaux** [comment]
@elandesign Could you please provide a savegame or test #519?

**Comment by Manuel-K** [comment]
I think we should add a new type of slog command that adds a message at the bottom of the log stating "something interesting happened. please send the log to the developers…". Obviously it would only be read by users running the game from a console, but it could be useful for us as well.
