### ISSUE TITLE
Sound file exception: doorcr_b.wav

### ISSUE THREAD

**Issue by elandesign** [ja2-stracciatella/ja2-stracciatella#520]
Another missing sound file. I've not updated my binary from master yet which would have caught and handled the exception, but I figured someone would want to know about this one to correct the filename.

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Opening file 'sounds/doorcr_b.wav' failed
```

Save file: [error.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/923093/error.sav.zip)
(the exception occurs when a merc dies, so not sure if this save file will be useful)

**Comment by selaux** [comment]
For me only `doorcr` (without `_b`) exists.

**Comment by Manuel-K** [comment]
`doorcr` is not referenced in the source code. Only `doorcr_b` is (in `src/game/Utils/Sound_Control.cc`).
