### ISSUE TITLE
Getting "Reading from file failed" when fast forwarding time after savegame load

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#528]
Whenever I load the savegame and then want to forward the time, the game crashes with this message:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Reading from file failed
Creating an emergency savegame succeeded (error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame.
Aborted
```

I attached the created savegame. I can also attach one of my own if needed.
[error.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1034563/error.zip)

**Comment by lynxlynxlynx** [comment]
What version are you using?

**Comment by Manuel-K** [comment]
Some information about your operation system might also be useful.

Please attach the other savegame as well.

**Comment by Tercus** [comment]
I compiled the latest sourcecode under KDE neon (based on ubuntu 16.04). The compilation worked perfectly and the game ran smoothly for quite some time. No problems with saving or loading saves. It just started one day and affected all savegames.

I can still use older savegames I had around and fast-forward time there.

**Comment by Tercus** [comment]
Here are all the Savegames from my playthrough so far.

[SavedGames.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1044908/SavedGames.zip)

**Comment by Tercus** [comment]
I was able to avoid a crash by loading a savegame, going into the sector and leaving the sector "manually". Since I was in a town, the 5 minutes had passed and from then on I was able to use fast forward again.

**Comment by Manuel-K** [comment]
I'll try to reproduce the crash tomorrow.

Which `CMAKE_BUILD_TYPE` did you use?

**Comment by Tercus** [comment]
CMakeCache.txt tells me I used this:
`//Choose the type of build, options are: Debug RelWithDebInfo.
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo`

I hope that's the right info you needed.

**Comment by Manuel-K** [comment]
The crash is related to ambient sounds. Apparently `LoadAmbientControlFile()` is never called and therefore `gAmbData` is not initialized which in turn makes `SetupNewAmbientSound()` make a chain of calls that end with `SoundLoadDisk()` being called with an empty string (`""`) as argument.

**Comment by Tercus** [comment]
may I ask how you managed to trace back the error? I'd like to be more helpful, but my knowledge is limited in that area...

**Comment by Manuel-K** [comment]
The back trace wasn't useful, so I searched the source code for "Reading from file failed" and added a break point to the corresponding line while running the game in a debugger.

**Comment by selaux** [comment]
Is this a candidate for retest? Looks like there was a PR fixing it.

**Comment by lynxlynxlynx** [comment]
The initial bug is fixed where it crashed, but this was left open to address the root cause, at some point. Could be a separate item, linking back.
