### ISSUE TITLE
Alt-Click action conflict under linux

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#533]
using Alt-click to move backwards or do other actions does not work for me under KDE neon (ubuntu 16.04), because that is also the shortcut to move windows.

Is there any way to make the keybindings configurable? I've seen that new ones have been implemented, so maybe the existing ones could be changed?

**Comment by lynxlynxlynx** [comment]
kwin is the problem here. You may be able to avoid the problem via special window settings, but I'm not sure we can signal alt+mouse is taken from within the app.

**Comment by Tercus** [comment]
is it possible to alter the key combination in the game? For example to set it to Tab+click or something like that?

**Comment by Tercus** [comment]
In input.cc I changed
```
		case SDLK_LALT:
		case SDLK_RALT:
			gfKeyState.set(ALT);
			break;
```
to
```
		case SDLK_LALT:
		case SDLK_RALT:
		case SDLK_h:
			gfKeyState.set(ALT);
			break;
```
and it worked nicely. Now I can use `h` as a key. I'll look further into it and maybe try to externalize the keys.

**Comment by Manuel-K** [comment]
>I also noticed, that the right ALT key is not recognized. The game ignores it and kwin doesn't use it either. Does anyone know what could be the cause?

The game should handle left ALT and right ALT the same way:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/Input.cc#L311

**Comment by Tercus** [comment]
It should, but doesn't. Could be an OS thing, but I don't know how to test that.

Also I noticed that after I added the "h" key as another button, using that results in me not being able to select any other character afterwards. Could it be that I also have to unset the gfKeyState somewhere?

**Comment by Manuel-K** [comment]
Sorry. My answer wasn't very useful. I guess I didn't read your comment carefully enough. I assumed that you were changing `src/game/Tactical/Turn_Based_Input.cc`.

**Comment by lynxlynxlynx** [comment]
Does this also happen if you enable mouse grab (pressing scroll lock)?

**Comment by lynxlynxlynx** [comment]
/.../ It  doesn't, so that's a good workaround.

Just using shift as well in the combo works fine too.

**Comment by Ulukai85** [comment]
When I hold ALT + LeftClick, nothing happens (trying to crawl backwards for example).

Playing under Ubuntu and normally there that Combo moves desktop windows. That collided somewhere else some time ago, so I changed it to CTRL + ALT + LeftClick.

So that can't be the Problem. Can someone help? Am I stupidly overlooking something?

**Comment by lynxlynxlynx** [comment]
Still works for me, also on ubuntu. Version? Are you testing in accessible areas?

**Comment by lynxlynxlynx** [comment]
Is there space to move back? The square being accessible, not just visible. JA2S version?

**Comment by Ulukai85** [comment]
Yeah, is accessible, tried it  on Different locations and mercs, standing, crawling, crouching. The higher movement cost is always shown. Version is

**Comment by lynxlynxlynx** [comment]
I bet you have another global hotkey bound. Like I said before, another workaround is to also press shift.

**Comment by flaviojs** [comment]
Same thing is happening to me in **Cinnamon 3.0.7** (Linux Mint 18 Sarah).
Followed https://forums.linuxmint.com/viewtopic.php?p=758145#p758145 to disable global alt-click:
> go to: system settings --> windows
> locate "modifier to use for modified window click actions"
> change it from "Alt" to nothing.

xev tells me that ButtonPress/ButtonRelease events are never received with global alt-click active:
[xev-with-global-alt-click.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2959676/xev-with-global-alt-click.log)
[xev-without-global-alt-click.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2959678/xev-without-global-alt-click.log)

Not sure if it's possible... can we cancel/reject the window grab when we receive a LeaveNotify event with NotifyGrab mode?

**Comment by lynxlynxlynx** [comment]
How would that work, these things are captured by the WM, not the app. See the previous discussion on the several workarounds.
