### ISSUE TITLE
Position of Mercenary task orders in Tactical screen

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#537]
I Tactical screen, right-clicking a mercenary let's you give them a task (training, repairing, etc). The position of that little window is a bit off. I guess it should position itself next to the mercenary, but instead it is somewhere else:
![screenshot_20170604_175226](https://cloud.githubusercontent.com/assets/3085791/26764319/f3a63846-4964-11e7-8f7d-fffbec18ca79.png)
![screenshot_20170604_175241](https://cloud.githubusercontent.com/assets/3085791/26764320/f3a68864-4964-11e7-8613-c972d3b43d6f.png)
It appears that the further down to the visible screen a mercenary is, the more worse the position of the little window becomes.

I'm playing with 1680x1050 on KDE neon (based on ubuntu 16.04). Can anyone confirm that bug?

**Comment by JAsmine-ja2** [comment]
I can confirm this bug on Windows, playing with Stracciatella 0.15.1
This seems to be related to the higher resolution, as it works on the standard 640x480 resolution.

**Comment by Manuel-K** [comment]
That confirms my suspicions. It looks like another scaling bug.

**Comment by derSteFfi** [comment]
please test this PR, worked fine for me.

**Comment by Manuel-K** [comment]
@derSteFfi Do you really want to keep this open?

**Comment by derSteFfi** [comment]
hm, I guess it is not an open issue in that sense. but IF we ever get to smoothless scrolling, we should remember. Lets just hope one of us will :)

**Comment by Manuel-K** [comment]
Maybe we should create a new tag for this kind of issues.

**Comment by Manuel-K** [comment]
Perhaps "future"?

**Comment by derSteFfi** [comment]
thats an idea.

**Comment by lynxlynxlynx** [comment]
won't it be obvious? And anything not specifically categorized is "for the future" anyway.

**Comment by Manuel-K** [comment]
If it is not closed, it is obviously for the future.
