### ISSUE TITLE
Right ALT key doesn't work the same as left ALT key

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#539]
Because it was mentioned here: #533

In both vanilla and Stracciatella, the right ALT key (ALT Gr) doesn't work the same as the left ALT key. Instead, it works like the CTRL key.

So I can bring up the hand cursor with the left CTRL key, the right CTRL key AND the right ALT key.
I can make my mercs strafe or walk backwards with only the left ALT key.

Is this intended? Is the right ALT key really supposed to work like the left ALT key?

Vanilla 1.12 English
Stracciatella 0.15.1

Windows 8.1

**Comment by Tercus** [comment]
Found a solution. After searching around for this error, I found [this forum thread](http://forums.libsdl.org/viewtopic.php?t=8590), which explains it a bit, but doesn't solve it. ALT GR is (or can be) emulated by CTRL+ALT. Some keyboards have a right ALT button, which is *not* the same as the ALT GR button. Checking for RALT thus isn't always enough.

But, after finding [this table](http://www.jose.it-berater.org/sdl/core/sdl_keysym.htm), I tried adding SDLK_MODE and that worked perfectly:
```
		case SDLK_LALT:
		case SDLK_RALT:
		case SDLK_MODE:
			gfKeyState.set(ALT);
			break;
```

**Comment by Manuel-K** [comment]
A question to both of you: What keyboard layout do you use?

A second question for @Tercus: Can you please post the output of `localectl` or something similar?

**Comment by Manuel-K** [comment]
I'll try to upload my simple SDL2 key test application that displays the name of the pressed key later.

**Comment by JAsmine-ja2** [comment]
I use a german keyboard layout.

**Comment by Manuel-K** [comment]
I've attached the test program. sdl2-key-test-src.zip contains the source code with a makefile that works on Linux. sdl2-key-test-win.zip contains an exe that I created using the mxe cross compilation environment and the source code with a modified makefile.

If you press a key while the window is focused, it should display messages on the terminal (on Windows it should open a terminal automatically). On my Windows 8.1 system AltGr is recognized as Left Ctrl and Right Alt. On all Linux systems that I tested AltGr is recognized as Right Alt.

[sdl2-key-test-src.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1054841/sdl2-key-test-src.zip)
[sdl2-key-test-win.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1054842/sdl2-key-test-win.zip)

**Comment by Tercus** [comment]
I use a german keyboard layout as well, but my OS language is English. Output of localectl:
```
   System Locale: LANG=en_GB.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc105
     X11 Variant: nodeadkeys
```
@Manuel-K, I've tested your program I pressed the following button sequence: left CTRL, left ALT, right ALT, right CTRL and this is the output:
```
KeyEvent: Left Ctrl down                                                                                                            
KeyEvent: Left Ctrl up                                                                                                              
KeyEvent: Left Alt down                                                                                                             
KeyEvent: Left Alt up                                                                                                               
KeyEvent:  down                                                                                                                     
KeyEvent:  up                                                                                                                       
KeyEvent: Right Ctrl down
KeyEvent: Right Ctrl up
```

**Comment by Manuel-K** [comment]
@Tercus Strange. Can you run the test program with `LC_ALL=c` and `LC_ALL=de_DE.utf8`?

**Comment by Tercus** [comment]
I get the same output for all of that :/

**Comment by lynxlynxlynx** [comment]
how about xev? Which key/scancodes does it print?

**Comment by Tercus** [comment]
```
KeyPress event, serial 40, synthetic NO, window 0x5000001,
    root 0x157, subw 0x0, time 14017495, (145,4), root:(1105,33),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x5000001,
    root 0x157, subw 0x0, time 14017623, (145,4), root:(1105,33),
    state 0x90, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by Manuel-K** [comment]
Weird. I get 
```
KeyPress event, serial 45, synthetic NO, window 0x3000001,
    root 0xd7, subw 0x0, time 53739519, (885,580), root:(886,604),
    state 0x0, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 48, synthetic NO, window 0x3000001,
    root 0xd7, subw 0x0, time 53739642, (885,580), root:(886,604),
    state 0x80, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
which seems to be the same.

What SDL2 version do you use?

**Comment by Tercus** [comment]
I think it is 2.0.4

**Comment by lynxlynxlynx** [comment]
So it sends ctrl as well; here's the sdl bug that was eventually reported:
https://github.com/libsdl-org/SDL/issues/5685
We could special-case it like @momoko-h just did for #1844, but adding SDLK_MODE to the two case statements sound better. It's just another modifier key. The wayland backend does exactly that as well:
https://github.com/libsdl-org/SDL/blob/d3f2de7f297d761a7dc5b0dda3c7b5d7bd49eac9/src/video/wayland/SDL_waylandevents.c#L1022
