### ISSUE TITLE
After travel, mercenaries spawn on the same spot

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#541]
After travelling from sector F10 through Cambria to G9, and then going into tactical view, some of my mercenaries spawned on top of each other. Savegame attached.

~[SaveGame09.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1056408/SaveGame09.zip)~ (not needed, read on)

**Comment by Tercus** [comment]
okay, weird. after reloading the game, they all had their normal position.

**Comment by Tercus** [comment]
the bug seems to be reproducible though. Load this savegame and travel to Cambria G9 and change to tactical view upon arrival. The mercs are all positioned on two tiles. Saving there and loading again spreads them out as it should be.
[SaveGame06.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1056413/SaveGame06.zip)

**Comment by lynxlynxlynx** [comment]
I suspect we already have a bug open for this, but thanks for the detailed report.

**Comment by JAsmine-ja2** [comment]
@lynxlynxlynx you're right. It's  #404

**Comment by lynxlynxlynx** [comment]
Thanks, I'll close this one then.
