### ISSUE TITLE
Enemy impossible to target

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#545]
In [this savegame](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1059257/SaveGame10.zip) is an enemy, that is impossible to target. Only once he lay down, I was able to even see him.

I realize that this also happens in vanilla Jagged Alliance, but maybe this can somehow be fixed?
![screenshot_20170607_221416](https://user-images.githubusercontent.com/3085791/26900253-e7d9ec3c-4bd1-11e7-9b27-e2d5747b2214.png)

**Comment by lynxlynxlynx** [comment]
Sounds like a line of sight thing, so not necessarily a bug.

**Comment by Tercus** [comment]
the problem was not that I wasn't able to shoot at the enemy. The problem is that the enemy can walk somewhere, where I can simply not see him as a player, because my view is obstructed by the bar "Player's turn" at the top. Similar things also happened in vanilla, but it was never this bad. In the savegame, the enemy is lying, but while he was standing, he was completely invisible to me and I also couldn't target him, because I then got the "leave sector" cursor.

What I was wondering is, if the game has any rules as to how far to the edge of a map the enemy is allowed to walk and if that could be changed.

**Comment by lynxlynxlynx** [comment]
We changed the leave area cursor to show 4px sooner for usability reasons. We tried showing one more tile row/col in all maps to avoid the vanilla headshot bug, but that brought new (cosmetic) problems. Whether it would be safe to reduce the spawning area remains to be tested.

**Comment by JAsmine-ja2** [comment]
I guess, we already have a similar report already: #195 ?
