### ISSUE TITLE
Area select rectangle not removed if interrupted

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#550]
If you create an area of selection (left mouse-button + drag) and you get interrupted by an action of one of your mercenaries, that rectangle stays.
![screenshot_20170608_232530](https://user-images.githubusercontent.com/3085791/26952162-82bfcbd6-4ca4-11e7-8c52-07e644b0a34e.png)

To reproduce with [this savegame](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1062504/SaveGame10.zip):
1. Select Player Terces to open the last door
1. create a selection rectangle and hold it
1. be interrupted by the "how to open the door" window.

**Comment by JAsmine-ja2** [comment]
I can confirm this bug on Vanilla and Stracciatella.
However, the rectangle can easily be "clicked" away and doesn't stay permanently - still a bit annoying.
