### ISSUE TITLE
ingame help cannot be viewed

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#552]
I cannot view the ingame help. It also doesn't show up when I start a new game. Can anyone confirm that problem?

**Comment by JAsmine-ja2** [comment]
![screen002](https://user-images.githubusercontent.com/17213795/26963795-ac3173d0-4cee-11e7-8ea2-baa949fb18e4.jpg)

I can't confirm this. I can bring up the ingame help by pressing 'h' as intended.
Stracciatella 0.15.1 on JA2 1.12 Gold English, Windows 8.1

**Comment by derSteFfi** [comment]
can't confirm either. on all screens except options/save/load the help pops up when pressing h

**Comment by Tercus** [comment]
yupp, must have been a weird coincidence. recompiled everything and now it works again.
