### ISSUE TITLE
The rust cli parser does not accept relative paths

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#559]
Discovered during testing of #515.

**Comment by Manuel-K** [comment]
Should be solved.

**Comment by selaux** [comment]
Retested and works for me. I didn't test on Windows though...

**Comment by Manuel-K** [comment]
Can someone test this one Windows, please?

**Comment by selaux** [comment]
Tested on Windows. Works.
