### ISSUE TITLE
CI fails on rust test (master)

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#562]
```
thread 'tests::parse_args_should_abort_on_unknown_switch' panicked at 'assertion failed: `(left == right)` (left: `"Unrecognized option: \'testunknown\'"`, right: `"Unrecognized option: \'testunknown\'."`)', src/stracciatella.rs:575
```

Affects Travis and AppVeyor.

Very strange. The left argument seem to be generated by `getopts::Options` method `parse`. On my system the test passes.

**Comment by Manuel-K** [comment]
The test was changed 8 months ago.

**Comment by Manuel-K** [comment]
The CIs use Cargo 0.19.0 and Rustc 1.18.0.

I'm still on Cargo 0.18.0 and Rustc 1.17.0.

**Comment by Manuel-K** [comment]
Found the problem: https://github.com/rust-lang-nursery/getopts/commit/137475053934a5fb86c95f93b669885c95a71fcf

**Comment by Manuel-K** [comment]
@lynxlynxlynx Should we remove the offending `.` to fix the CI issue now? It would break the rust unit tests for older versions of `getopts`, but IMO the automatic tests are more important.

Someone should definitely create a better version later.

**Comment by lynxlynxlynx** [comment]
fine with me. We can add regex matching later if needed.

**Comment by Manuel-K** [comment]
Done.

**Comment by Manuel-K** [comment]
Who wants to do the real fixing? @selaux?
