### ISSUE TITLE
Attacking teammate(dialogue) on roof puts him through the roof

### ISSUE THREAD

**Issue by daviel** [ja2-stracciatella/ja2-stracciatella#567]
If you attack a merc on a roof and he/she is saying something the merc will be put on the ground level through the roof.
This does not happen with merc which just shoot back.

![1](https://user-images.githubusercontent.com/9992455/28065646-c8b8a0c8-6639-11e7-8849-4c245e67c882.jpg)

![2](https://user-images.githubusercontent.com/9992455/28065652-cbe6fc22-6639-11e7-9afd-1de37c50d251.jpg)

![3](https://user-images.githubusercontent.com/9992455/28065654-ce4c87d4-6639-11e7-98ff-7145689f816c.jpg)

Save:
[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1138638/QuickSave.zip)

**Comment by chmallon** [comment]
I guess this happens because ChangeSoldierTeam() does not copy bLevel.
