### ISSUE TITLE
Jagged alliance 2

### ISSUE THREAD

**Issue by Belial03** [ja2-stracciatella/ja2-stracciatella#588]
When i first turned on jagged alliance 2 i was exited but the game was very laggy and unplayable. Im trying to play it on windows 10 please help

**Comment by JAsmine-ja2** [comment]
Could you please be a bit more specific about your problem?
Can you provide some more specs like version no of JA2 (e.g. 1.02 or 1.12 Gold) and version no of Stracciatella?
Does JA2 (without Stracciatella) work without lag?

**Comment by JAsmine-ja2** [comment]
Due to lack of useful information and a very vague description, I'll close this issue.
