### ISSUE TITLE
failure when building on msys2

### ISSUE THREAD

**Issue by askondro** [ja2-stracciatella/ja2-stracciatella#590]
make
[  0%] Built target gtest
[  0%] Built target slog
warning: unused manifest key: package.release-debuginfo
       Fresh winapi-build v0.1.1
       Fresh itoa v0.1.1
       Fresh winapi v0.2.8
       Fresh num-traits v0.1.40
       Fresh dtoa v0.2.2
       Fresh libc v0.2.29
       Fresh serde v0.8.23
       Fresh getopts v0.2.14 (https://github.com/rust-lang-nursery/getopts?rev=b8beaf63#b8beaf63)
       Fresh serde_json v0.8.6
       Fresh shell32-sys v0.1.1
       Fresh user32-sys v0.2.0
       Fresh stracciatella v0.1.0 (file:///C:/msys64/home/askon/ja2-stracciatella/rust)
    Finished release [optimized] target(s) in 0.0 secs
[  0%] Built target rust-build
[  2%] Built target smacker
make[2]: *** No rule to make target 'rust/release/libstracciatella.dll.dll.a', needed by 'ja2.exe'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/ja2.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

[full_log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1253723/full_log.txt)

**Comment by Manuel-K** [comment]
That's weird: `.dll.dll.a`

Can you please check what extension the libstracciatella that was built has?

**Comment by askondro** [comment]
I has the extension .dll

rust/release/stracciatella.dll

**Comment by Manuel-K** [comment]
@selaux Any ideas?

**Comment by selaux** [comment]
My guess is the issue is somewhere aroun here: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/CMakeLists.txt#L34

I don't know how to build through msys though, so it is really hard to reproduce for me.

**Comment by Manuel-K** [comment]
@selaux Are you sure that it is a good idea to concatenate `${CMAKE_SHARED_LIBRARY_SUFFIX}` and `${CMAKE_IMPORT_LIBRARY_SUFFIX}`?

**Comment by Manuel-K** [comment]
Btw. I can reproduce the issue. 

Basic steps: 
1. Install msys2. Then `pacman -Syu`, `pacman -Su base-devel fltk cmake` and several `mingw-w64-x86_64-` packages including `gcc`, `SDL2` and `boost´.
2. Use rustup with host triple `x86_64-pc-windows-gnu`. 
3. Add rust bin directory to `$PATH`. Set `CC` and `CXX`.
4. Use `cmake -G"MSYS Makefiles"`
5. Run make and wait.

**Comment by askondro** [comment]
Update:

I managed to build a workable ja2.exe with some manual steps:

After the vanilla build fails, building the ja2.exe manually with direct linking with the rust-created rust/release/stracciatella.dll works. No import library required.

`g++.exe   -O2 -g -DNDEBUG   -Wl,--whole-archive CMakeFiles/ja2.dir/objects.a -Wl,--no-whole-archive  -o ja2.exe -Wl,--major-image-version,0,--minor-image-version,0 -lmingw32 -Wl,-Bstatic -lSDL2main -Wl,-Bdynamic -lSDL2 -lboost_filesystem-mt -lboost_system-mt dependencies/lib-gtest/libgtest.a src/slog/libslog.a dependencies/lib-smacker/libsmacker.a rust/release/stracciatella.dll -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`

I will try to fix it in the build files..

**Comment by selaux** [comment]
@askondro A bit late, but can you retry with current master :wink:

**Comment by askondro** [comment]
Yes. it works now!

But I have to apply a little patch regarding SGPStrings.
Otherwise I get a std::WINswprintf not found error.


```
diff --git a/src/sgp/SGPStrings.cc b/src/sgp/SGPStrings.cc
index e0e9471e5..94dbe59cf 100644
--- a/src/sgp/SGPStrings.cc
+++ b/src/sgp/SGPStrings.cc
@@ -120,7 +120,7 @@ strlcpy(char *dst, const char *src, size_t siz)
 #endif


-#ifdef _WIN32
+/*#ifdef _WIN32

 int WINsnprintf(char* const s, size_t const n, const char* const fmt, ...)
 {
@@ -150,7 +150,7 @@ int WINvswprintf(wchar_t* const s, size_t const n, const wchar_t* const fmt, va_
        return ret;
 }

-#endif
+#endif*/

 void CopyTrimmedString(wchar_t* dst, const size_t maxLength, const wchar_t* src) {
        size_t sourceLength = wcslen(src);
diff --git a/src/sgp/SGPStrings.h b/src/sgp/SGPStrings.h
index 78b122264..a88d852c1 100644
--- a/src/sgp/SGPStrings.h
+++ b/src/sgp/SGPStrings.h
@@ -16,7 +16,7 @@ size_t strlcpy(char* dst, const char* src, size_t size);
 #endif


-#ifdef _WIN32
+#/*if defined _WIN32

 #include <stdarg.h>

@@ -29,7 +29,7 @@ int WINvswprintf(wchar_t* s, size_t n, const wchar_t* fmt, va_list arg);
 #define swprintf  WINswprintf
 #define vswprintf WINvswprintf

-#endif
+#endif*/

 void CopyTrimmedString(wchar_t* dst, const size_t maxLen, const wchar_t* src);
```
