### ISSUE TITLE
Smoke/Gas spreads over roof edge

### ISSUE THREAD

**Issue by daviel** [ja2-stracciatella/ja2-stracciatella#600]
I threw a tear gas grenade near the edge of a roof and the gas spred over the edge of the roof.
![1](https://user-images.githubusercontent.com/9992455/31712059-48572a8a-b3fa-11e7-8496-3d60147bfdbe.png)

**Comment by lynxlynxlynx** [comment]
Surely this is vanilla behaviour? I wonder what it did and what it did for short gaps, where's there's only one tile gap between two roofs.

**Comment by JAsmine-ja2** [comment]
This behavior look wrong. The cleanest solution would be for the gas to stop at the edge of the roof.

**Comment by daviel** [comment]
In vanilla the smoke can leave the roof as well. I saw it and thought that it looks defective/ugly. 

I don't think there are any gaps of one tile size. But there are sometimes 3 tiles between buidlings. If you throw a grenade right on the edge of one roof you can get 1 tile of the other roof filled with gas. Another case is throwing grenades on the edge of a corner...

**Comment by lynxlynxlynx** [comment]
ok, so we agree to deviate here.
