### ISSUE TITLE
Crash in SoundLoadDisk() on Arch Linux with SDL2 2.0.6

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#608]
It seems the call to `SDL_ConvertAudio` crashes for `music/menumix1.wav`.

I've never had that problem before.

**Comment by lynxlynxlynx** [comment]
Is it as easy to reproduce ingame as the filename suggests?

**Comment by Manuel-K** [comment]
At least on my system. I'm currently investigating if the problem is the version of SDL2.

**Comment by Manuel-K** [comment]
Obviously I'm very good a triggering main menu segfaults.

**Comment by Manuel-K** [comment]
Updating sdl2 from Arch Linux package version 2.0.6-2 to 2.0.7-1 fixed the problem. Downgrading to the previous version reintroduces the segfault.

**Comment by Manuel-K** [comment]
It's probably not our fault.

**Comment by lynxlynxlynx** [comment]
If that version is consistently bad, we should document it somewhere.

**Comment by Manuel-K** [comment]
I've tested several other versions:
- official Arch Linux 2.0.6-1 package: segfault.
- rebuilt 2.0.6-2 package: segfault
- official Arch Linux 2.0.5-4 package: okay

Are there any problems with 2.0.6 on other distributions?

**Comment by Manuel-K** [comment]
Multiplying the malloced amount (https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SoundMan.cc#L614) by an arbitrary factor e.g. 3 fixes the segfault with 2.0.6.

**Comment by selaux** [comment]
Maybe related: https://bugzilla.libsdl.org/show_bug.cgi?id=3858

**Comment by Manuel-K** [comment]
Yes, it seems to be related. But it also seems that we are already doing it the correct way.

**Comment by selaux** [comment]
Can we actually do something about this, or do we just assume `2.0.6` is the issue and we note that in the README. The crash actually occurs inside SDL, but I didn't debug further.

**Comment by Manuel-K** [comment]
It seems that chocolate-doom had the same crash and it seems they managed to fix it for 2.0.6 by changing the malloc size to something that looks similar to ours.

I've already built a sdl2-2.0.6-2 package with debug symbols, but I was busy with the launcher and the white space stuff.

**Comment by Manuel-K** [comment]
Ran the debugger and checked the error in the SDL2 code. Our buffer is large enough.

It seems that I was wrong. They needed the fix to make chocolate doom work with SDL 2.0.7. They're still throwing an error if the game detects 2.0.6: https://github.com/chocolate-doom/chocolate-doom/commit/4edede3f4a10bc7ce8685f61f618e04eb38acef6

**Comment by Manuel-K** [comment]
I've added code to disable all sounds when 2.0.6 is detected at run time. At the moment it displays an error with `SLOGE`, but I don't think a console/log file message is enough.

What's the easiest way to display a message in the main menu?
