### ISSUE TITLE
Sound memory limit hit after upgrading to SDL 2.0.7

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#609]
SDL2 2.0.7 seems to have changed something in the audio resampling code that makes the game hit the sound memory limit in the main menu:

```
2017/10/04 18:55:17 ERROR   [Sound           ] SoundLoadDisk: trying to play sounds/big switch 03 in.wav, not enough memory
Size: 40532, Used: 46464992, Max: 33554432
```

This does not happen with 2.0.5.

**Comment by Manuel-K** [comment]
Together with #608 this makes me suspect that there might be a problem with the way we use SDL2 to resample the sounds.

**Comment by lynxlynxlynx** [comment]
it did change and we're not the only ones to complain:
https://discourse.libsdl.org/t/sdl-2-0-7-released/23279

**Comment by Manuel-K** [comment]
It sounds like Brad's (@bradharding) problem from 2.0.6 may be hitting us: https://discourse.libsdl.org/t/sdl-2-0-6-released/23109/22

**Comment by Manuel-K** [comment]
I hope that we don't have to do something like this: https://github.com/bradharding/doomretro/commit/70ba9115c152d4c109565ad55550643fc41a5337

**Comment by bradharding** [comment]
This might help: https://github.com/chocolate-doom/chocolate-doom/commit/bd954b9413a16314c24c17dc9a4aacce3fa4c529

**Comment by lynxlynxlynx** [comment]
BTW, we already do manual conversion for sounds with too low sample rate (#78).

**Comment by Manuel-K** [comment]
Thanks. 

It seems that we already do that multiplication: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SoundMan.cc#L614

But it seems that `wavLength` is too small. It might assume the wrong wav format.

**Comment by Manuel-K** [comment]
@selaux Why is `cvt.len_mult` used in the calculation of the number of samples? https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SoundMan.cc#L627

**Comment by Manuel-K** [comment]
I think reusing `cvt.buf` for the sample (https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SoundMan.cc#L634) is wasteful, because the first buffer seems to be larger than the resulting wav data.

**Comment by selaux** [comment]
`cvt.len * cvt.len_mult` is the output size after the conversion as far as I remember. So cvt.buf should have the same size as the output data.  The output should always have the same sample rate `44100`, so we calculate `n_samples` from it. That was at least my idea for the resampling, not sure if that is really the case anymore (how can I test this?).

**Comment by selaux** [comment]
Also all the manual resampling code was replaced by resampling using SDL. I did't expect that to result in so many new issues 😖 . I rather thought that this would reduce our pain with resampling as it is more flexible than our previous method (doing it ourselves).

**Comment by selaux** [comment]
Looking at my machine `cvt->len_mult` seems to be wrong when upsampling:

```
From: wavlength: 5808124, format: 32784, channels: 2, freq: 22050
Cvt: cvt.len: 5808124, cvt.len_mult: 8, format: 32784, channels: 2, freq: 44100
```

**Comment by derSteFfi** [comment]
As mentioned [here](https://github.com/chocolate-doom/chocolate-doom/issues/945#issuecomment-340880021), SDL2 needs more space than 'thought', because they store additional information there. The API states one should use cvt.len_mult and allocate a sufficient amount.

We currently give SoundMan 32M of RAM to buffer the sounds. This seems to be not enough with SDL >= 2.0.7. When increasing ```SOUND_DEFAULT_MEMORY```, sound errors occur in the main menu, though...

**Comment by selaux** [comment]
Allright, so we should use `len_ratio` to calculate `n_samples` and allocate the final buffer. We can then throw away the cvts buffer. `SOUND_DEFAULT_MEMORY` only affects the loaded sounds, so after that we should be fine, as the loaded versions will again be as big as before.

**Comment by derSteFfi** [comment]
sounds good, can you wrap up a PR? :)

**Comment by Manuel-K** [comment]
I'm not sure that this is correct. It seems that `len_ratio` is not the factor that the result of the conversion is bigger than the source file, but it is the factor that the buffer that is required for the conversion is bigger than the source file.
