### ISSUE TITLE
No subtitles (messages) on tactical screen if non-default resolution selected

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#61]
Originally reported by: **Anonymous**
---

The game doesn't print any messages (e. g. hearing sounds by a merc) if a non-standart resolution is selected, hence the option in game settings is checked. Seen in russian ver. using 0.12.189 engine running in Ubuntu 13.04.
---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/61

**Comment by derSteFfi** [comment]
someone still seeing this? I can see all messages in high resolutions here.

**Comment by JAsmine-ja2** [comment]
I think this one can be closed. I have recently experienced a similar thing #398 but not on a regular basis. Per se, the messages are shown win non-standard resolutions.

**Comment by lynxlynxlynx** [comment]
Yeah, there's enough info there.
