### ISSUE TITLE
UI stretching/scaling

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#62]
Originally reported by: **Anonymous**

---

Though the in-game resolution can be modified, this option may not be much of use for some configurations due to UI elements becoming too small and hard to use.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/62

**Comment by lynxlynxlynx** [comment]
sdl2 natively supports scaling. It works in windowed mode and you just have to resize the window. Not sure if all these hardcoded coordinates would be problematic though, but from my experience it also scales event handling.

**Comment by supercom32** [comment]
I assume this is the same issue, but I did notice that when I set my game resolution with the appropriate command line options, that the UI remains at 640x480 with no stretching. When I enter actual gameplay, the map expands to cover the full resolution specified, but everyone looks super small given the original game's 640x480 size. 

Judging from the previous post, the workaround is to simply set the game into Windowed mode, and then resize the window?

**Comment by Manuel-K** [comment]
In principal - yes. But SDL2 does not allow window resizing per default and we do not set the option to explicitly allow it. You need to add the option `SDL_WINDOW_RESIZABLE` to the `SDL_CreateWindow` call in `src/sgp/Video.cc`, i.e. add the line `g_window_flags |= SDL_WINDOW_RESIZABLE;` before the `        g_game_window = SDL_CreateWindow(APPLICATION_NAME,` line.

**Comment by Manuel-K** [comment]
Note: This might break something if you resize the window.

**Comment by supercom32** [comment]
I see. I guess given the fact that it probably won't work correctly, I won't bother with it. However, it would be nice to have 2x, 3x, etc scaling options to take a lower resolution and just blow it up so it's easier to see (even if it looks more pixely - personally I like razor sharp pixels, but I digress. :-) ).

**Comment by Manuel-K** [comment]
> I guess given the fact that it probably won't work correctly, I won't bother with it. 

I have only tested it briefly, but I wouldn't be so pessimistic. It seemed to work.

> . However, it would be nice to have 2x, 3x, etc scaling options to take a lower resolution and just blow it up so it's easier to see (even if it looks more pixely - personally I like razor sharp pixels, but I digress. :-) ).

Yes, that would be better. I'd like to have such scaling options myself, but there are so many (other) issues with the code base…

**Comment by lynxlynxlynx** [comment]
sdl2 does that trivially, you just have to set some of hints (similar to env variables). Then you use windowed mode and scale by simply resizing the window. Multiples obviously work best.

**Comment by supercom32** [comment]
I'm not really a developer, so I'm probably not the best person to be recompiling/modifying/commenting about code, but given how long this issue has been opened, coupled with commenters saying SDL2 makes screen resizing trivial, perhaps this is something that could be of high value (low effort) to investigate and implement?

I would be totally down for testing this feature if someone with more technical knowledge would be willing to implement it. That is, someone who knows all options (hints) SDL2 needs in order to get resizing to work properly with Stracciatella.

**Comment by lynxlynxlynx** [comment]
It should be a oneliner like Manuel said above. SDL_WINDOW_RESIZABLE and SDL_WINDOW_FULLSCREEN_DESKTOP (if we don't use it yet; just a bonus - no display mode change).

**Comment by Manuel-K** [comment]
We don't use `SDL_WINDOW_FULLSCREEN_DESKTOP`, yet. I'm not sure if I really like it. It makes the game start in fullscreen even if `--fullscreen` is not set. On the other hand it stops the annoying resolution changes.

**Comment by Manuel-K** [comment]
Oh. You meant instead of `SDL_WINDOW_FULLSCREEN`. Should we really do that?

**Comment by lynxlynxlynx** [comment]
That's what we use in gemrb, but I don't remember the details. It was added to avoid the mode changes/x vs crashing issues.

**Comment by derSteFfi** [comment]
i just tried ```SDL_WINDOW_FULLSCREEN_DESKTOP``` and like it. very much.

```SDL_WINDOW_RESIZABLE``` beaks stuff for me with i3 (a  tiling window manager). Aren't we considering JA2 to be a fullscreen application anyway?

**Comment by lynxlynxlynx** [comment]
I'm curious — what happens?

**Comment by derSteFfi** [comment]
if you start ja2s with a given resolution, the window gets scaled up to fullscreen based on that resolution, e.g. ```-res 1920x1030``` gives you a small sirtech logo, when you start with ```-res 640x480```, the logo gets scaled up to the complete screen. Just try it, the line to change can be seen in the commit 2 days ago...

**Comment by lynxlynxlynx** [comment]
So you're talking about fullscreen mode, not tiling wm problems. The scaling is the whole point, but we can disable it for fullscreen mode, so people have a choice — scaled fullscreen window and normal fullscreen.

**Comment by derSteFfi** [comment]
ah, you meant the other thing... it tiled ja2s between my two terminals i had open and scaled it down to make it fit... previously, and with ```FULLSCREEN_DESKTOP``` the wm knows it has to put it over the terminals and does so

**Comment by janisozaur** [comment]
In case you're looking for inspiration, here's how it's done in OpenRCT2: https://github.com/OpenRCT2/OpenRCT2/pull/2280 (warning: may contain large images)

Basically we let user set "scale factor", by which we scale _down_ the surface we render to, then [stretch it](https://github.com/OpenRCT2/OpenRCT2/pull/2852) to fill whole window.

**Comment by Manuel-K** [comment]
I think we should do it the OpenXcom way. That is the game that has the nicest scaling options that I know.

**Comment by Manuel-K** [comment]
I like the ability to run the game in a window of arbitrary size, but I don't use a tiling window manager. I think you can define an exception that keeps the wm from squeezing the game window into small spaces.

**Comment by derSteFfi** [comment]
I guess i can, yes. Using a fullscreen option is the lazy man's choice, though :)

**Comment by janisozaur** [comment]
The video here goes through various option OpenXcom offers: https://www.youtube.com/watch?v=vjMuPcywad8

**Comment by supercom32** [comment]
So I was able to figure out how to setup my build environment properly and test the latest changes. Seems like the screen resizing works like a treat! But I must admit, I also don't use any tiling window manager, so I can't comment on how it performs with one.

PS: Slightly off topic, but maybe someone knows... :-) When I built from the master, I noted that my Ja2 binary had tied some "libstracciatella.so" library (or something to that effect) to the specific location where I built. Is there a way to not hardcode a path to such libraries so the build will work on anyones machine, in any arbitrary install location? (PS: I tried making a DEB package for it using "checkinstall" after my "make" to see if that helps, but it didn't work. I will admit, I'm way over my head so I'm just stabbing in the dark.) :-)

**Comment by derSteFfi** [comment]
I'm going to test with GNOME tomorrow. Maybe we can make this configurable. Ideally ingame in the settings? Like modern games do anyway?

**Comment by lynxlynxlynx** [comment]
@supercom32 you need a static build for that.

**Comment by supercom32** [comment]
Just for clarity, I did my testing using GNOME 3. I didn't try GNOME 2.x or anything like that.

**Comment by derSteFfi** [comment]
OK, this IS neat und GNOME :) Anyways, I'd prefer a config option to switch between resizable (maybe last resolution saved in .json-file, could also be used by default if nothing is given on the command line?) and fullscreen_desktop.

**Comment by lynxlynxlynx** [comment]
I don't think we have static build options available in our build system, but you could easily check the binaries in the debs: https://ja2-stracciatella.github.io/download/

**Comment by Manuel-K** [comment]
> When I built from the master, I noted that my Ja2 binary had tied some "libstracciatella.so" library (or something to that effect) to the specific location where I built.

It should also work if you move `libstracciatella.so` to the directory containing the `ja2` binary.

**Comment by Borkason** [comment]
Can't wait for this to finish. 1600*1200 upscaled from 800*600 would be amazing! You think it would be possible to have a borderless window that is 1920*1200 with black bars left and right?

**Comment by lynxlynxlynx** [comment]
It already works and SDL takes care of black borders if the aspect ratio is wrong.

**Comment by Borkason** [comment]
Does it? Doesn't work for me right now, but maybe I am missing something. I downloaded JA2-S [here](https://ja2-stracciatella.github.io/download/) and followed the [instruction to run](https://ja2-stracciatella.github.io/how-to-run/) it.

I currently run it with `ja2.exe -resversion ENGLISH -res 1280x960` and nothing is scaled and I am unable to resize the window.

Could you assist me with it? It would be great to have JA2 run in borderless window mode. 1600*1200 upscaled from 800*600.

**Comment by selaux** [comment]
Did you try adding `-fullscreen` or ALT+Enter while running?

**Comment by lynxlynxlynx** [comment]
I didn't specify anything when running, so you probably have to resize the window manually like I did.

**Comment by Borkason** [comment]
The window cannot be resized. And Alt-Tab doesn't scale, it just puts black bars around the game window.

**Comment by lynxlynxlynx** [comment]
So you're using the release version, not the code we're working with.

**Comment by Borkason** [comment]
Any time frame for the next release?

**Comment by lynxlynxlynx** [comment]
this year, see #437

**Comment by JAsmine-ja2** [comment]
0.16.0 on Windows.

When I start the game (with or without launcher) in 640x480 windowed mode, I can freely change the size of the game window. And the content scales appropriately, keeping the aspect ration. Very nice!!

However...
When I start the game in a higher resolution, let's say in 1024x768, certain parts of the game (well, everything except tactical map view) has a black frame around the 640x480 "core" picture. I marked it red in the screenshot:
![border](https://user-images.githubusercontent.com/17213795/34074794-3c5d92dc-e2b7-11e7-929c-53e69e315b20.jpg)

When I resize the window now, the whole content (including the black frame) scales accordingly. That means, I can't get rid of the black frame, which results in a very small laptop view (and strategic map, options screen etc.)

It would be very nice, if the content of the game could fill out the whole screen in higher resolutions.
I'm not sure if this was mentioned in #62 already?

**Comment by lynxlynxlynx** [comment]
This is not new behaviour. The GUI is hardcoded and only partly expanded for the tactical view. This new scaling option is upstream and pixel based — it affects the whole surface like you found out.

Resizing to smaller than the minimum or what you started with is PEBKAC material if you ask me.

**Comment by JAsmine-ja2** [comment]
Thanks for clearing this up for me.
> Resizing to smaller than the minimum or what you started with is PEBKAC material if you ask me.
Ofc, I was just trying to demonstrate th issue. Resizing the window to a larger resolution is more interesting.

**Comment by Manuel-K** [comment]
The UI code is a horrible mess. It definitely has to be rewritten with scalability in mind.

**Comment by lynxlynxlynx** [comment]
Closing this. Scaling is implemented, while refactoring or adding extra resources is a different topic deserving of separate issues (eg. #33  for 800x600).
