### ISSUE TITLE
Add github topics to the repo

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#620]
I think we should increase visibility of the project on GitHub. Setting topics would include us automatically on thematic lists. 

Possible topics would probably be:
- game
- c-plus-plus
- sdl2
- sdl
- strategy-game
- tactics
- video-game  
- jagged-alliance
- jagged-alliance2

**Comment by lynxlynxlynx** [comment]
Just do it. (tm)

**Comment by Manuel-K** [comment]
I can't. I'm not an owner.

**Comment by lynxlynxlynx** [comment]
Oh & added.
