### ISSUE TITLE
Should the barrel extender only deteriorate while shooting?

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#624]
Now it happens each time you aim — if you are the AI.  Unfair advantage? I don't think they use them any way, but perhaps some mods change that.

VXX addressed it here (end parts): https://github.com/ja2-stracciatella/ja2-stracciatella/commit/5329f15021a6beb921fb37c3a49de9f4c809a3e3

**Comment by Manuel-K** [comment]
Yes. It's highly illogical unless you bang the barrel against something while you take aim.

**Comment by ja2-derek** [comment]
Is it already fixed in #1133 (https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1133/commits/259227910e663dd1aef1ac0a6f0004979553d5a5) ?

**Comment by lynxlynxlynx** [comment]
yep
