### ISSUE TITLE
 Night Ops map pack for JA2 

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#628]
We still have commit 6874b4e356bd48e36bb9dfc899620a9607b95ea9 by @gtrafimenkov with the Night Ops map pack in the unmerged branch mod-pack.

Does it work? Is there a reason not to merge it?

**Comment by lynxlynxlynx** [comment]
I have several questions:
1. Licensing. I know the original JA2 has a dodgy license and while this mod comes with its own, it's not clear whether it uses any assets from the original — that would make it undistributable.
2. How big is it in bytes? It's a bunch of binaries, so git is not the best way to host it.
3. Is it just a map pack or a total conversion? Eg. could it play the role of our demo?

**Comment by Manuel-K** [comment]
I don't know, but I think we should do something. Moving it somewhere else might be the best choice.

There is a readme and some form of license:
https://github.com/ja2-stracciatella/ja2-stracciatella/tree/6874b4e356bd48e36bb9dfc899620a9607b95ea9/mods/nightops-maps

**Comment by ja2-derek** [comment]
It seems to work just fine. The entire map pack is ~45MB in total. 

It appears to be slightly modified version of vanilla JA2 maps. It doesn't seem to require any JSON data changes.

**Comment by lynxlynxlynx** [comment]
At minimum this should be in its own repository and have some docs, if it's usable out of the box. I guess we can treat it as any other mod.

See #39 and the link inside for the original ideas. Not really a priority.

**Comment by ja2-derek** [comment]
Uploaded to https://github.com/ja2-derek/mod-nightops-maps.

Yeah, I agree it is not a priority. Just doing this for my own enjoyment.

**Comment by lynxlynxlynx** [comment]
So this just changes the maps in the original campaign or what?

I'm not opposed to having this under our umbrella though, just not in the main repo.

**Comment by ja2-derek** [comment]
I am yet to do a playthrough and visit the maps.

So far I have seen it adding fences around mines, or adding sandbags on rooftops. Not much or no changes to buildings. Those are supposed to  somehow make Night Ops a necessity. 

I haven't seen any changes to NPCs and quest related stuff.

**Comment by ja2-derek** [comment]
Going deeper in game, the maps are quite different. Chitzena here really feels like a vacation resort. I am impressed. Still, I don't see a need to update any NPC or JSON data yet.

We can follow up further on the mods repo if there are no further questions.

**Comment by ja2-derek** [comment]
Moved to https://github.com/ja2-stracciatella/mod-nightops-maps

Let me know if there are any concerns.

**Comment by lynxlynxlynx** [comment]
Thanks!
