### ISSUE TITLE
Need two rust functions to implement display of game.json location in the launcher

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#630]
`find_ja2_executable_directory` that returns the full path of the executable directory.
`find_ja2_executable_name` that returns the name of the executable.

I'd drop `find_ja2_executable` instead. It seems to be rather hacky. Unless I'm mistaken, it depends on the length of the launcher executable's name.

**Comment by Manuel-K** [comment]
I'd like to include the functionality in 0.16.0.

**Comment by lynxlynxlynx** [comment]
packagers would hate this though, since they'll want to install the binary in a different location than the data.

**Comment by Manuel-K** [comment]
It's nothing new (only for the launcher). The game searches the `externalized` folder in `EXTRA_DATA_DIR` if it is defined or in the location of the binary (https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/sgp/SGP.cc#L365). Obviously the suggestion the launcher makes has to use to the same location.

The changes to the rust functions only affect the launcher.

**Comment by Manuel-K** [comment]
The current code has the length of the launcher's name hard-coded. That will not be popular with the packagers.

**Comment by Manuel-K** [comment]
On second thought – dropping `-launcher` or `-launcher.exe` from the name gives the most flexibility, unless we add a cmake option to chose the executable name.

**Comment by selaux** [comment]
So, should we close or rework?

**Comment by Manuel-K** [comment]
We definitely need a function that gives the absolute path to the binary. And it would be tidier if the other function would be reworked to return just the name.

That way we would not need to link boost to the launcher.

**Comment by selaux** [comment]
Can we postpone editing the `game.json`  to the next release? I currently don't have much time to implement this.

**Comment by Manuel-K** [comment]
I'll try to hack something together tomorrow. If it takes too long, I'll reassign the issue.

**Comment by Manuel-K** [comment]
On second thought. Let's bump this now.
