### ISSUE TITLE
I can't actually find the "optional launcher"

### ISSUE THREAD

**Issue by Voxette** [ja2-stracciatella/ja2-stracciatella#631]
Is it not supposed to be included in the current windows release?

**Comment by Manuel-K** [comment]
It's a new feature of the next release (0.16.0).

**Comment by lynxlynxlynx** [comment]
You could use the nightly build if you want to see it really badly. But we're right before the next release, so you can just wait,

**Comment by Voxette** [comment]
Okay, thanks for clearing that up. The website is very unclear.
