### ISSUE TITLE
General stuff release 0.16.0

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#637]
Testing the win 64 release of 0.16.0

The file "concrt140.dll" is present twice: once within the main directory, once within the "bin" directory. Is this correct?

"README.ENG.TXT" - we only have this file in one language, it could be renamed to simply "readme.txt".

**Comment by selaux** [comment]
I tested on a recently installed version as well and I agree that there are some issues with dlls. E.g. concrt140.dll is present, but the application actually looks for concrt140d.dll as far as I can see.

**Comment by selaux** [comment]
Closing, superseeded by #641
