### ISSUE TITLE
OGG audio files support

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#64]
Originally reported by: **Gennady Trafimenkov (Bitbucket: [gennady](http://bitbucket.org/gennady), GitHub: [gennady](http://github.com/gennady))**

---

It would be great to implement OGG audio files support.
It might come very handy for ModPack project (see wiki about ModPack).

OGG is open-source friendly format.  It should be a better choice than MP3.

OGG decoder preferably should be licensed under one of these licenses: LGPL, MIT, BSD 3-clause.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/64

**Comment by flaviojs** [comment]
SDL_mixer supports OGG.
