### ISSUE TITLE
game.json

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#643]
[game.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1576877/game.zip)

I corrected some small typos in game.json like "throug" and "Tractical". I also did some minor alterations to some describtions to make them a bit more clear (hopefully).

**Comment by JAsmine-ja2** [comment]
Note that, these two options are TRUE by default (Stracciatella) although they are FALSE by vanilla standards:

"gui_extras": true,
"middle_mouse_look": true,

**Comment by Manuel-K** [comment]
One small suggestion. You can use the integrated text-editor on GitHub if you only want to change minor things in a text file by clicking on the small pen button. That is the easiest way to create a PR by choosing “Create a new branch for this commit and start a pull request.” at the bottom of the page.

**Comment by JAsmine-ja2** [comment]
Okay, I will keep this in mind. :)
