### ISSUE TITLE
Sliders in IMP creation with altered game.json are messed up

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#644]
It seems like when you alter the settings for IMP attribute points in game.json, things can get messy when distributing the points in-game.

Clicking left or right of the slider which starts at default 55 points does not give the desired results -> the slider doesn't snap to the click-location as expected.

It is probably because I altered the settings:

        "max_attribute_points": 95, (was 85)
        "min_attribute_points": 15, (was 35)

You can still move the slider, so this is not game-breaking. However, it's very annoying.

**Comment by lynxlynxlynx** [comment]
Dragging the slider still works fine though. But yeah, likely one 35 or derivative stayed hardcoded.

**Comment by Manuel-K** [comment]
@JAsmine-ja2 Does http://builds-ja2.stefanlau.com/pull-requests/670/ work as you expect it?

**Comment by JAsmine-ja2** [comment]
![clipboard01](https://user-images.githubusercontent.com/17213795/34686414-bbe8d72c-f4ab-11e7-87ca-e963b0bae0a4.jpg)
Almost. There is a slight glitch with the clickable area for the arrows.

The right arrow "more points" has a small area to the left, where it is not clickable (red area).
The left arrow "less points" has a small area to the right, where it is still clickable, although the graphic for the arrow ends earlier (green area).
We're talking about just a few pixels on each side, but it is noticeable (and annoying ;)

**Comment by Manuel-K** [comment]
That is a separate problem in the same source file. Once more unto the breach…

**Comment by lynxlynxlynx** [comment]
Yeah, please post separate bugs as separate reports.

**Comment by JAsmine-ja2** [comment]
Okay, I didn't realize that these issues were not related.

**Comment by lynxlynxlynx** [comment]
The gui works basically by having hardcoded transparent overlays over the bitmap graphics. Like ye olde img maps in html. Just to know where the hotspots are. So it's completely unrelated to any other logic — just about fixing the hardcoded coordinates.

**Comment by Manuel-K** [comment]
> Like ye olde img maps in html. 

Except it was harder to mess up the map coordinates in HTML.
