### ISSUE TITLE
Green rectangle of radarmap cut off in small maps

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#647]
![screen002](https://user-images.githubusercontent.com/17213795/34260099-fb155fb0-e664-11e7-9491-4389c9d63f6a.jpg)

There are not many small maps in the game. Right now, only the "meanwhile..." map and the rebel hideout come to my mind. In resolutions > 640x480, the rectangle of the radarmap is cut off. This doesn't look correct. It would be nicer to limit the green rectangle to the radarmap box.

**Comment by lynxlynxlynx** [comment]
It's probably a duplicate of #73
