### ISSUE TITLE
[RU] Game crashing when hiring when browsing M.E.R.C.

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#65]
Originally reported by: **Anonymous**

---

To reproduce:
1. Enter M.E.R.C.
2. Listen to founder's monologue and create an account
3. Start browsing mercenaries - game crashses when showing merc's stats

Always reproductable, in all versions of ja2 stracciatella with russian localisation. The game crashes without restoring original screen resolution.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/65

**Comment by derSteFfi** [comment]
Also can't reproduce. Loaded the savegame, surfed MERC extensively and even hired some MERCs. No crash. Can anyone confirm?

**Comment by lynxlynxlynx** [comment]
Probably requires someone with 0.12.352 Russian localization.

**Comment by lynxlynxlynx** [comment]
Another Russian tester had no problems with this, closing.
