### ISSUE TITLE
win64: immediate abort on start

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#663]
one user is having odd problems with the 0.16 build:
http://thepit.ja-galaxy-forum.com/index.php?t=msg&th=23591&goto=351898&#msg_351898

any suggestions?

**Comment by Manuel-K** [comment]
I want screenshots of the error boxes.

**Comment by JAsmine-ja2** [comment]
I have windows 8.1 64 bit and I can run 0.16.0 without any issues.
I have, however, experienced the immediate abort on start with the map editor, after I had messed around with the editor.slf a bit. I couldn't reproduce this error on a regular basis.

**Comment by selaux** [comment]
Is it a wrong ja2 data directory? Because of `ini` -> `json` change?

**Comment by lynxlynxlynx** [comment]
who creates the json if it isn't there yet?

**Comment by selaux** [comment]
Rust code creates a default version.

**Comment by lynxlynxlynx** [comment]
By the progress in the thread, it doesn't look like this will go anywhere. Works elsewhere, just not on his main machine. 0.15 was fine.

**Comment by JAsmine-ja2** [comment]
I found out, that the launcher obviously doesn't check if the data directory is complete. If I delete all SLF archives from my data directory, the launcher will start JA2 and immediately abort it.

If I give the launcher a wrong location, it doesn't start JA2 at all, which isn't the same as the thing described above. Maybe, the user has an incomplete data directory?

**Comment by Manuel-K** [comment]
But sidav's problem is still not solved, correct?

**Comment by lynxlynxlynx** [comment]
Correct. He did reinstall everything, so the last proposal was fruitless.
