### ISSUE TITLE
moddable music error - not enough memory

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#664]
![music](https://user-images.githubusercontent.com/17213795/34560737-6115e0e0-f147-11e7-9a8e-8a655134dbff.jpg)

Adding custom music works - thanks to #387. AFAIK, we're restricted to the wav format right now. Adding some tracks, I ran into the error as seen in the screenshot.

EDIT: I can upload the wav file if it helps. It is around 16MB.

**Comment by Manuel-K** [comment]
Argh.

Related to #609.

**Comment by Manuel-K** [comment]
Can you confirm that you have SDL 2.0.7?

**Comment by Manuel-K** [comment]
On the other hand – the SDL version does not matter that much. The main problem is that we load all sound files (even music) completely. 

Solutions: 
 - Increase the sound buffer once more. Ugly. Easy workaround.
 - Stream large sound files. Tedious.

**Comment by JAsmine-ja2** [comment]
I have replaced sdl2.dll with this one: 
https://www.libsdl.org/download-2.0.php
which is version 2.0.7 which is -not- the same file as in the stracciatella folder. I have not messed with this file before.
However, it does not change anything. Same error.

**Comment by JAsmine-ja2** [comment]
Another idea: If we had support for OGG and/or MP3, filesizes would be much smaller...

**Comment by Manuel-K** [comment]
No, that would not help. The problem is not the size on the disc, but the size after conversion to wav with correct sample rate.
