### ISSUE TITLE
laptop transition time

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#67]
Originally reported by: **Anonymous**
---

The transition time when opening new web sites seems quite long and a little "laggy". I don't know if it only seems that way because I've been playing v1.13 for years. Just thought, I should mention it.

v0.12.189 on English JA2 Gold, ja2-ENGLISH-1024x768.bat
---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/67

**Comment by lynxlynxlynx** [comment]
If the timing is tied to game cycles, then it should again be just an effect of #99 .

**Comment by JAsmine-ja2** [comment]
Just tested it and can't confirm this.
Stracciatella 0.15.1
JA2 1.12 English

**Comment by lynxlynxlynx** [comment]
Ok, closing, especially since the opening is already tracked under a different bug.
