### ISSUE TITLE
"path blocked" - pathfinding on long distances

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#678]
When trying to move your merc/squad over a very long distance in tactical view (eg to the delivery destination in Drassen Airport B13 while standing on the western edge of the map), the game fails to do so and gives a "path blocked" error message. It seems like the pathfinding is not calculated over long distances.
Can we do something about this limitation?

**Comment by lynxlynxlynx** [comment]
Are you sure there aren't just civilians or militia blocking the entry? Doesn't take much in that sector.

**Comment by JAsmine-ja2** [comment]
I should have provided more information right away... sorry about that:

[SaveGame01.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1610013/SaveGame01.zip)
In this savegame, MD is standing on the standard southern entry point of B13. Trying to make him go directly to the hangar where the shipments arrive is not possible.
Take note, that all civilians, NPCs etc. are revealed with ALT+E cheat. As you can see in the radarmap, there is no one blocking the path.
If you move the screen closer to MD and shorten the route, there is a certain spot, up to which MD's path can be calculated.
It's easy to see what I'm talking about in the savegame.

![screen000](https://user-images.githubusercontent.com/17213795/34652232-c69bb44e-f3db-11e7-8f49-e4218f2fd41d.jpg)
![screen001](https://user-images.githubusercontent.com/17213795/34652198-81cc2f60-f3db-11e7-8f0b-3beb984f71ea.jpg)
![screen002](https://user-images.githubusercontent.com/17213795/34652199-81efa6ca-f3db-11e7-9551-df2f1be6c788.jpg)

Version: Vanilla 1.12, without Stracciatella

**Comment by RinneT** [comment]
IIRC the Path array is limited to a size of 128 (=128 fields in game) and changing that affects a lot of code.

**Comment by chmallon** [comment]
This might be related to TODO001C.
Though the path does not look longer than 256.
(From the bottom left to the top right of a map is 160 tiles.)
Of course there might be any number of bugs in the PathAI.cc, the code is pretty awful.

**Comment by chmallon** [comment]
The algorithm looks like A* with a bit strange cost estimate (not entirely unlike Manhattan distance).
Another possibility is that it runs out of paths, which it can follow, and so just drops them.
See ClosedListGet() check with QPOOLNDX.
