### ISSUE TITLE
misplaced buttons after squad got annihilated

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#679]
![screen000](https://user-images.githubusercontent.com/17213795/34652501-4efc4198-f3df-11e7-8e2f-0db339e93df4.jpg)

The squad (only 1 merc) got ambushed by Bloodcats and was wiped out. The player gets automatically taken to strategic view. Some buttons from tactical remain and are also clickable!

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1610062/SaveGame11.zip)

Happened while playing DiD mode.

**Comment by lynxlynxlynx** [comment]
this is probably the same bug that causes parts of the tactical ui be drawn over strategic (no need for highres). Not sure if we have it noted somewhere already.

**Comment by JAsmine-ja2** [comment]
This report seems to be a duplicate of #366
