### ISSUE TITLE
Carmen giving insufficient rewards

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#680]
Gave him two heads, received only 20k. Is the text in the bounty wrong (20k)? I see the code reserving 10k per head (src/game/Strategic/Strategic_Event_Handler.cc:892) over whatever he had before.

**Comment by michaelwgnr** [comment]
That's not a bug. Carmen is taking half of the share.

**Comment by JAsmine-ja2** [comment]
This is what Carmen tells the player.
Quote no.13 from npcdata\78.edt:

> That's what I'm doing here. I have reliable information that there could be as many as three or four of 'em hiding out in this country at this very moment. You get any of them for me, and I'm willing to split the reward with you.

**Comment by lynxlynxlynx** [comment]
Thanks!
