### ISSUE TITLE
Add a warning about min_attribute_points < 15 to game.json

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#681]
It is possible to set the min. Attribute points to as low as 1.
This allows the player to create an IMP character with <15 max. health.
However, the game requires each character to have at least 15 max. health. If an IMP character has <15 max. health, he/she arrives in Arulco DYING ;)
We need to have a special rule for the max. health attribute in the IMP creation to be 15 or higher.
[SaveGame02.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1612674/SaveGame02.zip)

**Comment by lynxlynxlynx** [comment]
IMHO this is too dumb to support. The modder had purposefully chosen an absurd value.

**Comment by Manuel-K** [comment]
I think we should enforce some sane values for game.json settings.

Especially if it is such a simple fix.

**Comment by lynxlynxlynx** [comment]
Cue someone complaining that they can't lower their health below 15, since there's no warning or notice. And it works for all other stats!

**Comment by Manuel-K** [comment]
Right. That might be a problem.

**Comment by Manuel-K** [comment]
Let's change this to: Add a warning about min_attribute_points < 15 to game.json.

**Comment by lynxlynxlynx** [comment]
Better, yeah. Nobody would do it seriously anyway, since this is the main stat.

**Comment by Manuel-K** [comment]
```
+    //  Warning: Setting min attribute points to a value less than 15 allows
+    //           the creation of a character with less than 15 health. This
+    //           is a dying character!
```

**Comment by lynxlynxlynx** [comment]
Too busy to commit or what?

**Comment by Manuel-K** [comment]
No, I wanted a quick feedback before committing. Too late.

**Comment by lynxlynxlynx** [comment]
It was fine. :+1:
