### ISSUE TITLE
inquiry about mirroring JA2S on a website

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#684]
I just received this message on [Stracciatella's ModDB profile](http://www.moddb.com/mods/ja2-stracciatella):

> I’m reaching out to you because we would like to ask your permission to share your mods on our website: [gry-online.pl](url). We would of course add proper credit with link to a source. We found your work really interesting and we would like to make it easier for our community from Poland to have access to the mods, especially since we include polish instructions for installation. Our website would only serve as a mirror and we will not be making a single penny from this – access to our download section is not restricted by any kind of paywall. The content we upload to gry-online.pl is also available at [gamepressure.com](url), which is an English version of our main site.
> We’ll be extremely grateful if you allow us to share your mod with our community. However, if you decide not to do that, please let us know either way.

What should I answer?

**Comment by lynxlynxlynx** [comment]
So I guess they just want to add something to https://www.gry-online.pl/gra.asp?ID=3302
IOW they're asking if they can promote us?

I don't have a problem with a mirror, as long as it is up to date. Otherwise it starts causing problems.

**Comment by Manuel-K** [comment]
If they provide a mirror they should also link to our download page and add a notice that there might be a newer version available here.

**Comment by selaux** [comment]
Closing because question has been answered.
