### ISSUE TITLE
Error writing in tmp dir

### ISSUE THREAD

**Issue by tanhorn** [ja2-stracciatella/ja2-stracciatella#687]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
Details, details, details.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  1.06 |  JA2 Gold Buka |    no    |    yes/no     |

OS: Windows 10 Pro Version 1709 (OS Build 16299.192)  x64

Problem: Debug error after launching game:
Program: C:\Program Files\JA2 Sctraciatella\ja2.exe
abort () has been called
Press Retry to Debug

No matter english or russian version is - same error even after running launcher as Administrator.
After running from command promt ja2.exe -datadir c:\games\ja2\data -unittests
can see, that all test passed except 

```
[----------] 5 tests from TempFiles
[ RUN      ] TempFiles.createFile
unknown file: error: C++ exception with description "Failed to create directory" thrown in the test body.
[  FAILED  ] TempFiles.createFile (1 ms)
[ RUN      ] TempFiles.writeToFile
unknown file: error: C++ exception with description "Failed to create directory" thrown in the test body.
[  FAILED  ] TempFiles.writeToFile (1 ms)
[ RUN      ] TempFiles.writeAndRead
unknown file: error: C++ exception with description "Failed to create directory" thrown in the test body.
[  FAILED  ] TempFiles.writeAndRead (0 ms)
[ RUN      ] TempFiles.append
unknown file: error: C++ exception with description "Failed to create directory" thrown in the test body.
[  FAILED  ] TempFiles.append (1 ms)
[ RUN      ] TempFiles.deleteFile
unknown file: error: C++ exception with description "Failed to create directory" thrown in the test body.
[  FAILED  ] TempFiles.deleteFile (1 ms) 
```
[scr01](https://user-images.githubusercontent.com/35425561/34917471-f53d6578-f957-11e7-9f2e-35ca64b700f6.gif)
[scr02](https://user-images.githubusercontent.com/35425561/34917474-f89861b4-f957-11e7-93f6-e4add532ec01.gif)
[scr03](https://user-images.githubusercontent.com/35425561/34917475-fb57d0ec-f957-11e7-99e3-aa0d5596e254.gif)

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

Michael

**Comment by lynxlynxlynx** [comment]
You have enough disk space, right?

**Comment by tanhorn** [comment]
Sure. It's even a system disk, but there's basically only the Windows, office and system utilities. About 60 GB of free space. Pagefile.sys is installed on another physical disk, also the system variables of temporary files are pointed to another disk

**Comment by tanhorn** [comment]
Actually, I experimented a bit with the command line. The game starts, you can see the logo, and then again the same thing happens.
Question: where should temporary files be written?
In my profile -  C: \ users \ ... \ Documents \ JA2 \ tmp?
Insomnia, I'll try to get some more shuffle :) By the way, I read yesterday about the same error on the Bear's pit forum

**Comment by lynxlynxlynx** [comment]
Could be an upstream problem in rust's tempdir crate. What are these windows variables that you're talking about?

https://github.com/rust-lang-nursery/tempdir

**Comment by tanhorn** [comment]
Actually, I experimented a bit with the command line. The game starts, you can see the logo, and then again the same thing happens.
Question: where should temporary files be written?
In my profile -  C: \ users \ ... \ Documents \ JA2 \ tmp?
Insomnia, I'll try to get some more shuffle :) By the way, I read yesterday about the same error on the Bear's pit forum

**Comment by tanhorn** [comment]
Lol. I have changed variable datadir from \ja2\data to\ja2\ and now all works
except... but its already my problem - old videocard

**Comment by Manuel-K** [comment]
Right. We should definitely add that information to the launcher.

And I wanted to change that error message a few times. I keep forgetting.
