### ISSUE TITLE
Fighting a battle in F10 breaks the hillbilly quest

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#688]
### Hillbilly quest is broken
Keith, the shop owner in Cambria G9, is supposed to give the player the quest to kill the hillbillies near Cambria (F10). This quest then makes him buy/sell guns (and maybe also increases his balance??).
In my current playtest, he doesn't give me this quest. He immediately buys guns and doesn't mention the hillbilly family.

 The only thing that might be related is, that I fought a battle against the army in F10. I won the battle. One hillbilly was killed as collateral damage (he was accidently killed without turning his faction hostile).

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
| 0.16.0 | JA2 English Gold 1.12  |    yes    |    yes     |

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1629460/SaveGame11.zip)

**Comment by lynxlynxlynx** [comment]
I got the quest just fine on master, so pretty much the same code. No idea about what he was trading in though.

**Comment by DSeyka** [comment]
>The only thing that might be related is, that I fought a battle against the army in F10. I won the battle. One hillbilly was killed as collateral damage (he was accidently killed without turning his faction hostile).
I'll try reproducing this in vanilla, something tells me this will break (well, "solve" the quest) there as well.

**Comment by DSeyka** [comment]
So it's day 532 here in vanilla and I have a theory, Queen's army is never supposed to be in F10 and the quest's trigger is just player winning a battle there.

**Comment by JAsmine-ja2** [comment]
Yep, there is no patrol group that crosses F10 and no garrison for F10.
However, F10 has soldier "placement slots" in it's map data, making it possible to have soldiers there. And there are patrol groups, that go into sectors adjacent to F10. Also, there is a garrison next to F10.
So, in my above game, somehow they ended up in F10.

I'm not quite sure, how reinforcements work - do they need to stick to existing patrol group routes when coming from Meduna, or can they just take a direct route to their destination??
Maybe, a reinforcement group was intercepted in F10?

**Comment by JAsmine-ja2** [comment]
Okay, more testing on this and some good ol' cheating reveals: 
### Fighting a battle against the army in F10 breaks the hillbilly quest

### 1) Normal approach
Gain people's trust in Cambria (20% loyality), talk to Keith in G9, get the quest:
![screen000](https://user-images.githubusercontent.com/17213795/34980194-feb09f10-faa3-11e7-8856-6b70bce2cfba.jpg)
![screen001](https://user-images.githubusercontent.com/17213795/34980193-fe93d290-faa3-11e7-9cb2-831841ed58fe.jpg)

### 2) Breaking the quest
Same approach as in 1). BUT somewhen before talking to Keith, a battle is fought in F10. Result: Keith won't give the quest.
![screen002](https://user-images.githubusercontent.com/17213795/34980237-278577c6-faa4-11e7-9e8f-b4e8027d4a42.jpg)
![screen003](https://user-images.githubusercontent.com/17213795/34980238-27a3783e-faa4-11e7-8ebf-0d5ec5c17e53.jpg)
![screen004](https://user-images.githubusercontent.com/17213795/34980240-27bfdd1c-faa4-11e7-8f3f-dc7551b00d6f.jpg)

Save 1: normal - before getting the quest
Save 2: breaking - after battle, before trying to get the quest
[SaveGame01.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1634264/SaveGame01.zip)
[SaveGame02.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1634265/SaveGame02.zip)

**Comment by lynxlynxlynx** [comment]
This is done in HandleVictoryInNPCSector. Any victory in the sector would do.

**Comment by JAsmine-ja2** [comment]
Okay, so the devs thought that with no garrison or patrol group in F10, the only victory possible would be a victory vs the hicks. 
Fighting against soldiers in F10 is not intended.
This brings me back to:


> I'm not quite sure, how enemy reinforcements work - do they need to stick to existing patrol group routes when coming from Meduna, or can they just take a direct route to their destination??
> Maybe, a reinforcement group that was headed for a northern sector was intercepted by the player in F10?

```

**Comment by DSeyka** [comment]
Can't we somehow blacklist F10 for the army? Keith actually says something about army intentionally avoiding hicks, so it's very likely that army presence there was never intended, despite there being army placements on the map -- it could have been done earlier in development and then nobody cared enough to remove them when quests were fleshed out.
That's of course just an assumption and to know for sure means trying to make sense of quest code I suppose. Which is arcane wizardry to put it lightly.

**Comment by Manuel-K** [comment]
So we should add a check to `HandleVictoryInNPCSector` to prevent the issue. Blacklisting F10 for the army seems to be the worse solution.

OT: IMO the quest code is better than the laptop code.

**Comment by DSeyka** [comment]
If it can be solved with a check then in's a win-win all around.
I didn't mention the laptop code because doing so would probably summon an ethereal being with a thousand maws bent on devouring the Earth.

**Comment by Manuel-K** [comment]
Weird. There is a `CheckFact(FACT_HILLBILLIES_KILLED, FALSE)` in `EnemyPermittedToAttackSector` that should prevent attacks on F10.

**Comment by DSeyka** [comment]
That's why I asked if there are some other circumstances when army can follow you there. I can't think of any in vanilla game unless there are hidden mechanics I'm not aware of, like maybe following wounded or lonely mercs, or something?
At least we can now say for sure that army isn't supposed to be in F10 ever.

**Comment by Manuel-K** [comment]
>  At least we can now say for sure that army isn't supposed to be in F10 _ever_.

Wrong. They are supposed to be there **after** the Hillbillies are dead.

**Comment by DSeyka** [comment]
Yeah, I meant before the quest is done. Sure. But JAsmine said they were there simultaneously.
It's probably a very rare circumstance, but still: how could the army be there with hicks at the same time?

**Comment by DSeyka** [comment]
That means we're looking in the wrong direction. It's not about that particular sector, maybe it's about AI squads traveling between sectors rather than about this one particular sector? I don't have the access to the code at the moment regretfully.

**Comment by flaviojs** [comment]
It's possible to get a soldier in F10 if you have a battle next to it and the soldier retreats in the direction of F10.

`FACT_HILLBILLIES_KILLED` is being set in `HandleVictoryInNPCSector` for any victory in F10:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7ba876c8fb6564dafe7ab5a21164e38a7d64a700/src/game/TacticalAI/NPC.cc#L2688-L2701

They are neutral at the beginning, so if they don't become hostile in the middle of your battle (stray bullet) they will still be alive when you win the battle.

To fix this just check if the hillbilies team is empty in `HandleVictoryInNPCSector`.

**Comment by lynxlynxlynx** [comment]
Yeah, the suggestion looks good. Also handles the case if the battle was due to an interrupted patrol.

**Comment by flaviojs** [comment]
I noticed something interesting while testing the fix with cheats on.
I shoot one to make them hostile and used Alt+O to kill them all but only 2 died.
I won the battle before the others hicks turned hostile.
It was the one I shot and probably someone that heard the shot and turned hostile.
I'm assuming this is related to stealth-attack mechanics.

If instead I pass the turn they all turn hostile.
I get a crash when I use Alt+O to kill them.
Should this crash be checked? or is using cheats enough to not bother

**Comment by lynxlynxlynx** [comment]
If it's easy to reproduce, why not?
