### ISSUE TITLE
Merging stacked items is not possible

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#690]
We can refill items (e.g. 1st aid kits) by merging them. It is not possible to merge stacked items. Right now, when the player has four 1st aid kits stacked, he has to shuffle them around in his inventory and can't simply refill them when "examining the stack" (see situation in the screenshot).
It would be a nice enhancement to be able to merge stacked items.

![screen002](https://user-images.githubusercontent.com/17213795/34919631-84424310-f967-11e7-8395-9af79a7d6221.jpg)

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1629701/SaveGame11.zip)

**Comment by lynxlynxlynx** [comment]
Yeah, even if you are already dragging the same item, it won't work on stack members.
