### ISSUE TITLE
Improve the error message when data_dir is not valid.

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#692]
The current error message is cryptic at best.

Note: This is a reminder to myself.

EDIT by lynx:

> terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>   what():  boost::filesystem::directory_iterator::construct: No such file or directory: "/some/place/where/the/data/is/data"
> Aborted (core dumped)
it should at least display the path to ja2.json.

**Comment by lynxlynxlynx** [comment]
This needs a recheck, since boost was ripped out and it's rust that's doing the FS stuff.

**Comment by ja2-derek** [comment]
If we are only talking about the error message, this is how it looks in the new launcher:

![image](https://user-images.githubusercontent.com/63151803/78739106-23b71100-7986-11ea-903b-66f75f183573.png)

**Comment by lynxlynxlynx** [comment]
No, this was the cmd. But it's fine now, closing:
> $ ./ja2
> Vanilla data directory has to be set either in config file or per command line switch
