### ISSUE TITLE
Release 0.16.1

### ISSUE THREAD

**Issue by Manuel-K** [ja2-stracciatella/ja2-stracciatella#696]
I've cherry-picked all three commits, updated the version number and updated the change log.

TODO:
- [x] create the tag
- [x] create release notes
- [x] attach builds to release
- [x] test the builds
  - [x] Windows
  - [x] Ubuntu
  - [x] Arch Linux
  - [x] macOS
- [x] announce

**Comment by Manuel-K** [comment]
If I understand #632 correctly, it the binaries are pushed to http://builds-ja2.stefanlau.com/releases/ when the tag is created, correct?

**Comment by lynxlynxlynx** [comment]
yep.

btw, I'm still travelling, so no forum or ja2 access for me.

**Comment by Manuel-K** [comment]
Oh what fun. I've forgot to update the tags before creating the branch.

**Comment by lynxlynxlynx** [comment]
done, lucky save.

**Comment by Manuel-K** [comment]
@JAsmine-ja2 Can you test the Windows version, please? The 32 bit version is built and the 64 bit version should be ready soon.

@selaux I'm not sure how often you have access to your friend's Mac… 

Anyhow… I don't have access to my Ubuntu partition at the moment, so I can only test the binary on Arch Linux.

**Comment by Manuel-K** [comment]
The deb works on Arch.

I've attached a PKGBUILD that uses the deb to create an Arch Linux package: [PKGBUILD.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1674879/PKGBUILD.gz)

**Comment by Manuel-K** [comment]
Added #495

**Comment by Manuel-K** [comment]
New binaries should be ready soon.

**Comment by selaux** [comment]
Same for Ubuntu

**Comment by lynxlynxlynx** [comment]
Cool & I can write the texts once the win build is ready.

**Comment by selaux** [comment]
Tested Windows 32 and 64 bit zips as well.

**Comment by lynxlynxlynx** [comment]
Added notes, not announced anywhere yet:
https://ja2-stracciatella.github.io/news/

You were building this off the 0.16.x branch, right? Looks like all the changes haven't been merged to master yet (eg. changes.md).

**Comment by lynxlynxlynx** [comment]
Pages updated, forum sent.

@JAsmine-ja2: can you update our moddb entry?

**Comment by JAsmine-ja2** [comment]
Moddb entry updated. Currently waiting for admin authorization.
