### ISSUE TITLE
Tile corruption when scrolling around

### ISSUE THREAD

**Issue by moll** [ja2-stracciatella/ja2-stracciatella#708]
I'm not sure why or what triggers it yet, but seeing tile corruption when navigating around. I mostly do so through the arrow keys, but I think scrolling with the mouse has the same per-tile movement.

See the building left of Blood. Parts of airplane poster on the top-left room also corrupt the grass tile seen through the window.

![screenshot from 2018-02-27 01-45-21](https://user-images.githubusercontent.com/156837/36706031-f67d5842-1b5f-11e8-8df7-3b56018ca937.png)

![screenshot from 2018-02-27 01-45-16](https://user-images.githubusercontent.com/156837/36706035-fb14ee10-1b5f-11e8-9b19-47f183ce66ec.png)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  00cb9fef9 | GOG v1.12 (17794)  |    Probably not due to wide resolution   |         |

This is on Arch Linux on GeForce 960 GTX with the resolution set to 2520x1080px.

Any other intel I could provide to help debug this?

**Comment by moll** [comment]
I have a feeling it's related to the somewhat non-standard resolution of 2520x1080px. Restarting with 2880x1080px doesn't reproduce this, but switching back to 2520x1080px does.

**Comment by lynxlynxlynx** [comment]
Is it visible also without the mercs moving? We have an older report for that here:  #551

**Comment by moll** [comment]
Everyone was stationary in my tests above. I didn't really notice the corruption until I got to Drassen, so I'd say no heavy corruption during movement. I don't remember what my "Merc Lights during Movement" setting was if that's relevant, but I can test if necessary given that the corruption was reproduceable with that non-standard resolution.

**Comment by maxrd2** [comment]
@moll Could you please confirm this still happens on current master?

**Comment by moll** [comment]
Yay. Thx. I'll report back next time I get around to compiling and playing JA2!

**Comment by flaviojs** [comment]
I remember seeing corruption like this (inside Drassen mines) when I used version 0.16.1.
I don't remember seeing it in current master de0701d089dcd947fd49ff918ae016a621f2dfcf.

**Comment by lynxlynxlynx** [comment]
Thanks, closing then.
