### ISSUE TITLE
Too low brightness or gamma values

### ISSUE THREAD

**Issue by iloveeclipse** [ja2-stracciatella/ja2-stracciatella#709]
First of all: great job! Thank you very much for this project. I can play the game with a decent resolution on my notebook without issues (or sort of). 

### What is wrong
My main problem: the in-game brightness (or gamma) values are pretty low, so that I have to push my screen brightness to 100%, which in turn is unusable with all other Windows applications. So I have to run the game only in full screen mode and every time switching back to Windows dim brightness down to (acceptable) 40%.

I see that you have managed to extract many hard coded values to json files. Is there a way to allow to configure brightness or gamma via json? If not, would this be possible? I'm not a game developer, but quick googling revealed for example this: https://msdn.microsoft.com/en-us/library/windows/desktop/bb173460(v=vs.85).aspx and this: https://stackoverflow.com/questions/1338398/adjust-brightness-contrast-gamma-of-scene-in-directx. So may be it is possible somehow to add this to the game on startup?

Many thanks again for this great project!

**Comment by lynxlynxlynx** [comment]
SDL supports setting brightness (SDL_SetWindowBrightness) and changing the gamma ramp (for the whole screen), so this is quite easily doable. Extracting the default factor of 1.0 likewise.

**Comment by iloveeclipse** [comment]
Thanks guys!
