### ISSUE TITLE
JA2 Wildfire for Linux lacks b_map.pcx

### ISSUE THREAD

**Issue by Patola** [ja2-stracciatella/ja2-stracciatella#712]
### What is wrong
Tried ja2-stracciatella with the Jagged Alliance 2: Wildfire available on steam (bought on a sale). It almost starts, but stops at this line:
```
(...)
2018/03/08 16:56:54 DEBUG   [Default CM      ] Opened file (from library ): fonts/largefont1.sti
2018/03/08 16:56:54 DEBUG   [Default CM      ] Opened file (from library ): fonts/smallcompfont.sti
2018/03/08 16:56:54 DEBUG   [Default CM      ] Opened file (from library ): fonts/smallfont1.sti
2018/03/08 16:56:54 DEBUG   [Default CM      ] Opened file (from library ): fonts/tinyfont1.sti
2018/03/08 16:56:54 INFO    [Game Loop       ] Version Label: Stracciatella "v0.16.x"
2018/03/08 16:56:54 INFO    [Game Loop       ] Version #:     Build 04.12.02
2018/03/08 16:56:54 INFO    [Render World    ] Increasing background slots to 100
terminate called after throwing an instance of 'std::runtime_error'
  what():  Opening file 'interface/b_map.pcx' failed
zsh: abort (core dumped)  ./ja2 -datadir /jogos/steam/steamapps/common/ja2_wildfire/Game -res 1920x1080
```

Tried both the provided .deb file and compiling from source from the latest github tree (from today).

No savegames. I am just trying to start the game.
Operating System: Ubuntu 17.10 64 bits

**Comment by lynxlynxlynx** [comment]
I guess that file is only present in vanilla. Appears to be the video file.

**Comment by Patola** [comment]
Any way to make ja2-stracciatella ignore it?

**Comment by lynxlynxlynx** [comment]
No, it's actually not video related. The real fix would be to find what wildfire used instead. Can you check what pcx files you have available? You can use our toolset to explore:
https://github.com/ja2-stracciatella/ja2-open-toolset

**Comment by Patola** [comment]
I used this script to get the content of all *.slf files under Data (but not the subdirectories):
```
for a in /jogos/steam/steamapps/common/ja2_wildfire/Game/Data/*.slf
do
  echo -e "file: $a"'\n============' >> /tmp/ja.log 2>&1 ; python examples/unpack_slf.py -o /tmp/ja -v "${a}" >> /tmp/ja.log 2>&1
done
```

I attached the resulting file (ja.log) to this message.

[ja.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1888029/ja.log)

**Comment by Patola** [comment]
The pcx files on the 'ja.log' seem to be:
|-- IMP_POPUP_BACKGROUND.PCX
|-- IN_TEXT_8.PCX
|-- LAPTOPPOPUPBACKGROUND.PCX
|-- POPUPBACKGROUND.PCX
|-- TACTPOPUPBACKGROUND.PCX
|-- TACTPOPUPBACKGROUNDMAIN.PCX
|-- TACTPOPUPGREYBACKGROUND.PCX
|-- TACTPOPUPWHITEBACKGROUND.PCX
|-- desktop.pcx

**Comment by JAsmine-ja2** [comment]
b_map.pcx is the worldmap AKA strategic map. The big map file of Arulco.
Wildfire has significant (AFAIK) code changes and I can't imagine that it will run with Stracciatella (more or less) out of the box.

**Comment by Patola** [comment]
I didn't know that. Sorry.
Should this bug report be closed then?

**Comment by lynxlynxlynx** [comment]
The real question is: is wildfire source code available? It seems doubtful, even though both things happened at the same time:
https://ja2-stracciatella.github.io/history/#11-jagged-alliance-2-wildfire-2004

So yeah, it appears to be useless as a wishlist item too.
