### ISSUE TITLE
Merc selection... 

### ISSUE THREAD

**Issue by JJ-Au** [ja2-stracciatella/ja2-stracciatella#714]
Cannot select Mercs with numbers, 1 through 6 :(

**Comment by lynxlynxlynx** [comment]
It's F1-F6, where did you get the info that it should be 1-6?

**Comment by JAsmine-ja2** [comment]
You can select squads with the numbers.

**Comment by lynxlynxlynx** [comment]
Yes, also in strategic.

**Comment by JJ-Au** [comment]
Probably my retarded ass memory :)

Actually, I been playing Icewind Dale Enhanced Edition... it's 1-6. My bad. Thanks heaps for the response tho!

JJ


________________________________
