### ISSUE TITLE
ja2-stracciatella_0.16.0 and later don't run on OS X 10.9 Mavericks (Dyld Error)

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#716]
Hello,

Thanks for all your work. I love the stable JA2.

**Issue**
Stracciatella v0.16.0 and newer don't run on OS X 10.9 Mavericks.

**Additional Info**
Stracciatella v0.15.1 and older run on OS X 10.9 Mavericks. 
Stracciatella v0.16.0 and newer run on OS X 10.11 El Capitan.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.16.0 and newer | n/a  |    no    |    yes     |

**0perating system**
OS X 10.9 Mavericks

**Possible cause**
Change to SDL2

**Possible solutions**
Specify Supported Versions / System Requirements to avoid frustrations for newcomers
Instruction on how to get it run OS X 10.9 Mavericks
Change it to make it work again in OS X 10.9 Mavericks

**Detailed Error Report**
```
Process:         ja2-launcher [437]
Path:            /Applications/JA2 Stracciatella.app/Contents/MacOS/JA2 Stracciatella
Identifier:      io.github.ja2-stracciatella
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [188]
Responsible:     ja2-launcher [437]
User ID:         501

Date/Time:       2018-05-13 08:28:09.103 +0200
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  8BD446B6-110C-26C7-AB2C-64DEEE16A478

Sleep/Wake UUID: CE231A0F-DF6C-436E-8AB5-3E139B1B690F

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libstracciatella.dylib
  Referenced from: /Applications/JA2 Stracciatella.app/Contents/Resources/ja2-launcher
  Reason: image not found

Binary Images:
    0x7fff6424e000 -     0x7fff64281887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff83806000 -     0x7fff8395aff3  com.apple.audio.toolbox.AudioToolbox (1.10 - 1.10) <69B273E8-5A8E-3FC7-B807-C16B657662FE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff84f2f000 -     0x7fff85aa5ff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff86c8f000 -     0x7fff86c9dfff  com.apple.opengl (9.6.5 - 9.6.5) <4FAEADD8-EEB3-3FD9-ADC6-BA65806228CC> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff87a84000 -     0x7fff87c69fff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff883c7000 -     0x7fff883c7ffd  com.apple.audio.units.AudioUnit (1.10 - 1.10) <68B21135-55A6-3563-A3D6-3E692A7DEB7F> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff8f8b8000 -     0x7fff8f8b8fff  com.apple.Carbon (154 - 157) <45A9A40A-78FF-3EA0-8FAB-A4F81052FA55> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff908c7000 -     0x7fff90933fff  com.apple.framework.IOKit (2.0.1 - 907.100.14) <10932113-9F7E-38A0-A158-A019A555CAC3> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit

Model: MacBook7,1, BootROM MB71.0039.B0E, 2 processors, Intel Core 2 Duo, 2.4 GHz, 2 GB, SMC 1.60f6
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x802C, 0x384A53463132383634485A2D314731463120
Memory Module: BANK 1/DIMM0, 1 GB, DDR3, 1067 MHz, 0x802C, 0x384A53463132383634485A2D314731463120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 15 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: TOSHIBA MK2555GSXF, 250.06 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: Built-in iSight
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: 
```

**Comment by lynxlynxlynx** [comment]
Regardless of the error, I believe none of us has an appropriate build machine any more.

**Comment by nemuc** [comment]
Sorry for the very late reply.
I tried this build and Stracciatella still doesn’t launch. However the launcher itself now starts.
Same result with the newest nightly ja2-stracciatella_0.16.x-20181106_macos.dmg.

![screen shot 2018-12-10 at 11 43 09](https://user-images.githubusercontent.com/39365524/49727553-d121f380-fc70-11e8-8888-1ffd4ee62897.png)

It is not important to me since I still have other means to play (older releases, on newer Laptop, on Debian).

**Comment by selaux** [comment]
Hi. Thanks for replying. Is the new error message different that the one posted above?

**Comment by nemuc** [comment]
Hi.

This time I don't see any error messages. Can you point out how I can capture error messages? I have the terminal open and I see the tips on https://github.com/ja2-stracciatella/ja2-stracciatella/wiki/Tips-and-Tricks-for-Developers.

Another info: The path to my ja2.exe is very long. It is "/Applications/Jagged Alliance 2.app/Contents/Resources/game/Jagged Alliance 2.app/Contents/Resources/drive_c/Program Files/GOG.com/Jagged Alliance 2" . Might this matter?

**Comment by flaviojs** [comment]
You could try: `./ja2 -debug`
It will spit out a lot of extra information, which should tell you more about why it failed.

**Comment by lynxlynxlynx** [comment]
@nemuc do you still have problems?

**Comment by nemuc** [comment]
As OS X 10.9 Mavericks doesn't receive security updates anymore, I changed to a newer version, where I do get to run Stracciatella. I have no longer access to 10.9 Mavericks and consider it obsolete. Therefore I close this issue.
