### ISSUE TITLE
menu bug when ending a game

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#72]
Originally reported by: **Anonymous**

---

When you end a current game and go back to the main menu, this is what it looks like:
![ending a game, going back to main menu](http://img.xrmb2.net/images/524571.jpeg)

the "old game" is still visible around the main menu. I guess, that most graphics (especially backgrounds) have to be provided to the game in stretched resolutions, as the game won't stretch the graphics itself???

I'm still playing v0.12.189 on english ja2 gold with ja2-ENGLISH-1024x768.bat

btw, sorry for spamming al these issues as a random anonymous nobody. Maybe I should register before posting more issues?!

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/72

**Comment by lynxlynxlynx** [comment]
Still present. I guess it would be easiest to do a final full-black blit before quit, so we don't need to redraw the frame all the time (may change with #206 though).

**Comment by derSteFfi** [comment]
i can not confirm this on master, my background is black... SDL v.1.2.15 (I'm on arch linux and they patch a few things in, but nothing looks suspicious to this).

**Comment by lynxlynxlynx** [comment]
Could also be driver related.

**Comment by JAsmine-ja2** [comment]
![menu-bug](https://cloud.githubusercontent.com/assets/17213795/15462924/3d06c906-20c6-11e6-8e8a-e6ad8d2d60f4.jpg)

Still present on v0.15 (windows)
How to reproduce:
- set resolution to higer than standard resolution
-start a new game or load a saved game
- enter tactical view
- enter options menu (directly from tactical view, do not enter strategic view)
- quit the game

**Comment by derSteFfi** [comment]
confirmed here on linux. when transitioning to the main menu, a restore of the bacground needs to happen. this is most probably related to #106
