### ISSUE TITLE
reproduceable crash near Alma

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#722]
### What is wrong
Details, details, details.
I attached Qujcksave and error.. but Quicksave should be enough to locate the error.

Fly the squad to F12 disembark the Heli and go south. Instant error on arrival.

I am running linux.

[error.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2367458/error.sav.gz)
[QuickSave.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2367459/QuickSave.sav.gz)

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold Dutch  |    yes/no    |    yes/no     |

latest commit:

commit f571f92f58956749187f45531adb27754a098d6a (HEAD -> master, origin/master, origin/HEAD)
Merge: 7d66aa475 54799c6de
Author: Jaka Kranjc <smgl@lynxlynx.info>
Date:   Tue Jul 24 19:36:10 2018 +0200

    Merge pull request #720 from aellwein/master
    
    fix possible division by zero / SIGFPE

JA2 Gold English

Vanilla bug? I dont know, but I dont think so because that sector should just work.

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by JAsmine-ja2** [comment]
I can reproduce this crash on JA2S 0.16.0
I can NOT reproduce this crash with JA2 vanilla 1.10 US

Message in the launcher:
![clipboard02](https://user-images.githubusercontent.com/17213795/48972370-0a2f5680-f029-11e8-936e-61101e1f826d.jpg)

**Comment by flaviojs** [comment]
what() says "Failed to add node to world" so it's this exception:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7ba876c8fb6564dafe7ab5a21164e38a7d64a700/src/game/TileEngine/WorldMan.h#L12-L19

being thrown here:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7ba876c8fb6564dafe7ab5a21164e38a7d64a700/src/game/TileEngine/WorldMan.cc#L518-L521

It turns out the crash is not when the squad arrives at G12 but before that, when Skyrider arrives at B13 to refuel.

**Comment by ja2-derek** [comment]
I believe this is the same issue as https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1107

As a work-around- it does not crash if you move the B13 squad away before the Heli returns.
