### ISSUE TITLE
disappearing throwing knife

### ISSUE THREAD

**Issue by mirageglobe** [ja2-stracciatella/ja2-stracciatella#724]
### What is wrong
Using 0.16.1 on vanilla. When throwing *throwing knife* on floor, it works as expected. When throwing  *throwing knife* on wall, or dead body, it disappears. According to vanilla, it should still be available.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1 | eg. JA2 Gold US  |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

Simply pick up bloody throwing knife in omerta. Throwing the *throwing knife* on floor, works as expected. Upon throwing  *throwing knife* on wall, or dead body, it disappears.

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by JAsmine-ja2** [comment]
I just tested this in Vanilla JA2 Gold version 1.10 and 1.12 and can confirm, that this is vanilla behavior. Throwing knives disappear, when being thrown at a wall or dead body.
Stracciatella behaves the same - no issue here.
