### ISSUE TITLE
Visual Studio Build/Compilation Errors

### ISSUE THREAD

**Issue by arnodick** [ja2-stracciatella/ja2-stracciatella#725]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

Hi Stracciatella folks,

I'm trying to get Stracciatella compiling on Windows 7 with Visual Studio 2017 but having difficulty.

So far I've used:

`cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-msvc.cmake -G "Visual Studio 15 2017" ../`

Which successfully builds the VS project when run from a _bin folder.

Then I had to set _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING in the preprocessor definitions for the gtest and gtest_main projects. This had something to do with std::tr1 being deprecated in Visual Studio, and I'm not sure if it's a good long term solution. It might just be that gtest moves away from std:tr1 and releases a version that will work in VS 15.

Now I'm trying to get the ja2 project to compile, but getting this error:

`ja2-stracciatella-master\_bin\dependencies\lib-fltk\fltk-internal-prefix\src\fltk-internal\src\flstring.h(28): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory [...\ja2-stracciatella-master\_bin\dependencies\lib-fltk\fltk-internal-prefix\src\fltk-internal-build\src\fltk.vcxproj]`

As far as I can tell there is a mistaken build directive called HAVE_STRINGS_H that is being set when it shouldn't be. It should be using string.h instead, I think. I've tried setting HAVE_STRINGS_H to 0 in CMakeCache for fltk, but it didn't have any affect.

When building INSTALL I'm also getting a variety of errors like this:

`SGP.obj : error LNK2019: unresolved external symbol _create_engine_options referenced in function _SDL_main`

Which I'm not sure how to resolve. There are many lines of this, each mentioning a different symbol.

(I'm also not entirely sure which project I should be building in the fist place. ja2, ja2-launcher, INSTALL?)

Any help would be much appreciated! Would love to help getting build/compilation working consistently.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16 | JA2 Gold English  |    no    |    no?     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
You should be building ja2 and ja2-launcher. The INSTALL error hint to the rust library not being found, was that built correctly?

**Comment by selaux** [comment]
I fixed the gtest issue by updating here: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/730

I didnt stumble over the `strings.h` issue, but read that this might happen when you have a `strings.h` file installed at some location that cmake tries to discover automatically. E.g. when you have Mingw installed.

To debug the `SGP.obj` issue further I need more logs (somewhere it should say why `stracciatella.lib` it is not linked).

**Comment by arnodick** [comment]
I tried the latest version with the gtest fix and it got much closer! There was only one error when building:

`LINK : fatal error LNK1104: cannot open file 'lib-gtest\lib\gtest.lib'`

I found a file called lib-gtest\lib\gtestd.lib and if I rename it to gtest.lib then I get:

`LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc140-mt-gd-1_61.lib'`

**Comment by selaux** [comment]
Do you use the internal boost version?

**Comment by selaux** [comment]
Regarding gtest: What `CMAKE_BUILD_TYPE` are you using? Because the `d` part should be discovered automatically based on build type: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/CMakeLists.txt#L203

**Comment by arnodick** [comment]
Okay, I confirmed that adding set(LOCAL_GTEST_LIB ON CACHE BOOL "" FORCE) to toolchain-msvc.cmake works.

Also, you were correct about the strings.h issue being caused by an external file. I have MinGW installed and it has a strings.h file in it that was being detected by fltk. I did the simplest and laziest thing I could and just renamed MinGW's strings.h to something else, and fltk now builds properly in Visual Studio! This must be an issue with how fltk finds its dependencies, bu I don't know if there is a way to set its build process to ignore strings.h under these circumstances. Maybe it is just looking in too many places for dependencies?

I'll those RUST_TOOLCHAIN commands to fix the unresolved symbols and get back to you. Should those commands be in CMakeLists.txt though? I noticed these lines that specify MSVC and have the same conditionals: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/11fdd97a0a18bd77dd255dea967ff6b232f92312/CMakeLists.txt#L306

**Comment by arnodick** [comment]
Okay, I tried putting ```
if(NOT "${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)")
    set(RUST_TOOLCHAIN "stable-i686-pc-windows-msvc" CACHE STRING "" FORCE)
else()
    set(RUST_TOOLCHAIN "stable-x86_64-pc-windows-msvc" CACHE STRING "" FORCE)
endif()
```
in both CMakeLists.txt and toolchain-msvc.cmake, but no success so far. I also tried just putting set(RUST_TOOLCHAIN "stable-x86_64-pc-windows-msvc" CACHE STRING "" FORCE) straight in there with no conditionals, but no success there unfortunately. Still getting unresolved external symbol errors.

**Comment by selaux** [comment]
Should work now on current master, if not please let us know.

**Comment by arnodick** [comment]
Apologies, been very busy the last couple of weeks.

I'm getting errors about rust crates:
```
error[E0463]: can't find crate for `core`
2>  |
2>  = note: the `i686-pc-windows-msvc` target may not be installed
2>
2>CUSTOMBUILD : error : aborting due to previous error
2>
2>For more information about this error, try `rustc --explain E0463`.
2>CUSTOMBUILD : error : Could not compile `unicode-width`.
2>
2>Caused by:
2>  process didn't exit successfully: `rustc --crate-name unicode_width C:\Users\Arno\.cargo\registry\src\github.com-1ecc6299db9ec823\unicode-width-0.1.5\src\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg "feature=\"default\"" -C metadata=998d4a7ae4bead9d -C extra-filename=-998d4a7ae4bead9d -C rpath --out-dir "E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" --target i686-pc-windows-msvc -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\release\deps" --cap-lints allow --print=native-static-libs -C target-feature=+crt-static` (exit code: 1)
2>CUSTOMBUILD : warning : build failed, waiting for other jobs to finish...
2>error[E0463]: can't find crate for `std`
2>error[E0463]: can't find crate for `std`
2>  |
2>  |
2>  = note: the `i686-pc-windows-msvc` target may not be installed
2>
2>= note: the `i686-pc-windows-msvc` target may not be installed
2>
2>CUSTOMBUILD : error : aborting due to previous error
2>
2>For more information about this error, try `rustc --explain E0463`.
2>CUSTOMBUILD : error : aborting due to previous error
2>
2>For more information about this error, try `rustc --explain E0463`.
2>CUSTOMBUILD : error : Could not compile `itoa`.
2>
2>Caused by:
2>  process didn't exit successfully: `rustc --crate-name itoa C:\Users\Arno\.cargo\registry\src\github.com-1ecc6299db9ec823\itoa-0.4.3\src\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"std\"" -C metadata=f95bc2720b03591e -C extra-filename=-f95bc2720b03591e -C rpath --out-dir "E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" --target i686-pc-windows-msvc -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\release\deps" --cap-lints allow --print=native-static-libs -C target-feature=+crt-static` (exit code: 1)
2>CUSTOMBUILD : warning : build failed, waiting for other jobs to finish...
2>CUSTOMBUILD : error : Could not compile `libc`.
2>
2>Caused by:
2>  process didn't exit successfully: `rustc --crate-name libc C:\Users\Arno\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.43\src\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"use_std\"" -C metadata=dbc53faa32a4be17 -C extra-filename=-dbc53faa32a4be17 -C rpath --out-dir "E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" --target i686-pc-windows-msvc -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\release\deps" --cap-lints allow --print=native-static-libs -C target-feature=+crt-static` (exit code: 1)
2>CUSTOMBUILD : warning : build failed, waiting for other jobs to finish...
2>error[E0463]: can't find crate for `std`
2>  |
2>  = note: the `i686-pc-windows-msvc` target may not be installed
2>
2>CUSTOMBUILD : error : aborting due to previous error
2>
2>For more information about this error, try `rustc --explain E0463`.
2>CUSTOMBUILD : error : Could not compile `winapi`.
2>
2>Caused by:
2>  process didn't exit successfully: `rustc --crate-name winapi C:\Users\Arno\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.8\src\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=fd873b4f3f2fcfb1 -C extra-filename=-fd873b4f3f2fcfb1 -C rpath --out-dir "E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" --target i686-pc-windows-msvc -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\i686-pc-windows-msvc\release\deps" -L "dependency=E:/Documents/Game Design/Mod Projects/test18/_bin/rust\release\deps" --cap-lints allow --print=native-static-libs -C target-feature=+crt-static` (exit code: 1)
2>Done building project "rust-build.vcxproj" -- FAILED.
```
I'll do some more playing around and see if it's something on my end.

**Comment by selaux** [comment]
Seems like the correct rust target is not installed. Try `rustup target add i686-pc-windows-msvc`.

**Comment by arnodick** [comment]
Ah yes that makes sense, had to do a similar thing with the cross compile version will try this out soon!

**Comment by arnodick** [comment]
Apologies again for the long response time.

It's now building! Just had to download the i686 for rust.
