### ISSUE TITLE
Cross-build for Windows on Linux Debian using MinGW errors

### ISSUE THREAD

**Issue by arnodick** [ja2-stracciatella/ja2-stracciatella#726]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

Hi Stracciatella folks,

I'm trying to get Stracc compiling for Windows on a Debian Linux machine and running into issues.

I've got the build portion of it working (I think?) and am at the point where I run make.

There seems to be a bug in the build process. The make process reports:
`target 'rust/CMakeFiles/rust-build' failed`

This is referring to the file JA2PROJECT/_bin/rust/CMakeFiles/rust-build.dir/build.make. If I edit this file by commenting out the line:
'rust/CMakeFiles/rust-build'
then the make process continues, but fails later saying:
`/usr/lib/gcc/x86_64-w64-mingw32/4.9-win32/include/c++/bits/basic_string.h:3017:46: error: 'WINvswprintf' is not a member of 'std'`

This seems to be an issue similar to the Windows Visual Studio build, which gave errors about the wrong strings.h/string.h being used.

I'm not sure if there is actually supposed to be a rust/CMakeFiles/rust-build file that is not being created and should be there, or if it's a bug and the cmake process is writing a line that just shouldn't exist.

Some other issues I ran into, that might help others who are trying to do this cross build:
You need mingw-w64, not just normal mingw! Use:
`sudo apt-get mingw-w64`
Rust doesn't include the standard library for Windows cross-compilation for reasons that are beyond me, and you have to install it yourself.
`rustup target add x86_64-pc-windows-gnu`

A side question: is the cross build meant to make the actual JA2 Stracc launcher, or a Visual Studio project? I only ask because if it is the latter then I'll move on to trying other build methods, because I already have a VS project building (but not compiling).

Thanks for any help! Looking forward to getting Stracc building consistently, and am happy to help in any way I can.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16 | JA2 Gold English  |    no    |    no?     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by arnodick** [comment]
Ah, thanks for the tip! I took the lazy route and commented out these lines:

```
#define snprintf  WINsnprintf
#define swprintf  WINswprintf
#define vswprintf WINvswprintf
```

It is no longer giving an error about strings!

It got to about 98% complete and gave this error when trying to make ja2.exe:

```
make[2]: *** No rule to make target 'rust/x86_64-pc-windows-gnu/release/stracciatella.lib', needed by 'ja2.exe'.  Stop.
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/ja2.dir/all' failed
make[1]: *** [CMakeFiles/ja2.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by selaux** [comment]
To fix that you can `cd` into the rust directory, build the rust lib with `cardo build --release` and check what library is created in target and put the path here: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/CMakeLists.txt#L26 (e.g. `rust/x86_64-pc-windows-gnu/release/stracciatella.dll`)

**Comment by selaux** [comment]
Can you retry with the branch from this PR: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/729? This works without issues, at least on Travis CI. I didn't check whether the executable works yet though...

**Comment by arnodick** [comment]
> 
> 
> Can you retry with the branch from this PR: #729? This works without issues, at least on Travis CI. I didn't check whether the executable works yet though...

Okay great, been away for the last week or so, but will give it a try as soon as I get a chance!

**Comment by selaux** [comment]
Closing because we build for MinGW in CI and it should work. Please reopen if it does not :wink:.
