### ISSUE TITLE
Placing an Item on the floor directly where the character stands/sits renders same character immobile.

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#727]
Using latest git
commit f571f92f58956749187f45531adb27754a098d6a (HEAD -> master, origin/master, origin/HEAD)

When this happens that character can still shoot or throw but wont be able to go in any direction. There wont be footsteps indicators either.

**Comment by JAsmine-ja2** [comment]
I can't reproduce this on either vanilla or Stracciatella.
How exactly can you produce this issue?

**Comment by misanthropos** [comment]
I did not have a .sav but it did not happen to me when I tried 0.20.0. Closing the issue.
