### ISSUE TITLE
Issue with radarmaps

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#73]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

The green square in the radarmaps gets hidden by the lower and the right borders of the radarmap-window. The upper and left borders behave normal.
![radarmap issue](http://img.xrmb2.net/images/932468.jpeg)
left side: normal behavior on the upper-left corner.
right side: wrong behavior on the lower-right corner.

v0.12.189, English JA2 Gold, ja2-ENGLISH-1024x768.bat

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/73

**Comment by derSteFfi** [comment]
the code that draws this is:
```C
			// Find the diustance from render center to true world center
			INT16 const sDistToCenterX = gsRenderCenterX - gCenterWorldX;
			INT16 const sDistToCenterY = gsRenderCenterY - gCenterWorldY;

			// From render center in world coords, convert to render center in "screen" coords
			INT16 sScreenCenterX;
			INT16 sScreenCenterY;
			FromCellToScreenCoordinates(sDistToCenterX, sDistToCenterY, &sScreenCenterX, &sScreenCenterY);

			// Subtract screen center
			sScreenCenterX += gsCX;
			sScreenCenterY += gsCY;

			// Get corners in screen coords
			// TOP LEFT
			INT16 const sX_S = g_ui.m_tacticalMapCenterX;
			INT16 const sY_S = g_ui.m_tacticalMapCenterY;

			INT16 const sTopLeftWorldX     = sScreenCenterX - sX_S;
			INT16 const sTopLeftWorldY     = sScreenCenterY - sY_S;
			INT16 const sBottomRightWorldX = sScreenCenterX + sX_S;
			INT16 const sBottomRightWorldY = sScreenCenterY + sY_S;

			// Determine radar coordinates
			INT16 const sRadarCX = gsCX * gdScaleX;
			INT16 const sRadarCY = gsCY * gdScaleY;

			INT16 const sWidth  = RADAR_WINDOW_WIDTH;
			INT16 const sHeight = RADAR_WINDOW_HEIGHT;
			INT16 const sX      = RADAR_WINDOW_X;

			INT16 const sRadarTLX = sTopLeftWorldX     * gdScaleX - sRadarCX + sX       + sWidth  / 2;
			INT16 const sRadarTLY = sTopLeftWorldY     * gdScaleY - sRadarCY + gsRadarY + sHeight / 2;
			INT16 const sRadarBRX = sBottomRightWorldX * gdScaleX - sRadarCX + sX       + sWidth  / 2;
			INT16 const sRadarBRY = sBottomRightWorldY * gdScaleY - sRadarCY + gsRadarY + sHeight / 2;

			UINT16 const line_colour = Get16BPPColor(FROMRGB(0, 255, 0));
			RectangleDraw(TRUE, sRadarTLX, sRadarTLY, sRadarBRX, sRadarBRY, line_colour, pDestBuf);
```
looks overcomplicated to me, I'm in it right now. I would like to determine the border of the radar screen and limit the green rectangle to this.

**Comment by lynxlynxlynx** [comment]
It's likely just an off-by-one error, so you can try just playing with the values a bit.

**Comment by derSteFfi** [comment]
you are, of course partly, right :)
a bit before that code, there is a 
```C
		SetClippingRegionAndImageWidth(l.Pitch(), RADAR_WINDOW_X, gsRadarY, RADAR_WINDOW_WIDTH - 1, RADAR_WINDOW_HEIGHT - 1);
```
I removed the '-1's. There is a background image that is set for the radar map with +1 for the bottom and left coordinates, so ithink clipping at +0 is legimate.
Then I introduced Limits for the rectangle at RADAR_WINDOW_X + RADAR_WINDOW_WIDTH -1 (and for y respectively). I'll get together a PR as soon as I figure out how to do this on GH :)

I don't think this solution is perfect, the rectangle changes its size near the bottom and right dorners with this...

**Comment by lynxlynxlynx** [comment]
How did it work in the original? Just didn't let itself be drawn that deep into a border?

**Comment by derSteFfi** [comment]
afair in the original the lines weren't drawn at the right and bottom borders.
for the changing size at the bottom, i don't recall it from the original but i guess its part of the problem we have with northmost and southmost tiles in tactical (e.g. #195 )

**Comment by lynxlynxlynx** [comment]
I checked, the original just made sure the whole rect was drawn, no resizing. The way it is now, even removing/shifting a few grid lines on the bottom wouldn't work — you have to remove too many; we display only one row more than the original.

**Comment by JAsmine-ja2** [comment]
![radar-rectangle](https://cloud.githubusercontent.com/assets/17213795/15463743/97205664-20cb-11e6-8117-dba06a887e69.jpg)

Issue is still present in v0.15

**Comment by JAsmine-ja2** [comment]
![radar2](https://cloud.githubusercontent.com/assets/17213795/15463955/cced2d34-20cc-11e6-830f-6dac56bee456.jpg)
Basically the same thing but with a small map.

**Comment by JAsmine-ja2** [comment]
![radar](https://user-images.githubusercontent.com/17213795/34648203-91d4739e-f396-11e7-95ff-b15ef91eea0b.jpg)

This doesn't concern the green rectangle, but might be related: The two mercs on the southernmost row of tiles aren't displayed on the radarmap (Barry & Spider).

This whole issue is really annoying and probably the most severe graphical, stracciatella-introduced issue still present in the game.

**Comment by JAsmine-ja2** [comment]
I really get the impression (not only from the latest specific situation), that the whole displayed area of the tactical map is one, two or maybe three lines too far in the south and not far enough in the northern row.
#195 is definitely related.

**Comment by lynxlynxlynx** [comment]
#195 is not really related — we proved that if we display another row at the top, the maps aren't ready for it. I guess the issue could be we allow for placement in one row too many. Similarly at the bottom, I think any less space and you couldn't move around a San Mona building on the south side.

**Comment by maxrd2** [comment]
Soldier dots should always be rendered with commit efda096 (#733). Green rect wont be cut off anymore.
