### ISSUE TITLE
quick saving

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#74]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**
---

I'm on day 2 of a running campaign in San Mona. I just noticed that quick saving the game takes up much more time than usual. It takes almost 2 seconds (compared to next to nothing in v1.13).
I know that this report is rather vague and probably not of much help. I'll try to gather more information on this. Maybe others experience the same?

EDIT:
I further investigated this issue and found out, that it also happens with normal saving.
Saving and quick saving a game takes significantly longer compared to vanilla JA2 or v1.13. Sometimes it takes even more than 3 seconds.

EDIT2:
This might be related to the time the current session is running. I was in Cambri Hospital (F8) and quick-saving took really long, like 5 seconds.
After exiting, restarting and reloading, the quick-saving was back to normal (=took <1 second).
---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/74

**Comment by lynxlynxlynx** [comment]
Works smoothly for me (HDD). Was this with a modded install?

**Comment by JAsmine-ja2** [comment]
Can't confirm this now. Have played an extensive campaign on 0.15.1 with long sessions. Quicksaving doesn't take long.
Close?

**Comment by lynxlynxlynx** [comment]
Yep, thanks.
