### ISSUE TITLE
"Opening file 'genbutn.sti' failed" when run ja2

### ISSUE THREAD

**Issue by s3341458** [ja2-stracciatella/ja2-stracciatella#742]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)
When start game with ja2 recieved following error:
> terminate called after throwing an instance of 'std::runtime_error'
>  what():  Opening file 'genbutn.sti' failed
> fish: 'ja2' terminated by signal SIGABRT (Abort)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1      | 1.13                |    unknown   |    unknown     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
1. download JA2 from http://freegogpcgames.com/1909/jagged-alliance-2/
2. wine JA2_113_FullRelease_English_7435.exe
3. set up ja2.json as
> {
>     "help": "Put the directory to your original ja2 installation into the line below",
>     "data_dir": "/home/chengyu/games/ja2/"
> }
4. run ja2

Operating system that I am using: 
Linux chengyu 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux

please provide any clue how can I fix this, thanks so much.

**Comment by lynxlynxlynx** [comment]
1.13 is not supported, only the original games.

**Comment by s3341458** [comment]
thanks everything got sorted.

**Comment by mnalis** [comment]
This also happens to me. I don't think it is related to 1.13...

This definitely used to work in old bitbucket.org git revision 97316b596e35fef679410f5e2009cb97f8f134bc (I've been away for time, yes), and is broken in current master 76ae1e7043f75948727093e66a0d7a3253f03aef

I've run git bisect, and it says the problematic commit is this:
4436b98dd57206bea98108c2ed875e754ca92de1

So I guess it might be something related to new JSON configuration file.
