### ISSUE TITLE
Missing libpng12.so.0 on Ubuntu 18.04

### ISSUE THREAD

**Issue by saimonsez** [ja2-stracciatella/ja2-stracciatella#747]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
ja2-launcher does not work on Ubuntu 18.04 out of the box.

$ sudo dpkg -i ja2-stracciatella_0.16.1_amd64.deb 
$ ja2-launcher 
ja2-launcher: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1 | JA2 from GOG  |    no    |    no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by saimonsez** [comment]
There is an easy workaround, as I just found out. According to [this blog post](https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html) libpng12-0 has been dropped starting with Ubuntu 16.10. Just download and install it from [xenial packages](https://packages.ubuntu.com/xenial/amd64/libpng12-0/download).

However, this might be a security risk.

**Comment by lynxlynxlynx** [comment]
Our builds are not against the latest ubuntu, that's all.

**Comment by lynxlynxlynx** [comment]
Well, as of #745, we're now building for xenial, so it closes this one too. Everyone the same situation can grab a nightly from here:
https://ja2-stracciatella.github.io/download/
