### ISSUE TITLE
Doreen Harrows still in Drassen C13 after quest completion

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#750]
### Doreen Harrows is still in sector C13 even though I already convinced her to leave

On day 1, I peacefully resolved the quest number 20 "Doreen is cruel to children" by convincing her to leave.
On day 4, I found that she is still in sector C13 Drassen.
Both, the history log and the Quest Debug Screen show the quest as done.
[SaveGame11.sav.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2705315/SaveGame11.sav.zip)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ja2-stracciatella_0.16.1_amd64.deb | JA2 Gold English (GOG)  |    ~no~ yes    |    yes    |

- savegame attached
- operating system is an up to date Debian 9.6 (Stretch)

**Comment by JAsmine-ja2** [comment]
I can confirm this bug in
JA2S 0.16.0 win64 on top of JA2 1.12 EN Gold
and in
JA2 1.12 Gold vanilla.

Here's how to reproduce it:
1) start the Doreen-quest by either talking to a civilian ("There is evil in our town.") or by talking to Doreen.
2) Talk Doreen out of running the factory (solve quest peacefully). When she starts walking away, enter strategic view and leave the sector (load another sector). Do this BEFORE Doreen reaches the edge of the tactical map.
3) Now, when you re-enter C13, Doreen is parked near the edge of the map
![screen000](https://user-images.githubusercontent.com/17213795/51786020-f7d3b500-215e-11e9-92b1-5bed9dcc8f5c.jpg)
4) In the evening, she will leave the map, according to her schedule and re-appear the next morning (also according to her schedule). She will then remain on the map permanently.

Here's another savegame with Doreen present in C13 after the quest was resolved.
[SaveGame01.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2798898/SaveGame01.zip)
