### ISSUE TITLE
IMP quiz honest answers mod directory case sensitivity

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#751]
This bug report is opened following the discussion in #303 

### IMP quiz honest answers mod directories lowercase differ from the base game

- The instruction for the mod in `IMP quiz honest answers mod.txt` read

> Just copy the data-folder into your JA2 folder. No files will be overwritten.

- My Jagged Alliance 2 from **GOG** names the directory `/Data/BinaryData/`. That is twice **uppercase D**.
- The v0.16.1 (2018-04-08) of the IMP quiz honest answers mod names the directory `/data/Binarydata/`. That is twice **lowercase d**.
- Thus when following the instructions `IMPTEXT.EDT `will be in the wrong directory and the mod will not work.
- The workaround is to manually moving `IMPTEXT.EDT` to `/Data/BinaryData/`. Then the mod works.

I suggest to either: 

1. Change the instruction in `IMP quiz honest answers mod.txt` to _Just move `IMPTEXT.EDT into `/Data/BinaryData/` inside your JA2 folder._

2. Repackage `IMPTEXT.EDT` to `/Data/BinaryData/`. I only own the GOG version of Jaggged Alliance 2 and cannot check how this will affect other versions.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.16.1 (2018-04-08) | JA2 Gold English (GOG)  |    no    |    no     |

I checked this in Debian Stretch and OS X 10.9 Mavericks.

**Comment by lynxlynxlynx** [comment]
Finally took a look. I reinstalled and yes, everything is caseful, on ext4 and it just works. There's no copying needed any more, if there ever was, and we even print a debug statement whenever we use mod resources. So the only thing to do is to clean up the docs. :)
