### ISSUE TITLE
Segmentation fault on soldier death

### ISSUE THREAD

**Issue by RinneT** [ja2-stracciatella/ja2-stracciatella#753]
If the death animation of a soldier finishes while he is on screen, the game crashes with a segmentation fault. Moving the camera so the soldier disappears before the animation is finished doesn't 

I get differing frame stacks, which is probably due to faulty memory allocation.
Sometimes it crashes during a libc call in the radeonsi driver, last time it crashed in Blt8BPPDataTo16BPPBufferTransZTransShadowIncObscureClip() at /src/game/TileEngine/RenderWorld.cc:3306

I have bisected the issue and landed at commit 25503e9ab721d2f67276889015d448e8eca1a7e3

Reverting this commit fixed the issue for me.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  current head | JA2 Gold English  |    yes    |    yes     |

Savegame: If you shoot the soldier with Len he should die immediately:
[CrashDuringDeath.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2752428/CrashDuringDeath.zip)

How to reproduce: Kill the soldier
OS: Gentoo linux

**Comment by lynxlynxlynx** [comment]
@maxrd2 can you look at this? Seems like one of the blit functions isn't happy about the buffer changes.

**Comment by maxrd2** [comment]
Should be fixed now @lynxlynxlynx 

@RinneT thank you for detailed report.
