### ISSUE TITLE
TODO0008: Attitude generation is broken

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#756]
### Attitude generation results are different that quiz answers suggest

Already reported as #405 
Closed as invalid but clearly doesn't work

### How to reproduce
Select quiz answers:
5
3
1
1
3
4
4
4
2
1
3
5
1
4
4
1
This selection has exactly 1 attitude selected by 2 answers (aggressive). All other attitudes have at most 1 answer.
This should generate an aggressive merc regardless of what number RNG picks.
But it doesn't.

There are 2 bugs next to each other that cause this. First is TODO0008.
Second, the final assignment when picking a stat should be
iAttitude = i;
instead of
iAttitude = iCounter2;

After fixing those I can finally generate an aggressive merc.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.16.1 | eg. JA2 Gold En  |    yes    |    no     |

**Comment by akdjka** [comment]
Nope. Button X = case (X-1)

**Comment by lynxlynxlynx** [comment]
Then you get PSYCHO twice by the eight question.

**Comment by akdjka** [comment]
Yes, but psycho is personality, not attitude.
That character is both aggressive and psychotic.

**Comment by lynxlynxlynx** [comment]
Oh, sorry, too similar — you are right. Also agree on TODO 8. Care to submit a pull request with the change?
