### ISSUE TITLE
Behavior in San Mona's brothel

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#76]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

The brothel doesn't seem to work as intended. When talking to Madame for the first time, she does nothing but give you access to her establishment, allowing you to go to Maria and rescue her without paying any money.

It's not possible to "use" the service.

I'm not quite sure, if the brothel was somehow censored in English JA2 Gold?
I guess, that this is an issue not introduced by Stracciatella. Maybe, Stracciatella could revert this back to normal (=working) behavior, though?

I've attached a savegame just before talking to Madame for the first time.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/76

**Comment by lynxlynxlynx** [comment]
So a data bug, fixed with non-free data. Not much we can do about it in this project. Voting to close.

**Comment by derSteFfi** [comment]
I agree. Although i think finding an oper solution would be great. Maybe we can tackle this again if and when we get the corresponding ressources externalized (stretch on IF)?

**Comment by derSteFfi** [comment]
lokks like the disable is located [here](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/Build/TileEngine/Explosion_Control.cc#L2120)

we should be able to bring this back.

**Comment by derSteFfi** [comment]
PR pending (#256)

**Comment by lynxlynxlynx** [comment]
The question is, does the commented code fail gracefully if the data files are not there? The original fix also contains a binary .npc file (huh) besides the modified cc file. If you didn't have the cutscene before and now do, just disregard my comment. :)
