### ISSUE TITLE
Cleaning blood from knives

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#769]
### One can clean blood from a knife
There are (at least 2 ways to clean up a knife).
One is surely a bug:  throw a bloody knife through a window which still has glass. Glass stops the knife and cleans it up.
The other is arguably a feature: throw it at a ground.

Fixing the latter is trivial and if there's interest I can do it.

Fixing the first is not trivial. At the point where the game decides about item placement there's no information about the item itself; just a bullet with a flag "is knife".

Best fix? My first idea is to extend the bullet class with a pointer to the item it represents which is null for all bullets that are not items? As well as remove redundant fields (like status).
Though simply adding a "is bloody knife" flag would work as well.

I may try fixing the first as well.

Attached a save that makes testing both cases easy.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  ce14a7344a8 | eg. JA2 Gold Dutch  |    yes/no    |    yes/no     |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2776907/s.zip)

**Comment by lynxlynxlynx** [comment]
The second is definitely a feature and widely known — not to be removed. 

The bullet class is a misnomer if it's for everything, but I don't see a problem with your plan.

**Comment by JAsmine-ja2** [comment]
+1 for not removing the second "feature".

**Comment by akdjka** [comment]
I see that bullets are a part of a saved game. I guess that kills my fix idea?

**Comment by akdjka** [comment]
But the extra flag would work. There are 8 flags already and 16 bits for them.
As long as the extra flag had semantics "is bloody" and was used together with "knife", saves would be 2-way compatible.

**Comment by akdjka** [comment]
Going through the code I found another way to clean up a knife.
Throw it at enemy who has full inventory. A clean knife will appear on the ground.
I will change it to be always bloody....
