### ISSUE TITLE
Different paths taken when running and walking?

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#787]
Not sure if it's a bug but it's not something I'd expect.
In the attached save, order Johny to walk or run to punch enemy. In either case a different path is taken.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  f970499b5 | JA2 Gold En  |        |        |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2895755/s.zip)

**Comment by JAsmine-ja2** [comment]
I think, this is a result/limitation of the 25 AP system in use.*

| situation | walking AP cost | running AP cost |
| - | - | - |
|  1st tile (straight) | 2 AP  | 2 AP |
| 1st tile (diagonal) | 3 AP | 3 AP |
| following tile (straight) | 2 AP | 1 AP |
| following tile (diagonal) | 3 AP | 2 AP |

When going straight, running costs half as much compared to walking.
When going diagonally, running costs two thirds of walking. IMO, illogical and not consequent. 

As a result, a different path might be the "best" (aka "cheapest") one, depending on the character running or walking.


* Ideally, running 1 tile diagonally would cost 1,5 AP. This is not possible. If max. AP was e.g. 50 and every AP-cost was just multiplied by 2, running diagonally could cost 3 AP per tile (vs. 6 AP when walking). One of the reasons why 100 AP system was introduced years ago in v1.13...

**Comment by lynxlynxlynx** [comment]
Yeah, let's close this. 100 AP is also out of scope for us, however it could be a mod once all AP costs are externalised. That deserves its own enhancement request though.
