### ISSUE TITLE
Picking up item from the ground for 0 AP

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#790]
Pick up the gun at Johny's feet

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
| f970499 |  JA2 Gold En  |        |       |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2896700/s.zip)

**Comment by JAsmine-ja2** [comment]
Can be recreated when loading the savegame in JA2S or vanilla.
