### ISSUE TITLE
Music Stop error

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#805]
### What is wrong
I keep getting "ERROR   [Music Control   ] Music Stop -1 3" in the console while playing the game.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  de0701d089dcd947fd49ff918ae016a621f2dfcf | ENGLISH  |        |         |

Debugging told me that it's the `MusicStop()` call in `MusicPlay`.
`fMusicPlaying` is `TRUE` and `uiMusicHandle` is `NO_SAMPLE`.

**Comment by lynxlynxlynx** [comment]
Thanks, looks like just a needless warning corner case.
