### ISSUE TITLE
Energy cost(?) when picking locks

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#81]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

This is an old vanilla bug that is still present: every time a merc tries to pick a lock, he gains 2 points of energy. Maybe it's a typo and was supposed to cost 2 points of energy instead?

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/81

**Comment by derSteFfi** [comment]
sooo... we close this? :)

**Comment by selaux** [comment]
I would also vote to close...

**Comment by lynxlynxlynx** [comment]
so everyone is in agreement, closing.
