### ISSUE TITLE
About supporting chinese localization maybe?

### ISSUE THREAD

**Issue by ChinaSakhalin** [ja2-stracciatella/ja2-stracciatella#810]
Uh, sorry for devs and everyone, but I don't know how to use this. I found the original english text file in source code named "_EnglishText.cc", I should translate it into chinese right? I don't know programming, but translation is good, so after I made it, I should give the file to developers like you and you make them work, right?

**Comment by lynxlynxlynx** [comment]
Translating the file would be the first step, correct. The problem is that the JA2 fonts don't have Chinese glyphs though, so first a solution for that needs to be found, for you to not waste work. Maybe there's already a modded font out there?

**Comment by ChinaSakhalin** [comment]
Thank you, sir! Really appreciated! Didn't think the reply come fast like this. I will translate, thank you again!

**Comment by JAsmine-ja2** [comment]
@lynxlynxlynx 
Yes, indeed. Old official v1.13 release has chinese localization with modded fonts included:

![SCREEN000](https://user-images.githubusercontent.com/17213795/55580958-0bca0300-571c-11e9-8d7e-b19b7520d4b6.jpg)
![SCREEN001](https://user-images.githubusercontent.com/17213795/55580960-0bca0300-571c-11e9-9774-03cd757e0dda.jpg)
![SCREEN002](https://user-images.githubusercontent.com/17213795/55580961-0c629980-571c-11e9-9df5-5b1e7da800d2.jpg)

Download available here:
http://kermi.pp.fi/JA_2/v1.13_Releases/Official/Chinese/

@ChinaSakhalin 
I can't judge if the old localization of v1.13 is complete and of good quality - but it can probably be of help for you.

**Comment by JAsmine-ja2** [comment]
Just for reference: @gtrafimenkov brought up the idea for a "master font.slf" which supports all game versions here: #43

**Comment by ChinaSakhalin** [comment]
Thank you all, gentlemen! I really appreciate your replies. And I have finished the translation, and slightly changed GameRes.cc and GameRes.h file, didn't know whether I did right or not. I just upload here, or somewhere else? if I did something wrong, please, no hesitate to tell me. I just want to give a little contribution to your great MOD, I really love the original JA2, and I love your idea, so please, if the translation file is bad, I will correct it. Thank you!

[ja2-stracciatella-0.16.1.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3050478/ja2-stracciatella-0.16.1.zip)

**Comment by lynxlynxlynx** [comment]
Cool, that's a start. I'll clean it up and post a WIP pull request. Please also translate the three files in:
build/externalized/strings/

use -cn as the language suffix.

**Comment by lynxlynxlynx** [comment]
Once the test build is complete, you will be able to play around and see if any of the translations need changing. Also, please dig up the chinese font from the 1.13 install that Jasmine-ja2 mentioned above. Without it, you'll just see question marks instead of most of the text.

**Comment by ChinaSakhalin** [comment]
> Once the test build is complete, you will be able to play around and see if any of the translations need changing. Also, please dig up the chinese font from the 1.13 install that Jasmine-ja2 mentioned above. Without it, you'll just see question marks instead of most of the text.

Sorry for the missing texts, I've finished them and uploaded here. And about the chinese font of 1.13 install, I just found the old 1.13 chinese version uses winfont, that is some players told me. They said build a sole font file for JA2 is impossible, the words are too many and the workload is huge. So I found a old JA2 1.13 sourcecode which may has included some code about winfont, didn't know if it is functional.

The fonts are useless, look same with the original.[Fonts.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3051038/Fonts.zip)
[JA2.v1.13-4452.sourcecode.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3051039/JA2.v1.13-4452.sourcecode.zip)
[ja2-stracciatella-0.16.1.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3051040/ja2-stracciatella-0.16.1.zip)

**Comment by lynxlynxlynx** [comment]
The three file translations are likely malformed, but this winfont situation is the thing that really complicates matters. I don't have the time to look into transposing/reimplementing support for that, so it will have to wait for someone else. If you know any Chinese coders that'd be interested, do bring them on board.

**Comment by noword** [comment]
I fork the source and try to make this game support Chinese with original font system.
When all done, I will open a pull request.
@ChinaSakhalin  how can I contact you, maybe provide your QQ number? My email address: noword@sina.com
