### ISSUE TITLE
Leftover buttons after bloodcat ambush

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#815]
### What is wrong
I was exploring at night with Shadow and ran into a Bloodcat ambush.
I was knocked unconscious during the fight (I think) and got a dialog saying that they showed me no mercy.
After closing the dialog it showed the map screen with 3 leftover buttons from tactical.
![after_bloodcat_death](https://user-images.githubusercontent.com/1009600/55855430-6cfc3700-5b5f-11e9-8ecd-beefaca21e18.png)

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  de0701d089dcd947fd49ff918ae016a621f2dfcf | ENGLISH  |        |         |

**Comment by JAsmine-ja2** [comment]
Seems like we've discovered another way to trigger #366. I think we should close this one and keep #366

**Comment by flaviojs** [comment]
It shows the same kind of result but the code that triggers it can be different, so fixing one case might not fix the others.
I think it's fine to close this issue as long as the other issue tracks what "duplicates" have been fixed.

**Comment by flaviojs** [comment]
In the save of #679 the player gets knocked out and I get the same message, so this is a duplicate of that issue.

Backtrace in the function that creates those buttons:
```
#0  CreateTEAMPanelButtons () at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Interface_Panels.cc:2518
#1  0x000000000066621b in InitializeTEAMPanel () at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Interface_Panels.cc:2259
#2  0x000000000064bcea in InitializeCurrentPanel () at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Interface.cc:258
#3  0x000000000064bfb5 in SetCurrentInterfacePanel (ubNewPanel=ubNewPanel@entry=TEAM_PANEL) at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Interface.cc:345
#4  0x00000000006d5f1d in UpdateCurrentlySelectedMerc (bSquadValue=2 '\002', pSoldier=0xe17d80 <Menptr+20288>) at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Squads.cc:743
#5  RemoveCharacterFromSquads (s=s@entry=0xe17d80 <Menptr+20288>) at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Squads.cc:319
#6  0x00000000005f6db0 in HandleStrategicDeath (s=...) at /home/hp/tmp/ja2-stracciatella/src/game/Strategic/Strategic.cc:26
#7  0x0000000000607bed in StrategicHandlePlayerTeamMercDeath (s=...) at /home/hp/tmp/ja2-stracciatella/src/game/Strategic/Strategic_Merc_Handler.cc:123
#8  0x000000000069e271 in HandlePlayerTeamMemberDeath (pSoldier=0xe17d80 <Menptr+20288>) at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Overhead.cc:2353
#9  0x00000000006b6ec7 in HandlePlayerTeamMemberDeathAfterSkullAnimation (pSoldier=<optimized out>) at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Soldier_Ani.cc:3017
#10 0x0000000000666eec in FinishAnySkullPanelAnimations () at /home/hp/tmp/ja2-stracciatella/src/game/Tactical/Interface_Panels.cc:2853
#11 0x000000000076fc8a in InternalLeaveTacticalScreen (uiNewScreen=<optimized out>) at /home/hp/tmp/ja2-stracciatella/src/game/GameScreen.cc:324
#12 0x00000000007702fa in MainGameScreenHandle () at /home/hp/tmp/ja2-stracciatella/src/game/GameScreen.cc:623
#13 0x000000000076e1ad in GameLoop () at /home/hp/tmp/ja2-stracciatella/src/game/GameLoop.cc:200
#14 0x00000000004e929e in MainLoop (msPerGameCycle=25) at /home/hp/tmp/ja2-stracciatella/src/sgp/SGP.cc:238
#15 main (argc=1, argv=<optimized out>) at /home/hp/tmp/ja2-stracciatella/src/sgp/SGP.cc:488
```
This looks like the transition from tactical view to strategic view. `InternalLeaveTacticalScreen` is called with `MAP_SCREEN`

This fixes it for me: [fix_issue_679_815.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3315705/fix_issue_679_815.txt)

Issue #366 has a different root cause, so I think this issue and #679 are not duplicates of #366.

**Comment by maxrd2** [comment]
In fact this is unrelated to 366, have provided a patch that should solve this and possibly similar cases when switching interfaces/leaving tactical.
