### ISSUE TITLE
Crash to desktop after picking up Tear Gas Grenade in I8 Central SAM

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#821]
### How to reproduce

1. Load attached save game.
2. Load Sector I8 Central SAM
3. Move Gasket to the northeastern fence.
4. Pick up the stacked Tear Gas Grenade.

### Result
Crash to Desktop
[i8.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3138182/i8.zip)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.16.1 (2018-04-08)| JA2 Gold English  |    don't know    |    yes     |

Operating system is Debian Stretch

PS:
I can't fix this myself.

**Comment by lynxlynxlynx** [comment]
You can work around it by opening the merc inventory first. Had trouble reproducing at first — just ctrl-click on the pile immediately.

Something corrupts the memory, mangling a bit of gpWorldLevelData, so it then crashes here:
```
#0  0x0000555555a3ba8a in LightTrueLevel (sGridNo=25601, bLevel=0 '\000')
    at src/game/TileEngine/Lighting.cc:578
578      iSum=pNode->ubNaturalShadeLevel - (pNode->ubSumLights - pNode->ubFakeShadeLevel )

#1  0x000055555598a6ba in DistanceVisible (pSoldier=0x555556058488 <Menptr+2536>, bFacingDir=9 '\t', 
    bSubjectDir=9 '\t', sSubjectGridNo=25601, bLevel=0 '\000')
    at src/game/Tactical/OppList.cc:953
#2  0x000055555594f433 in CheckForDisabledForGiveItem ()
    at src/game/Tactical/Interface_Panels.cc:421
#3  0x00005555559496e0 in InternalBeginItemPointer (pSoldier=0x555556058488 <Menptr+2536>, 
    pObject=0x555557af7484, bHandPos=-1 '\377')
    at src/game/Tactical/Interface_Items.cc:2823
#4  0x0000555555924f3d in HandleAutoPlaceFail (pSoldier=0x555556058488 <Menptr+2536>, o=0x555557af7484, 
    sGridNo=9232) at src/game/Tactical/Handle_Items.cc:1184
#5  0x00005555559253d0 in SoldierGetItemFromWorld (s=0x555556058488 <Menptr+2536>, iItemIndex=39, sGridNo=9232, 
    bZLevel=0 '\000', pfSelectionList=0x0)
    at src/game/Tactical/Handle_Items.cc:1292
#6  0x0000555555925794 in HandleSoldierPickupItem (s=0x555556058488 <Menptr+2536>, item_idx=-1, gridno=9232, 
    z_level=0 '\000') at src/game/Tactical/Handle_Items.cc:1388
#7  0x00005555559bf8c8 in AdjustToNextAnimationFrame (pSoldier=0x555556058488 <Menptr+2536>)
    at src/game/Tactical/Soldier_Ani.cc:1557
#8  0x0000555555995731 in ExecuteOverhead ()
    at src/game/Tactical/Overhead.cc:774
#9  0x0000555555a973cd in MainGameScreenHandle ()
    at src/game/GameScreen.cc:494
```

**Comment by lynxlynxlynx** [comment]
Your save is corrupted, sorry.

CheckForDisabledForGiveItem uses gpSMCurrentMerc to know the actor and is set first at load time (later only if you reselect someone else). And already in the save the supposedly selected one has a position of NOWHERE, which is what ends up causing the out of bounds access.
