### ISSUE TITLE
Crash from panic trigger when there are no soldiers.

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#851]
I first got this crash when testing the fix for #688.

Example 1: [crash1.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3496535/crash1.zip)
 * shoot the torso
 * skip your turn
 * kill everyone with Alt+O (with cheats enabled)

Example 2: [crash2.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3496579/crash2.zip)
 * shoot the legs

-----

I'm using revision 298096f574ae53599783d59ff1523806a7a9607b and the crash is in `ClosestPanicTrigger`:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/298096f574ae53599783d59ff1523806a7a9607b/src/game/TacticalAI/PanicButtons.cc#L368

There are no army guys here, only hicks (civilians), so this is performing a division by 0.
I wouldn't be surprised if there is other code like this, since fighting the army is your "main job".

I see 2 ways of fixing this:
 * exit the function if `pSoldier` is not part of the army (easy)
 * extend the logic to non-army enemies (hard)

**Comment by lynxlynxlynx** [comment]
The way it is used, I'd just go for the simple pragmatic fix.
