### ISSUE TITLE
"stracciatella.h" is missing for building via "Generate Visual Studio Solution"

### ISSUE THREAD

**Issue by hb029** [ja2-stracciatella/ja2-stracciatella#862]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
This problem occurs with Windows 10. When downloading the trunk, resolving all dependencies and using cmake for the tooling with "Generate Visual Studio Solution", then Visual Studio does not compile, for the include "stracciatella.h" is not found. It might be some file that is thought to be generated by cmake, for it is not in the repository. This reproduces with the option for Visual Studio 15. The other options are not tested.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  b794c9c | eg. JA2 Gold German|    no    |    yes     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
Did cmake finish, configure, successfully?

This is what our build bot does:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/appveyor.yml

**Comment by flaviojs** [comment]
Maybe you opened the project and saw that error before building?
If that is the case, then everything is fine.

That header is generated with rust during the build.

**Comment by hb029** [comment]
Actually I found the problem in the msvc output. In my setup, cargo is outdated and the libstracciatella-build fails somewhere in the process. I have created the setup sometimes around 2017. I will have to figure out, how to get cargo 1.32.0.

Thanks for the hints so far!

Appendix:
5>CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
5>  Could NOT find Cargo: Found unsuitable version "0.25.0", but required is at
5>  least "1.32.0" (found C:/Users/User/.cargo/bin/cargo.exe)
5>Call Stack (most recent call first):
5>  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
5>  D:/OldStuff/JA2_MDK/StracciatellaC/ja2-stracciatella-trunk/cmake/FindCargo.cmake:24 (find_package_handle_standard_args)
5>  CMakeLists.txt:7 (find_package)
5>
5>
5>-- Configuring incomplete, errors occurred!
5>See also "D:/OldStuff/JA2_MDK/StracciatellaC/workspace/libstracciatella-prefix/src/libstracciatella-build/CMakeFiles/CMakeOutput.log".
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet.
5>Die Erstellung des Projekts "libstracciatella.vcxproj" ist abgeschlossen -- FEHLER.

**Comment by selaux** [comment]
You need to have at least rust version `1.32.0` installed, see [COMPILATION.md](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/COMPILATION.md#rust-notes)
