### ISSUE TITLE
Main menu music doesn't restart

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#87]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

When I start the game, the main menu music plays fine.
But when I load or start a game and then end the game and return to the main menu, it remains silent. No music starts.
I think the main menu music should always play when inside the main menu.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/87

**Comment by derSteFfi** [comment]
probably related to #106 or at least can be solved at the same spot

**Comment by JAsmine-ja2** [comment]
How to easily reproduce this:
1) Start a new game.
2) End the current game.
-> Game takes you back to the main menu. With no music playing.
