### ISSUE TITLE
Can't save games after a certain Point in the Game

### ISSUE THREAD

**Issue by teddy123454321** [ja2-stracciatella/ja2-stracciatella#872]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong

After a certain Point in the Game, around Day 50, I repeatedly receive an error message when trying to save games. If sometimes it does work, I find the slot empty after reopening the game. It happend to me twice now having to entirely restart the game. Also: It happened both time shortly after I hired Ivan (haha).

I also dont understand where the straciatella app puts my savegames because the savegames folder from the JA2 game data I use with the straciatella app is always empty. 

I am using the straciatella app with mojave 10.14.6 and an unupdated version of the ja2 gold package. 

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold Dutch  |    yes/no    |    yes/no     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by lynxlynxlynx** [comment]
This has been fixed already #487 and it is indeed kinda Ivan's fault.

**Comment by lynxlynxlynx** [comment]
We'll likely make a new release before the end of the year; until then you could grab one of the travis builds, since the nightlies have been discontinued.

**Comment by flaviojs** [comment]
Just to make sure, since you didn't specify which git version you're using...
Are you using a git version before f8fbab887573707de8758304feb83e7a8a7f33a7?

If you are then hopefully it's already fixed with #487 and you can try updating and recompiling.

**Comment by lynxlynxlynx** [comment]
That's just the template he ignored instead of filling out ...

**Comment by flaviojs** [comment]
Ups, I see... then it's probably the last release 0.16.1.

**Comment by teddy123454321** [comment]
Yes, exactly. Sorry about that. I wasnt really sure what to fit in. Thanks also for your help, even though I unfortunately neither know what a travis build, nor what a nightly is, nor do I understand the article attached. But I tried (and so did you).
