### ISSUE TITLE
Nightlies are not built anymore

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#873]
### What is wrong
Nightlies are not built anymore. This is because I had a job running on a personal CI server that actually triggered the nightly build. This CI server does not exist anymore (actually for a long time now :wink: ).

It would be nice to evaluate whether GitHub Actions can be used for that, so everybody in the team has access.

**Comment by lynxlynxlynx** [comment]
Yep, it supports cron, basically:
https://help.github.com/en/articles/events-that-trigger-workflows#scheduled-events-schedule

**Comment by selaux** [comment]
For reference this was the previous script in jenkins:

```groovy
node() {
    def today = new Date().format('yyyyMMdd');
    def buildId = today
    def branch = "master"
    def message = "Nightly build $buildId triggered via API request"
    
    stage "Git Poll"
    git poll: true, url: 'https://github.com/ja2-stracciatella/ja2-stracciatella'
    
    stage "Trigger travis nightly build"
    withCredentials([[$class: 'StringBinding', credentialsId: 'travis-ci-trigger-token', variable: 'TOKEN']]) {
        def headers = [
            [name: 'Travis-API-Version', value: '3'],
            [name: 'Authorization', value: "token ${env.TOKEN}" ]
        ]
        def postBody = """{
            "request": {
                "message": "$message",
                "branch": "$branch",
                "config": {
                    "env": {
                        "global": [
                            { "secure": "hGKZH6OhE4695iUBAOIUI1j6ZySnsBr/vMMLP3yEgOgEcpV4uHZd7ksEDMQ3O7sbc3YGA0a5dBZZmBktJF7FWYazcy7X7G2UTDNuigYdEcsD46XqJ+f9c91QofOsyvg2OFFU98ORJ7Q2l6a7aemdM/UAwEiM1MV65TMkPZURwEGD6iXI7JtbZI0llfHeXhccksqrO/GUH8VyfYn0LA71dagxzcGHThndCTqizqxtkiI0bUquXErt4w09faie2gB0pwRBSZvlYMHaqcsoC8WcGy5upUPxIX5hfpGrHMwpcHH2S3k6OWNYhILFYqfR/2p4zlnzwXC27YETMO9XOGVjZegePkRRR1iurW5KtVVy8a7Ap/CmS3VC99yvGIRMDJIgSLQku8GC4GRSNjPUXvhP0Sf6NEN5xCyy/zlD3KGJelBXjoGzlhFRUIqamo7ahrnIjtO0op2Z7EOcfNP5146EJnMTA1Nk07x5y9TSdveLvbFziI3ak6VSF+prffwoET5AOYddUNlWdjdtEEK/m/kKYyUa1dlgFVzBwwcpfSD3aJbKtwLAeQf3gUDrHX/WQD1srT2vnt8Zk4c+mTPn3l7Qt/ygot2NFKTnxW7sjD/rdVYDHh99M3I/lCI16TFt7GnJ7/DPqf8vqOld6ubfu/+ExdkFvVFfoYTDpNgXyDEyCWM=" },
                            { "secure": "aCkkzCZe/Vm5eaL/Rg+CPeBVS5/WeAFmgIY/RueI61tj2WnjrgoE58hftOcg7oIptdz2heQTEB16aUpt6W+wqGKRSGKeo8G/y/Q08WNLcVgomDvfT6snQKm/LVcxc6a9sN7HZgWGdfkHVUP3tA/wTO2w/nKKIrMu3PmeSMkCJlM6CV8TQO/daOfJMUWkIImrzBO5E2lK11a/G4w/RxS0BKhnR6F/VEfvAkh/CDV/BK8Fpeiowk3bvIMA8Bc/Ect03A5mf2y17E9uFI2KEk77cll/bAp/GlwiE0YEjBfY0q6agHREHL605CGAQUkYGrZCrP6gGX/X/b7hjcCaOTV5DdoDCXiceINMxb2x/cKPyMTP5vAHpy+3PnZM2P18UzYwPmo8+3BCE5fhNBJ3xeFK9HkzjCbfW5REMcQ5bY1a+Yc5Alf4dNe+Q5b0hLBPtgm9cgxIXft6fIRBTS9xV9bHWgiEySgCpfPNAE9jqyb+gpoXtPLowVbuc2WsGW1XpUXvbGyCsyFQX0mAoH8SbfInJd6oAwS3Dg8/Ver6X1NjBzFvqI6xHxR+Io8TQ3P5PF30k17X8FitgDOZ/9VvnA9wi8/pxc8zV+2qQF//3UX6KKcxDKAFlIugLOknssof1p4pWcRPI8nhXB5m0ce//bX5To1FwJrEs5ryNfQTQBnr1Ow=" }
                        ],
                        "matrix": ["NIGHTLY_VERSION=$buildId"]
                    }
                }
            }
        }"""
        
        httpRequest(
            acceptType: 'APPLICATION_JSON',
         
            contentType: 'APPLICATION_JSON',
            validResponseCodes: '200:299',
            customHeaders: headers,
            httpMode: 'POST',
            requestBody: postBody,
            url: "https://api.travis-ci.org/repo/ja2-stracciatella%2Fja2-stracciatella/requests"
        )
    }
    
    stage "Trigger appveyor nightly build"
    withCredentials([[$class: 'StringBinding', credentialsId: 'appveyor-ci-trigger-token', variable: 'TOKEN']]) {
        def headers = [
            [name: 'Authorization', value: "Bearer ${env.TOKEN}" ]
        ]
        def postBody = """{
            "accountName": "ja2-stracciatella",
            "projectSlug": "ja2-stracciatella",
            "branch": "$branch",
            "message": "$message",
            "environmentVariables": {
                "NIGHTLY_VERSION": "$buildId"
            }
        }"""
        
        httpRequest(
            acceptType: 'APPLICATION_JSON',
            contentType: 'APPLICATION_JSON',
            validResponseCodes: '200:299',
            customHeaders: headers,
            httpMode: 'POST',
            requestBody: postBody,
            url: "https://ci.appveyor.com/api/builds"
        )
    }
}
```

**Comment by flaviojs** [comment]
These GitHub workflows/actions look good at a glance.

I see 3 ways of making nightly builds in the cron job:
1) send a custom build request like the original script (if I understood it correctly)
2) set a nightly tag to master (needs commit access?)
3) have a nightly branch and merge master into it (needs commit access?)

any preference?

**Comment by lynxlynxlynx** [comment]
3 sounds the cleanest, but 1 is fine with me too.

**Comment by flaviojs** [comment]
Good, it seems like we have a working github action that updates the nightly branch at 23:00 UTC (fast forward only).

Now we need to make travis and appveyor build when it changes.

**Comment by flaviojs** [comment]
http://builds-ja2.stefanlau.com/nightlies/ has most builds after 3:00, but I don't know the timezone of that server.

At what time were they being built before?

**Comment by selaux** [comment]
Sweet. The previous builds were made at 3am CET if I remember correctly. But I don't think the exact time matters.

**Comment by flaviojs** [comment]
:tada: Yay, nightly releases are back!

But there are some issues...
1) uploading the deb failed just like the previous time in 2018. Is it gonna continue to fail? Maybe we should add a retry option or change the upload mechanism (not ftp).
2) the mingw release is bigger than expected, from the output of `objdump -g` it appears to be debug info from rust.

When nightly does not change I except no new files.
This scenario still needs testing (wait a day without updating master).

**Comment by flaviojs** [comment]
Adding a retry option was not enough, ftp is still failing... this time 2 uploads failed.

Travis starts all jobs at the same time and they can finish around the same time.
Maybe the ftp service limiting the number of concurrent uploads?

If it is, as a workaround, setting the retry delay higher than the upload time should solve it.

**Comment by flaviojs** [comment]
The deb nightly is also bigger than expected, as seen here (all uploads succeeded): http://builds-ja2.stefanlau.com/pull-requests/885/

Are mingw and deb failing to upload because of the size?

**Comment by lynxlynxlynx** [comment]
deb:
- includes the build dir, almost 80M unpacked; /home should be excluded
- usr/bin is 100M unpacked, half for ja2, quarter for the launcher and the rest for the resource pack (editor stuff? What's it doing in bin?)
  - stripping debug symbols reduces it to just shy of 30M unpacked; so the setting in .travis.yml is ignored and they're built with Debug build type

**Comment by flaviojs** [comment]
The scenario where nightly doesn't change works as expected. (nightly isn't built)

Err... I just realized the link I gave is for a pull request, which is indeed built as debug.

**Comment by flaviojs** [comment]
The mingw nightly build has debug symbols for rust because we are telling rust to add them  in release too...
Added in: #519
Updated in: #634

Why do we have/want debug symbols in release?

**Comment by lynxlynxlynx** [comment]
We want them in proper releases, so users can help figure out crashes. There's no need for this in PR builds. For nightlies, I'm not sure.

But the build dir / /home should definitely not be packed.

**Comment by flaviojs** [comment]
Currently releases only have rust debug info (cmake is invoked with `Release`, not `RelWithDebInfo`).
Right now nightlies mimic releases.
PRs build as debug, so they always have debug symbols.

Maybe we should always force build with `RelWithDebInfo`?

**Comment by flaviojs** [comment]
The deb also contains the install step files of the external projects.
Weird... probably a bug or an incomplete configuration.

**Comment by flaviojs** [comment]
In the coverity branch the code is being built 6 times total and we only want 1.

Each of the 3 jobs builds for coverity, then normally.
After looking at the their example instructions I though it took care of the build by itself and so I removed the branch from the list but that didn't work as expected.

Now that I reread https://scan.coverity.com/travis_ci carefully, at the end it says we should add a condition to the normal build command `if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then <build command> ; fi`.

Now I'm looking into TravisCI docs. I want to have a separate job for coverity that only triggers on the nightly branch.

**Comment by flaviojs** [comment]
I'm happy with how coverity is working.

The weird size mystery was solved (rust debug symbols are intended).

To close this issue, uploads need to be fixed.
@selaux can you install/add a way to upload with a HTTP POST or HTTP PUT?

**Comment by selaux** [comment]
Nope unfortunately not. FTPS and FTP are currently the only options.

**Comment by flaviojs** [comment]
Here is the problem: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

Random upload failures will remain, unless it's possible to create a vpn connection to the server (I doubt it). :(

Apparently github can also build stuff with actions, should we try to replace travis-ci with github?

**Comment by lynxlynxlynx** [comment]
Sounds bothersome, why don't we just dump them on a server that does support SFTP?

**Comment by selaux** [comment]
Yes replacing it is certainly possible. It would actually be possible to do all CI in Github Actions, as they support all operating systems. I would also be an opportunity to split up CI into separate jobs (Linting, Building, Testing, Packaging, etc.). I might be a bunch of work though...

**Comment by flaviojs** [comment]
In the docs they recommend we avoid using github actions for high-value workflows and content during the public beta period. I'll give it a shot when it comes out of beta if uploads are still a problem.

**Comment by flaviojs** [comment]
Hmm... we could also create a pre-release in the nightly github action and upload the assets there, but that would probably flood the releases list.

**Comment by flaviojs** [comment]
Github actions are no longer beta: https://github.blog/2019-11-13-universe-day-one/
I'll try to make a CI build workflow.

**Comment by flaviojs** [comment]
I don't know why but the nightly branch isn't being built in GitHub CI. :(

**Comment by ja2-derek** [comment]
Just noticed the  `.deb` and `mingw64-cross` builds are zero bytes since May 30.

**Comment by lynxlynxlynx** [comment]
I doubt it, at least directly, since it still generates fine for me locally through:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCPACK_GENERATOR=DEB
make package -j3
```

**Comment by ja2-derek** [comment]
Are nightlies still built by Travis?

I found this https://travis-ci.org/github/ja2-stracciatella/ja2-stracciatella/jobs/693682710:

```
* Connect data stream passively

< 229 Entering Extended Passive Mode (|||52485|)

*   Trying 213.133.104.61...

* Connecting to 213.133.104.61 (213.133.104.61) port 52485

* Connected to www61.your-server.de (213.133.104.61) port 21 (#2)

> TYPE I

< 200 Type set to I

> STOR ja2-stracciatella_0.17.0-20200602+7d0a241_amd64.deb

* Operation timed out after 150001 milliseconds with 0 bytes received

* Closing connection 2

curl: (28) Operation timed out after 150001 milliseconds with 0 bytes received

The command "curl -v --connect-timeout 60 --max-time 150 --ftp-create-dirs -T ja2-stracciatella_0.17.0-20200602+7d0a241_amd64.deb -u [secure]:[secure] ftp://www61.your-server.de/nightlies/" failed 3 times.

Done. Your build exited with 0.
```

**Comment by selaux** [comment]
Yes. I think that is a known issue with FTP uploads on Travis CI, see [their blog](https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci). Maybe we can find another way to upload, I have to look at my Webspace Provider. Or we find another Provider that has free space for open source projects, which would also solve the issue of only me having admin access to that.

**Comment by ja2-derek** [comment]
We can consider the offers from the big clouds - e.g. Google has a free tier for storage up to 5GB.

**Comment by lynxlynxlynx** [comment]
SourceForge works fine and is practically limitless. They perhaps wouldn't accept the license, but I wouldn't bet on it.

**Comment by selaux** [comment]
I've migrated the old nightly builds to google storage. I currently have set up a limit of 10 EUR for the storage account. Let's see how far this takes us: [https://storage.googleapis.com/ja2-builds/index.html](https://storage.googleapis.com/ja2-builds/index.html). Currently the forecast is 0.02 EUR...

Next steps would be to upload to google storage after the build and integrate browsing of nightlies on the website...

**Comment by ja2-derek** [comment]
> 
> 
> I don't know why but the nightly branch isn't being built in GitHub CI. :(

My guess is that we are doing `--ff` fast-forward push, so there are no actual commits pushed on `nightly`. I suggest that we make `nightly` a tag instead of a branch, and we move the tag nightly.

**Comment by ja2-derek** [comment]
_Correction_ 

From https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

> When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "Authenticating with the GITHUB_TOKEN."
