### ISSUE TITLE
External project files are included in the deb

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#887]
Found by @lynxlynxlynx  in #873.

The deb contains the install step files of the external projects.

The problem only happens when `BUILD_ALWAYS` is present.

Without that option the projects are not rebuilt if the sources are modified.
This means it can be removed from`gtest-internal`, but not `libstracciatella`.

Must find an alternate way to trigger a rebuild when the sources change.

**Comment by lynxlynxlynx** [comment]
We could also just tweak cpack to remove stuff after the fact, right? Some options that look interesting:
CPACK_INSTALL_CMAKE_PROJECTS
CPACK_INSTALL_COMMANDS
CPACK_PACKAGE_DIRECTORY
