### ISSUE TITLE
Size of SOLDIERTYPE::bOppList

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#902]
Coverity detected at least one out of bounds read in `ManSeesMan` when the opponent id is 155.

The function checks that the ids are lower than 156:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3e9284a195ef38d774ecb4b3c0cf601576cb996/src/game/Tactical/OppList.cc#L1521-L1522

and uses the id as an index to `bOppList`:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3e9284a195ef38d774ecb4b3c0cf601576cb996/src/game/Tactical/OppList.cc#L1543

but `SOLDIERTYPE::bOppList` has size 148:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7d66aa47554c125a250db5d27dd4f77acb513ae8/src/game/Tactical/Soldier_Control.h#L516

---

Either the size of bOppList needs to be increased or the id checks need to change.
Too much code touches `bOppList` so I can't make a judgement.

Increasing the size of bOppList will produce saves that are incompatible with older versions, unless we also ignore the last 8 slots when saving and initialize the remaining slots when loading.

Changing the id checks requires checking that they don't go beyond 147 with the current code.

Note that `gsLastKnownOppLoc` is also used with the same ids and has size 156x156:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3e9284a195ef38d774ecb4b3c0cf601576cb996/src/game/Tactical/OppList.cc#L93

**Comment by lynxlynxlynx** [comment]
I would just adapt the checks in the function. If the ids are consecutive, I don't know of any way of reaching that high a body count, so it looks like a minor corner case.

**Comment by flaviojs** [comment]
Looking at `TacticalCreateSoldier` it appears that each team has a range of ids reserved.

The ranges are probably based on this:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b23cc131ed695f7f2bd43f7fb3d61551ebd7c4f2/src/game/Tactical/Overhead.cc#L203-L224

Any idea what this planning soldiers team is about? That's the difference between 148 and 156.

**Comment by lynxlynxlynx** [comment]
Not really, they're not even named in the team type defines:
```
// DEFINE TEAMS
#define OUR_TEAM                    0
#define ENEMY_TEAM                  1
#define CREATURE_TEAM                   2
#define MILITIA_TEAM                    3
#define CIV_TEAM                    4
#define LAST_TEAM                   CIV_TEAM
```

I've checked most users of MAXTEAM (6) and found nothing interesting. Might be unused. The colors are radar colors, but I don't remember any blues.

**Comment by flaviojs** [comment]
Looking at the original code I found team PLAYER_PLAN, which tron removed in 547869ce13511ab3b12d867bbe32563a1e47dfb7.

In the commit message tron says is was never set.

Considering the size of the team (8) and the size of `bOppList`, it's probably something that was still under development.

**Comment by lynxlynxlynx** [comment]
Great, then we can just remove the leftovers and lower NOBODY.

**Comment by flaviojs** [comment]
I'm not sure if it's safe to lower NOBODY, it might make save files incompatible with earlier versions.

**Comment by lynxlynxlynx** [comment]
True, probably some of the saved ids can be set to that.

**Comment by flaviojs** [comment]
I'm seeing TOTAL_SOLDIERS (156) in lots of places, including load/save code, so removing the leftovers seems complicated.

I'll try to understand how team PLAYER_PLAN was going to be used in the original...

**Comment by flaviojs** [comment]
The team was used in the planning mode (removed in fc3af8b1d06a36d603e3a52e26d5b96e1ea0c075), which didn't have a hotkey assigned so tron remove it.

It appears to be a "preview" mode for turn-based combat, where you can plan where you will move to and shoot with the current APs. They would disappear when the turn ends, so I think it's safe to exclude them from AI stuff.


If the planning mode wasn't removed, we could bind it to an extra hotkey (enabled in `game.json`).
I wanted to see it in action, too bad. =~

**Comment by lynxlynxlynx** [comment]
Eh, just decrease those safeties by NUM_PLANNING_MERCS and forget about it. Maybe add a refactoring todo comment, if we ever decide to break save compatibility radically.
