### ISSUE TITLE
Can't set coverity scan components

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/ja2-stracciatella#920]
Some time ago I tried to fix bad component regexes for what coverity should ignore (in "Analysis Settings") but when I pressed "Save changes" I was taken to https://scan.coverity.com/projects/ja2-stracciatella-ja2-stracciatella/update_components and shown a 404 page.

All the components were gone after that and I can't set them again.
@lynxlynxlynx @selaux is it the same for you?

I tried sending them an email but no reply so far.

**Comment by lynxlynxlynx** [comment]
I didn't have the problem about a month ago when selaux had the seeming login problems.

**Comment by flaviojs** [comment]
The component regexes of what to ignore:
* system files: `/usr/.*`
* our dependencies: `.*/dependencies/lib-.*`

**Comment by lynxlynxlynx** [comment]
Now I unfortunately have the same 404 problem as you.

**Comment by flaviojs** [comment]
Then it's probably because of a recent update on their part. I'll just wait for now. :(

Maybe it's possible to set ignorable paths before the coverity build, I'll give it a try.

**Comment by flaviojs** [comment]
It's setup and working properly, closing.
