### ISSUE TITLE
Error: Encoding issue with some Quest Texts crashes the game hard

### ISSUE THREAD

**Issue by Standfuss** [ja2-stracciatella/ja2-stracciatella#927]
Hi Guys,

There seems to be an issue with the Quest text encoding on the master branch (at least for me), I am running on Linux. The Error looks something like that.`

`2019-11-18T13:53:11 [DEBUG] game/TacticalAI/NPC.cc: Fact (191:'John(118) is bleeding') Must be True, status is False, returning
2019-11-18T13:53:11 [DEBUG] game/TacticalAI/NPC.cc: New Approach for NPC ID: 119 'Mary' against Merc: 56 'Czrneboh'
															Testing Record #: 5
thread '<unnamed>' panicked at 'Converting "Quest(119:\'\xfc\x8f\x8b\xa6\x9b\x83\xe8\x90\x9f\xfc\x8f\x80\x80\x80\x80\xe4\x90\x9f\xfd\xad\xa8\xa2\x97\xbf\xfc\xae\x99\xa0\x81\x9e\xf8\xa1\x81\xbc\x8f\') Must be in Progress, status is 0. False, return" to str: Utf8Error { valid_up_to: 11, error_len: Some(1) }', stracciatella_c_api/src/c/mod.rs:118:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Aborted (core dumped)
`
Issue occured in Sector A2, when talking / trying to open the Mary Quest. I build 0.16.x there it seems to work fine.

I think I encountered it as well in San Mona when talking to Bar Tender and the Whore House Lady in Sector C4.

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/3858946/QuickSave.zip)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
|  master branch (17.11.2019)|  JA2 English  |  dont know what that means, guess i go with no |   yes (seems to work in the 0.16.x branch (the only other I tested) |

[//]: # (- the operating system)
Linux Kernel: 5.2.21-1-MANJARO
boost-libs 1.71.0-2
linux-api-headers 5.3.1-1
gcc-libs 9.2.0-3
sdl2 2.0.10-1
glib2 2.62.2-1
wayland 1.17.0-1

Hope that helps. 

Besides, thanks for the great work. I do really appreciate the effort you put into this and enjoy the game.

Best Regards,

Bernd

**Comment by lynxlynxlynx** [comment]
Thanks for the report, it seems something is still left to be done in the string refactoring that was started.

**Comment by flaviojs** [comment]
It crashes because this line produced invalid utf8:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/fd5ab6055c39776fc86bfb072905234826f62da0/src/game/TacticalAI/NPC.cc#L1166-L1169

`pNPCQuoteInfo->ubQuest` is 119
`QuestDescText` is an array of length 30
`QuestDescText[ pNPCQuoteInfo->ubQuest ]` points to garbage <= the cause

**Comment by flaviojs** [comment]
I don't understand the true purpose of this log line...
It seems like a "soft" assert, but I can't figure out the exact condition it's trying to test.

Maybe it should be removed instead of fixed?

**Comment by lynxlynxlynx** [comment]
Yeah, it's only somewhat useful for debugging, so it can go. The following code does as instructed in the text.
