### ISSUE TITLE
Life insurance can make player's balance negative

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#93]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

After renewing a merc's contract I ended up with a negative balance.
This happened because the merc (Shadow) had a life insurance. I had a balance of $39k and some bucks. The contract for two weeks cost exactly $39k. But the insurance was like ~$1000 additionally.
I guess, it shouldn't be possible for the player to get a negative balance. I'm not sure, but this might be an issue from vanilla JA2?!![http://img.xrmb2.net/images/884232.jpeg](http://img.xrmb2.net/images/884232.jpeg) 

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/93

**Comment by JAsmine-ja2** [comment]
I tested this some more:
The life insurance that the player can (100% optionally) sign for each merc via the "Malleus, Incus & Stapes" website is not calculated against the player's balance, when extending a mercs (AIM) contract.

Look at these screenshots: The player extends MD's contract and ends up with a negative balance.
![screen000](https://user-images.githubusercontent.com/17213795/51788867-02a04100-2183-11e9-9fa4-96367c0bc48d.jpg)
![screen001](https://user-images.githubusercontent.com/17213795/51788868-02a04100-2183-11e9-92f4-e928ec5619f5.jpg)
![screen002](https://user-images.githubusercontent.com/17213795/51788869-02a04100-2183-11e9-92c3-d84009088f90.jpg)
![screen003](https://user-images.githubusercontent.com/17213795/51788871-02a04100-2183-11e9-8827-ada7fb5da876.jpg)

Here's the savegame from the screenshots.
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2799117/SaveGame10.zip)
