### ISSUE TITLE
Win7 Aero mode - game internal resolution enlarged causing blurriness

### ISSUE THREAD

**Issue by Nostaljaded** [ja2-stracciatella/ja2-stracciatella#933]
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
The internal resolution with 'Win7 Aero On' is probably scaled to 'game resolution + window borders' as the top portion shifts more than the other 3 sides.

Using the below example, 640x480 probably scaled to 656x518:

**Win7 Aero On**
![AeroOn](https://user-images.githubusercontent.com/28423237/69836031-f6a66500-1213-11ea-8a7d-7d673560d5dd.png)

**Win7 Aero Off/Correct Behavior**
![AeroOff](https://user-images.githubusercontent.com/28423237/69836035-ff973680-1213-11ea-8c8e-618a74a57b9d.png)

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release |  JA2 Gold English  |    no    |    not sure     |

[//]: # (Please also include:)
[//]: # Aero Mode On
[//]: # Win7

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by flaviojs** [comment]
Can't reproduce with the current [nightly](http://builds-ja2.stefanlau.com/nightlies/) (2019-11-26) in my windows 7.

By "release" you probably mean v0.16.1, can you try the nightly?

**Comment by Nostaljaded** [comment]
Enlargement issue still exists for current nightly (2019-11-26) using msvc32 & msvc64 builds.

Also, cannot launch ja2-launcher.exe for mingw build, with the following error message:
![mingw](https://user-images.githubusercontent.com/28423237/69846377-d9888b00-1241-11ea-9b45-0681bc027624.png)


Does not have enlargement nor mingw build issue with other SDL2 games in Aero mode.

**Comment by flaviojs** [comment]
The mingw issue was moved to a different issue.

I can't do anything about the enlargement issue unless I can reproduce it.
Are you using default settings?
If not, try starting fresh by deleting `ja2.json` (full path shown in the bottom of the launcher) and setting the game dir again.

**Comment by Nostaljaded** [comment]
Yes, fresh installation with default settings.

If other players have same problem with Win7 aero mode, hopefully they will report as well.
Leave this issue as it is for now, thanks for taking a look.

**Comment by Nostaljaded** [comment]
**Cause:** Bugged Intel iGPU Drivers v15.45.19.4678

**Resolved by:** Installing v15.45.31.5127
