### ISSUE TITLE
Open doors can block grenades

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#94]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

---

In this savegame, an enemy soldier is in prone position, inside a building, just behind the open front door. Throwing a stun grenade just in front of the soldier has absolutely no effect on the enemy. No reaction. It might be, because the enemy is inside the building and the door (although open) is somehow shielding him.
![http://img.xrmb2.net/images/159793.jpeg](http://img.xrmb2.net/images/159793.jpeg)

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/94

**Comment by JAsmine-ja2** [comment]
I did some more testing:

Doors can block the blast of grenades just like walls. This is fine. However, when a door is opened, the grenade is still blocked, which is weird.

More info:
- This is vanilla behavior. I tested both Stracciatella 0.15.1 and Vanilla 1.12 Gold
- type of grenade (regular or mini) doesn't matter
- angle of the door doesn't matter
- even cheat-grenade (strg+k) is blocked

![door-grenade](https://cloud.githubusercontent.com/assets/17213795/20457573/8bac0408-ae8e-11e6-8a21-3d494130d157.jpg)

Savegame:
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/601634/SaveGame10.zip)
